/* Opt-in real-recording ambience. Does not change med.js. */
(()=>{'use strict';if(window.AksharaAmbience)return;let a=null,playing=false,root=null;
const text=(te,en)=>`<span>${te}</span><span style="display:block;font-size:12px;opacity:.7">${en}</span>`;
function stop(){if(a)a.pause();playing=false;const b=document.getElementById('md-real-toggle');if(b){b.setAttribute('aria-pressed','false');b.innerHTML=text('▶ ప్రశాంత ధ్వని','Play calm ambience')}}
function mount(){const md=document.getElementById('md');if(md){const walk=document.createTreeWalker(md,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode()){const t=n.nodeValue.replace(/🧘|🌌|🌿|🎵/gu,'♪');if(t!==n.nodeValue)n.nodeValue=t}}if(!md){stop();root=null;return}const anchor=md.querySelector('#mdbtn');if(!anchor){stop();return}if(md.querySelector('#md-real-audio'))return;
const c=document.createElement('section');c.id='md-real-audio';c.className='c';c.setAttribute('aria-label','Optional real recording ambience');c.innerHTML=`<h3>♪ ${text('ప్రశాంత నేపథ్య ధ్వని','Calm recorded ambience')}</h3><p class="sm">${text('ఐచ్ఛికం. తక్కువ శబ్దంతో వినండి. మాటలు లేని 90 సెకన్ల ధ్వని మళ్ళీ వస్తుంది.','Optional. Keep volume low. A 90-second recording repeats with soft fades.')}</p><button class="b g" id="md-real-toggle" aria-pressed="false">${text('▶ ప్రశాంత ధ్వని','Play calm ambience')}</button><label style="display:block;margin-top:8px">${text('శబ్ద స్థాయి','Ambience volume')}<input id="md-real-volume" type="range" min="0" max="30" value="12" aria-label="Ambience volume" style="width:100%"></label><p id="md-real-status" role="status" class="sm"></p><p class="sm">HoliznaCC0 · <a href="https://freemusicarchive.org/music/holiznacc0/space-sleep-meditation/20-minute-meditation-1/" target="_blank" rel="noopener noreferrer" style="color:#67e8f9;text-decoration:underline">Track / CC0 license</a></p>`;
anchor.closest('.row').after(c);root=md;
c.querySelector('#md-real-toggle').onclick=async()=>{if(playing){stop();return}try{if(!a){a=new Audio('./learn/ambient/calm.mp3');a.loop=true;a.preload='none';a.onerror=()=>{stop();c.querySelector('#md-real-status').textContent='ధ్వని అందుబాటులో లేదు. / Audio unavailable.'}}a.volume=Number(c.querySelector('#md-real-volume').value)/100;window.MeditationApp?.music?.stop();await a.play();playing=true;const b=c.querySelector('#md-real-toggle');b.setAttribute('aria-pressed','true');b.innerHTML=text('⏸ ధ్వని ఆపు','Pause ambience');c.querySelector('#md-real-status').textContent='ప్రశాంత ధ్వని / Calm ambience'}catch(e){stop();c.querySelector('#md-real-status').textContent='మళ్ళీ ప్లే నొక్కండి. / Tap Play again.'}};
c.querySelector('#md-real-volume').oninput=e=>{if(a)a.volume=Number(e.target.value)/100};
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;if(['ppause','pstop','back','home','close'].includes(b.dataset.a))stop();if(b.dataset.a==='set'&&b.dataset.k==='music')stop();if(b.dataset.a==='pplay'&&playing)setTimeout(()=>window.MeditationApp?.music?.stop(),0)},true);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('pagehide',stop);
new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});mount();window.AksharaAmbience={stop};})();
