// AksharaNova topic bank 1: extra topics added by LD.add(subject, [classes], topic). Original text; facts checked (sources in notes to maintainers).
(function(){const A=LD.add;
A('social',[8,9,10],{id:'tgirr',i:'💧',te:'తెలంగాణ నీటిపారుదల ప్రాజెక్టులు',en:'Telangana irrigation projects',
kw:'irrigation water rivers godavari krishna kaleshwaram nagarjuna sagar srisailam sriramsagar sriram sagar pochampadu nizam sagar manjira mission kakatiya tanks cheruvu canal dam project lift neeti paarudala neeru praject nIti pAruDala సాగునీరు నీటి పారుదల ప్రాజెక్టు చెరువు గోదావరి కృష్ణా కాళేశ్వరం',
n:[
'నీటిపారుదల అంటే పంటలకు నదులు, చెరువులు, బావుల నుంచి నీరు అందించడం. తెలంగాణలో ప్రధాన నదులు గోదావరి, కృష్ణా.§Irrigation means giving crops water from rivers, tanks and wells. The main rivers of Telangana are the Godavari and the Krishna.',
'శ్రీరామ సాగర్ (పోచంపాడు) ప్రాజెక్టు గోదావరి నదిపై నిజామాబాద్ జిల్లాలో ఉంది. దీనికి 1963 జూలై 26న శంకుస్థాపన జరిగింది. ఇది ఉత్తర తెలంగాణ జిల్లాలకు ముఖ్యమైన సాగునీటి వనరు.§The Sriram Sagar (Pochampadu) Project is on the Godavari in Nizamabad district. Its foundation stone was laid on 26 July 1963. It is a key water source for the districts of north Telangana.',
'నాగార్జున సాగర్ కృష్ణా నదిపై నల్గొండ (తెలంగాణ), పల్నాడు (ఆంధ్రప్రదేశ్) జిల్లాల మధ్య ఉంది. ఇది ప్రపంచంలోనే అతి పెద్ద, ఎత్తైన రాతి (మేసనరీ) ఆనకట్టగా పేరొందింది. పని 1955లో మొదలై 1967లో పూర్తయింది.§Nagarjuna Sagar is on the Krishna between Nalgonda (Telangana) and Palnadu (Andhra Pradesh). It is known as the largest and highest masonry dam in the world. Work began in 1955 and finished in 1967.',
'శ్రీశైలం ఆనకట్ట కృష్ణా నదిపై నల్లమల కొండల్లో ఉంది (నాగర్‌కర్నూల్, తెలంగాణ - నంద్యాల, ఆంధ్రప్రదేశ్ సరిహద్దు). ఇది సాగునీరు, తాగునీరు, జలవిద్యుత్ ఇస్తుంది.§Srisailam Dam is on the Krishna in the Nallamala hills (border of Nagarkurnool in Telangana and Nandyal in Andhra Pradesh). It gives irrigation, drinking water and hydro-electricity.',
'నిజాం సాగర్ గోదావరి ఉపనది అయిన మంజీరపై కామారెడ్డి జిల్లాలో ఉంది. ఇది తెలంగాణలో అత్యంత పురాతన ఆనకట్ట.§Nizam Sagar is on the Manjira, a tributary of the Godavari, in Kamareddy district. It is the oldest dam in Telangana.',
'కాళేశ్వరం ఎత్తిపోతల పథకం గోదావరి నీటిని మేడిగడ్డ వద్ద ఎత్తిపోసి అనేక జిల్లాలకు చేరుస్తుంది. పనులు 2016లో మొదలై 2019 జూన్ 21న ప్రారంభమయ్యాయి. ఇందులో మూడు బ్యారేజీలు (మేడిగడ్డ, అన్నారం, సుందిళ్ల), పంపు హౌస్‌లు, సొరంగాలు, కాలువలు ఉన్నాయి.§The Kaleshwaram lift irrigation project lifts Godavari water at Medigadda and carries it to many districts. Work began in 2016 and it was inaugurated on 21 June 2019. It has three barrages (Medigadda, Annaram, Sundilla), pump houses, tunnels and canals.',
'ఎత్తిపోతల పథకం అంటే పంపులతో నీటిని ఎత్తైన చోటికి ఎత్తి కాలువల ద్వారా పంపడం. తెలంగాణ భూమి ఎత్తుపల్లాలుగా ఉండటంతో ఇవి అవసరం.§A lift scheme uses pumps to raise water to higher ground and then sends it through canals. Telangana has uneven land, so lifts are needed.',
'మిషన్ కాకతీయ (2015) చిన్న నీటి చెరువులను మరమ్మతు చేసి పునరుద్ధరించే కార్యక్రమం. చెరువులు తెలంగాణ రైతులకు ప్రాణాధారం.§Mission Kakatiya (2015) restores and repairs minor irrigation tanks. Tanks have long been a lifeline for Telangana farmers.'],
q:[
'శ్రీరామ సాగర్ ప్రాజెక్టు ఏ నదిపై ఉంది?§On which river is the Sriram Sagar Project?|గోదావరి~Godavari|కృష్ణా~Krishna|మంజీర~Manjira|తుంగభద్ర~Tungabhadra|శ్రీరామ సాగర్ (పోచంపాడు) గోదావరిపై నిజామాబాద్ జిల్లాలో ఉంది§Sriram Sagar (Pochampadu) is on the Godavari in Nizamabad district',
'నాగార్జున సాగర్ ఏ నదిపై ఉంది?§Nagarjuna Sagar is built on which river?|కృష్ణా~Krishna|గోదావరి~Godavari|పెన్నా~Penna|మంజీర~Manjira|నాగార్జున సాగర్ కృష్ణా నదిపై ఉంది§Nagarjuna Sagar is on the Krishna river',
'కాళేశ్వరం ప్రాజెక్టు ఏ రకం పథకం?§What kind of scheme is the Kaleshwaram project?|ఎత్తిపోతల పథకం~Lift irrigation scheme|జలవిద్యుత్ మాత్రమే~Only hydro power|సముద్ర నీటి శుద్ధి~Sea water purification|రోడ్డు ప్రాజెక్టు~Road project|ఇది పంపులతో గోదావరి నీటిని ఎత్తిపోస్తుంది§It lifts Godavari water using pumps',
'కాళేశ్వరం ప్రాజెక్టులోని బ్యారేజీ ఏది?§Which is a barrage of the Kaleshwaram project?|మేడిగడ్డ~Medigadda|శ్రీశైలం~Srisailam|నిజాం సాగర్~Nizam Sagar|జూరాల~Jurala|మేడిగడ్డ, అన్నారం, సుందిళ్ల అనే మూడు బ్యారేజీలు ఉన్నాయి§The three barrages are Medigadda, Annaram and Sundilla',
'తెలంగాణలో అత్యంత పురాతన ఆనకట్ట ఏది?§Which is the oldest dam in Telangana?|నిజాం సాగర్~Nizam Sagar|నాగార్జున సాగర్~Nagarjuna Sagar|శ్రీశైలం~Srisailam|కాళేశ్వరం~Kaleshwaram|నిజాం సాగర్ మంజీరపై ఉంది§Nizam Sagar is on the Manjira',
'మిషన్ కాకతీయ దేనికి సంబంధించినది?§What is Mission Kakatiya about?|చెరువుల పునరుద్ధరణ~Restoring tanks|రోడ్ల నిర్మాణం~Building roads|పాఠశాలలు~Schools|విద్యుత్ లైన్లు~Power lines|ఇది చిన్న నీటి చెరువులను పునరుద్ధరిస్తుంది§It restores minor irrigation tanks']});
LD.reg('bank',1)})();
