// English vocabulary and early-grammar topics (original wording; standard English usage)
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
A('english',[1,2],{id:'eng-alphabet',i:'🔤',te:'ఆంగ్ల వర్ణమాల',en:'English Alphabet',kw:'alphabet abc letters capital small varnamala వర్ణమాల అక్షరాలు',
n:['ఆంగ్ల వర్ణమాలలో 26 అక్షరాలు ఉన్నాయి: A నుండి Z వరకు.§The English alphabet has 26 letters, from A to Z.','ప్రతి అక్షరానికి రెండు రూపాలు: Capital (A, B, C) మరియు Small (a, b, c).§Each letter has two forms: capital (A, B, C) and small (a, b, c).','అచ్చులు (Vowels) 5: a, e, i, o, u. మిగతా 21 అక్షరాలు హల్లులు (Consonants).§There are 5 vowels: a, e, i, o, u. The other 21 letters are consonants.','పదాలు అక్షరాల క్రమంలో అమర్చడాన్ని alphabetical order అంటారు: apple, ball, cat.§Arranging words by their first letters is alphabetical order: apple, ball, cat.','సారాంశం: 26 అక్షరాలు = 5 vowels + 21 consonants.§Summary: 26 letters = 5 vowels + 21 consonants.'],
q:[Q('ఆంగ్ల వర్ణమాలలో ఎన్ని అక్షరాలు?§How many letters are in the English alphabet?',['26~26','24~24','21~21','30~30'],'సరైన సమాధానం: 26§Correct answer: 26'),Q('ఏది vowel?§Which is a vowel?',['e~e','t~t','m~m','s~s'],'సరైన సమాధానం: e§Correct answer: e'),Q('ఎన్ని consonants ఉన్నాయి?§How many consonants are there?',['21~21','5~5','26~26','20~20'],'సరైన సమాధానం: 21§Correct answer: 21'),Q('Alphabetical order లో మొదట వచ్చే పదం: cat, ball, apple§Which word comes first in alphabetical order: cat, ball, apple?',['apple~apple','ball~ball','cat~cat','all same~all same'],'సరైన సమాధానం: apple§Correct answer: apple'),Q('\'B\' కు small letter?§Small letter of \'B\'?',['b~b','d~d','p~p','q~q'],'సరైన సమాధానం: b§Correct answer: b')]});
A('english',[1,2,3],{id:'eng-opposites',i:'↔️',te:'వ్యతిరేక పదాలు',en:'Opposites (Antonyms)',kw:'opposites antonyms hot cold big small vyatireka padalu వ్యతిరేక పదాలు',
n:['వ్యతిరేక అర్థం ఉన్న పదాలను Antonyms (opposites) అంటారు.§Words with opposite meanings are called antonyms (opposites).','big - small, hot - cold, up - down, day - night.§big - small, hot - cold, up - down, day - night.','happy - sad, open - close, fast - slow, old - new, full - empty.§happy - sad, open - close, fast - slow, old - new, full - empty.','tall - short, heavy - light, near - far, rich - poor, early - late.§tall - short, heavy - light, near - far, rich - poor, early - late.','సారాంశం: ప్రతి పదానికి వ్యతిరేకం తెలుసుకుంటే పదజాలం పెరుగుతుంది.§Summary: knowing opposites grows your vocabulary.'],
q:[Q('\'hot\' కు opposite?§Opposite of \'hot\'?',['cold~cold','warm~warm','big~big','fast~fast'],'సరైన సమాధానం: cold§Correct answer: cold'),Q('\'day\' కు opposite?§Opposite of \'day\'?',['night~night','noon~noon','sun~sun','light~light'],'సరైన సమాధానం: night§Correct answer: night'),Q('\'open\' కు opposite?§Opposite of \'open\'?',['close~close','start~start','wide~wide','come~come'],'సరైన సమాధానం: close§Correct answer: close'),Q('\'rich\' కు opposite?§Opposite of \'rich\'?',['poor~poor','kind~kind','big~big','happy~happy'],'సరైన సమాధానం: poor§Correct answer: poor'),Q('\'early\' కు opposite?§Opposite of \'early\'?',['late~late','soon~soon','first~first','fast~fast'],'సరైన సమాధానం: late§Correct answer: late')]});
A('english',[1,2,3],{id:'eng-action-words',i:'🏃',te:'క్రియా పదాలు (Action Words)',en:'Action Words',kw:'action words verbs run jump eat read kriya padalu క్రియలు',
n:['పని చేయడాన్ని చెప్పే పదాలు Action words (verbs).§Words that tell what someone does are action words (verbs).','run, jump, eat, drink, sleep, read, write, sing, dance.§run, jump, eat, drink, sleep, read, write, sing, dance.','He runs. She sings. They play. (he/she కు చివర s)§He runs. She sings. They play. (add s with he/she)','ఇప్పుడు జరుగుతున్న పనికి -ing: running, eating, reading.§Add -ing for an action happening now: running, eating, reading.','సారాంశం: ప్రతి వాక్యంలో ఒక action word ఉంటుంది.§Summary: every sentence has an action word.'],
q:[Q('Action word ఏది?§Which is an action word?',['jump~jump','table~table','red~red','happy~happy'],'సరైన సమాధానం: jump§Correct answer: jump'),Q('Birds ___ . (fly/flies)§Birds ___ .',['fly~fly','flies~flies','flying~flying','flew~flew'],'సరైన సమాధానం: fly§Correct answer: fly'),Q('She ___ a song.§She ___ a song.',['sings~sings','sing~sing','singing~singing','sang~sang'],'సరైన సమాధానం: sings§Correct answer: sings'),Q('\'read\' + ing =§\'read\' + ing =',['reading~reading','readding~readding','readed~readed','readen~readen'],'సరైన సమాధానం: reading§Correct answer: reading'),Q('\'The boy eats.\' Action word?§\'The boy eats.\' Action word?',['eats~eats','boy~boy','the~the','none~none'],'సరైన సమాధానం: eats§Correct answer: eats')]});
A('english',[1,2,3],{id:'eng-this-that',i:'👉',te:'This, That, These, Those',en:'This, That, These, Those',kw:'this that these those demonstrative near far ఇది అది',
n:['దగ్గరగా ఉన్న ఒకదానికి this; దూరంగా ఉన్న ఒకదానికి that.§Use this for one thing near you; that for one thing far away.','దగ్గరగా ఉన్న ఎక్కువ వాటికి these; దూరంగా ఉన్న ఎక్కువ వాటికి those.§Use these for many things near you; those for many things far away.','this book - these books; that pen - those pens.§this book - these books; that pen - those pens.','Is/Are: This is a cat. These are cats.§This is a cat. These are cats.','సారాంశం: ఏకవచనం this/that, బహువచనం these/those.§Summary: singular this/that, plural these/those.'],
q:[Q('___ is my bag. (bag near me)§___ is my bag. (bag near me)',['This~This','That~That','These~These','Those~Those'],'సరైన సమాధానం: This§Correct answer: This'),Q('___ are birds. (many birds far away)§___ are birds. (many birds far away)',['Those~Those','These~These','This~This','That~That'],'సరైన సమాధానం: Those§Correct answer: Those'),Q('Plural of \'this\':§Plural of \'this\':',['these~these','those~those','that~that','thus~thus'],'సరైన సమాధానం: these§Correct answer: these'),Q('___ pen is mine. (near)§___ pen is mine. (near)',['This~This','These~These','Those~Those','Them~Them'],'సరైన సమాధానం: This§Correct answer: This'),Q('Plural of \'that\':§Plural of \'that\':',['those~those','these~these','this~this','thats~thats'],'సరైన సమాధానం: those§Correct answer: those')]});
A('english',[2,3,4],{id:'eng-is-am-are',i:'🅱️',te:'is, am, are',en:'Is, Am, Are',kw:'is am are was were be verb singular plural',
n:['I తో am వాడతాం: I am happy.§Use am with I: I am happy.','he, she, it, ఒక్క వస్తువు/వ్యక్తి తో is: She is a girl.§Use is with he, she, it and one person or thing: She is a girl.','we, you, they, ఎక్కువ వస్తువులతో are: They are friends.§Use are with we, you, they and many: They are friends.','గతంలో: I/he/she/it - was; we/you/they - were.§In the past: I/he/she/it - was; we/you/they - were.','సారాంశం: subject చూసి am/is/are ఎంచండి.§Summary: choose am/is/are by the subject.'],
q:[Q('I ___ a student.§I ___ a student.',['am~am','is~is','are~are','be~be'],'సరైన సమాధానం: am§Correct answer: am'),Q('They ___ playing.§They ___ playing.',['are~are','is~is','am~am','was~was'],'సరైన సమాధానం: are§Correct answer: are'),Q('The cat ___ sleeping.§The cat ___ sleeping.',['is~is','are~are','am~am','were~were'],'సరైన సమాధానం: is§Correct answer: is'),Q('We ___ in class yesterday.§We ___ in class yesterday.',['were~were','was~was','are~are','is~is'],'సరైన సమాధానం: were§Correct answer: were'),Q('He ___ at home yesterday.§He ___ at home yesterday.',['was~was','were~were','is~is','are~are'],'సరైన సమాధానం: was§Correct answer: was')]});
A('english',[3,4,5,6],{id:'eng-synonyms',i:'🟰',te:'సమానార్థక పదాలు',en:'Synonyms',kw:'synonyms same meaning vocabulary samanarthaka padalu సమానార్థక పదాలు',
n:['ఒకే అర్థం ఉన్న పదాలు Synonyms.§Words with the same or nearly the same meaning are synonyms.','big - large - huge; small - little - tiny.§big - large - huge; small - little - tiny.','happy - glad - cheerful; sad - unhappy - sorrowful.§happy - glad - cheerful; sad - unhappy - sorrowful.','begin - start - commence; end - finish - complete.§begin - start - commence; end - finish - complete.','brave - bold - courageous; quick - fast - rapid.§brave - bold - courageous; quick - fast - rapid.','సారాంశం: ఒకే భావాన్ని వేర్వేరు పదాలతో చెప్పవచ్చు; సందర్భం చూసి ఎంచాలి.§Summary: one idea can be said in many words; pick by context.'],
q:[Q('Synonym of \'big\':§Synonym of \'big\':',['large~large','tiny~tiny','thin~thin','low~low'],'సరైన సమాధానం: large§Correct answer: large'),Q('Synonym of \'begin\':§Synonym of \'begin\':',['start~start','end~end','stop~stop','close~close'],'సరైన సమాధానం: start§Correct answer: start'),Q('Synonym of \'brave\':§Synonym of \'brave\':',['bold~bold','timid~timid','weak~weak','lazy~lazy'],'సరైన సమాధానం: bold§Correct answer: bold'),Q('Synonym of \'glad\':§Synonym of \'glad\':',['happy~happy','angry~angry','sad~sad','sleepy~sleepy'],'సరైన సమాధానం: happy§Correct answer: happy'),Q('Synonym of \'quick\':§Synonym of \'quick\':',['fast~fast','slow~slow','late~late','heavy~heavy'],'సరైన సమాధానం: fast§Correct answer: fast')]});
A('english',[4,5,6,7],{id:'eng-homophones',i:'🔉',te:'ఒకేలా వినిపించే పదాలు',en:'Homophones',kw:'homophones sound alike their there to too two see sea',
n:['పలుకు ఒకటే కానీ అర్థం, స్పెల్లింగ్ వేరుగా ఉండే పదాలు Homophones.§Homophones sound the same but have different spelling and meaning.','two (2) - to (వైపు) - too (కూడా); see (చూడు) - sea (సముద్రం).§two (number) - to (direction) - too (also); see (look) - sea (ocean).','their (వారి) - there (అక్కడ) - they\'re (they are).§their (belonging to them) - there (that place) - they\'re (they are).','write (రాయి) - right (సరైనది); flower (పువ్వు) - flour (పిండి); knew - new; hear - here.§write - right; flower - flour; knew - new; hear - here.','సారాంశం: సందర్భం చూసి సరైన స్పెల్లింగ్ వాడాలి.§Summary: use context to choose the right spelling.'],
q:[Q('I ___ a bird in the sky. (see/sea)§I ___ a bird in the sky.',['see~see','sea~sea','c~c','si~si'],'సరైన సమాధానం: see§Correct answer: see'),Q('Please ___ your name. (write/right)§Please ___ your name.',['write~write','right~right','rite~rite','wright~wright'],'సరైన సమాధానం: write§Correct answer: write'),Q('___ going to school. (They\'re/Their)§___ going to school.',['They\'re~They\'re','Their~Their','There~There','Thier~Thier'],'సరైన సమాధానం: They\'re§Correct answer: They\'re'),Q('I ___ you clearly. (hear/here)§I ___ you clearly.',['hear~hear','here~here','hare~hare','hair~hair'],'సరైన సమాధానం: hear§Correct answer: hear'),Q('He is ___ tired. (too/two)§He is ___ tired.',['too~too','two~two','to~to','tu~tu'],'సరైన సమాధానం: too§Correct answer: too')]});
A('english',[5,6,7,8,9,10],{id:'eng-prefix-suffix',i:'🧩',te:'ఉపసర్గ - ప్రత్యయం',en:'Prefixes and Suffixes',kw:'prefix suffix un re dis ful less ness word formation upasarga pratyayam ఉపసర్గ ప్రత్యయం',
n:['Prefix: పదం ముందు చేర్చే భాగం; అర్థం మారుస్తుంది (happy - unhappy).§A prefix is added before a word and changes its meaning (happy - unhappy).','సాధారణ prefixes: un-, in-, im-, dis-, re-, mis-, pre-. (do - undo, like - dislike, write - rewrite, spell - misspell)§Common prefixes: un-, in-, im-, dis-, re-, mis-, pre-. (do - undo, like - dislike, write - rewrite, spell - misspell)','Suffix: పదం చివర చేర్చే భాగం; కొత్త పదం/రకాన్ని ఇస్తుంది (care - careful).§A suffix is added at the end and makes a new word or word type (care - careful).','సాధారణ suffixes: -ful, -less, -ness, -ment, -er, -able, -ly. (kind - kindness, help - helpless, enjoy - enjoyment)§Common suffixes: -ful, -less, -ness, -ment, -er, -able, -ly. (kind - kindness, help - helpless, enjoy - enjoyment)','సారాంశం: prefix ముందు, suffix వెనుక.§Summary: prefix in front, suffix at the end.'],
q:[Q('\'unhappy\' లో prefix?§What is the prefix in \'unhappy\'?',['un~un','happy~happy','py~py','hap~hap'],'సరైన సమాధానం: un§Correct answer: un'),Q('\'careless\' లో suffix?§What is the suffix in \'careless\'?',['less~less','care~care','car~car','ss~ss'],'సరైన సమాధానం: less§Correct answer: less'),Q('\'kind\' + ness =§\'kind\' + ness =',['kindness~kindness','kindly~kindly','kinder~kinder','unkind~unkind'],'సరైన సమాధానం: kindness§Correct answer: kindness'),Q('\'re\' + write =§\'re\' + write =',['rewrite~rewrite','unwrite~unwrite','miswrite~miswrite','write~write'],'సరైన సమాధానం: rewrite§Correct answer: rewrite'),Q('\'dis\' + like =§\'dis\' + like =',['dislike~dislike','unlike~unlike','relike~relike','mislike~mislike'],'సరైన సమాధానం: dislike§Correct answer: dislike')]});
LD.reg('beng2',1)})();
