// Telangana GK. NOT yet page-verified: facts written from general knowledge; reference URLs are suggested, to be checked. Class tags are suitability, not SCERT chapter maps.
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
// Suggested reference (unverified): https://www.telangana.gov.in/about/state-profile/
A('social',[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],{"id":"gk_tg_symbols","i":"🦌","te":"తెలంగాణ రాష్ట్ర చిహ్నాలు","en":"Telangana State Symbols","kw":"Telangana state symbols animal bird tree flower జింక పాలపిట్ట జమ్మి తంగేడు","n":["# సారాంశం§# Summary", "తెలంగాణ రాష్ట్ర రాజధాని హైదరాబాద్. రాష్ట్రానికి అధికారిక చిహ్నాలు ఉన్నాయి.§Hyderabad is the capital of Telangana. The state has official symbols.", "రాష్ట్ర జంతువు జింక (చుక్కల జింక).§The state animal is the deer (spotted deer).", "రాష్ట్ర పక్షి పాలపిట్ట (ఇండియన్ రోలర్).§The state bird is the Palapitta (Indian roller).", "రాష్ట్ర వృక్షం జమ్మి చెట్టు.§The state tree is the Jammi tree.", "రాష్ట్ర పుష్పం తంగేడు.§The state flower is Tangedu."],"q":[Q("తెలంగాణ రాష్ట్ర పక్షి ఏది?§Which is the state bird of Telangana?",["పాలపిట్ట~Palapitta (Indian roller)", "నెమలి~Peacock", "చిలుక~Parrot", "కాకి~Crow"],"పాలపిట్ట రాష్ట్ర పక్షి.§Palapitta is the state bird."),Q("రాష్ట్ర పుష్పం ఏది?§Which is the state flower?",["తంగేడు~Tangedu", "గులాబీ~Rose", "తామర~Lotus", "మల్లె~Jasmine"],"తంగేడు రాష్ట్ర పుష్పం.§Tangedu is the state flower."),Q("రాష్ట్ర వృక్షం ఏది?§Which is the state tree?",["జమ్మి~Jammi", "మామిడి~Mango", "వేప~Neem", "రావి~Peepal"],"జమ్మి రాష్ట్ర వృక్షం.§Jammi is the state tree.")]});
// Suggested reference (unverified): https://tourism.telangana.gov.in/page/festivals-and-fairs
A('social',[3, 4, 5, 6, 7, 8, 9, 10],{"id":"gk_tg_medaram","i":"🌳","te":"సమ్మక్క సారలమ్మ జాతర","en":"Sammakka Saralamma Jatara (Medaram)","kw":"Medaram jatara Telangana Sammakka Saralamma Mulugu tribal సమ్మక్క సారలమ్మ మేడారం","n":["# సారాంశం§# Summary", "సమ్మక్క సారలమ్మ జాతర తెలంగాణలోని మేడారంలో జరిగే పెద్ద గిరిజన పండుగ.§The Sammakka Saralamma Jatara is a large tribal festival held at Medaram in Telangana.", "ఇది రెండేళ్లకు ఒకసారి జరుగుతుంది.§It is held once every two years.", "లక్షలాది మంది ప్రజలు వచ్చి గిరిజన దేవతలను గౌరవిస్తారు.§Lakhs of people visit to honour the tribal goddesses.", "మేడారం ములుగు జిల్లాలో ఉంది.§Medaram is in Mulugu district."],"q":[Q("మేడారం జాతర ఏ రాష్ట్రంలో జరుగుతుంది?§In which state is the Medaram Jatara held?",["తెలంగాణ~Telangana", "కేరళ~Kerala", "పంజాబ్~Punjab", "అసోం~Assam"],"ఇది తెలంగాణలో జరుగుతుంది.§It is held in Telangana."),Q("ఈ జాతర ఎన్నేళ్లకు ఒకసారి?§How often is it held?",["రెండేళ్లకు~Every two years", "ప్రతి నెల~Every month", "ప్రతి వారం~Every week", "ప్రతి రోజు~Every day"],"రెండేళ్లకు ఒకసారి.§Once in two years."),Q("ఇది ఏ రకమైన పండుగ?§What kind of festival is it?",["గిరిజన జాతర~Tribal fair", "క్రీడా పోటీ~Sports contest", "ఎన్నికల రోజు~Election day", "సైన్స్ ఫెయిర్~Science fair"],"ఇది గిరిజన జాతర.§It is a tribal fair.")]});
// Suggested reference (unverified): https://www.telangana.gov.in/about/state-profile/
A('social',[3, 4, 5, 6, 7, 8, 9, 10],{"id":"gk_tg_charminar","i":"🕌","te":"చార్మినార్ - హైదరాబాద్","en":"Charminar and Hyderabad","kw":"Charminar Hyderabad Telangana Quli Qutb Shah 1591 చార్మినార్ హైదరాబాద్","n":["# సారాంశం§# Summary", "చార్మినార్ హైదరాబాద్‌లోని ప్రసిద్ధ చారిత్రక కట్టడం.§Charminar is a famous historic monument in Hyderabad.", "దీనిని 1591లో మహమ్మద్ కులీ కుతుబ్ షా నిర్మించారు.§It was built in 1591 by Muhammad Quli Qutb Shah.", "'చార్ మినార్' అంటే నాలుగు మినార్లు.§'Char Minar' means four minarets.", "హైదరాబాద్ తెలంగాణ రాజధాని.§Hyderabad is the capital of Telangana."],"q":[Q("చార్మినార్ ఏ నగరంలో ఉంది?§In which city is Charminar?",["హైదరాబాద్~Hyderabad", "చెన్నై~Chennai", "ముంబై~Mumbai", "ఢిల్లీ~Delhi"],"హైదరాబాద్‌లో ఉంది.§It is in Hyderabad."),Q("చార్మినార్‌ను ఎవరు నిర్మించారు?§Who built Charminar?",["మహమ్మద్ కులీ కుతుబ్ షా~Muhammad Quli Qutb Shah", "అక్బర్~Akbar", "అశోకుడు~Ashoka", "షాజహాన్~Shah Jahan"],"కులీ కుతుబ్ షా నిర్మించారు.§Quli Qutb Shah built it."),Q("'చార్' అంటే?§What does 'char' mean?",["నాలుగు~Four", "రెండు~Two", "పది~Ten", "ఒకటి~One"],"చార్ అంటే నాలుగు.§Char means four.")]});
// Suggested reference (unverified): https://www.telangana.gov.in/about/state-profile/
A('social',[4, 5, 6, 7, 8, 9, 10],{"id":"gk_tg_rivers","i":"🌊","te":"తెలంగాణ నదులు","en":"Rivers of Telangana","kw":"Telangana rivers Godavari Krishna Manjira Musi తెలంగాణ నదులు గోదావరి కృష్ణా","n":["# సారాంశం§# Summary", "తెలంగాణలో ప్రధాన నదులు గోదావరి మరియు కృష్ణా.§The major rivers of Telangana are the Godavari and the Krishna.", "మంజీర గోదావరి ఉపనది.§The Manjira is a tributary of the Godavari.", "మూసీ నది హైదరాబాద్ గుండా ప్రవహిస్తుంది.§The Musi river flows through Hyderabad.", "నదులను శుభ్రంగా ఉంచుకోవడం మన బాధ్యత.§Keeping rivers clean is our responsibility."],"q":[Q("తెలంగాణలోని రెండు ప్రధాన నదులు?§Two major rivers of Telangana?",["గోదావరి, కృష్ణా~Godavari and Krishna", "గంగ, యమున~Ganga and Yamuna", "సింధు, సట్లెజ్~Indus and Sutlej", "నర్మద, తాపి~Narmada and Tapi"],"గోదావరి, కృష్ణా.§Godavari and Krishna."),Q("హైదరాబాద్ గుండా ప్రవహించే నది?§Which river flows through Hyderabad?",["మూసీ~Musi", "బ్రహ్మపుత్ర~Brahmaputra", "కావేరి~Kaveri", "మహానది~Mahanadi"],"మూసీ.§The Musi."),Q("మంజీర దేని ఉపనది?§The Manjira is a tributary of?",["గోదావరి~Godavari", "గంగ~Ganga", "సింధు~Indus", "కావేరి~Kaveri"],"గోదావరి ఉపనది.§A tributary of the Godavari.")]});
LD.reg('bgk6',1)})();
