// Sources: NCERT Math-Magic Classes 3-5 (data handling, area/perimeter, fractions) concepts; formulas standard; numeric answers computed in code. Placement approximate - confirm against TS SCERT.
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
A('maths',[2,3,4],{id:'m15_pictograph',i:'🖼️',te:'చిత్రాలేఖనం (పిక్టోగ్రాఫ్) చదవడం',en:'Reading Pictographs',kw:'pictograph picture graph symbol key data chitralekhanam పిక్టోగ్రాఫ్ చిత్రలేఖనం గుర్తు కీ సమాచారం',
n:['# పిక్టోగ్రాఫ్§# Pictograph','సమాచారాన్ని చిత్రాలతో చూపే పటం. ప్రతి చిత్రం ఒక సంఖ్యను సూచిస్తుంది.§A graph that shows data with pictures. Each picture stands for a number.','# కీ (సూచిక)§# Key','కీ చెబుతుంది ఒక బొమ్మ ఎంతకు సమానమో. ఉదా: 🍎 = 2 పండ్లు.§The key tells what one symbol equals. Example: 🍎 = 2 fruits.','# చదివే విధానం§# How to read','బొమ్మల సంఖ్యను కీ విలువతో గుణించండి. 4 బొమ్మలు × 2 = 8.§Multiply the number of symbols by the key value. 4 symbols × 2 = 8.','# అర్ధ బొమ్మ§# Half symbol','సగం బొమ్మ ఉంటే కీ విలువలో సగం. 🍎 = 2 అయితే సగం బొమ్మ = 1.§A half symbol is half the key value. If 🍎 = 2 then half = 1.','# సారాంశం§# Summary','కీ ని చదవకుండా పిక్టోగ్రాఫ్ చదవకండి.§Never read a pictograph without the key.'],
q:[Q('కీ: 1 బొమ్మ = 5 పిల్లలు. 6 బొమ్మలు = ?§Key: 1 symbol = 5 children. 6 symbols = ?',['30','11','35','25'],'30.§30.'),Q('కీ: 1 బొమ్మ = 2. 3½ బొమ్మలు = ?§Key 1 symbol = 2. 3½ symbols = ?',['7','6','8','3.5'],'7.§7.'),Q('కీ 1 బొమ్మ = 10. 45 ను చూపడానికి ఎన్ని బొమ్మలు?§Key 1 = 10. Symbols to show 45?',['4½','45','5','4'],'45÷10.§45 ÷ 10.'),Q('పిక్టోగ్రాఫ్‌లో కీ ఎందుకు?§Why a key in a pictograph?',['ఒక బొమ్మ విలువ చెప్పడానికి~To give the value of one symbol','అందంగా ఉండటానికి~For decoration','రంగుల కోసం~For colour','అవసరం లేదు~Not needed'],'కీ లేకుండా విలువ తెలియదు.§Without it the value is unknown.'),Q('A కి 4 బొమ్మలు, B కి 7 బొమ్మలు (1 = 3). B, A కంటే ఎంత ఎక్కువ?§A has 4 symbols, B has 7 (1 = 3). How much more is B?',['9','3','7','12'],'3×3 = 9.§3 × 3 = 9.')]});
A('maths',[3,4,5],{id:'m15_bargraph',i:'📊',te:'బార్ గ్రాఫ్ గీయడం, చదవడం',en:'Drawing and Reading Bar Graphs',kw:'bar graph scale axes data table height compare bar graph బార్ గ్రాఫ్ స్కేలు అక్షాలు సమాచారం',
n:['# బార్ గ్రాఫ్§# Bar graph','సమాన వెడల్పు పట్టీలతో సమాచారాన్ని చూపే గ్రాఫ్. పట్టీ ఎత్తు విలువను సూచిస్తుంది.§A graph with equal-width bars. The height shows the value.','# అక్షాలు§# Axes','అడ్డు అక్షంపై వర్గాలు, నిలువు అక్షంపై సంఖ్యలు ఉంటాయి. శీర్షిక ఉండాలి.§Categories sit on the horizontal axis and numbers on the vertical axis. Add a title.','# స్కేలు§# Scale','1 గడి = 2 అని ఎంచుకోవచ్చు. అన్ని విలువలు స్కేలుతో సరిపోవాలి.§Choose a scale like 1 square = 2. All values must fit it.','# గీసే దశలు§# Steps','1) సమాచారం పట్టిక 2) స్కేలు 3) పట్టీలు 4) పేర్లు, శీర్షిక.§1) Table 2) Scale 3) Bars 4) Labels and title.','# సారాంశం§# Summary','ఎత్తైన పట్టీ = ఎక్కువ విలువ.§The tallest bar is the largest value.'],
q:[Q('పట్టీ ఎత్తు 7 గడులు, స్కేలు 1 గడి = 2 అయితే విలువ?§Bar 7 squares high, scale 1 square = 2. Value?',['14','7','9','5'],'14.§14.'),Q('విలువ 30, స్కేలు 1 గడి = 5 అయితే ఎత్తు?§Value 30 with scale 1 square = 5. Height?',['6 గడులు~6 squares','35 గడులు~35 squares','150 గడులు~150 squares','25 గడులు~25 squares'],'6.§6.'),Q('A=8, B=12, C=6 లో పొట్టి పట్టీ?§A=8, B=12, C=6. Shortest bar?',['C','A','B','అన్నీ సమానం~All equal'],'6.§6.'),Q('పై సమాచార మొత్తం?§Total of A, B, C?',['26','24','28','20'],'26.§26.'),Q('B ని A తో పోలిస్తే ఎంత ఎక్కువ?§How much more is B than A?',['4','20','2','6'],'4.§4.')]});
A('maths',[4],{id:'m15_area4',i:'🟦',te:'వైశాల్యం: చదరపు యూనిట్లు',en:'Area: Square Units',kw:'area square unit cm2 m2 count squares grid rectangle vaishalyam వైశాల్యం చదరపు సెంటీమీటర్ గడులు',
n:['# వైశాల్యం§# Area','ఒక ఆకారం లోపల ఉన్న చదరపు యూనిట్ల సంఖ్య.§The number of unit squares inside a shape.','# గడులు లెక్కించడం§# Counting squares','గడుల కాగితంపై ఆకారం లోపల పూర్తి గడులను లెక్కించండి. 4 వరుసలు × 6 = 24 చ.సెం.మీ.§Count the full squares on grid paper. 4 rows × 6 = 24 cm².','# ప్రమాణాలు§# Units','చ.సెం.మీ (cm²), చ.మీ (m²). 1 చ.మీ = 100×100 = 10,000 చ.సెం.మీ.§cm², m². 1 m² = 100 × 100 = 10,000 cm².','# సూత్రం§# Formula','దీర్ఘచతురస్రం = పొడవు × వెడల్పు. చతురస్రం = భుజం × భుజం.§Rectangle = length × breadth. Square = side × side.','# సారాంశం§# Summary','వైశాల్యం చదరపు యూనిట్లలో, చుట్టుకొలత పొడవు యూనిట్లలో.§Area is in square units, perimeter in length units.'],
q:[Q('4 వరుసలు × 6 గడులు వైశాల్యం?§4 rows × 6 squares. Area?',['24 చ.సెం.మీ~24 cm²','10 చ.సెం.మీ~10 cm²','20 చ.సెం.మీ~20 cm²','48 చ.సెం.మీ~48 cm²'],'24.§24.'),Q('భుజం 7 మీ చతురస్ర వైశాల్యం?§Area of square side 7 m?',['49 చ.మీ~49 m²','28 చ.మీ~28 m²','14 చ.మీ~14 m²','77 చ.మీ~77 m²'],'49.§49.'),Q('1 చ.మీ = ఎన్ని చ.సెం.మీ?§1 m² = how many cm²?',['10,000','100','1000','1,00,000'],'100×100.§100 × 100.'),Q('పొడవు 12 మీ, వెడల్పు 5 మీ గది వైశాల్యం?§Room 12 m by 5 m. Area?',['60 చ.మీ~60 m²','34 చ.మీ~34 m²','17 చ.మీ~17 m²','120 చ.మీ~120 m²'],'60.§60.'),Q('వైశాల్యం యూనిట్?§Unit of area?',['చ.సెం.మీ~cm²','సెం.మీ~cm','కి.గ్రా~kg','లీటరు~L'],'చదరపు యూనిట్.§Square unit.')]});
A('maths',[4,5],{id:'m15_perimeter4',i:'🏞️',te:'బహుభుజుల చుట్టుకొలత, నిజ జీవిత లెక్కలు',en:'Perimeter of Polygons and Real-Life Problems',kw:'perimeter polygon triangle fence boundary rope chuttukolata చుట్టుకొలత కంచె బహుభుజి త్రిభుజం',
n:['# సాధారణ సూత్రం§# General rule','ఏ బహుభుజి చుట్టుకొలతైనా అన్ని భుజాల పొడవుల మొత్తం.§Perimeter of any polygon is the sum of all its sides.','# త్రిభుజం§# Triangle','భుజాలు 5, 6, 7 సెం.మీ → చుట్టుకొలత 18 సెం.మీ. సమబాహు త్రిభుజం = 3 × భుజం.§Sides 5, 6, 7 cm → perimeter 18 cm. Equilateral = 3 × side.','# సమ బహుభుజి§# Regular polygon','సమ షడ్భుజి భుజం 4 → 6×4 = 24. సమ పంచభుజి భుజం 3 → 5×3 = 15.§Regular hexagon side 4 → 6×4 = 24. Regular pentagon side 3 → 5×3 = 15.','# కంచె§# Fencing','పొలం చుట్టూ కంచె వేయడానికి చుట్టుకొలత కావాలి. కంచె పొడవు × మీటరు ధర = ఖర్చు.§Fencing needs the perimeter. Cost = length of fence × price per metre.','# సారాంశం§# Summary','యూనిట్లు ఒకటే ఉండాలి.§Keep units the same.'],
q:[Q('భుజాలు 5, 6, 7 సెం.మీ త్రిభుజ చుట్టుకొలత?§Triangle sides 5, 6, 7 cm. Perimeter?',['18 సెం.మీ~18 cm','210 సెం.మీ~210 cm','11 సెం.మీ~11 cm','13 సెం.మీ~13 cm'],'18.§18.'),Q('భుజం 4 సెం.మీ సమ షడ్భుజి చుట్టుకొలత?§Regular hexagon side 4 cm. Perimeter?',['24 సెం.మీ~24 cm','16 సెం.మీ~16 cm','10 సెం.మీ~10 cm','32 సెం.మీ~32 cm'],'24.§24.'),Q('20 మీ × 15 మీ పొలం చుట్టూ కంచె పొడవు?§Fence around a 20 m × 15 m field?',['70 మీ~70 m','35 మీ~35 m','300 మీ~300 m','50 మీ~50 m'],'70.§70.'),Q('కంచె ₹50/మీ అయితే పై పొలానికి ఖర్చు?§At ₹50/m cost of that fence?',['₹3,500','₹1,750','₹350','₹3,000'],'70×50 = 3500.§70 × 50 = 3500.'),Q('సమబాహు త్రిభుజం భుజం 9 సెం.మీ. చుట్టుకొలత?§Equilateral triangle side 9 cm. Perimeter?',['27 సెం.మీ~27 cm','18 సెం.మీ~18 cm','81 సెం.మీ~81 cm','12 సెం.మీ~12 cm'],'27.§27.')]});
A('maths',[3,4],{id:'m15_fraccol',i:'🥭',te:'సమూహంలో భిన్నం',en:'Fractions of a Collection',kw:'fraction of a collection group fraction of a number sets bhinnam samuham భిన్నం సమూహం లెక్క',
n:['# సమూహం భిన్నం§# Fraction of a group','ఒక సమూహంలో కొంత భాగాన్ని భిన్నంగా చెప్పవచ్చు. 12 మామిడిపండ్లలో 3 పచ్చివి → 3/12 = 1/4.§Part of a group as a fraction. 3 of 12 mangoes are raw → 3/12 = 1/4.','# భిన్నం విలువ§# Value of fraction','ఛేదంతో భాగించి అంశంతో గుణించండి. 20 లో 3/4 = 20÷4×3 = 15.§Divide by the denominator, multiply by the numerator. 3/4 of 20 = 20÷4×3 = 15.','# ఉదాహరణ§# Example','24 పెన్సిళ్లలో 2/3 = 24÷3×2 = 16.§2/3 of 24 pencils = 24÷3×2 = 16.','# మిగిలినవి§# Remainder','24 లో 2/3 తీసుకుంటే మిగిలినది 1/3 = 8.§If 2/3 of 24 is taken, 1/3 = 8 remains.','# సారాంశం§# Summary','భాగించడం ముందు, గుణించడం తర్వాత.§Divide first, multiply next.'],
q:[Q('20 లో 3/4?§3/4 of 20?',['15','5','12','23'],'15.§15.'),Q('24 లో 2/3?§2/3 of 24?',['16','8','12','48'],'16.§16.'),Q('12 లో 3 పచ్చి మామిడి. భిన్నం?§3 of 12 are raw. Fraction?',['1/4','1/3','3/4','1/2'],'3/12 = 1/4.§3/12 = 1/4.'),Q('40 లో 1/5?§1/5 of 40?',['8','5','35','200'],'8.§8.'),Q('36 లో 5/6?§5/6 of 36?',['30','6','25','36'],'30.§30.')]});
A('maths',[3,4],{id:'m15_bills3',i:'🧾',te:'బిల్లులు, షాపింగ్ లెక్కలు',en:'Bills and Shopping Sums',kw:'bill shopping total price quantity change receipt bill lekkalu బిల్లు షాపింగ్ మొత్తం ధర చిల్లర',
n:['# బిల్లు§# Bill','వస్తువు, పరిమాణం, ధర, మొత్తం ఉంటాయి. మొత్తం = పరిమాణం × ధర.§A bill lists item, quantity, rate and amount. Amount = quantity × rate.','# ఉదాహరణ§# Example','3 కిలోల బియ్యం ₹48/కిలో = ₹144; 2 కిలోల పప్పు ₹110/కిలో = ₹220; మొత్తం ₹364.§3 kg rice at ₹48 = ₹144; 2 kg dal at ₹110 = ₹220; total ₹364.','# చిల్లర§# Change','ఇచ్చిన డబ్బు − బిల్లు = చిల్లర. ₹500 ఇస్తే ₹136.§Money given − bill = change. Give ₹500 → ₹136.','# తనిఖీ§# Check','ప్రతి వరుస గుణకారం, మొత్తం కూడికను తనిఖీ చేయండి.§Check each multiplication and the final addition.','# సారాంశం§# Summary','బిల్లు తీసుకోవడం మంచి అలవాటు.§Taking a bill is a good habit.'],
q:[Q('3 కిలోలు ₹48/కిలో?§3 kg at ₹48/kg?',['₹144','₹51','₹124','₹154'],'144.§144.'),Q('₹144 + ₹220 = ?§₹144 + ₹220 = ?',['₹364','₹354','₹374','₹264'],'364.§364.'),Q('₹500 ఇస్తే ₹364 బిల్లుకు చిల్లర?§Pay ₹500 on a ₹364 bill. Change?',['₹136','₹146','₹126','₹236'],'136.§136.'),Q('2 డజన్ల అరటిపండ్లు డజను ₹36. ఖర్చు?§2 dozen bananas at ₹36 a dozen. Cost?',['₹72','₹38','₹62','₹92'],'72.§72.'),Q('బిల్లులో "మొత్తం" ఎలా వస్తుంది?§How is the amount on a bill found?',['పరిమాణం × ధర~Quantity × rate','పరిమాణం + ధర~Quantity + rate','ధర − పరిమాణం~Rate − quantity','ధర ÷ పరిమాణం~Rate ÷ quantity'],'గుణకారం.§Multiplication.')]});
LD.reg('bmat15-9',1)})();
