// Science topic bank (original text; facts standard school science). Helper: Q(question te§en, [correct te~en, w1, w2, w3], explanation te§en)
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
A('science',[6,7,8,9,10],{id:'photo',i:'🌿',te:'కిరణజన్య సంయోగక్రియ (ఫొటోసింథసిస్)',en:'Photosynthesis',fl:{cap:'కిరణజన్య సంయోగక్రియ దశలు§Steps of photosynthesis',steps:['☀️ సూర్యకాంతి + 💧 నీరు + CO₂§☀️ Sunlight + 💧 water + CO₂','🌿 ఆకులోని క్లోరోఫిల్ (క్లోరోప్లాస్ట్)§🌿 Chlorophyll in the leaf (chloroplast)','🍬 గ్లూకోజ్ (ఆహారం) + ఆక్సిజన్ విడుదల§🍬 Glucose (food) + oxygen released']},ex:'కిరణజన్య సంయోగక్రియ: పచ్చని మొక్కలు క్లోరోఫిల్ సహాయంతో సూర్యకాంతి సమక్షంలో కార్బన్ డయాక్సైడ్, నీటి నుంచి గ్లూకోజ్ తయారు చేసి ఆక్సిజన్ విడుదల చేసే ప్రక్రియ. సమీకరణం: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂.§Photosynthesis: the process in which green plants, using chlorophyll and sunlight, make glucose from carbon dioxide and water and release oxygen. Equation: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂.',kw:'photosynthesis chlorophyll sunlight glucose oxygen stomata leaf kiranajanya sanyogakriya క్లోరోఫిల్ ఆకులు ఆహారం తయారీ',
n:['# సారాంశం§# Summary','మొక్కలు సూర్యకాంతి సహాయంతో కార్బన్ డయాక్సైడ్, నీటి నుంచి తమ ఆహారాన్ని (గ్లూకోజ్) తయారు చేసుకునే ప్రక్రియను కిరణజన్య సంయోగక్రియ అంటారు. దీనిలో ఆక్సిజన్ విడుదలవుతుంది.§Photosynthesis is the process by which plants make their food (glucose) from carbon dioxide and water using sunlight. Oxygen is released.','# సమీకరణం§# Equation','6CO₂ + 6H₂O → (సూర్యకాంతి, క్లోరోఫిల్) → C₆H₁₂O₆ + 6O₂§6CO₂ + 6H₂O → (sunlight, chlorophyll) → C₆H₁₂O₆ + 6O₂','# ఎక్కడ జరుగుతుంది§# Where it happens','ఆకుల్లోని పత్రహరితం (క్లోరోఫిల్) ఉన్న క్లోరోప్లాస్ట్‌లలో జరుగుతుంది. నీరు వేర్ల ద్వారా, కార్బన్ డయాక్సైడ్ పత్రరంధ్రాల (స్టోమాటా) ద్వారా ఆకులోకి వెళ్తాయి.§It happens in chloroplasts that contain chlorophyll. Water comes up through roots and carbon dioxide enters through stomata.','# కావలసినవి§# Requirements','సూర్యకాంతి, క్లోరోఫిల్, కార్బన్ డయాక్సైడ్, నీరు.§Sunlight, chlorophyll, carbon dioxide and water.','# ఎందుకు ముఖ్యం§# Why it matters','ఇది అన్ని ఆహార శృంఖలాలకు ఆధారం, గాలికి ఆక్సిజన్ ఇస్తుంది, కార్బన్ డయాక్సైడ్‌ను తగ్గిస్తుంది. మొక్కలు మిగిలిన గ్లూకోజ్‌ను పిండిపదార్థంగా నిల్వ చేస్తాయి.§It supports every food chain, gives oxygen and uses up carbon dioxide. Plants store extra glucose as starch.','> ప్రయోగం: ఒక ఆకుపై అయోడిన్ వేస్తే పిండిపదార్థం ఉంటే నీలి-నలుపు రంగు వస్తుంది.§> Test: iodine on a leaf turns blue-black if starch is present.'],
q:[Q('కిరణజన్య సంయోగక్రియలో విడుదలయ్యే వాయువు?§Which gas is released in photosynthesis?',['ఆక్సిజన్~Oxygen','కార్బన్ డయాక్సైడ్~Carbon dioxide','నైట్రోజన్~Nitrogen','హైడ్రోజన్~Hydrogen'],'మొక్కలు ఆక్సిజన్ విడుదల చేస్తాయి§Plants release oxygen'),
Q('పత్రహరితం ఉండే భాగం?§Chlorophyll is found in?',['క్లోరోప్లాస్ట్~Chloroplast','కేంద్రకం~Nucleus','మైటోకాండ్రియా~Mitochondria','రైబోసోమ్~Ribosome'],'క్లోరోప్లాస్ట్‌లో క్లోరోఫిల్ ఉంటుంది§Chlorophyll is in chloroplasts'),
Q('ఆకుల్లో గాలి ప్రవేశించే చిన్న రంధ్రాలు?§Tiny pores in leaves for gases?',['పత్రరంధ్రాలు~Stomata','వేరు రోమాలు~Root hairs','కాండం~Stem','పుష్పం~Flower'],'స్టోమాటా ద్వారా వాయు మార్పిడి జరుగుతుంది§Gas exchange happens through stomata'),
Q('కిరణజన్య సంయోగక్రియలో తయారయ్యే ఆహారం?§Food made in photosynthesis?',['గ్లూకోజ్~Glucose','ప్రోటీన్~Protein','కొవ్వు~Fat','విటమిన్~Vitamin'],'మొదట గ్లూకోజ్ తయారవుతుంది§Glucose is made first'),
Q('కిరణజన్య సంయోగక్రియకు అవసరం కానిది?§Not needed for photosynthesis?',['ఆక్సిజన్~Oxygen','సూర్యకాంతి~Sunlight','నీరు~Water','కార్బన్ డయాక్సైడ్~Carbon dioxide'],'ఆక్సిజన్ ఉత్పత్తి అవుతుంది, అవసరం కాదు§Oxygen is a product, not a requirement')]});
A('science',[7,8,9,10],{id:'resp',i:'🫁',te:'శ్వాసక్రియ',en:'Respiration',kw:'respiration breathing aerobic anaerobic glucose energy atp lungs shwasakriya శ్వాస శక్తి ఊపిరితిత్తులు',
n:['శ్వాసక్రియ అంటే ఆహారం (గ్లూకోజ్) ఆక్సిజన్‌తో విచ్ఛిన్నమై శక్తి విడుదలవడం. ఇది అన్ని జీవ కణాల్లో జరుగుతుంది.§Respiration is the breakdown of food (glucose) to release energy. It happens in all living cells.','ఆక్సిజన్ ఉన్నప్పుడు జరిగేది వాయుసహిత శ్వాసక్రియ: గ్లూకోజ్ + ఆక్సిజన్ → కార్బన్ డయాక్సైడ్ + నీరు + శక్తి.§With oxygen it is aerobic respiration: glucose + oxygen → carbon dioxide + water + energy.','ఆక్సిజన్ లేకుండా జరిగేది అవాయు శ్వాసక్రియ. ఈస్ట్‌లో ఆల్కహాల్ + CO₂, కండరాల్లో లాక్టిక్ ఆమ్లం తయారవుతుంది.§Without oxygen it is anaerobic respiration. Yeast makes alcohol and CO₂; muscles make lactic acid.','శ్వాస తీసుకోవడం (ఊపిరి) శ్వాసక్రియ కాదు; అది ఆక్సిజన్ లోపలికి తీసుకోవడం మాత్రమే. శక్తి కణాల్లో విడుదలవుతుంది.§Breathing is not respiration itself; it only brings oxygen in. Energy is released inside cells.','కణంలో శక్తి ATP రూపంలో ఉంటుంది; మైటోకాండ్రియాను కణ శక్తి కేంద్రం అంటారు.§Energy in cells is held as ATP; mitochondria are the powerhouse of the cell.'],
q:[Q('శ్వాసక్రియలో విడుదలయ్యేది?§Respiration releases?',['శక్తి~Energy','ఆక్సిజన్~Oxygen','క్లోరోఫిల్~Chlorophyll','సూర్యకాంతి~Sunlight'],'ఆహారం నుంచి శక్తి వస్తుంది§Energy comes from food'),
Q('కణ శక్తి కేంద్రం?§Powerhouse of the cell?',['మైటోకాండ్రియా~Mitochondria','కేంద్రకం~Nucleus','రైబోసోమ్~Ribosome','వాక్యూల్~Vacuole'],'మైటోకాండ్రియాలో ATP తయారవుతుంది§ATP is made in mitochondria'),
Q('కండరాల్లో అవాయు శ్వాసక్రియలో తయారయ్యేది?§Anaerobic respiration in muscles makes?',['లాక్టిక్ ఆమ్లం~Lactic acid','ఆల్కహాల్~Alcohol','నీరు మాత్రమే~Only water','ఆక్సిజన్~Oxygen'],'ఎక్కువ వ్యాయామంలో లాక్టిక్ ఆమ్లం పేరుకుంటుంది§Lactic acid builds up in hard exercise'),
Q('వాయుసహిత శ్వాసక్రియలో వాడేది?§Aerobic respiration uses?',['ఆక్సిజన్~Oxygen','నైట్రోజన్~Nitrogen','హీలియం~Helium','ఆర్గాన్~Argon'],'ఆక్సిజన్ అవసరం§Oxygen is needed')]});
A('science',[8,9,10],{id:'genet',i:'🧬',te:'అనువంశికత (జన్యుశాస్త్రం)',en:'Heredity and genetics',kw:'genetics heredity mendel gene dna chromosome dominant recessive traits variation anuvamshikata జన్యువులు క్రోమోజోములు మెండల్ లక్షణాలు',
n:['అనువంశికత అంటే తల్లిదండ్రుల లక్షణాలు పిల్లలకు వెళ్లడం. పిల్లలు తల్లిదండ్రులను పూర్తిగా పోలి ఉండరు; ఈ తేడాలను వైవిధ్యాలు అంటారు.§Heredity is the passing of traits from parents to children. Offspring are not exactly like parents; such differences are called variations.','జన్యువులు DNAలో ఉండే భాగాలు. DNA క్రోమోజోముల్లో ఉంటుంది. మనిషి కణంలో 46 క్రోమోజోములు (23 జతలు) ఉంటాయి.§Genes are sections of DNA. DNA is packed in chromosomes. A human cell has 46 chromosomes (23 pairs).','గ్రెగర్ మెండల్ బఠానీ మొక్కలతో ప్రయోగాలు చేసి అనువంశికత నియమాలు కనుగొన్నారు, అందుకే ఆయనను జన్యుశాస్త్ర పితామహుడు అంటారు.§Gregor Mendel studied pea plants and found the rules of heredity, so he is called the father of genetics.','ప్రబల లక్షణం (ఉదా: ఎత్తు T) జతలో ఒకటి ఉన్నా కనిపిస్తుంది; ఆవర్తన లక్షణం (t) రెండూ ఆవర్తనమైతేనే కనిపిస్తుంది. Tt × Tt నుంచి ఎత్తు:పొడవు = 3:1 నిష్పత్తి.§A dominant trait (T, tall) shows even with one copy; a recessive trait (t) shows only when both copies are recessive. Tt × Tt gives tall:short in a 3:1 ratio.','అబ్బాయా అమ్మాయా అనేది X, Y క్రోమోజోముల వల్ల నిర్ణయమవుతుంది: XX = ఆడ, XY = మగ. తండ్రి నుంచి వచ్చే క్రోమోజోమ్ నిర్ణయిస్తుంది.§Sex is decided by X and Y chromosomes: XX is female, XY is male. The chromosome from the father decides.'],
q:[Q('జన్యుశాస్త్ర పితామహుడు?§Father of genetics?',['గ్రెగర్ మెండల్~Gregor Mendel','చార్లెస్ డార్విన్~Charles Darwin','లూయీ పాశ్చర్~Louis Pasteur','న్యూటన్~Newton'],'మెండల్ బఠానీ ప్రయోగాలు చేశారు§Mendel experimented with peas'),
Q('మనిషిలో క్రోమోజోముల సంఖ్య?§Number of chromosomes in a human cell?',['46','23','44','48'],'23 జతలు = 46§23 pairs = 46'),
Q('Tt × Tt సంకరణలో ఎత్తు:పొట్టి నిష్పత్తి?§Tall:short ratio in Tt × Tt?',['3:1','1:1','2:1','1:3'],'TT, Tt, Tt ఎత్తు; tt పొట్టి§TT, Tt, Tt are tall; tt is short'),
Q('ఆడ శిశువులో లింగ క్రోమోజోములు?§Sex chromosomes of a girl?',['XX','XY','YY','XO'],'XX అంటే ఆడ§XX means female')]});
A('science',[3,4,5,6,7],{id:'wcycle',i:'🌧️',te:'నీటి చక్రం',en:'Water cycle',kw:'water cycle evaporation condensation precipitation rain clouds neeti chakram బాష్పీభవనం సాంద్రీకరణ వర్షం మేఘాలు',
fl:{cap:'నీటి చక్రం§The water cycle',steps:['☀️ బాష్పీభవనం: సూర్యుని వేడికి నీరు ఆవిరి అవుతుంది§☀️ Evaporation: the sun heats water into vapour','☁️ సాంద్రీకరణ: ఆవిరి చల్లబడి మేఘాలు ఏర్పడతాయి§☁️ Condensation: vapour cools into clouds','🌧️ అవపాతం: వర్షం, మంచు రూపంలో నీరు కురుస్తుంది§🌧️ Precipitation: water falls as rain or snow','🏞️ నదులు, సముద్రాలకు నీరు చేరుతుంది§🏞️ Water flows back to rivers and seas'],loop:'చక్రం మళ్ళీ మొదలవుతుంది§The cycle repeats'},
ex:'నీటి చక్రం అంటే నీరు భూమి, సముద్రం, గాలి మధ్య తిరిగే నిరంతర ప్రక్రియ: బాష్పీభవనం, సాంద్రీకరణ, అవపాతం.§The water cycle is the continuous movement of water between land, sea and air: evaporation, condensation and precipitation.',
n:['సూర్యుని వేడికి సముద్రాలు, నదులు, చెరువుల నుంచి నీరు ఆవిరిగా మారడాన్ని బాష్పీభవనం అంటారు.§Evaporation is when the sun heats water in seas, rivers and ponds and turns it into vapour.','ఆవిరి పైకి వెళ్లి చల్లబడి చిన్న నీటి బిందువులుగా మారి మేఘాలు ఏర్పడతాయి. దీన్ని సాంద్రీకరణ అంటారు.§Vapour rises, cools and turns into tiny droplets that form clouds. This is condensation.','మేఘాల్లో బిందువులు పెద్దవై వర్షం, మంచు లేదా వడగళ్ళుగా కిందకు పడతాయి. దీన్ని అవపాతం అంటారు.§Droplets grow heavy and fall as rain, snow or hail. This is precipitation.','కురిసిన నీరు నదులు, భూగర్భ జలాల ద్వారా మళ్ళీ సముద్రానికి చేరుతుంది. అందుకే నీటి చక్రం ఆగదు.§The water flows back to the sea through rivers and groundwater, so the cycle never stops.','మొక్కల ఆకుల నుంచి నీరు ఆవిరవడాన్ని బాష్పోత్సేకం అంటారు; అది కూడా నీటి చక్రంలో భాగం.§Water leaving plant leaves as vapour is called transpiration, also a part of the cycle.'],
q:[Q('సూర్యుని వేడికి నీరు ఆవిరవడం?§Water turning to vapour by heat from the sun?',['బాష్పీభవనం~Evaporation','సాంద్రీకరణ~Condensation','అవపాతం~Precipitation','ఘనీభవనం~Freezing'],'ద్రవం ఆవిరి కావడం బాష్పీభవనం§Liquid to vapour is evaporation'),
Q('మేఘాలు ఏర్పడే దశ?§Clouds form in which step?',['సాంద్రీకరణ~Condensation','బాష్పీభవనం~Evaporation','అవపాతం~Precipitation','ప్రవాహం~Runoff'],'ఆవిరి చల్లబడి బిందువులవుతుంది§Vapour cools into droplets'),
Q('వర్షం కురవడాన్ని ఏమంటారు?§Rain falling is called?',['అవపాతం~Precipitation','బాష్పీభవనం~Evaporation','సాంద్రీకరణ~Condensation','బాష్పోత్సేకం~Transpiration'],'వర్షం, మంచు, వడగళ్ళు అవపాతం§Rain, snow and hail are precipitation'),
Q('మొక్కల ఆకుల నుంచి నీరు ఆవిరవడం?§Water vapour loss from leaves?',['బాష్పోత్సేకం~Transpiration','అవపాతం~Precipitation','ఘనీభవనం~Freezing','కరగడం~Melting'],'ఇది నీటి చక్రంలో భాగం§It is part of the water cycle')]});
A('science',[4,5,6,7],{id:'fchain',i:'🦊',te:'ఆహార గొలుసు',en:'Food chain',kw:'food chain food web producer consumer decomposer herbivore carnivore ahara golusu ఆహార శృంఖల ఉత్పత్తిదారులు వినియోగదారులు విచ్ఛిన్నకారులు',
fl:{cap:'ఒక ఆహార గొలుసు§A food chain',steps:['🌿 గడ్డి (ఉత్పత్తిదారు)§🌿 Grass (producer)','🐇 కుందేలు (శాకాహారి)§🐇 Rabbit (herbivore)','🦊 నక్క (మాంసాహారి)§🦊 Fox (carnivore)','🍄 విచ్ఛిన్నకారులు (శిలీంధ్రాలు, బాక్టీరియా)§🍄 Decomposers (fungi, bacteria)']},
ex:'ఆహార గొలుసు అంటే ఒక జీవి మరొక జీవిని తింటూ శక్తి బదిలీ అయ్యే వరుస. ఇది ఉత్పత్తిదారుతో మొదలవుతుంది.§A food chain is a sequence in which energy passes as one organism eats another. It starts with a producer.',
n:['ఉత్పత్తిదారులు సూర్యకాంతితో తమ ఆహారాన్ని తయారు చేసుకునే మొక్కలు.§Producers are plants that make their own food using sunlight.','వినియోగదారులు ఆహారం కోసం ఇతర జీవులపై ఆధారపడతాయి: శాకాహారులు (మొక్కలు), మాంసాహారులు (జంతువులు), సర్వభక్షకులు (రెండూ).§Consumers depend on others for food: herbivores (plants), carnivores (animals) and omnivores (both).','విచ్ఛిన్నకారులు (శిలీంధ్రాలు, బాక్టీరియా) చనిపోయిన జీవులను కుళ్లబెట్టి పోషకాలను నేలకు తిరిగి ఇస్తాయి.§Decomposers (fungi, bacteria) break down dead organisms and return nutrients to the soil.','అనేక ఆహార గొలుసులు కలిస్తే ఆహార జాలం అవుతుంది.§Many food chains joined together make a food web.','శక్తి ప్రతి స్థాయిలో తగ్గుతూ వెళ్తుంది; సుమారు 10% మాత్రమే తరువాతి స్థాయికి చేరుతుంది.§Energy decreases at each level; only about 10% passes to the next level.'],
q:[Q('ఆహార గొలుసు ఎవరితో మొదలవుతుంది?§A food chain starts with?',['ఉత్పత్తిదారు~A producer','మాంసాహారి~A carnivore','విచ్ఛిన్నకారి~A decomposer','శాకాహారి~A herbivore'],'మొక్కలు మొదటి ఆహార వనరు§Plants are the first source of food'),
Q('కుందేలు ఏ రకం వినియోగదారు?§A rabbit is a?',['శాకాహారి~Herbivore','మాంసాహారి~Carnivore','సర్వభక్షకి~Omnivore','ఉత్పత్తిదారు~Producer'],'కుందేలు గడ్డి తింటుంది§A rabbit eats grass'),
Q('చనిపోయిన జీవులను కుళ్లబెట్టేవి?§Which break down dead matter?',['విచ్ఛిన్నకారులు~Decomposers','ఉత్పత్తిదారులు~Producers','శాకాహారులు~Herbivores','మాంసాహారులు~Carnivores'],'శిలీంధ్రాలు, బాక్టీరియా§Fungi and bacteria'),
Q('ఒక స్థాయి నుంచి తరువాతికి చేరే శక్తి సుమారు?§Energy passed to the next level is about?',['10%','50%','90%','100%'],'10% నియమం§The 10% rule')]});
LD.reg('bsci',1)})();
