// Science batch 2 (AksharaNova). Facts are standard school-level science; sources: NCERT Science Classes 6-10 (ncert.nic.in), Telangana SCERT Science textbooks (scert.telangana.gov.in), Britannica/Wikipedia for cross-check.
// Class placement is approximate to SCERT/NCERT chapter positions.
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
// Sources: NCERT Class 8 'Cell - Structure and Functions'; NCERT Class 9 'The Fundamental Unit of Life'
A('science',[8,9],{id:'cell',i:'🔬',te:'కణం - జీవ ప్రాథమిక ప్రమాణం',en:'The Cell',kw:'cell nucleus cytoplasm cell membrane cell wall mitochondria chloroplast vacuole robert hooke kanam కణం కేంద్రకం కణత్వచం కణకవచం',
n:['# సారాంశం§# Summary','కణం జీవులకు నిర్మాణ, క్రియా ప్రమాణం. అన్ని జీవులు ఒకటి లేదా ఎక్కువ కణాలతో ఏర్పడతాయి.§The cell is the structural and functional unit of life. All organisms are made of one or more cells.','# కణ భాగాలు§# Cell parts','కణత్వచం కణం లోపలికి, బయటికి పోయే పదార్థాలను నియంత్రిస్తుంది. కేంద్రకం కణ కార్యకలాపాలను నియంత్రిస్తుంది, DNA ఇందులో ఉంటుంది. కణద్రవ్యంలో (సైటోప్లాజం) కణాంగాలు ఉంటాయి.§The cell membrane controls what enters and leaves. The nucleus controls cell activities and holds DNA. Organelles lie in the cytoplasm.','# కణాంగాలు§# Organelles','మైటోకాండ్రియా శ్వాసక్రియ ద్వారా శక్తిని విడుదల చేస్తుంది (కణ శక్తి కేంద్రం). రైబోసోమ్‌లు ప్రోటీన్లను తయారు చేస్తాయి. వాక్యూల్ పదార్థాలను నిల్వ చేస్తుంది.§Mitochondria release energy by respiration (powerhouse). Ribosomes make proteins. Vacuoles store substances.','# మొక్క - జంతు కణం§# Plant vs animal cell','మొక్క కణాలకు కణకవచం (సెల్యులోజ్), క్లోరోప్లాస్ట్‌లు, పెద్ద వాక్యూల్ ఉంటాయి. జంతు కణాలకు కణకవచం, క్లోరోప్లాస్ట్‌లు ఉండవు.§Plant cells have a cellulose cell wall, chloroplasts and a large vacuole. Animal cells lack a cell wall and chloroplasts.','> 1665లో రాబర్ట్ హుక్ కార్క్ ముక్కలో చిన్న గదులను చూసి వాటికి "సెల్" అని పేరు పెట్టాడు.§> In 1665 Robert Hooke saw small chambers in cork and named them "cells".','అమీబా వంటి ఏకకణ జీవులు, మానవుడు వంటి బహుకణ జీవులు ఉంటాయి.§Amoeba is unicellular; humans are multicellular.'],
q:[Q('కణాన్ని మొదట చూసిన శాస్త్రవేత్త?§Who first observed cells?',['రాబర్ట్ హుక్~Robert Hooke','చార్లెస్ డార్విన్~Charles Darwin','లూయీ పాశ్చర్~Louis Pasteur','గ్రెగర్ మెండల్~Gregor Mendel'],'1665లో కార్క్‌లో చూశాడు§Seen in cork in 1665'),
Q('కణ శక్తి కేంద్రం అని దేన్ని అంటారు?§Which is called the powerhouse of the cell?',['మైటోకాండ్రియా~Mitochondria','కేంద్రకం~Nucleus','రైబోసోమ్~Ribosome','వాక్యూల్~Vacuole'],'మైటోకాండ్రియాలో శ్వాసక్రియ ద్వారా శక్తి విడుదల§Energy is released by respiration there'),
Q('జంతు కణంలో ఉండనిది?§Absent in animal cells?',['కణకవచం~Cell wall','కేంద్రకం~Nucleus','కణత్వచం~Cell membrane','మైటోకాండ్రియా~Mitochondria'],'కణకవచం మొక్కల్లో ఉంటుంది§Cell wall is found in plants'),
Q('కణ కార్యకలాపాలను నియంత్రించే భాగం?§Which part controls cell activities?',['కేంద్రకం~Nucleus','కణత్వచం~Cell membrane','వాక్యూల్~Vacuole','కణద్రవ్యం~Cytoplasm'],'కేంద్రకంలో DNA ఉంటుంది§The nucleus holds DNA'),
Q('ఏకకణ జీవి ఏది?§Which is a unicellular organism?',['అమీబా~Amoeba','కుక్క~Dog','మామిడి చెట్టు~Mango tree','చేప~Fish'],'అమీబా ఒకే కణంతో ఉంటుంది§Amoeba has a single cell'),
Q('మొక్క కణకవచం దేనితో తయారవుతుంది?§Plant cell wall is made of?',['సెల్యులోజ్~Cellulose','ప్రోటీన్~Protein','కొవ్వు~Fat','గ్లూకోజ్~Glucose'],'సెల్యులోజ్ దృఢత్వాన్ని ఇస్తుంది§Cellulose gives rigidity')]});
// Sources: NCERT Class 7 'Acids, Bases and Salts'; NCERT Class 10 'Acids, Bases and Salts'
A('science',[7,10],{id:'acidbase',i:'🧪',te:'ఆమ్లాలు, క్షారాలు, లవణాలు',en:'Acids, Bases and Salts',kw:'acid base salt litmus indicator ph neutralisation turmeric amlalu ksharalu lavanalu ఆమ్లం క్షారం లవణం లిట్మస్ ఉదాసీనీకరణ',
n:['# సారాంశం§# Summary','ఆమ్లాలు పుల్లని రుచి కలిగి నీలి లిట్మస్‌ను ఎరుపుగా మారుస్తాయి. క్షారాలు ఎర్ర లిట్మస్‌ను నీలిగా మారుస్తాయి, జారుడుగా ఉంటాయి. రుచి చూసి పరీక్షించకూడదు.§Acids taste sour and turn blue litmus red. Bases turn red litmus blue and feel soapy. Never taste chemicals to test them.','# ఉదాహరణలు§# Examples','ఆమ్లాలు: నిమ్మలో సిట్రిక్ ఆమ్లం, చింతపండులో టార్టారిక్ ఆమ్లం, పెరుగులో లాక్టిక్ ఆమ్లం, HCl. క్షారాలు: సున్నపు తేట (కాల్షియం హైడ్రాక్సైడ్), సోడియం హైడ్రాక్సైడ్, మెగ్నీషియా పాలు.§Acids: citric acid in lemon, tartaric acid in tamarind, lactic acid in curd, HCl. Bases: calcium hydroxide, sodium hydroxide, milk of magnesia.','# pH స్కేలు§# pH scale','pH 0-14 వరకు ఉంటుంది. 7 కంటే తక్కువ ఆమ్లం, 7 తటస్థం (స్వచ్ఛమైన నీరు), 7 కంటే ఎక్కువ క్షారం.§pH runs 0-14. Below 7 is acidic, 7 is neutral (pure water), above 7 is basic.','# తటస్థీకరణ§# Neutralisation','ఆమ్లం, క్షారం కలిసి లవణం, నీరు ఏర్పడే చర్యను తటస్థీకరణ అంటారు. HCl + NaOH → NaCl + H₂O.§Acid + base gives salt + water. HCl + NaOH → NaCl + H₂O.','> చీమ కుట్టినప్పుడు ఫార్మిక్ ఆమ్లం వల్ల మంట వస్తుంది; బేకింగ్ సోడా రాస్తే ఉపశమనం.§> An ant sting has formic acid; baking soda gives relief.','అజీర్ణానికి యాంటాసిడ్ (క్షారం) ఉపయోగిస్తారు, ఎందుకంటే కడుపులో అదనపు ఆమ్లం తటస్థమవుతుంది.§Antacids (bases) cure indigestion by neutralising excess stomach acid.'],
q:[Q('నీలి లిట్మస్‌ను ఎరుపుగా మార్చేది?§What turns blue litmus red?',['ఆమ్లం~Acid','క్షారం~Base','లవణం~Salt','నీరు~Water'],'ఆమ్లాలు నీలి లిట్మస్‌ను ఎరుపు చేస్తాయి§Acids turn blue litmus red'),
Q('స్వచ్ఛమైన నీటి pH?§pH of pure water?',['7','1','10','14'],'7 తటస్థం§7 is neutral'),
Q('నిమ్మలో ఉండే ఆమ్లం?§Acid in lemon?',['సిట్రిక్ ఆమ్లం~Citric acid','లాక్టిక్ ఆమ్లం~Lactic acid','ఎసిటిక్ ఆమ్లం~Acetic acid','ఫార్మిక్ ఆమ్లం~Formic acid'],'నిమ్మ, నారింజలో సిట్రిక్ ఆమ్లం§Citrus fruits have citric acid'),
Q('HCl + NaOH చర్యలో ఏర్పడే లవణం?§Salt formed from HCl + NaOH?',['సోడియం క్లోరైడ్~Sodium chloride','సోడియం సల్ఫేట్~Sodium sulphate','కాల్షియం క్లోరైడ్~Calcium chloride','పొటాషియం క్లోరైడ్~Potassium chloride'],'NaCl (వంట ఉప్పు)§NaCl (common salt)'),
Q('అజీర్ణానికి వాడే మందు ఏ రకం?§Medicine used for indigestion is a?',['క్షారం (యాంటాసిడ్)~Base (antacid)','ఆమ్లం~Acid','లవణం~Salt','ఏదీ కాదు~None'],'అదనపు ఆమ్లాన్ని తటస్థం చేస్తుంది§It neutralises excess acid'),
Q('pH 3 ఉన్న ద్రావణం?§A solution with pH 3 is?',['ఆమ్లం~Acidic','క్షారం~Basic','తటస్థం~Neutral','చెప్పలేం~Cannot say'],'7 కంటే తక్కువ = ఆమ్లం§Below 7 is acidic')]});
// Sources: NCERT Class 6 'Electricity and Circuits'; NCERT Class 10 'Electricity' (Ohm's law V=IR)
A('science',[6,7,8,10],{id:'electric',i:'💡',te:'విద్యుత్ ప్రవాహం, ఓం నియమం',en:'Electric Current and Ohm\'s Law',kw:'electricity current voltage resistance ohm law circuit conductor insulator ampere volt vidyut ఓం నియమం విద్యుత్ వలయం వాహకం బంధకం',
n:['# సారాంశం§# Summary','విద్యుత్ ఆవేశాల ప్రవాహాన్ని విద్యుత్ ప్రవాహం అంటారు. ప్రమాణం ఆంపియర్ (A). దీన్ని అమ్మీటర్‌తో కొలుస్తారు.§Flow of electric charge is current. Its unit is the ampere (A), measured with an ammeter.','# వాహకాలు, బంధకాలు§# Conductors and insulators','లోహాలు (రాగి, అల్యూమినియం) విద్యుత్‌ను బాగా ప్రసరింపజేస్తాయి - వాహకాలు. ప్లాస్టిక్, రబ్బరు, గాజు ప్రసరింపజేయవు - బంధకాలు.§Metals like copper and aluminium conduct electricity. Plastic, rubber and glass do not - insulators.','# ఓం నియమం§# Ohm\'s law','స్థిర ఉష్ణోగ్రత వద్ద వాహకం గుండా ప్రవహించే విద్యుత్ ప్రవాహం దాని చివరల మధ్య పొటెన్షియల్ భేదానికి అనులోమానుపాతంలో ఉంటుంది. V = I × R.§At constant temperature, current through a conductor is proportional to the potential difference across it. V = I × R.','# ప్రమాణాలు§# Units','పొటెన్షియల్ భేదం - వోల్ట్ (V), వోల్ట్‌మీటర్‌తో కొలుస్తారు. నిరోధం - ఓం (Ω).§Potential difference - volt (V), measured by a voltmeter. Resistance - ohm (Ω).','> 2 Ω నిరోధం గుండా 3 A ప్రవహిస్తే V = 3 × 2 = 6 V.§> If 3 A flows through 2 Ω, V = 3 × 2 = 6 V.','సిరీస్‌లో ఒకే ప్రవాహం అన్నింటి గుండా వెళ్తుంది; సమాంతరంలో ప్రతి శాఖకు ఒకే వోల్టేజ్ ఉంటుంది. తడి చేతులతో స్విచ్ ముట్టుకోకండి.§In series the same current passes through all; in parallel each branch has the same voltage. Never touch switches with wet hands.'],
q:[Q('విద్యుత్ ప్రవాహ ప్రమాణం?§Unit of electric current?',['ఆంపియర్~Ampere','వోల్ట్~Volt','ఓం~Ohm','వాట్~Watt'],'ప్రవాహం ఆంపియర్లలో§Current is in amperes'),
Q('ఓం నియమం సూత్రం?§Ohm\'s law formula?',['V = IR','V = I/R','I = VR','R = VI'],'V = I × R§V = I × R'),
Q('విద్యుత్ బంధకం ఏది?§Which is an insulator?',['రబ్బరు~Rubber','రాగి~Copper','ఇనుము~Iron','అల్యూమినియం~Aluminium'],'రబ్బరు విద్యుత్‌ను ప్రసరింపజేయదు§Rubber does not conduct'),
Q('నిరోధ ప్రమాణం?§Unit of resistance?',['ఓం~Ohm','ఆంపియర్~Ampere','వోల్ట్~Volt','జౌల్~Joule'],'ప్రమాణం Ω§Unit is Ω'),
Q('4 Ω నిరోధం గుండా 2 A ప్రవహిస్తే వోల్టేజ్?§Voltage if 2 A flows through 4 Ω?',['8 V','2 V','6 V','0.5 V'],'V = 2 × 4 = 8§V = 2 × 4 = 8'),
Q('అమ్మీటర్ దేన్ని కొలుస్తుంది?§Ammeter measures?',['విద్యుత్ ప్రవాహం~Current','వోల్టేజ్~Voltage','నిరోధం~Resistance','ఉష్ణోగ్రత~Temperature'],'ప్రవాహాన్ని కొలుస్తుంది§Measures current')]});
// Sources: NCERT Class 7 'Light'; NCERT Class 8 'Light'; NCERT Class 10 'Light - Reflection and Refraction'
A('science',[6,7,8,10],{id:'light',i:'🔦',te:'కాంతి - పరావర్తనం, వక్రీభవనం',en:'Light: Reflection and Refraction',kw:'light reflection refraction mirror lens rainbow speed of light kanti paravartanam vakribhavanam కాంతి పరావర్తనం వక్రీభవనం దర్పణం కటకం ఇంద్రధనుస్సు',
n:['# కాంతి ప్రయాణం§# How light travels','కాంతి ఏకరీతి యానకంలో సరళరేఖలో ప్రయాణిస్తుంది. శూన్యంలో దాని వేగం సుమారు 3 × 10⁸ మీ/సె.§Light travels in straight lines in a uniform medium. Its speed in vacuum is about 3 × 10⁸ m/s.','# పరావర్తనం§# Reflection','కాంతి ఒక తలంపై పడి వెనక్కి మరలడం పరావర్తనం. నియమాలు: పతన కోణం = పరావర్తన కోణం; పతన కిరణం, పరావర్తన కిరణం, లంబం ఒకే తలంలో ఉంటాయి.§Light bouncing off a surface is reflection. Laws: angle of incidence = angle of reflection; incident ray, reflected ray and normal lie in the same plane.','# సమతల దర్పణం§# Plane mirror','ప్రతిబింబం మిథ్యా, నిటారుగా, వస్తువు పరిమాణంలోనే ఉంటుంది; పార్శ్వ విలోమం ఉంటుంది.§The image is virtual, erect, same size, and laterally inverted.','# వక్రీభవనం§# Refraction','కాంతి ఒక యానకం నుంచి మరొకదానిలోకి వెళ్లేటప్పుడు దిశ మారడం వక్రీభవనం. గాలి నుంచి నీటిలోకి వెళ్తే లంబం వైపు వంగుతుంది.§Light bending when it passes from one medium to another is refraction. From air into water it bends towards the normal.','# కటకాలు, దర్పణాలు§# Lenses and mirrors','కుంభాకార కటకం కాంతిని కేంద్రీకరిస్తుంది, పుటాకార కటకం వ్యాపింపజేస్తుంది. కారు హెడ్‌లైట్లలో పుటాకార దర్పణం, వాహనాల సైడ్ మిర్రర్‌లో కుంభాకార దర్పణం వాడతారు.§A convex lens converges light; a concave lens diverges it. Headlights use concave mirrors; vehicle side mirrors use convex mirrors.','> నీటిలో ఉంచిన పెన్సిల్ వంగినట్లు కనిపించడం వక్రీభవనం వల్లే.§> A pencil in water looks bent because of refraction.','తెల్లని కాంతి ప్రిజంలో ఏడు రంగులుగా విడిపోతుంది (విక్షేపణం): ఊదా, ముదురు నీలం, నీలం, ఆకుపచ్చ, పసుపు, నారింజ, ఎరుపు.§White light splits into seven colours in a prism (dispersion): violet, indigo, blue, green, yellow, orange, red.'],
q:[Q('శూన్యంలో కాంతి వేగం సుమారు?§Speed of light in vacuum is about?',['3 × 10⁸ మీ/సె~3 × 10⁸ m/s','3 × 10⁵ మీ/సె~3 × 10⁵ m/s','340 మీ/సె~340 m/s','3 × 10³ మీ/సె~3 × 10³ m/s'],'సుమారు 3 లక్షల కి.మీ/సె§About 3 lakh km/s'),
Q('పతన కోణం 30° అయితే పరావర్తన కోణం?§If angle of incidence is 30°, angle of reflection?',['30°','60°','15°','90°'],'రెండూ సమానం§They are equal'),
Q('సమతల దర్పణంలో ప్రతిబింబం?§Image in a plane mirror is?',['మిథ్యా, నిటారు~Virtual, erect','నిజ, తలకిందులు~Real, inverted','నిజ, నిటారు~Real, erect','మిథ్యా, తలకిందులు~Virtual, inverted'],'సమతల దర్పణం మిథ్యా ప్రతిబింబం ఇస్తుంది§Plane mirror gives a virtual image'),
Q('కాంతిని కేంద్రీకరించే కటకం?§Which lens converges light?',['కుంభాకార~Convex','పుటాకార~Concave','సమతల~Plane','ఏదీ కాదు~None'],'కుంభాకార కటకం అభిసరణం§Convex lens converges'),
Q('ఇంద్రధనుస్సుకు కారణం?§Rainbow is caused by?',['విక్షేపణం~Dispersion','పరావర్తనం మాత్రమే~Reflection only','ధ్వని~Sound','అయస్కాంతం~Magnetism'],'నీటి బిందువుల్లో కాంతి విక్షేపణం§Dispersion of light in water drops'),
Q('వాహనాల సైడ్ మిర్రర్‌లో వాడే దర్పణం?§Mirror used as a vehicle side mirror?',['కుంభాకార~Convex','పుటాకార~Concave','సమతల~Plane','గోళాకార కాదు~Not spherical'],'విశాల దృశ్యం కనిపిస్తుంది§It gives a wide field of view')]});
// Sources: NCERT Class 8 'Sound'; NCERT Class 10 'Sound' (earlier ed.)
A('science',[8,9],{id:'sound',i:'🔊',te:'ధ్వని',en:'Sound',kw:'sound vibration frequency amplitude pitch echo hertz medium dhwani ధ్వని కంపనం పౌనఃపున్యం కంపనపరిమితి ప్రతిధ్వని',
n:['# సారాంశం§# Summary','కంపించే వస్తువుల వల్ల ధ్వని పుడుతుంది. ధ్వని ప్రసారానికి యానకం (ఘన, ద్రవ, వాయు) కావాలి; శూన్యంలో ప్రయాణించదు.§Sound is produced by vibrating objects. It needs a medium (solid, liquid or gas) and cannot travel in vacuum.','# లక్షణాలు§# Properties','పౌనఃపున్యం అంటే సెకనుకు కంపనాల సంఖ్య (ప్రమాణం హెర్ట్జ్). పౌనఃపున్యం ఎక్కువైతే స్వరస్థాయి (పిచ్) ఎక్కువ. కంపన పరిమితి ఎక్కువైతే ధ్వని గట్టిగా ఉంటుంది.§Frequency is vibrations per second (hertz). Higher frequency means higher pitch. Larger amplitude means louder sound.','# వినికిడి పరిధి§# Audible range','మానవులు సుమారు 20 Hz నుంచి 20,000 Hz వరకు వినగలరు. 20,000 Hz పైన అతిధ్వనులు (అల్ట్రాసౌండ్).§Humans hear roughly 20 Hz to 20,000 Hz. Above 20,000 Hz is ultrasound.','# వేగం§# Speed','గాలిలో ధ్వని వేగం సుమారు 340-343 మీ/సె (సుమారు 20-25°C వద్ద). సాధారణంగా ఘనాల్లో వేగం ఎక్కువ, వాయువుల్లో తక్కువ.§In air sound travels at about 340-343 m/s near room temperature. It is usually fastest in solids and slowest in gases.','# ప్రతిధ్వని§# Echo','ధ్వని గట్టి తలం నుంచి పరావర్తనం చెంది మళ్లీ వినిపించడం ప్రతిధ్వని. స్పష్టంగా వినాలంటే కనీసం సుమారు 17 మీ దూరం కావాలి.§An echo is reflected sound. To hear it clearly the reflecting surface should be at least about 17 m away.','> 17 మీ దూరం: ధ్వని వెళ్లి రావడానికి 34 మీ, 340 మీ/సె వేగంతో 0.1 సె; వినికిడి నిలుపుదల కాలం సుమారు 0.1 సె.§> 34 m round trip at 340 m/s takes 0.1 s, about the persistence of hearing.','అతిధ్వనులను ఆసుపత్రుల్లో స్కానింగ్‌కు, గబ్బిలాలు దారి కనుగొనడానికి ఉపయోగిస్తాయి.§Ultrasound is used in medical scans, and bats use it to navigate.'],
q:[Q('ధ్వని శూన్యంలో ప్రయాణిస్తుందా?§Can sound travel in vacuum?',['లేదు~No','అవును~Yes','కొన్నిసార్లు~Sometimes','వేగంగా~Faster'],'యానకం అవసరం§A medium is needed'),
Q('పౌనఃపున్య ప్రమాణం?§Unit of frequency?',['హెర్ట్జ్~Hertz','డెసిబెల్~Decibel','మీటర్~Metre','వాట్~Watt'],'Hz§Hz'),
Q('ధ్వని గట్టిదనం దేనిపై ఆధారపడుతుంది?§Loudness depends on?',['కంపన పరిమితి~Amplitude','పౌనఃపున్యం~Frequency','యానకం రంగు~Colour of medium','ఆకారం~Shape'],'ఎక్కువ amplitude = ఎక్కువ గట్టిదనం§More amplitude means louder'),
Q('మానవ వినికిడి పరిధి?§Human audible range?',['20 Hz - 20,000 Hz','2 Hz - 200 Hz','200 Hz - 2000 Hz','20,000 Hz పైన~Above 20,000 Hz'],'ఈ పరిధికి బయటి ధ్వనులు వినబడవు§Sounds outside are inaudible'),
Q('ప్రతిధ్వని దేని వల్ల?§An echo is due to?',['ధ్వని పరావర్తనం~Reflection of sound','ధ్వని వక్రీభవనం~Refraction','కాంతి~Light','అయస్కాంతం~Magnet'],'గట్టి తలంపై పరావర్తనం§Reflection from a hard surface'),
Q('ధ్వని సాధారణంగా ఎందులో వేగంగా వెళ్తుంది?§Sound usually travels fastest in?',['ఘనాలు~Solids','వాయువులు~Gases','శూన్యం~Vacuum','అన్నిట్లో సమానం~Same in all'],'ఘనాల్లో ఎక్కువ§Highest in solids')]});
// Sources: NCERT Class 9 'Motion', 'Force and Laws of Motion' (Newton's laws)
A('science',[8,9],{id:'newton',i:'🚀',te:'న్యూటన్ చలన నియమాలు',en:'Newton\'s Laws of Motion',kw:'newton laws motion inertia force acceleration action reaction momentum F=ma jadatvam బలం త్వరణం జడత్వం చర్య ప్రతిచర్య',
n:['# మొదటి నియమం (జడత్వ నియమం)§# First law (law of inertia)','బాహ్య బలం పనిచేయనంతవరకు నిశ్చల వస్తువు నిశ్చలంగానే, చలిస్తున్న వస్తువు ఒకే వేగంతో సరళరేఖలో చలిస్తూనే ఉంటుంది. వస్తువు ద్రవ్యరాశి ఎక్కువైతే జడత్వం ఎక్కువ.§A body stays at rest, or keeps moving in a straight line at constant speed, unless an external force acts. More mass means more inertia.','# రెండో నియమం§# Second law','వస్తువు వేగమార్పు రేటు (ద్రవ్యవేగ మార్పు రేటు) దానిపై పనిచేసే బలానికి అనులోమానుపాతం. F = m × a. బలం ప్రమాణం న్యూటన్ (N).§Rate of change of momentum is proportional to the force. F = m × a. The unit of force is the newton (N).','# మూడో నియమం§# Third law','ప్రతి చర్యకు సమాన, వ్యతిరేక ప్రతిచర్య ఉంటుంది. ఈ రెండు బలాలు వేర్వేరు వస్తువులపై పనిచేస్తాయి.§Every action has an equal and opposite reaction. The two forces act on different bodies.','# ద్రవ్యవేగం§# Momentum','ద్రవ్యవేగం p = m × v. ప్రమాణం కి.గ్రా·మీ/సె.§Momentum p = m × v. Unit kg·m/s.','> 2 కిలోల వస్తువుకు 5 మీ/సె² త్వరణం ఇవ్వడానికి F = 2 × 5 = 10 N.§> To give 2 kg an acceleration of 5 m/s², F = 2 × 5 = 10 N.','బస్సు హఠాత్తుగా కదిలితే ప్రయాణికులు వెనక్కి వాలడం జడత్వం వల్ల. రాకెట్ వాయువులను కిందికి వదిలి పైకి వెళ్లడం మూడో నియమం.§Passengers lurching back when a bus starts is inertia. A rocket pushing gas down and rising is the third law.'],
q:[Q('జడత్వం దేనిపై ఆధారపడుతుంది?§Inertia depends on?',['ద్రవ్యరాశి~Mass','రంగు~Colour','ఆకారం~Shape','ఉష్ణోగ్రత~Temperature'],'ద్రవ్యరాశి ఎక్కువ = జడత్వం ఎక్కువ§More mass means more inertia'),
Q('F = ma ఏ నియమం?§F = ma is which law?',['రెండో~Second','మొదటి~First','మూడో~Third','నాలుగో~Fourth'],'న్యూటన్ రెండో నియమం§Newton\'s second law'),
Q('బల ప్రమాణం?§Unit of force?',['న్యూటన్~Newton','జౌల్~Joule','వాట్~Watt','పాస్కల్~Pascal'],'N = కి.గ్రా·మీ/సె²§N = kg·m/s²'),
Q('3 కిలోల వస్తువుపై 12 N బలం పనిచేస్తే త్వరణం?§Acceleration of 3 kg under 12 N?',['4 మీ/సె²~4 m/s²','36 మీ/సె²~36 m/s²','9 మీ/సె²~9 m/s²','0.25 మీ/సె²~0.25 m/s²'],'a = F/m = 12/3 = 4§a = F/m = 12/3 = 4'),
Q('రాకెట్ పైకి వెళ్లడం ఏ నియమానికి ఉదాహరణ?§A rocket rising illustrates?',['మూడో నియమం~Third law','మొదటి నియమం~First law','ఓం నియమం~Ohm\'s law','బాయిల్ నియమం~Boyle\'s law'],'చర్య-ప్రతిచర్య§Action-reaction'),
Q('ద్రవ్యవేగం సూత్రం?§Formula of momentum?',['m × v','m / v','v / m','m + v'],'p = mv§p = mv')]});
// Sources: NCERT Class 9 'Gravitation'
A('science',[9],{id:'gravity',i:'🍎',te:'గురుత్వాకర్షణ',en:'Gravitation',kw:'gravitation gravity g 9.8 weight mass free fall universal law newton guruthvakarshana గురుత్వాకర్షణ భారం ద్రవ్యరాశి స్వేచ్ఛాపతనం',
n:['# విశ్వ గురుత్వాకర్షణ నియమం§# Universal law of gravitation','విశ్వంలోని ప్రతి వస్తువు మరొక వస్తువును ఆకర్షిస్తుంది. బలం ద్రవ్యరాశుల లబ్ధానికి అనులోమానుపాతం, దూరం వర్గానికి విలోమానుపాతం. F = G m₁m₂ / r².§Every body attracts every other body. The force is proportional to the product of masses and inversely proportional to the square of the distance. F = G m₁m₂ / r².','# గురుత్వ త్వరణం§# Acceleration due to gravity','భూమి ఉపరితలం వద్ద g ≈ 9.8 మీ/సె². గాలి నిరోధం లేకపోతే అన్ని వస్తువులు ఒకే త్వరణంతో పడతాయి.§Near Earth\'s surface g ≈ 9.8 m/s². Without air resistance all bodies fall with the same acceleration.','# ద్రవ్యరాశి - భారం§# Mass vs weight','ద్రవ్యరాశి వస్తువులోని పదార్థ పరిమాణం (కి.గ్రా), ఎక్కడైనా స్థిరం. భారం = m × g (న్యూటన్లు), స్థలాన్ని బట్టి మారుతుంది.§Mass is the amount of matter (kg) and stays constant. Weight = m × g (newtons) and changes with place.','# చంద్రునిపై§# On the Moon','చంద్రునిపై g భూమిపై కంటే సుమారు ఆరో వంతు. కాబట్టి భారం ఆరో వంతు, ద్రవ్యరాశి మారదు.§Moon\'s g is about one-sixth of Earth\'s, so weight is one-sixth; mass is unchanged.','> 10 కిలోల వస్తువు భారం భూమిపై సుమారు 10 × 9.8 = 98 N.§> A 10 kg body weighs about 10 × 9.8 = 98 N on Earth.','G విశ్వ గురుత్వ స్థిరాంకం (6.67 × 10⁻¹¹ N·m²/kg²); g వేరు, G వేరు.§G is the universal gravitational constant (6.67 × 10⁻¹¹ N·m²/kg²); G and g are different.'],
q:[Q('భూమిపై g విలువ సుమారు?§Value of g on Earth is about?',['9.8 మీ/సె²~9.8 m/s²','98 మీ/సె²~98 m/s²','0.98 మీ/సె²~0.98 m/s²','6.67 మీ/సె²~6.67 m/s²'],'సుమారు 9.8§About 9.8'),
Q('భారం ప్రమాణం?§Unit of weight?',['న్యూటన్~Newton','కిలోగ్రామ్~Kilogram','మీటర్~Metre','లీటర్~Litre'],'భారం ఒక బలం§Weight is a force'),
Q('దూరం రెట్టింపైతే గురుత్వ బలం?§If distance doubles, gravitational force becomes?',['నాలుగో వంతు~One-fourth','సగం~Half','రెట్టింపు~Double','నాలుగు రెట్లు~Four times'],'1/r² కాబట్టి§Because of 1/r²'),
Q('చంద్రునిపై వస్తువు ద్రవ్యరాశి?§Mass of an object on the Moon?',['మారదు~Unchanged','ఆరో వంతు~One-sixth','ఆరు రెట్లు~Six times','సున్నా~Zero'],'ద్రవ్యరాశి స్థిరం§Mass is constant'),
Q('గాలి లేకుండా ఇనుప బంతి, ఈకలు పడే విధానం?§In vacuum, an iron ball and a feather fall?',['ఒకేసారి~Together','ఇనుప బంతి ముందు~Ball first','ఈక ముందు~Feather first','పడవు~Do not fall'],'అన్నిటికీ ఒకే g§Same g for all'),
Q('విశ్వ గురుత్వ నియమం ఎవరిది?§Universal law of gravitation is by?',['న్యూటన్~Newton','ఐన్‌స్టీన్~Einstein','గెలీలియో~Galileo','ఫారడే~Faraday'],'ఐజాక్ న్యూటన్§Isaac Newton')]});
// Sources: NCERT Class 7 'Heat'; NCERT Class 6-7 'Changes around us' (for heat transfer)
A('science',[7,8],{id:'heat',i:'🔥',te:'ఉష్ణం, ఉష్ణ ప్రసారం',en:'Heat and its Transfer',kw:'heat temperature conduction convection radiation thermometer celsius ushnam ఉష్ణం ఉష్ణోగ్రత ప్రసరణ ఉష్ణప్రసరణ వికిరణం',
n:['# ఉష్ణం, ఉష్ణోగ్రత§# Heat and temperature','ఉష్ణోగ్రత వస్తువు ఎంత వేడిగా ఉందో తెలుపుతుంది (థర్మామీటర్‌తో కొలుస్తారు). ఉష్ణం ఒక శక్తి రూపం; వేడి వస్తువు నుంచి చల్లని వస్తువుకు ప్రవహిస్తుంది.§Temperature tells how hot a body is (measured by a thermometer). Heat is a form of energy that flows from hot to cold bodies.','# ప్రసరణ§# Conduction','ఘనాల్లో కణాలు కదలకుండా ఉష్ణం ఒక కణం నుంచి మరొక కణానికి వెళ్లడం. లోహాలు మంచి ఉష్ణవాహకాలు.§In solids heat passes from particle to particle without the particles moving along. Metals are good conductors.','# ఉష్ణ సంవహనం (కన్వెక్షన్)§# Convection','ద్రవాలు, వాయువుల్లో వేడెక్కిన భాగం పైకి వెళ్లి, చల్లని భాగం కిందికి రావడం ద్వారా ఉష్ణం వ్యాపిస్తుంది. సముద్ర గాలులు ఇలాగే ఏర్పడతాయి.§In liquids and gases warm parts rise and cooler parts sink, spreading heat. Sea breezes form this way.','# వికిరణం§# Radiation','యానకం లేకుండా ఉష్ణం ప్రసరించడం. సూర్యుని నుంచి భూమికి వచ్చే ఉష్ణం వికిరణం ద్వారానే.§Heat travelling without a medium. Heat from the Sun reaches Earth by radiation.','> నల్లని రంగు ఉష్ణాన్ని ఎక్కువగా గ్రహిస్తుంది, తెలుపు తక్కువ; అందుకే వేసవిలో తెల్ల దుస్తులు హాయిగా ఉంటాయి.§> Dark colours absorb more heat, white less; so white clothes feel cooler in summer.','నీరు 0°C వద్ద గడ్డకడుతుంది, 100°C వద్ద మరుగుతుంది (సాధారణ పీడనంలో).§Water freezes at 0°C and boils at 100°C (at normal pressure).'],
q:[Q('ఘనాల్లో ఉష్ణ ప్రసారం?§Heat transfer in solids is mainly?',['ప్రసరణ~Conduction','సంవహనం~Convection','వికిరణం~Radiation','బాష్పీభవనం~Evaporation'],'ఘనాల్లో ప్రసరణ§Conduction in solids'),
Q('సూర్యుని నుంచి భూమికి ఉష్ణం ఎలా వస్తుంది?§How does Sun\'s heat reach Earth?',['వికిరణం~Radiation','ప్రసరణ~Conduction','సంవహనం~Convection','ధ్వని~Sound'],'శూన్యంలో వికిరణమే§Only radiation works in vacuum'),
Q('సాధారణ పీడనంలో నీరు మరిగే ఉష్ణోగ్రత?§Boiling point of water at normal pressure?',['100°C','0°C','50°C','212°C'],'100°C = 212°F§100°C = 212°F'),
Q('మంచి ఉష్ణవాహకం?§A good conductor of heat?',['రాగి~Copper','కలప~Wood','ప్లాస్టిక్~Plastic','రబ్బరు~Rubber'],'లోహాలు ఉష్ణవాహకాలు§Metals conduct heat'),
Q('ద్రవాల్లో వేడెక్కిన భాగం ఎటు వెళ్తుంది?§In liquids, the warmed part moves?',['పైకి~Up','కిందికి~Down','పక్కకు మాత్రమే~Only sideways','కదలదు~Does not move'],'సంవహన ప్రవాహాలు§Convection currents')]});
// Sources: NCERT Class 6 'Components of Food', Class 7 'Nutrition in Animals', Class 10 'Life Processes'
A('science',[6,7,10],{id:'digest',i:'🍽️',te:'జీర్ణవ్యవస్థ',en:'Human Digestive System',kw:'digestion stomach intestine saliva enzyme liver pancreas bile jeernavyavastha జీర్ణక్రియ జీర్ణవ్యవస్థ కడుపు పేగులు లాలాజలం కాలేయం',
n:['# సారాంశం§# Summary','ఆహారాన్ని శరీరం గ్రహించగల సరళ పదార్థాలుగా విడగొట్టడం జీర్ణక్రియ. జీర్ణ నాళం: నోరు → ఆహారనాళం → జీర్ణాశయం → చిన్న పేగు → పెద్ద పేగు → పాయువు.§Digestion breaks food into simple absorbable substances. Path: mouth → oesophagus → stomach → small intestine → large intestine → anus.','# నోరు§# Mouth','లాలాజలంలోని అమైలేజ్ ఎంజైమ్ పిండిపదార్థాన్ని చక్కెరగా మార్చడం మొదలుపెడుతుంది.§Salivary amylase begins converting starch into sugar.','# జీర్ణాశయం§# Stomach','హైడ్రోక్లోరిక్ ఆమ్లం, పెప్సిన్ ఎంజైమ్ ఉంటాయి; ప్రోటీన్ల జీర్ణం ఇక్కడ మొదలవుతుంది.§It has hydrochloric acid and pepsin; protein digestion starts here.','# చిన్న పేగు§# Small intestine','జీర్ణక్రియ పూర్తవుతుంది. కాలేయం పైత్యరసాన్ని (కొవ్వుల జీర్ణానికి), క్లోమం ఎంజైమ్‌లను అందిస్తాయి. పేగు లోపలి అంకురాలు (విల్లై) ఆహారాన్ని రక్తంలోకి గ్రహిస్తాయి.§Digestion is completed here. The liver gives bile (for fats), the pancreas gives enzymes. Villi absorb nutrients into blood.','# పెద్ద పేగు§# Large intestine','నీరు, లవణాలు గ్రహించబడతాయి; మిగిలిన వ్యర్థం మలంగా బయటికి వెళ్తుంది.§Water and salts are absorbed; the remaining waste leaves as faeces.','> మనిషి చిన్న పేగు పొడవు సుమారు 6-7 మీటర్లు.§> The human small intestine is roughly 6-7 m long.','శరీరంలో అతిపెద్ద గ్రంథి కాలేయం.§The liver is the largest gland in the body.'],
q:[Q('జీర్ణక్రియ ఎక్కడ మొదలవుతుంది?§Where does digestion begin?',['నోరు~Mouth','జీర్ణాశయం~Stomach','చిన్న పేగు~Small intestine','పెద్ద పేగు~Large intestine'],'లాలాజలంతో నోటిలోనే§With saliva in the mouth'),
Q('పిండిపదార్థ జీర్ణం మొదలు పెట్టే ఎంజైమ్?§Enzyme starting starch digestion?',['అమైలేజ్~Amylase','పెప్సిన్~Pepsin','లైపేజ్~Lipase','ట్రిప్సిన్~Trypsin'],'లాలాజల అమైలేజ్§Salivary amylase'),
Q('పైత్యరసం ఏ అవయవం తయారు చేస్తుంది?§Which organ makes bile?',['కాలేయం~Liver','క్లోమం~Pancreas','మూత్రపిండం~Kidney','గుండె~Heart'],'కాలేయం§Liver'),
Q('ఆహారం ఎక్కువగా రక్తంలోకి గ్రహించబడేది?§Where is most food absorbed?',['చిన్న పేగు~Small intestine','పెద్ద పేగు~Large intestine','జీర్ణాశయం~Stomach','ఆహారనాళం~Oesophagus'],'విల్లై వల్ల§Thanks to villi'),
Q('జీర్ణాశయంలోని ఆమ్లం?§Acid in the stomach?',['హైడ్రోక్లోరిక్~Hydrochloric','సల్ఫ్యూరిక్~Sulphuric','సిట్రిక్~Citric','ఎసిటిక్~Acetic'],'HCl§HCl'),
Q('శరీరంలో అతిపెద్ద గ్రంథి?§Largest gland in the body?',['కాలేయం~Liver','క్లోమం~Pancreas','థైరాయిడ్~Thyroid','లాలాజల గ్రంథి~Salivary gland'],'కాలేయం§Liver')]});
// Sources: NCERT Class 10 'Life Processes' (transportation); NCERT Class 7 'Transportation in Animals and Plants'
A('science',[7,10],{id:'heart',i:'❤️',te:'గుండె, రక్త ప్రసరణ',en:'Heart and Blood Circulation',kw:'heart blood circulation artery vein rbc wbc platelets haemoglobin raktaprasarana గుండె రక్తం ధమని సిర ఎర్ర రక్త కణాలు హిమోగ్లోబిన్',
n:['# గుండె§# The heart','గుండె కండరాలతో నిర్మితమైన పంపు. మనిషి గుండెకు నాలుగు గదులు: పై రెండు కర్ణికలు, కింది రెండు నిలయాలు (జఠరికలు).§The heart is a muscular pump with four chambers: two upper atria and two lower ventricles.','# రక్తనాళాలు§# Blood vessels','ధమనులు గుండె నుంచి రక్తాన్ని శరీరానికి తీసుకెళ్తాయి (ఊపిరితిత్తుల ధమని తప్ప ఆక్సిజన్ ఉన్న రక్తం). సిరలు రక్తాన్ని గుండెకు తెస్తాయి. కేశనాళికలు పదార్థ మార్పిడి చేస్తాయి.§Arteries carry blood away from the heart; veins bring it back; capillaries exchange materials.','# రక్త భాగాలు§# Blood components','ఎర్ర రక్త కణాలు హిమోగ్లోబిన్‌తో ఆక్సిజన్ తీసుకెళ్తాయి. తెల్ల రక్త కణాలు వ్యాధులతో పోరాడతాయి. ప్లేట్‌లెట్లు రక్తం గడ్డకట్టడానికి సహాయపడతాయి. ప్లాస్మా ద్రవ భాగం.§Red cells carry oxygen with haemoglobin. White cells fight disease. Platelets help clotting. Plasma is the liquid part.','# ద్వంద్వ ప్రసరణ§# Double circulation','మనిషిలో రక్తం ఒక చుట్టులో రెండుసార్లు గుండె గుండా వెళ్తుంది: ఊపిరితిత్తుల ప్రసరణ, శరీర ప్రసరణ.§In humans blood passes through the heart twice per cycle: pulmonary and systemic circulation.','> విశ్రాంతిలో పెద్దవారి గుండె నిమిషానికి సుమారు 72 సార్లు కొట్టుకుంటుంది (సాధారణ పరిధి సుమారు 60-100).§> An adult heart at rest beats about 72 times a minute (normal range roughly 60-100).','రక్తం ఎరుపు రంగుకు కారణం హిమోగ్లోబిన్ (ఇనుము ఉంటుంది).§Haemoglobin (contains iron) gives blood its red colour.'],
q:[Q('మానవ గుండెకు ఎన్ని గదులు?§Chambers in the human heart?',['4','2','3','5'],'2 కర్ణికలు + 2 నిలయాలు§2 atria + 2 ventricles'),
Q('ఆక్సిజన్ రవాణా చేసే వర్ణద్రవ్యం?§Pigment carrying oxygen?',['హిమోగ్లోబిన్~Haemoglobin','క్లోరోఫిల్~Chlorophyll','మెలనిన్~Melanin','కెరోటిన్~Carotene'],'RBCలో ఉంటుంది§Found in RBCs'),
Q('రక్తం గడ్డకట్టడానికి తోడ్పడేవి?§Which help clotting?',['ప్లేట్‌లెట్లు~Platelets','ఎర్ర కణాలు~RBC','తెల్ల కణాలు~WBC','ప్లాస్మా మాత్రమే~Plasma only'],'ప్లేట్‌లెట్లు§Platelets'),
Q('గుండె నుంచి రక్తాన్ని తీసుకెళ్లే నాళాలు?§Vessels taking blood away from the heart?',['ధమనులు~Arteries','సిరలు~Veins','కేశనాళికలు~Capillaries','శోషరసనాళాలు~Lymph vessels'],'ధమనులు§Arteries'),
Q('వ్యాధులతో పోరాడే కణాలు?§Cells that fight disease?',['తెల్ల రక్త కణాలు~WBC','ఎర్ర రక్త కణాలు~RBC','ప్లేట్‌లెట్లు~Platelets','నాడీ కణాలు~Neurons'],'WBC రక్షణ ఇస్తాయి§WBCs protect')]});
// Sources: NCERT Class 8 'Atoms and Molecules' (Class 9 'Structure of the Atom')
A('science',[8,9],{id:'atom',i:'⚛️',te:'పరమాణు నిర్మాణం',en:'Structure of the Atom',kw:'atom proton neutron electron nucleus atomic number mass number isotope bohr rutherford paramanu ప్రోటాన్ న్యూట్రాన్ ఎలక్ట్రాన్ పరమాణు సంఖ్య ద్రవ్యరాశి సంఖ్య',
n:['# కణాలు§# Particles','పరమాణువులో ప్రోటాన్ (ధనావేశం), న్యూట్రాన్ (ఆవేశం లేదు), ఎలక్ట్రాన్ (రుణావేశం) ఉంటాయి. ప్రోటాన్లు, న్యూట్రాన్లు కేంద్రకంలో; ఎలక్ట్రాన్లు దాని చుట్టూ కక్ష్యల్లో.§An atom has protons (positive), neutrons (neutral) and electrons (negative). Protons and neutrons are in the nucleus; electrons orbit around it.','# సంఖ్యలు§# Numbers','పరమాణు సంఖ్య (Z) = ప్రోటాన్ల సంఖ్య. ద్రవ్యరాశి సంఖ్య (A) = ప్రోటాన్లు + న్యూట్రాన్లు. తటస్థ పరమాణువులో ప్రోటాన్లు = ఎలక్ట్రాన్లు.§Atomic number Z = number of protons. Mass number A = protons + neutrons. In a neutral atom protons = electrons.','# శాస్త్రవేత్తలు§# Scientists','ఎలక్ట్రాన్‌ను జె.జె. థాంసన్, కేంద్రకాన్ని రూథర్‌ఫర్డ్, న్యూట్రాన్‌ను చాడ్విక్ కనుగొన్నారు. కక్ష్యల నమూనా ఇచ్చింది నీల్స్ బోర్.§J.J. Thomson found the electron, Rutherford the nucleus, Chadwick the neutron. Niels Bohr proposed the orbit model.','# ఎలక్ట్రాన్ విన్యాసం§# Electron arrangement','కక్ష్యల్లో గరిష్ఠ ఎలక్ట్రాన్లు: K-2, L-8, M-18. కార్బన్ (Z=6): 2, 4. సోడియం (Z=11): 2, 8, 1.§Maximum electrons: K-2, L-8, M-18. Carbon (Z=6): 2, 4. Sodium (Z=11): 2, 8, 1.','> ఆక్సిజన్: Z = 8, A = 16, కాబట్టి న్యూట్రాన్లు 16 − 8 = 8.§> Oxygen: Z = 8, A = 16, so neutrons = 16 − 8 = 8.','ఒకే పరమాణు సంఖ్య, వేర్వేరు ద్రవ్యరాశి సంఖ్యలు ఉన్న పరమాణువులు ఐసోటోపులు (ఉదా. క్లోరిన్-35, క్లోరిన్-37).§Atoms with the same Z but different A are isotopes (e.g. chlorine-35 and chlorine-37).'],
q:[Q('ధనావేశం ఉండే కణం?§Which particle is positively charged?',['ప్రోటాన్~Proton','ఎలక్ట్రాన్~Electron','న్యూట్రాన్~Neutron','ఫోటాన్~Photon'],'ప్రోటాన్ ధనావేశం§Proton is positive'),
Q('న్యూట్రాన్‌ను కనుగొన్నది?§Neutron was discovered by?',['చాడ్విక్~Chadwick','థాంసన్~Thomson','రూథర్‌ఫర్డ్~Rutherford','బోర్~Bohr'],'జేమ్స్ చాడ్విక్§James Chadwick'),
Q('పరమాణు సంఖ్య అంటే?§Atomic number equals?',['ప్రోటాన్ల సంఖ్య~Number of protons','న్యూట్రాన్ల సంఖ్య~Number of neutrons','ద్రవ్యరాశి సంఖ్య~Mass number','కక్ష్యల సంఖ్య~Number of shells'],'Z = ప్రోటాన్లు§Z = protons'),
Q('సోడియం (Z=11) ఎలక్ట్రాన్ విన్యాసం?§Electron configuration of sodium (Z=11)?',['2, 8, 1','2, 8, 8','2, 9','8, 3'],'K=2, L=8, M=1§K=2, L=8, M=1'),
Q('ఒకే Z, వేర్వేరు A ఉన్నవి?§Same Z, different A are called?',['ఐసోటోపులు~Isotopes','ఐసోబార్లు~Isobars','అయాన్లు~Ions','అణువులు~Molecules'],'ఐసోటోపులు§Isotopes'),
Q('కేంద్రకాన్ని కనుగొన్నది?§Nucleus was discovered by?',['రూథర్‌ఫర్డ్~Rutherford','డాల్టన్~Dalton','మెండలీఫ్~Mendeleev','న్యూటన్~Newton'],'ఆల్ఫా కణ పరిక్షేపణ ప్రయోగం§Alpha-particle scattering experiment')]});
// Sources: NCERT Class 10 'Chemical Reactions and Equations'
A('science',[8,10],{id:'chemrxn',i:'⚗️',te:'రసాయన చర్యలు, సమీకరణాలు',en:'Chemical Reactions and Equations',kw:'chemical reaction equation balanced combination decomposition displacement redox rasayana charya రసాయన చర్య సమీకరణం సంయోగం వియోగం స్థానభ్రంశం ఆక్సీకరణ క్షయకరణం',
n:['# సారాంశం§# Summary','రసాయన చర్యలో కొత్త పదార్థాలు ఏర్పడతాయి. గుర్తులు: రంగు మార్పు, వాయువు విడుదల, అవక్షేపం, ఉష్ణోగ్రత మార్పు.§New substances form in a chemical reaction. Signs: colour change, gas release, precipitate, temperature change.','# సమతుల్య సమీకరణం§# Balanced equation','ద్రవ్యనిత్యత్వ నియమం ప్రకారం చర్యలో పరమాణువులు సృష్టించబడవు, నశించవు. కాబట్టి ఇరువైపులా ప్రతి మూలక పరమాణువుల సంఖ్య సమానం కావాలి. 2H₂ + O₂ → 2H₂O.§By the law of conservation of mass atoms are neither created nor destroyed, so each element has equal atoms on both sides. 2H₂ + O₂ → 2H₂O.','# రకాలు§# Types','సంయోగం: A + B → AB. వియోగం: AB → A + B. స్థానభ్రంశం: Fe + CuSO₄ → FeSO₄ + Cu. ద్వంద్వ వియోగం: ఉదా. అవక్షేపం ఏర్పడటం.§Combination: A + B → AB. Decomposition: AB → A + B. Displacement: Fe + CuSO₄ → FeSO₄ + Cu. Double displacement often forms a precipitate.','# ఆక్సీకరణ, క్షయకరణం§# Oxidation and reduction','ఆక్సిజన్ కలవడం లేదా హైడ్రోజన్ తొలగడం ఆక్సీకరణ; ఆక్సిజన్ తొలగడం లేదా హైడ్రోజన్ కలవడం క్షయకరణం. రెండూ ఒకేసారి జరుగుతాయి (రెడాక్స్).§Gain of oxygen or loss of hydrogen is oxidation; loss of oxygen or gain of hydrogen is reduction. They occur together (redox).','> ఇనుము తుప్పు పట్టడం, ఆహారం చెడిపోవడం (రాన్సిడిటీ) ఆక్సీకరణ ఉదాహరణలు.§> Rusting of iron and rancidity of food are oxidation.','సున్నపురాయి వేడిచేస్తే కాల్షియం ఆక్సైడ్, CO₂ వస్తాయి: CaCO₃ → CaO + CO₂.§Heating limestone gives calcium oxide and CO₂: CaCO₃ → CaO + CO₂.'],
q:[Q('ద్రవ్యనిత్యత్వ నియమం ఏం చెబుతుంది?§Law of conservation of mass says?',['చర్యలో ద్రవ్యరాశి మారదు~Mass is conserved in a reaction','ద్రవ్యరాశి పెరుగుతుంది~Mass increases','ద్రవ్యరాశి తగ్గుతుంది~Mass decreases','శక్తి నశిస్తుంది~Energy is destroyed'],'మొత్తం ద్రవ్యరాశి స్థిరం§Total mass stays constant'),
Q('Fe + CuSO₄ → FeSO₄ + Cu ఏ చర్య?§Fe + CuSO₄ → FeSO₄ + Cu is?',['స్థానభ్రంశం~Displacement','సంయోగం~Combination','వియోగం~Decomposition','తటస్థీకరణ~Neutralisation'],'ఇనుము రాగిని స్థానభ్రంశం చేసింది§Iron displaces copper'),
Q('2H₂ + O₂ → 2H₂O లో H పరమాణువులు ఎడమవైపు?§In 2H₂ + O₂ → 2H₂O, H atoms on left?',['4','2','1','6'],'2 × 2 = 4§2 × 2 = 4'),
Q('తుప్పు పట్టడం ఏ చర్య?§Rusting is?',['ఆక్సీకరణ~Oxidation','క్షయకరణం~Reduction','వియోగం~Decomposition','తటస్థీకరణ~Neutralisation'],'ఇనుము ఆక్సిజన్, తేమతో చర్య§Iron reacts with oxygen and moisture'),
Q('CaCO₃ వేడి చేస్తే వచ్చే వాయువు?§Gas released on heating CaCO₃?',['కార్బన్ డయాక్సైడ్~Carbon dioxide','ఆక్సిజన్~Oxygen','హైడ్రోజన్~Hydrogen','నైట్రోజన్~Nitrogen'],'CaO + CO₂§CaO + CO₂')]});
// Sources: NCERT Class 6 'Magnets', Class 7/8 magnetism, Class 10 'Magnetic Effects of Electric Current'
A('science',[6,7,10],{id:'magnet',i:'🧲',te:'అయస్కాంతాలు',en:'Magnets and Magnetism',kw:'magnet magnetic field poles compass electromagnet oersted ayaskantam అయస్కాంతం ధ్రువాలు దిక్సూచి క్షేత్రం విద్యుదయస్కాంతం',
n:['# లక్షణాలు§# Properties','ప్రతి అయస్కాంతానికి రెండు ధ్రువాలు (ఉత్తర, దక్షిణ) ఉంటాయి. విజాతి ధ్రువాలు ఆకర్షించుకుంటాయి, సజాతి ధ్రువాలు వికర్షించుకుంటాయి.§Every magnet has two poles (north and south). Unlike poles attract, like poles repel.','# అయస్కాంత పదార్థాలు§# Magnetic materials','ఇనుము, నికెల్, కోబాల్ట్ అయస్కాంతానికి ఆకర్షితమవుతాయి. రాగి, ప్లాస్టిక్, కాగితం కావు.§Iron, nickel and cobalt are attracted. Copper, plastic and paper are not.','# దిక్సూచి§# Compass','స్వేచ్ఛగా వేలాడదీసిన అయస్కాంతం ఉత్తర-దక్షిణ దిశలో నిలుస్తుంది. దిక్సూచి సూది భూమి అయస్కాంత క్షేత్రం వల్ల దిశ చూపుతుంది.§A freely suspended magnet settles in the north-south direction. A compass needle follows Earth\'s magnetic field.','# అయస్కాంత క్షేత్రం§# Magnetic field','అయస్కాంత క్షేత్ర రేఖలు ఉత్తర ధ్రువం నుంచి బయటికి వచ్చి దక్షిణ ధ్రువంలోకి వెళ్తాయి; ఒకదాన్నొకటి ఖండించుకోవు.§Field lines emerge from the north pole and enter the south pole, outside the magnet; they never cross.','# విద్యుదయస్కాంతం§# Electromagnet','తీగ చుట్టను, ఇనుప కడ్డీ చుట్టూ చుట్టి విద్యుత్ పంపితే తాత్కాలిక అయస్కాంతం ఏర్పడుతుంది. విద్యుత్ ప్రవాహానికి అయస్కాంత ప్రభావం ఉందని ఓర్స్టెడ్ కనుగొన్నాడు.§A coil with current around an iron rod makes a temporary magnet. Oersted showed that current has a magnetic effect.','> అయస్కాంతాన్ని ముక్కలు చేస్తే ప్రతి ముక్కకూ రెండు ధ్రువాలు ఉంటాయి.§> Break a magnet and every piece still has two poles.','క్రేన్లు, ఎలక్ట్రిక్ బెల్స్, మోటార్లలో విద్యుదయస్కాంతాలు వాడతారు.§Electromagnets are used in cranes, electric bells and motors.'],
q:[Q('సజాతి ధ్రువాలు ఏం చేస్తాయి?§Like poles do what?',['వికర్షిస్తాయి~Repel','ఆకర్షిస్తాయి~Attract','ఏమీ కాదు~Nothing','కలిసిపోతాయి~Merge'],'N-N వికర్షణ§N-N repel'),
Q('అయస్కాంతానికి ఆకర్షితమయ్యేది?§Attracted by a magnet?',['ఇనుము~Iron','రాగి~Copper','ప్లాస్టిక్~Plastic','గాజు~Glass'],'ఇనుము అయస్కాంత పదార్థం§Iron is magnetic'),
Q('విద్యుత్ ప్రవాహ అయస్కాంత ప్రభావాన్ని కనుగొన్నది?§Who found the magnetic effect of current?',['ఓర్స్టెడ్~Oersted','న్యూటన్~Newton','ఓం~Ohm','పాశ్చర్~Pasteur'],'హాన్స్ క్రిస్టియన్ ఓర్స్టెడ్§Hans Christian Oersted'),
Q('దిక్సూచి దేన్ని చూపుతుంది?§A compass shows?',['ఉత్తర-దక్షిణ దిశ~North-south direction','సమయం~Time','వేగం~Speed','ఉష్ణోగ్రత~Temperature'],'భూ అయస్కాంత క్షేత్రం వల్ల§Due to Earth\'s field'),
Q('అయస్కాంత క్షేత్ర రేఖలు ఏమి చేయవు?§Field lines never?',['ఒకదాన్నొకటి ఖండించవు~Cross each other','ఉత్తరం నుంచి బయటికి రావు~Leave the north pole','వంపు తిరుగుతాయి~Curve','కొనసాగుతాయి~Continue'],'అవి ఖండించుకోవు§They do not intersect')]});
// Sources: NCERT Class 6 'Separation of Substances', Class 8 'Synthetic Fibres and Plastics' not used; NCERT Class 9 'Is Matter Around Us Pure?'
A('science',[6,8,9],{id:'matterstate',i:'🧊',te:'పదార్థ స్థితులు',en:'States of Matter',kw:'matter solid liquid gas evaporation melting boiling condensation sublimation padartha sthitulu ఘనం ద్రవం వాయువు బాష్పీభవనం ద్రవీభవనం ఉత్పతనం',
n:['# మూడు స్థితులు§# Three states','పదార్థం ఘన, ద్రవ, వాయు స్థితుల్లో ఉంటుంది. ఘనాలకు నిర్దిష్ట ఆకారం, ఘనపరిమాణం; ద్రవాలకు నిర్దిష్ట ఘనపరిమాణం మాత్రమే; వాయువులకు రెండూ ఉండవు.§Matter exists as solid, liquid and gas. Solids have fixed shape and volume; liquids fixed volume only; gases neither.','# కణాల అమరిక§# Particle arrangement','ఘనాల్లో కణాలు దగ్గరగా, ద్రవాల్లో కొంచెం దూరంగా, వాయువుల్లో చాలా దూరంగా ఉంటాయి; వాయు కణాలు స్వేచ్ఛగా కదులుతాయి.§Particles are close in solids, farther in liquids, very far in gases, which move freely.','# స్థితి మార్పులు§# Changes of state','ద్రవీభవనం: ఘనం → ద్రవం. బాష్పీభవనం: ద్రవం → వాయువు. సాంద్రీకరణం: వాయువు → ద్రవం. ఘనీభవనం: ద్రవం → ఘనం. ఉత్పతనం: ఘనం ↔ వాయువు నేరుగా (కర్పూరం, నాఫ్తలీన్).§Melting: solid to liquid. Vaporisation: liquid to gas. Condensation: gas to liquid. Freezing: liquid to solid. Sublimation: solid to gas directly (camphor, naphthalene).','# బాష్పీభవనం ఎక్కువయ్యే పరిస్థితులు§# Faster evaporation','ఉష్ణోగ్రత ఎక్కువ, ఉపరితల వైశాల్యం ఎక్కువ, గాలి వేగం ఎక్కువ, తేమ తక్కువ ఉంటే ఎక్కువ.§Higher temperature, larger surface area, more wind and lower humidity speed evaporation.','> తడి బట్టలు ఎండలో, గాలిలో త్వరగా ఆరతాయి.§> Wet clothes dry fast in sun and wind.','చెమట ఆవిరవుతూ శరీరాన్ని చల్లబరుస్తుంది; కుండలో నీరు చల్లగా ఉండటానికి కారణం ఇదే.§Evaporating sweat cools the body; the same reason keeps water cool in a clay pot.'],
q:[Q('నిర్దిష్ట ఆకారం, ఘనపరిమాణం ఉండేది?§Which has fixed shape and volume?',['ఘనం~Solid','ద్రవం~Liquid','వాయువు~Gas','ఏదీ కాదు~None'],'ఘనాలు§Solids'),
Q('ఘనం నేరుగా వాయువుగా మారడం?§Solid changing directly to gas?',['ఉత్పతనం~Sublimation','ద్రవీభవనం~Melting','సాంద్రీకరణం~Condensation','ఘనీభవనం~Freezing'],'కర్పూరం ఉదాహరణ§Camphor is an example'),
Q('వాయువుల్లో కణాల మధ్య దూరం?§Particle spacing in gases?',['ఎక్కువ~Very large','తక్కువ~Very small','లేదు~None','ఘనాలతో సమానం~Same as solids'],'వాయు కణాలు దూరంగా§Gas particles are far apart'),
Q('బాష్పీభవనం వేగంగా జరగడానికి?§Evaporation is faster with?',['ఎక్కువ ఉష్ణోగ్రత~Higher temperature','ఎక్కువ తేమ~More humidity','తక్కువ గాలి~Less wind','తక్కువ వైశాల్యం~Less area'],'వేడి వల్ల వేగం పెరుగుతుంది§Heat speeds it up'),
Q('వాయువు ద్రవంగా మారడం?§Gas changing to liquid?',['సాంద్రీకరణం~Condensation','బాష్పీభవనం~Evaporation','ద్రవీభవనం~Melting','ఉత్పతనం~Sublimation'],'సాంద్రీకరణం§Condensation')]});
LD.reg('bsci2',1)})();
