// Science batch 3 (AksharaNova). Each topic lists its sources. NCERT Class 10 Science (Reprint 2026-27) and Class 8 Science read directly from ncert.nic.in PDFs; second source is independent (Britannica/EPA/UNEP/NatGeo/LibreTexts/Wikipedia).
// Class numbers = where the topic is confirmed in the current NCERT book. SCERT Telangana may place a topic in other classes too; builder can add classes after checking SCERT books.
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
// Sources: NCERT Class 10 Ch.10 'The Human Eye and the Colourful World' https://ncert.nic.in/textbook/pdf/jesc110.pdf ; OpenStax College Physics 26.2 'Vision Correction' https://phys.libretexts.org/Bookshelves/College_Physics/College_Physics_1e_(OpenStax)/26%3A_Vision_and_Optical_Instruments/26.02%3A_Vision_Correction
A('science',[10],{id:'eye',i:'👁️',te:'మానవ నేత్రం, దృష్టి దోషాలు',en:'The Human Eye and Defects of Vision',kw:'eye cornea iris pupil retina lens accommodation myopia hypermetropia presbyopia cataract near point netram kanti కన్ను నేత్రం హ్రస్వదృష్టి దీర్ఘదృష్టి కనుపాప తారక రెటీనా శుక్లం',
n:['# సారాంశం§# Summary','కన్ను కెమెరాలా పనిచేస్తుంది. కటకం రెటీనాపై వస్తువు యొక్క తలకిందులైన నిజ ప్రతిబింబాన్ని ఏర్పరుస్తుంది. రెటీనాలోని కాంతి సున్నిత కణాలు సంకేతాలను దృక్ నాడుల ద్వారా మెదడుకు పంపుతాయి, మెదడు వాటిని వివరించుకుంటుంది.§The eye works like a camera. The lens forms an inverted real image on the retina. Light-sensitive cells send signals through the optic nerves to the brain, which interprets them.','# భాగాలు§# Parts','కాంతి ముందుగా పారదర్శక పొర అయిన కార్నియా గుండా కంటిలోకి వెళ్తుంది; కాంతి వక్రీభవనం ఎక్కువగా కార్నియా బయటి తలం వద్దే జరుగుతుంది. కంటి కటకం సూక్ష్మ సర్దుబాటు చేస్తుంది. కనుపాప (ఐరిస్) తారక (పపిల్) పరిమాణాన్ని నియంత్రించి కంటిలోకి వచ్చే కాంతి పరిమాణాన్ని నియంత్రిస్తుంది.§Light enters through the transparent cornea, where most refraction occurs. The lens does fine adjustment. The iris controls the size of the pupil and so the amount of light entering.','# నేత్ర సమంజసత్వం (అకామడేషన్)§# Accommodation','సిలియరీ కండరాలు సడలినప్పుడు కటకం పలుచబడి నాభ్యంతరం పెరుగుతుంది, దూరపు వస్తువులు స్పష్టంగా కనిపిస్తాయి. కండరాలు సంకోచిస్తే కటకం మందంగా మారి నాభ్యంతరం తగ్గుతుంది, దగ్గరి వస్తువులు కనిపిస్తాయి.§When ciliary muscles relax the lens gets thinner (longer focal length) for distant objects. When they contract the lens gets thicker (shorter focal length) for near objects.','# సమీప బిందువు, దూర బిందువు§# Near and far point','సాధారణ కంటికి సమీప బిందువు సుమారు 25 సెం.మీ. దూర బిందువు అనంతం. అంటే 25 సెం.మీ నుంచి అనంత దూరం వరకు స్పష్టంగా చూడగలదు.§For a normal eye the near point is about 25 cm and the far point is infinity.','# దృష్టి దోషాలు§# Defects of vision','హ్రస్వదృష్టి (మయోపియా): దగ్గరివి కనిపిస్తాయి, దూరపు వస్తువులు స్పష్టంగా కనిపించవు; పుటాకార కటకంతో సరిచేస్తారు. దీర్ఘదృష్టి (హైపర్‌మెట్రోపియా): దూరపివి కనిపిస్తాయి, దగ్గరివి కనిపించవు; కుంభాకార కటకంతో సరిచేస్తారు. వయసుతో సమీప బిందువు దూరమవడాన్ని ప్రెస్బియోపియా అంటారు.§Myopia: near objects are clear, distant ones blurred; corrected with a concave lens. Hypermetropia: distant objects are clear, near ones blurred; corrected with a convex lens. Presbyopia is the near point receding with age.','> వృద్ధాప్యంలో కటకం పాలలా మబ్బుగా మారితే దాన్ని కంటిశుక్లం (క్యాటరాక్ట్) అంటారు; శస్త్రచికిత్సతో చూపు తిరిగి వస్తుంది.§> When the lens becomes milky and cloudy in old age it is called cataract; surgery can restore vision.'],
q:[Q('రెటీనాపై ఏర్పడే ప్రతిబింబం?§The image formed on the retina is?',['నిజ, తలకిందులు~Real, inverted','మిథ్యా, నిటారు~Virtual, erect','నిజ, నిటారు~Real, erect','మిథ్యా, తలకిందులు~Virtual, inverted'],'కటకం నిజ, తలకిందుల ప్రతిబింబం ఇస్తుంది§The lens forms a real, inverted image'),
Q('కంటిలోకి వెళ్లే కాంతి పరిమాణాన్ని నియంత్రించేది?§What controls the amount of light entering the eye?',['కనుపాప (ఐరిస్)~Iris','రెటీనా~Retina','కార్నియా~Cornea','దృక్ నాడి~Optic nerve'],'ఐరిస్ తారక పరిమాణాన్ని మారుస్తుంది§The iris changes pupil size'),
Q('సాధారణ కంటి సమీప బిందువు సుమారు?§Near point of a normal eye is about?',['25 సెం.మీ~25 cm','25 మీ~25 m','2.5 సెం.మీ~2.5 cm','అనంతం~Infinity'],'25 సెం.మీ§25 cm'),
Q('హ్రస్వదృష్టిని సరిచేసే కటకం?§Lens used to correct myopia?',['పుటాకార~Concave','కుంభాకార~Convex','సమతల~Plane','ద్విఫోకల్ మాత్రమే~Only bifocal'],'మయోపియాకు పుటాకార కటకం§Concave lens for myopia'),
Q('దీర్ఘదృష్టికి సరిచేసే కటకం?§Lens used to correct hypermetropia?',['కుంభాకార~Convex','పుటాకార~Concave','సమతల~Plane','పట్టకం~Prism'],'హైపర్‌మెట్రోపియాకు కుంభాకార కటకం§Convex lens for hypermetropia'),
Q('దగ్గరి వస్తువును చూసేటప్పుడు కటకం?§When looking at a near object the eye lens becomes?',['మందంగా (నాభ్యంతరం తగ్గుతుంది)~Thicker (focal length decreases)','పలుచగా~Thinner','మారదు~Unchanged','చదునుగా~Flat'],'సిలియరీ కండరాలు సంకోచిస్తాయి§Ciliary muscles contract')]});
// Sources: NCERT Class 10 Ch.3 'Metals and Non-metals' https://ncert.nic.in/textbook/pdf/jesc103.pdf ; Britannica 'Mercury' https://www.britannica.com/science/mercury-chemical-element ; Wikipedia 'Alkali metal' https://en.wikipedia.org/wiki/Alkali_metal
A('science',[10],{id:'metals',i:'🪙',te:'లోహాలు, అలోహాలు',en:'Metals and Non-metals',kw:'metal nonmetal malleability ductility reactivity series mercury ionic compound alloy lohalu alohalu లోహాలు అలోహాలు స్థితి క్రియాశీలత శ్రేణి అయానిక సమ్మేళనం',
n:['# భౌతిక ధర్మాలు§# Physical properties','లోహాలను పలుచని రేకులుగా సాగదీయవచ్చు (స్తరణీయత) , సన్నని తీగలుగా లాగవచ్చు (తన్యత). బంగారం, వెండి అత్యంత సాగే లోహాలు; బంగారం అత్యంత తన్యత గల లోహం. ఒక గ్రాము బంగారం నుంచి సుమారు 2 కి.మీ పొడవు తీగ లాగవచ్చు.§Metals can be beaten into sheets (malleability) and drawn into wires (ductility). Gold and silver are the most malleable; gold is the most ductile. About 2 km of wire can be drawn from 1 g of gold.','# అపవాదాలు§# Exceptions','పాదరసం తప్ప అన్ని లోహాలు గది ఉష్ణోగ్రత వద్ద ఘనాలు. గాలియం, సీజియం తక్కువ ద్రవీభవన స్థానం కలవి. లిథియం, సోడియం, పొటాషియం కత్తితో కోయగలిగేంత మెత్తనివి. అలోహాల్లో బ్రోమిన్ ద్రవం; అయోడిన్ అలోహమైనా మెరుస్తుంది; గ్రాఫైట్ (కార్బన్ రూపాంతరం) విద్యుత్ వాహకం; వజ్రం కఠినమైన సహజ పదార్థం.§All metals except mercury are solid at room temperature. Gallium and caesium melt at very low temperatures. Lithium, sodium and potassium can be cut with a knife. Among non-metals bromine is a liquid, iodine is lustrous, graphite conducts electricity and diamond is the hardest natural substance.','# క్రియాశీలత శ్రేణి§# Reactivity series','అధిక నుంచి తక్కువ క్రియాశీలత: K, Na, Ca, Mg, Al, Zn, Fe, Pb, [H], Cu, Hg, Ag, Au. ఎక్కువ క్రియాశీల లోహం తక్కువ క్రియాశీల లోహాన్ని దాని ద్రావణం నుంచి స్థానభ్రంశం చేస్తుంది.§From most to least reactive: K, Na, Ca, Mg, Al, Zn, Fe, Pb, [H], Cu, Hg, Ag, Au. A more reactive metal displaces a less reactive one from its solution.','# అయానిక సమ్మేళనాలు§# Ionic compounds','లోహం నుంచి అలోహానికి ఎలక్ట్రాన్ల బదిలీతో ఏర్పడతాయి. ఇవి ఘనాలు, కొంత కఠినం, పెళుసు; అధిక ద్రవీభవన, బాష్పీభవన స్థానాలు; నీటిలో కరుగుతాయి; ఘన స్థితిలో విద్యుత్ ప్రసరించవు, ద్రావణంలో ప్రసరిస్తాయి.§They form by transfer of electrons from a metal to a non-metal. They are solid, somewhat hard and brittle, have high melting and boiling points, dissolve in water, and conduct electricity in solution but not as solids.','> క్రియాశీలత శ్రేణిలో కింద ఉన్న లోహాలు (బంగారం, వెండి) తక్కువ క్రియాశీలమైనవి కాబట్టి ప్రకృతిలో స్వతంత్ర రూపంలో లభిస్తాయి.§> Metals low in the series, such as gold and silver, are least reactive and often found free in nature.'],
q:[Q('గది ఉష్ణోగ్రత వద్ద ద్రవంగా ఉండే లోహం?§Which metal is liquid at room temperature?',['పాదరసం~Mercury','ఇనుము~Iron','రాగి~Copper','అల్యూమినియం~Aluminium'],'పాదరసం తప్ప లోహాలన్నీ ఘనాలు§All metals except mercury are solid'),
Q('అత్యంత తన్యత గల లోహం?§The most ductile metal?',['బంగారం~Gold','ఇనుము~Iron','సీసం~Lead','జింక్~Zinc'],'1 గ్రా బంగారం నుంచి సుమారు 2 కి.మీ తీగ§About 2 km wire from 1 g'),
Q('క్రియాశీలత శ్రేణిలో అత్యంత క్రియాశీల లోహం?§Most reactive metal in the series?',['పొటాషియం~Potassium','బంగారం~Gold','రాగి~Copper','ఇనుము~Iron'],'K మొదటి స్థానం§K is at the top'),
Q('ద్రవ స్థితిలో ఉండే అలోహం?§Which non-metal is liquid?',['బ్రోమిన్~Bromine','అయోడిన్~Iodine','సల్ఫర్~Sulphur','కార్బన్~Carbon'],'బ్రోమిన్ ద్రవం§Bromine is a liquid'),
Q('విద్యుత్ వాహకంగా ఉండే కార్బన్ రూపాంతరం?§Which allotrope of carbon conducts electricity?',['గ్రాఫైట్~Graphite','వజ్రం~Diamond','రెండూ~Both','ఏదీ కాదు~Neither'],'గ్రాఫైట్ వాహకం§Graphite conducts'),
Q('రాగి, ఇనుము - ఏది ఎక్కువ క్రియాశీలం?§Which is more reactive, copper or iron?',['ఇనుము~Iron','రాగి~Copper','సమానం~Equal','చెప్పలేం~Cannot say'],'శ్రేణిలో Fe, Cu కంటే పైన§Fe is above Cu in the series')]});
// Sources: NCERT Class 10 Ch.13 'Our Environment' https://ncert.nic.in/textbook/pdf/jesc113.pdf ; National Geographic 'Energy Flow and the 10% Rule' https://education.nationalgeographic.org/resource/energy-flow-and-10-percent-rule/ ; Wikipedia 'Ten percent law' https://en.wikipedia.org/wiki/Ten_percent_law
A('science',[10],{id:'foodchain',i:'🌾',te:'ఆహార గొలుసు, ఆహార జాలం, పర్యావరణ వ్యవస్థ',en:'Food Chain, Food Web and Ecosystem',kw:'ecosystem food chain food web trophic level producers consumers decomposers 10 percent energy flow paryavarana ఆహార గొలుసు ఆహార జాలం ఉత్పత్తిదారులు వినియోగదారులు విచ్ఛిన్నకారులు',
n:['# పర్యావరణ వ్యవస్థ§# Ecosystem','ఒక ప్రాంతంలోని జీవులు (జీవ అంశాలు), భౌతిక అంశాలు (గాలి, నీరు, నేల, సూర్యకాంతి) కలిసి పర్యావరణ వ్యవస్థ అవుతుంది. జీవులు ఉత్పత్తిదారులు, వినియోగదారులు, విచ్ఛిన్నకారులుగా ఉంటాయి.§An ecosystem is the living and non-living components of an area together. Living things act as producers, consumers and decomposers.','# ఆహార గొలుసు§# Food chain','ఒకదాన్ని ఒకటి తినే జీవుల వరుసను ఆహార గొలుసు అంటారు; ప్రతి దశ ఒక పోషక స్థాయి. స్వయంపోషకాలైన ఉత్పత్తిదారులు (మొక్కలు) మొదటి పోషక స్థాయిలో ఉంటాయి. ఉదా: గడ్డి → మిడత → కప్ప → పాము → గద్ద.§A series of organisms eating one another is a food chain; each step is a trophic level. Autotrophic producers (plants) are at the first level. E.g. grass → grasshopper → frog → snake → hawk.','# శక్తి ప్రవాహం - 10% నియమం§# Energy flow - 10% rule','తిన్న ఆహారంలో సగటున 10% మాత్రమే తదుపరి పోషక స్థాయికి శక్తిగా చేరుతుంది. అందుకే ఆహార గొలుసులో సాధారణంగా మూడు లేదా నాలుగు దశలే ఉంటాయి.§On average only about 10% of energy passes to the next trophic level, so food chains usually have only three or four steps.','# ఆహార జాలం§# Food web','ప్రకృతిలో అనేక ఆహార గొలుసులు ఒకదానితో ఒకటి కలిసి ఆహార జాలం ఏర్పడుతుంది.§Many interlinked food chains form a food web.','# విచ్ఛిన్నకారులు§# Decomposers','బ్యాక్టీరియా, శిలీంధ్రాలు వంటి సూక్ష్మజీవులు మృత జీవులను, వ్యర్థాలను విచ్ఛిన్నం చేసి పోషకాలను నేలకు తిరిగి ఇస్తాయి.§Microorganisms such as bacteria and fungi break down dead matter and return nutrients to the soil.','> 1000 జౌళ్ల శక్తి ఉత్పత్తిదారుల్లో ఉంటే ప్రాథమిక వినియోగదారులకు సుమారు 100 J చేరుతుంది.§> If producers hold 1000 J, about 100 J reaches primary consumers.'],
q:[Q('ఆహార గొలుసులో మొదటి పోషక స్థాయి?§First trophic level in a food chain?',['ఉత్పత్తిదారులు~Producers','శాకాహారులు~Herbivores','మాంసాహారులు~Carnivores','విచ్ఛిన్నకారులు~Decomposers'],'స్వయంపోషక మొక్కలు§Autotrophic plants'),
Q('ఒక పోషక స్థాయి నుంచి తదుపరికి సగటున చేరే శక్తి?§Average energy passed to the next trophic level?',['10%','50%','90%','1%'],'10% నియమం§The 10% rule'),
Q('మృత జీవులను విచ్ఛిన్నం చేసేవి?§Which break down dead organisms?',['బ్యాక్టీరియా, శిలీంధ్రాలు~Bacteria and fungi','మొక్కలు~Plants','పక్షులు~Birds','చేపలు~Fish'],'విచ్ఛిన్నకారులు§Decomposers'),
Q('ఆహార గొలుసులో సాధారణంగా ఎన్ని దశలు ఉంటాయి?§Usual number of steps in a food chain?',['3 లేదా 4~3 or 4','10~10','1~1','20~20'],'శక్తి నష్టం వల్ల§Because of energy loss'),
Q('అనేక ఆహార గొలుసుల కలయిక?§A network of many food chains?',['ఆహార జాలం~Food web','ఆహార పిరమిడ్ మాత్రమే~Food pyramid only','జీవావరణం~Biosphere','నివాసం~Habitat'],'ఆహార జాలం§Food web')]});
// Sources: NCERT Class 10 Ch.13 'Our Environment' (13.2.1 Ozone layer) https://ncert.nic.in/textbook/pdf/jesc113.pdf ; US EPA 'Basic Ozone Layer Science' https://www.epa.gov/ozone-layer-protection/basic-ozone-layer-science ; UNEP Ozone Secretariat https://ozone.unep.org/20-questions-and-answers
A('science',[10],{id:'ozone',i:'🌍',te:'ఓజోన్ పొర',en:'The Ozone Layer',kw:'ozone layer uv radiation cfc depletion montreal protocol stratosphere ozone paramanu ఓజోన్ పొర అతినీలలోహిత కిరణాలు సీఎఫ్‌సీ',
n:['# ఓజోన్ అంటే§# What is ozone','ఓజోన్ (O₃) మూడు ఆక్సిజన్ పరమాణువులతో ఏర్పడిన అణువు. దిగువ వాతావరణంలో ఇది హానికర వాయువు, కానీ ఎగువ వాతావరణంలో జీవులకు అవసరమైన రక్షణ ఇస్తుంది.§Ozone (O₃) is a molecule of three oxygen atoms. At ground level it is harmful, but high in the atmosphere it protects life.','# రక్షణ§# Protection','ఎగువ వాతావరణంలోని (స్ట్రాటోస్ఫియర్) ఓజోన్ సూర్యుని హానికర అతినీలలోహిత (UV) కిరణాలను గ్రహించి భూమిపై జీవులను కాపాడుతుంది.§Ozone in the stratosphere absorbs harmful ultraviolet (UV) rays from the Sun and protects life on Earth.','# క్షీణత§# Depletion','రిఫ్రిజిరేటర్లు, అగ్నిమాపక పరికరాల్లో వాడిన క్లోరోఫ్లోరోకార్బన్లు (CFCs) ఓజోన్ పొరను దెబ్బతీస్తాయి.§Chlorofluorocarbons (CFCs), used in refrigerants and fire extinguishers, damage the ozone layer.','# అంతర్జాతీయ చర్య§# Global action','ఓజోన్‌ను క్షీణింపజేసే పదార్థాలపై 1987లో మాంట్రియల్ ప్రొటోకాల్ ఒప్పందం కుదిరింది.§The Montreal Protocol on substances that deplete the ozone layer was agreed in 1987.','> ఓజోన్ పొర పలుచబడితే UV కిరణాలు ఎక్కువగా భూమికి చేరుతాయి.§> A thinner ozone layer lets more UV reach Earth.'],
q:[Q('ఓజోన్ అణు సూత్రం?§Molecular formula of ozone?',['O₃','O₂','O','CO₂'],'3 ఆక్సిజన్ పరమాణువులు§Three oxygen atoms'),
Q('ఓజోన్ పొర ఏ కిరణాలను గ్రహిస్తుంది?§Ozone layer absorbs which rays?',['అతినీలలోహిత~Ultraviolet','పరారుణ మాత్రమే~Infrared only','ధ్వని~Sound','రేడియో~Radio'],'UV కిరణాలు§UV rays'),
Q('ఓజోన్‌ను క్షీణింపజేసే రసాయనాలు?§Chemicals depleting ozone?',['CFCలు~CFCs','CO₂','O₂','నైట్రోజన్~Nitrogen'],'క్లోరోఫ్లోరోకార్బన్లు§Chlorofluorocarbons'),
Q('మాంట్రియల్ ప్రొటోకాల్ ఏ సంవత్సరం?§Year of the Montreal Protocol?',['1987','1947','2007','1997'],'1987§1987'),
Q('ఓజోన్ రక్షణ పొర ఏ వాతావరణ పొరలో ఉంటుంది?§In which layer of atmosphere is the protective ozone?',['స్ట్రాటోస్ఫియర్~Stratosphere','ట్రోపోస్ఫియర్~Troposphere','ఎక్సోస్ఫియర్~Exosphere','భూమి లోపల~Inside Earth'],'ఎగువ వాతావరణంలో§High in the atmosphere')]});
// Sources: NCERT Class 10 Ch.7 'How do Organisms Reproduce?' https://ncert.nic.in/textbook/pdf/jesc107.pdf ; Wikipedia 'Pollination' https://en.wikipedia.org/wiki/Pollination
A('science',[10],{id:'plantrepro',i:'🌸',te:'పుష్పించే మొక్కల్లో ప్రత్యుత్పత్తి',en:'Reproduction in Flowering Plants',kw:'flower pollination fertilisation stamen pistil ovary ovule seed fruit pollen tube self cross budding regeneration spore పుష్పం పరాగసంపర్కం ఫలదీకరణం కేసరం అండకోశం అండం విత్తనం ఫలం',
n:['# అలైంగిక పద్ధతులు§# Asexual methods','ద్విదావిచ్ఛిత్తి (అమీబా), మొగ్గ తొడగడం (హైడ్రా), పునరుత్పత్తి (ప్లనేరియా), బీజాంశ ఏర్పాటు (రైజోపస్) అలైంగిక పద్ధతులు.§Binary fission (Amoeba), budding (Hydra), regeneration (Planaria) and spore formation (Rhizopus) are asexual methods.','# పుష్పం§# The flower','పుష్పంలో రక్షక పత్రాలు, ఆకర్షక పత్రాలు, కేసరాలు, స్త్రీకేసరం (పిస్టిల్) ఉంటాయి. కేసరాలు, స్త్రీకేసరం ప్రత్యుత్పత్తి భాగాలు. కేసరాలు పరాగరేణువులను తయారు చేస్తాయి.§A flower has sepals, petals, stamens and a pistil. Stamens and the pistil are the reproductive parts. Stamens make pollen grains.','# స్త్రీకేసరం§# Pistil','అడుగున ఉబ్బిన భాగం అండాశయం, మధ్య పొడవైన భాగం కీలం, చివరి భాగం కీలాగ్రం (స్టిగ్మా). అండాశయంలో అండాలు ఉంటాయి; ప్రతి అండంలో అండ కణం ఉంటుంది.§The swollen base is the ovary, the middle part the style and the tip the stigma. The ovary has ovules, each with an egg cell.','# పరాగసంపర్కం§# Pollination','పరాగరేణువులు కేసరం నుంచి కీలాగ్రానికి చేరడం పరాగసంపర్కం. అదే పుష్పంలో జరిగితే స్వపరాగసంపర్కం, ఒక పుష్పం నుంచి మరొక పుష్పానికి జరిగితే పరపరాగసంపర్కం.§Transfer of pollen from stamen to stigma is pollination: self-pollination in the same flower, cross-pollination between flowers.','# ఫలదీకరణం§# Fertilisation','కీలాగ్రంపై పడిన పరాగరేణువు నుంచి పరాగనాళం కీలం గుండా అండాశయం చేరుతుంది. పురుష బీజకణం అండ కణంతో కలిసి సంయుక్త బీజం (జైగోట్) ఏర్పడుతుంది.§A pollen tube grows through the style to the ovary. The male gamete fuses with the egg to form a zygote.','# విత్తనం, ఫలం§# Seed and fruit','సంయుక్త బీజం విభజన చెంది భ్రూణం ఏర్పడుతుంది. అండం విత్తనంగా, అండాశయం ఫలంగా మారుతుంది.§The zygote divides to form an embryo. The ovule becomes the seed and the ovary becomes the fruit.'],
q:[Q('కేసరాలు ఉత్పత్తి చేసేవి?§Stamens produce?',['పరాగరేణువులు~Pollen grains','అండాలు~Ovules','విత్తనాలు~Seeds','ఫలాలు~Fruits'],'పురుష బీజకణాలు పరాగరేణువుల్లో§Male gametes are in pollen'),
Q('ఫలంగా మారే భాగం?§Which part becomes the fruit?',['అండాశయం~Ovary','అండం~Ovule','కీలం~Style','కేసరం~Stamen'],'అండాశయం ఫలం§Ovary becomes fruit'),
Q('విత్తనంగా మారే భాగం?§Which part becomes the seed?',['అండం~Ovule','అండాశయం~Ovary','పుష్ప దళాలు~Petals','కీలాగ్రం~Stigma'],'ఫలదీకరణ తర్వాత అండం విత్తనం§Ovule becomes seed after fertilisation'),
Q('పరాగరేణువు కేసరం నుంచి కీలాగ్రానికి చేరడం?§Pollen moving from stamen to stigma?',['పరాగసంపర్కం~Pollination','ఫలదీకరణం~Fertilisation','అంకురోత్పత్తి~Germination','విచ్ఛిత్తి~Fission'],'పరాగసంపర్కం§Pollination'),
Q('హైడ్రాలో ఉండే అలైంగిక పద్ధతి?§Asexual method in Hydra?',['మొగ్గ తొడగడం~Budding','బీజాంశాలు~Spores','ద్విదావిచ్ఛిత్తి~Binary fission','పరాగసంపర్కం~Pollination'],'హైడ్రా మొగ్గ తొడుగుతుంది§Hydra reproduces by budding')]});
// Sources: NCERT Class 10 Ch.6 'Control and Coordination' https://ncert.nic.in/textbook/pdf/jesc106.pdf ; LibreTexts OpenStax Concepts in Biology 'The Body's Systems' https://bio.libretexts.org/Bookshelves/Introductory_and_General_Biology/Concepts_in_Biology_(OpenStax)/16%3A_The_Body's_Systems
A('science',[10],{id:'nervous',i:'🧠',te:'నాడీ వ్యవస్థ, మెదడు, ప్రతిచర్య',en:'Nervous System, Brain and Reflex Action',kw:'nervous system neuron axon dendrite synapse reflex arc brain cerebrum cerebellum medulla spinal cord nadi vyavastha నాడీ కణం మెదడు వెన్నుపాము ప్రతీకార చర్య అనుమస్తిష్కం మజ్జాముఖం',
n:['# నాడీ కణం§# Neuron','నాడీ కణం (న్యూరాన్) నాడీ వ్యవస్థ నిర్మాణ, క్రియా ప్రమాణం. విద్యుత్ ప్రచోదనం డెండ్రైట్ నుంచి కణదేహానికి, అక్కడి నుంచి ఆక్సాన్ గుండా దాని చివరకు ప్రయాణిస్తుంది.§The neuron is the structural and functional unit of the nervous system. An impulse travels from the dendrite to the cell body, then along the axon to its end.','# సైనాప్స్§# Synapse','ఒక న్యూరాన్ ఆక్సాన్ చివర, తరువాతి న్యూరాన్ డెండ్రైట్ మధ్య ఉండే ఖాళీని సైనాప్స్ అంటారు. అక్కడ రసాయనాల సహాయంతో సంకేతం తరువాతి న్యూరాన్‌కు చేరుతుంది.§The gap between one neuron\'s axon end and the next neuron\'s dendrite is the synapse. The signal passes on with the help of chemicals.','# ప్రతీకార చర్య§# Reflex action','హఠాత్తుగా, ఆలోచన లేకుండా జరిగే వేగవంతమైన చర్యను ప్రతీకార చర్య అంటారు. ప్రతీకార చర్య మార్గాన్ని ప్రతీకార చాపం అంటారు; ఇది వెన్నుపాములో ఏర్పడుతుంది.§A sudden, quick response without thinking is a reflex action. Its pathway is the reflex arc, formed in the spinal cord.','# కేంద్ర నాడీ వ్యవస్థ§# Central nervous system','మెదడు, వెన్నుపాము కలిసి కేంద్ర నాడీ వ్యవస్థ. మెదడులో మూడు భాగాలు: అగ్ర మెదడు (ఫోర్‌బ్రెయిన్), మధ్య మెదడు, వెనుక మెదడు (హిండ్‌బ్రెయిన్).§The brain and spinal cord form the central nervous system. The brain has three parts: fore-brain, mid-brain and hind-brain.','# భాగాల విధులు§# Functions','అగ్ర మెదడు ఆలోచనకు ప్రధాన భాగం; ఇంద్రియ సమాచారాన్ని స్వీకరించి, వివరించి, ఐచ్ఛిక కండరాలకు ఆదేశాలు ఇస్తుంది. మజ్జాముఖం (మెడుల్లా) రక్తపోటు, లాలాజలం, వాంతి వంటి అనైచ్ఛిక చర్యలను నియంత్రిస్తుంది. అనుమస్తిష్కం (సెరిబెల్లం) ఐచ్ఛిక చర్యల కచ్చితత్వాన్ని, శరీర భంగిమను, సమతుల్యాన్ని చూస్తుంది.§The fore-brain is the main thinking part; it receives and interprets sensory information and directs voluntary muscles. The medulla controls involuntary actions such as blood pressure, salivation and vomiting. The cerebellum gives precision to voluntary actions and keeps posture and balance.','> వేడి వస్తువును తాకగానే చేయి వెనక్కి తీసుకోవడం ప్రతీకార చర్యకు ఉదాహరణ.§> Pulling your hand away from a hot object is a reflex.'],
q:[Q('నాడీ వ్యవస్థ నిర్మాణ, క్రియా ప్రమాణం?§Structural and functional unit of nervous system?',['న్యూరాన్~Neuron','నెఫ్రాన్~Nephron','హిమోగ్లోబిన్~Haemoglobin','కణత్వచం~Cell membrane'],'నాడీ కణం§Nerve cell'),
Q('శరీర సమతుల్యతను, భంగిమను నియంత్రించే భాగం?§Which part keeps balance and posture?',['అనుమస్తిష్కం (సెరిబెల్లం)~Cerebellum','మజ్జాముఖం~Medulla','అగ్ర మెదడు~Fore-brain','వెన్నుపాము~Spinal cord'],'సెరిబెల్లం§Cerebellum'),
Q('రక్తపోటు, వాంతిని నియంత్రించేది?§Controls blood pressure and vomiting?',['మజ్జాముఖం (మెడుల్లా)~Medulla','సెరిబెల్లం~Cerebellum','అగ్ర మెదడు~Fore-brain','సైనాప్స్~Synapse'],'హిండ్‌బ్రెయిన్‌లోని మెడుల్లా§The medulla in the hind-brain'),
Q('ప్రతీకార చాపం ఎక్కడ ఏర్పడుతుంది?§Where are reflex arcs formed?',['వెన్నుపాము~Spinal cord','గుండె~Heart','ఊపిరితిత్తులు~Lungs','మూత్రపిండం~Kidney'],'వెన్నుపాములో§In the spinal cord'),
Q('రెండు న్యూరాన్ల మధ్య ఖాళీ?§The gap between two neurons?',['సైనాప్స్~Synapse','ఆక్సాన్~Axon','డెండ్రైట్~Dendrite','కణదేహం~Cell body'],'సైనాప్స్§Synapse'),
Q('కేంద్ర నాడీ వ్యవస్థలో ఉండేవి?§The central nervous system consists of?',['మెదడు, వెన్నుపాము~Brain and spinal cord','గుండె, ఊపిరితిత్తులు~Heart and lungs','కాలేయం, క్లోమం~Liver and pancreas','చేతులు, కాళ్లు~Arms and legs'],'CNS = మెదడు + వెన్నుపాము§CNS = brain + spinal cord')]});
// Sources: NCERT Class 10 Ch.6 'Control and Coordination' https://ncert.nic.in/textbook/pdf/jesc106.pdf ; NCBI Bookshelf 'Physiology, Insulin' https://www.ncbi.nlm.nih.gov/books/NBK279029/
A('science',[10],{id:'hormones',i:'💉',te:'హార్మోన్లు',en:'Hormones in Animals and Plants',kw:'hormone insulin thyroxine adrenaline growth hormone pituitary pancreas diabetes goitre auxin gibberellin cytokinin abscisic acid harmonulu హార్మోన్లు ఇన్సులిన్ థైరాక్సిన్ అడ్రినలిన్ మధుమేహం గాయిటర్ ఆక్సిన్',
n:['# జంతువుల్లో హార్మోన్లు§# Animal hormones','హార్మోన్లు రసాయన దూతలు; అంతస్రావ గ్రంథులు వాటిని నేరుగా రక్తంలోకి విడుదల చేస్తాయి. అవి శరీర పెరుగుదల, జీవక్రియను సమన్వయపరుస్తాయి.§Hormones are chemical messengers released straight into the blood by endocrine glands. They coordinate growth and metabolism.','# థైరాక్సిన్§# Thyroxine','థైరాయిడ్ గ్రంథి థైరాక్సిన్‌ను తయారు చేస్తుంది. దీనికి అయోడిన్ అవసరం. ఆహారంలో అయోడిన్ లోపిస్తే మెడ వాపుతో గాయిటర్ వస్తుంది; అందుకే అయోడిన్ కలిపిన ఉప్పు వాడతారు.§The thyroid gland makes thyroxine, which needs iodine. Lack of iodine causes goitre (swollen neck), so iodised salt is used.','# ఇన్సులిన్§# Insulin','క్లోమం (పాంక్రియాస్) ఇన్సులిన్‌ను ఉత్పత్తి చేసి రక్తంలో చక్కెర స్థాయిని నియంత్రిస్తుంది. లోపిస్తే మధుమేహం (డయాబెటిస్) వస్తుంది; చికిత్సగా ఇన్సులిన్ ఇంజెక్షన్లు ఇస్తారు.§The pancreas produces insulin, which regulates blood sugar. Its shortage causes diabetes, treated with insulin injections.','# వృద్ధి హార్మోన్, అడ్రినలిన్§# Growth hormone and adrenaline','పిట్యూటరీ గ్రంథి స్రవించే వృద్ధి హార్మోన్ పెరుగుదలను నియంత్రిస్తుంది. భయం, ఆందోళన సమయాల్లో అడ్రినల్ గ్రంథి అడ్రినలిన్‌ను స్రవిస్తుంది.§Growth hormone from the pituitary regulates growth. The adrenal gland secretes adrenaline in fear or stress.','# మొక్కల హార్మోన్లు§# Plant hormones','ఆక్సిన్: కాండం కొన వద్ద తయారై నీడ వైపు కణాలను పొడవుగా పెంచుతుంది. జిబ్బరెల్లిన్‌లు కాండం పెరుగుదలకు తోడ్పడతాయి. సైటోకైనిన్‌లు కణ విభజనను ప్రోత్సహిస్తాయి. అబ్సిసిక్ ఆమ్లం పెరుగుదలను నిరోధిస్తుంది.§Auxin makes cells on the shady side grow longer. Gibberellins help stem growth. Cytokinins promote cell division. Abscisic acid inhibits growth.','> కాంతి వైపు మొక్క వంగడానికి (ఫోటోట్రోపిజం) కారణం ఆక్సిన్ పంపిణీ.§> Auxin distribution makes plants bend towards light.'],
q:[Q('ఇన్సులిన్ ఏ అవయవం తయారు చేస్తుంది?§Which organ produces insulin?',['క్లోమం~Pancreas','కాలేయం~Liver','థైరాయిడ్~Thyroid','పిట్యూటరీ~Pituitary'],'క్లోమం§Pancreas'),
Q('థైరాక్సిన్ తయారీకి కావలసిన మూలకం?§Element needed to make thyroxine?',['అయోడిన్~Iodine','ఇనుము~Iron','కాల్షియం~Calcium','సోడియం~Sodium'],'అయోడిన్ లోపంతో గాయిటర్§Iodine lack causes goitre'),
Q('ఇన్సులిన్ లోపంతో వచ్చే వ్యాధి?§Disease caused by lack of insulin?',['మధుమేహం~Diabetes','గాయిటర్~Goitre','రక్తహీనత~Anaemia','క్షయ~TB'],'డయాబెటిస్§Diabetes'),
Q('నీడ వైపు కణాలు పొడవుగా పెరగడానికి కారణమయ్యే మొక్క హార్మోన్?§Plant hormone making cells on the shady side grow longer?',['ఆక్సిన్~Auxin','సైటోకైనిన్~Cytokinin','అబ్సిసిక్ ఆమ్లం~Abscisic acid','అడ్రినలిన్~Adrenaline'],'ఆక్సిన్§Auxin'),
Q('కణ విభజనను ప్రోత్సహించే మొక్క హార్మోన్?§Plant hormone promoting cell division?',['సైటోకైనిన్~Cytokinin','అబ్సిసిక్ ఆమ్లం~Abscisic acid','ఇన్సులిన్~Insulin','థైరాక్సిన్~Thyroxine'],'సైటోకైనిన్§Cytokinin'),
Q('భయం సమయంలో విడుదలయ్యే హార్మోన్?§Hormone released during fear?',['అడ్రినలిన్~Adrenaline','ఇన్సులిన్~Insulin','థైరాక్సిన్~Thyroxine','ఆక్సిన్~Auxin'],'అడ్రినల్ గ్రంథి§Adrenal gland')]});
// Sources: NCERT Class 10 Ch.4 'Carbon and its Compounds' https://ncert.nic.in/textbook/pdf/jesc104.pdf ; LibreTexts 'Hydrocarbons and the Homologous Series' https://chem.libretexts.org/Courses/Chabot_College/Chem_12A%3A_Organic_Chemistry_Fall_2022/05%3A__Alkanes_and_Conformations/5.01%3A_Hydrocarbons_and_the_Homologous_Series
A('science',[10],{id:'carbon',i:'💎',te:'కార్బన్, దాని సమ్మేళనాలు',en:'Carbon and its Compounds',kw:'carbon covalent bond tetravalency catenation saturated unsaturated alkane alkene alkyne methane ethane hydrocarbon homologous series functional group karban కార్బన్ సమయోజనీయ బంధం చతుర్ సంయోజకత శృంఖలనం ఆల్కేన్ ఆల్కీన్ ఆల్కైన్ మీథేన్',
n:['# సమయోజనీయ బంధం§# Covalent bond','పరమాణువులు ఎలక్ట్రాన్లను పంచుకోవడం వల్ల ఏర్పడే బంధాన్ని సమయోజనీయ బంధం అంటారు. కార్బన్‌కు నాలుగు వేలన్సీ ఎలక్ట్రాన్లు ఉండటంతో అది చతుర్ సంయోజకం (టెట్రావాలెంట్).§A bond formed by sharing electrons is a covalent bond. Carbon has four valence electrons, so it is tetravalent.','# శృంఖలనం (క్యాటినేషన్)§# Catenation','కార్బన్ పరమాణువులు ఒకదానితో ఒకటి బంధాలు ఏర్పరచి పొడవైన గొలుసులు, శాఖలున్న గొలుసులు, వలయాలుగా ఏర్పడగలవు. ఈ ధర్మాన్ని శృంఖలనం అంటారు. ఈ ధర్మం కార్బన్‌కు ఉన్నంతగా మరే మూలకానికి లేదు.§Carbon atoms can link to form long chains, branched chains and rings. This is catenation. No other element shows it to the extent carbon does.','# సంతృప్త, అసంతృప్త§# Saturated and unsaturated','కార్బన్ పరమాణువుల మధ్య ఏకబంధాలు మాత్రమే ఉన్న సమ్మేళనాలు సంతృప్తాలు; ద్విబంధం లేదా త్రిబంధం ఉన్నవి అసంతృప్తాలు. సంతృప్తాలు సాధారణంగా తక్కువ క్రియాశీలం.§Compounds with only single bonds between carbon atoms are saturated; those with double or triple bonds are unsaturated. Saturated ones are normally less reactive.','# హైడ్రోకార్బన్లు§# Hydrocarbons','కార్బన్, హైడ్రోజన్‌లు మాత్రమే ఉన్న సమ్మేళనాలు హైడ్రోకార్బన్లు. సంతృప్తాలు ఆల్కేన్లు (CₙH₂ₙ₊₂), ద్విబంధం ఉన్నవి ఆల్కీన్లు (CₙH₂ₙ), త్రిబంధం ఉన్నవి ఆల్కైన్లు.§Compounds of only carbon and hydrogen are hydrocarbons. Saturated ones are alkanes (CₙH₂ₙ₊₂), those with double bonds are alkenes (CₙH₂ₙ) and with triple bonds are alkynes.','# మొదటి ఆల్కేన్లు§# First alkanes','మీథేన్ CH₄, ఈథేన్ C₂H₆, ప్రొపేన్ C₃H₈, బ్యూటేన్ C₄H₁₀, పెంటేన్ C₅H₁₂. మీథేన్ బయోగ్యాస్, CNG లలో ప్రధాన భాగం.§Methane CH₄, ethane C₂H₆, propane C₃H₈, butane C₄H₁₀, pentane C₅H₁₂. Methane is a main part of biogas and CNG.','# సజాతీయ శ్రేణి§# Homologous series','ఒకే క్రియాత్మక సమూహం ఉండి, వరుస సభ్యుల మధ్య -CH₂- తేడా ఉండే సమ్మేళనాల శ్రేణిని సజాతీయ శ్రేణి అంటారు (ఉదా. CH₄, C₂H₆).§A series with the same functional group where consecutive members differ by a -CH₂- unit is a homologous series (e.g. CH₄, C₂H₆).','> ప్రొపేన్ (C₃H₈): n = 3, CₙH₂ₙ₊₂ = C₃H₈.§> Propane (C₃H₈): n = 3, CₙH₂ₙ₊₂ = C₃H₈.'],
q:[Q('కార్బన్ వేలన్సీ?§Valency of carbon?',['4','2','3','1'],'4 వేలన్సీ ఎలక్ట్రాన్లు§Four valence electrons'),
Q('కార్బన్ పరమాణువులు గొలుసులు ఏర్పరచే ధర్మం?§Property of carbon forming chains?',['శృంఖలనం~Catenation','అయనీకరణం~Ionisation','విద్యుద్విశ్లేషణ~Electrolysis','ఆక్సీకరణం~Oxidation'],'క్యాటినేషన్§Catenation'),
Q('ఆల్కేన్‌ల సాధారణ సూత్రం?§General formula of alkanes?',['CₙH₂ₙ₊₂','CₙH₂ₙ','CₙH₂ₙ₋₂','CₙHₙ'],'ఉదా. ప్రొపేన్ C₃H₈§E.g. propane C₃H₈'),
Q('ఈథేన్ అణు సూత్రం?§Formula of ethane?',['C₂H₆','C₂H₄','CH₄','C₃H₈'],'2 కార్బన్లు, 6 హైడ్రోజన్లు§2 C and 6 H'),
Q('ద్విబంధం ఉన్న హైడ్రోకార్బన్లు?§Hydrocarbons with double bonds?',['ఆల్కీన్లు~Alkenes','ఆల్కేన్లు~Alkanes','ఆల్కైన్లు~Alkynes','ఆల్కహాల్లు~Alcohols'],'ఆల్కీన్ CₙH₂ₙ§Alkene CₙH₂ₙ'),
Q('బయోగ్యాస్, CNG లో ప్రధాన వాయువు?§Main gas in biogas and CNG?',['మీథేన్~Methane','ఈథేన్~Ethane','హైడ్రోజన్~Hydrogen','నైట్రోజన్~Nitrogen'],'మీథేన్ CH₄§Methane CH₄')]});
// Sources: NCERT Class 8 Ch.8 'Force and Pressure' https://ncert.nic.in/textbook/pdf/hesc108.pdf ; Wikipedia 'Pressure' https://en.wikipedia.org/wiki/Pressure
A('science',[8],{id:'pressure',i:'📏',te:'పీడనం',en:'Pressure',kw:'pressure force area pascal atmospheric pressure liquids gases peedanam పీడనం బలం వైశాల్యం పాస్కల్ వాతావరణ పీడనం',
n:['# నిర్వచనం§# Definition','ఏకాంక వైశాల్యంపై పనిచేసే బలాన్ని పీడనం అంటారు. పీడనం = బలం ÷ బలం పనిచేసే వైశాల్యం.§Force acting on a unit area is pressure. Pressure = force ÷ area on which it acts.','# ప్రమాణం§# Unit','పీడన ప్రమాణం న్యూటన్/మీ² (N/m²), దీన్ని పాస్కల్ (Pa) అంటారు.§The unit of pressure is newton per square metre (N/m²), called the pascal (Pa).','# వైశాల్యం ప్రభావం§# Effect of area','ఒకే బలానికి వైశాల్యం తక్కువైతే పీడనం ఎక్కువ. అందుకే మొనదేలిన మేకు సులభంగా దిగుతుంది, పదునైన కత్తి బాగా కోస్తుంది; భారమైన సంచులకు వెడల్పాటి పట్టీలు ఉంటాయి.§For the same force a smaller area gives more pressure. So a pointed nail goes in easily, a sharp knife cuts well, and heavy bags have broad straps.','# ద్రవాలు, వాయువులు§# Liquids and gases','ద్రవాలు, వాయువులు తమ పాత్ర గోడలపై పీడనం కలిగిస్తాయి. ద్రవం ఒకే లోతు వద్ద అన్ని వైపులా సమాన పీడనం కలిగిస్తుంది.§Liquids and gases exert pressure on the walls of their containers. A liquid exerts equal pressure at the same depth.','# వాతావరణ పీడనం§# Atmospheric pressure','గాలి మన చుట్టూ ఉన్న అన్ని వస్తువులపై కలిగించే పీడనాన్ని వాతావరణ పీడనం అంటారు. అది ఉంది కాబట్టి సక్షన్ కప్పు గోడకు అతుక్కుంటుంది.§The pressure air exerts on everything around us is atmospheric pressure. It is why a suction cup sticks to a wall.','> 100 N బలం 2 మీ² పై పనిచేస్తే పీడనం = 100 ÷ 2 = 50 Pa.§> 100 N on 2 m² gives pressure = 100 ÷ 2 = 50 Pa.'],
q:[Q('పీడనం సూత్రం?§Formula of pressure?',['బలం ÷ వైశాల్యం~Force ÷ area','బలం × వైశాల్యం~Force × area','వైశాల్యం ÷ బలం~Area ÷ force','బలం + వైశాల్యం~Force + area'],'P = F/A§P = F/A'),
Q('పీడన ప్రమాణం?§Unit of pressure?',['పాస్కల్~Pascal','న్యూటన్~Newton','జౌల్~Joule','వాట్~Watt'],'1 Pa = 1 N/m²§1 Pa = 1 N/m²'),
Q('ఒకే బలానికి వైశాల్యం తగ్గితే పీడనం?§If area decreases for the same force, pressure?',['పెరుగుతుంది~Increases','తగ్గుతుంది~Decreases','మారదు~Unchanged','సున్నా~Zero'],'వైశాల్యానికి విలోమానుపాతం§Inversely related to area'),
Q('50 N బలం 5 మీ² పై పనిచేస్తే పీడనం?§Pressure of 50 N on 5 m²?',['10 Pa','250 Pa','55 Pa','0.1 Pa'],'50 ÷ 5 = 10§50 ÷ 5 = 10'),
Q('భారమైన సంచులకు వెడల్పాటి పట్టీలు ఎందుకు?§Why do heavy bags have broad straps?',['పీడనం తగ్గడానికి~To reduce pressure','పీడనం పెంచడానికి~To raise pressure','అందం కోసం మాత్రమే~Only for looks','బరువు పెంచడానికి~To add weight'],'వైశాల్యం ఎక్కువైతే పీడనం తక్కువ§Larger area, less pressure')]});
LD.reg('bsci3',1)})();
