// Science batch 4 (AksharaNova). NCERT sources are the current textbook PDFs on ncert.nic.in (Class 6 'Curiosity' fecu1xx, Class 7 gesc1xx, Class 8 hesc1xx). Each topic has a second independent source.
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
// Sources: NCERT Class 6 Ch.12 'Beyond Earth' https://ncert.nic.in/textbook/pdf/fecu112.pdf ; NASA 'Planets' https://science.nasa.gov/solar-system/planets/ ; Britannica 'Proxima Centauri' https://www.britannica.com/science/Proxima-Centauri ; Britannica '88 constellations' https://www.britannica.com/question/How-many-constellations-are-officially-recognized
A('science',[6],{id:'solarsystem',i:'🪐',te:'సౌరకుటుంబం',en:'The Solar System',kw:'solar system sun planets earth mars venus mercury jupiter saturn uranus neptune asteroid comet star constellation pole star rotation revolution sourakutumbam సౌరకుటుంబం గ్రహాలు సూర్యుడు నక్షత్రం కుజుడు శుక్రుడు భూమి',
n:['# సూర్యుడు§# The Sun','సూర్యుడు ఒక నక్షత్రం; మనకు అత్యంత దగ్గరి నక్షత్రం. సూర్యుని తరువాత మనకు దగ్గరి నక్షత్రం ప్రాక్సిమా సెంటారీ.§The Sun is a star, the one closest to us. After the Sun, the nearest star to us is Proxima Centauri.','# గ్రహాలు§# Planets','గ్రహం అంటే సూర్యుని చుట్టూ తిరిగే పెద్ద, దాదాపు గోళాకార వస్తువు. సూర్యుని నుంచి దూరం పెరిగే క్రమంలో ఎనిమిది గ్రహాలు: బుధుడు, శుక్రుడు, భూమి, కుజుడు, గురుడు, శని, యురేనస్, నెప్ట్యూన్.§A planet is a large, nearly spherical object that revolves around the Sun. The eight planets in order of distance from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.','# లోపలి నాలుగు గ్రహాలు§# Inner planets','బుధుడు, శుక్రుడు, భూమి, కుజుడు చిన్నవి; వీటికి రాళ్లతో కూడిన ఘన ఉపరితలాలు ఉంటాయి.§Mercury, Venus, Earth and Mars are smaller and have solid rocky surfaces.','# భూమి కదలికలు§# Earth\'s movements','భూమి సూర్యుని చుట్టూ తిరగడాన్ని పరిభ్రమణం (రివల్యూషన్) అంటారు; ఒక చుట్టుకు సుమారు ఒక సంవత్సరం పడుతుంది. తన అక్షం చుట్టూ తిరగడానికి (భ్రమణం) సుమారు 24 గంటలు పడుతుంది; దీన్ని ఒక రోజు అంటారు.§Earth going round the Sun is revolution and takes about one year. One rotation on its axis takes about 24 hours, called a day.','# ప్రత్యేక పేర్లు§# Special names','కుజుడు (మార్స్) నేల ఎర్రగా ఉండటం వల్ల ఎర్ర గ్రహం. భూమి ఎక్కువ భాగం నీటితో కప్పబడి ఉండటంతో అంతరిక్షం నుంచి నీలంగా కనిపించి నీలి గ్రహం అనబడుతుంది. శుక్రుడు నక్షత్రం కాకపోయినా ఉదయ, సాయంత్ర నక్షత్రంగా పిలువబడతాడు.§Mars is the Red Planet because its soil is reddish. Earth is the Blue Planet because water covers much of it. Venus is called the Morning or Evening Star though it is not a star.','# నక్షత్ర రాశులు§# Constellations','నక్షత్రాల సమూహ నమూనాలను నక్షత్ర రాశులు అంటారు. అధికారికంగా 88 రాశులు గుర్తించబడ్డాయి. ధ్రువ నక్షత్రం (పోలారిస్) ఉత్తర దిశలో దాదాపు స్థిరంగా కనిపిస్తుంది.§Patterns of stars are constellations. 88 are officially recognised. The Pole Star (Polaris) appears nearly stationary in the north.','> కుజుడు, గురుడు గ్రహాల మధ్య చిన్న రాతి ముక్కలు ఉన్న ప్రాంతాన్ని గ్రహశకలాల పట్టీ (ఆస్టరాయిడ్ బెల్ట్) అంటారు.§> The region of many small rocky bodies between Mars and Jupiter is the asteroid belt.'],
q:[Q('సౌరకుటుంబంలో గ్రహాల సంఖ్య?§Number of planets in the solar system?',['8','9','7','10'],'బుధుడు నుంచి నెప్ట్యూన్ వరకు§Mercury to Neptune'),
Q('సూర్యునికి అత్యంత దగ్గరి గ్రహం?§Planet nearest the Sun?',['బుధుడు~Mercury','శుక్రుడు~Venus','భూమి~Earth','కుజుడు~Mars'],'బుధుడు మొదటి గ్రహం§Mercury is first'),
Q('ఎర్ర గ్రహం అని దేన్ని అంటారు?§Which is called the Red Planet?',['కుజుడు~Mars','శుక్రుడు~Venus','శని~Saturn','గురుడు~Jupiter'],'నేల ఎర్రగా ఉంటుంది§Its soil is reddish'),
Q('భూమి తన అక్షం చుట్టూ తిరగడానికి పట్టే సమయం?§Time for Earth to rotate once on its axis?',['సుమారు 24 గంటలు~About 24 hours','సుమారు 1 సంవత్సరం~About 1 year','సుమారు 1 నెల~About 1 month','సుమారు 12 గంటలు~About 12 hours'],'ఒక రోజు§One day'),
Q('మనకు అత్యంత దగ్గరి నక్షత్రం?§Nearest star to us?',['సూర్యుడు~Sun','ప్రాక్సిమా సెంటారీ~Proxima Centauri','ధ్రువ నక్షత్రం~Pole Star','శుక్రుడు~Venus'],'సూర్యుడు ఒక నక్షత్రం§The Sun is a star'),
Q('అధికారికంగా గుర్తించిన నక్షత్ర రాశుల సంఖ్య?§Number of officially recognised constellations?',['88','12','48','108'],'IAU 88 రాశులను గుర్తించింది§The IAU recognises 88')]});
// Sources: NCERT Class 6 Ch.8 'A Journey through States of Water' https://ncert.nic.in/textbook/pdf/fecu108.pdf ; USGS 'The Water Cycle' https://www.usgs.gov/water-science-school/water-cycle
A('science',[6],{id:'watercycle',i:'🌧️',te:'నీటి స్థితులు, జలచక్రం',en:'States of Water and the Water Cycle',kw:'water cycle evaporation condensation melting freezing rain clouds vapour jalachakram నీటి చక్రం జలచక్రం బాష్పీభవనం సాంద్రీకరణం మేఘాలు వర్షం మంచు',
n:['# మూడు స్థితులు§# Three states','నీరు ఘనం (మంచు), ద్రవం (నీరు), వాయువు (నీటి ఆవిరి) స్థితుల్లో ఉంటుంది. మంచు, నీరు ఒకే పదార్థం యొక్క రెండు రూపాలు.§Water exists as solid (ice), liquid (water) and gas (water vapour). Ice and water are two forms of the same substance.','# ద్రవీభవనం, ఘనీభవనం§# Melting and freezing','ఘనం ద్రవంగా మారడం ద్రవీభవనం; ద్రవం ఘనంగా మారడం ఘనీభవనం.§Solid turning into liquid is melting; liquid turning into solid is freezing.','# బాష్పీభవనం§# Evaporation','ద్రవం నీటి ఆవిరిగా మారడాన్ని బాష్పీభవనం అంటారు. ఇది నిరంతరం జరుగుతుంది; వర్షపు రోజుల్లో కంటే ఎండ, గాలి ఉన్న రోజుల్లో బట్టలు త్వరగా ఆరతాయి.§A liquid changing to vapour is evaporation. It happens all the time. Clothes dry quicker on sunny, windy days.','# సాంద్రీకరణం§# Condensation','నీటి ఆవిరి ద్రవంగా మారడాన్ని సాంద్రీకరణం అంటారు. చల్లని నీటి గ్లాసు బయట నీటి బిందువులు ఏర్పడటానికి కారణం గాలిలోని ఆవిరి సాంద్రీకరణం.§Vapour changing to liquid is condensation. Droplets on a cold glass form when vapour in air condenses.','# మేఘాలు, వర్షం§# Clouds and rain','నీటి ఆవిరి పైకి వెళ్లి చల్లబడి చిన్న నీటి బిందువులుగా మారి మేఘాలు ఏర్పడతాయి. అనేక బిందువులు కలిసి బరువెక్కి వర్షంగా కురుస్తాయి.§Vapour rises, cools and forms tiny droplets that make clouds. Many droplets join, grow heavy and fall as rain.','# జలచక్రం§# Water cycle','భూమి, సముద్రాల నుంచి నీరు ఆవిరై, మేఘాలుగా మారి, వర్షంగా తిరిగి భూమికి చేరే నిరంతర ప్రసరణను జలచక్రం అంటారు.§The continuous circulation of water by evaporation, cloud formation and rain back to Earth is the water cycle.','> మట్టి కుండ (సురాహి)లో నీరు చల్లగా ఉండటానికి కారణం కుండ గోడల నుంచి నీరు ఆవిరవుతూ చల్లదనం ఇవ్వడం.§> Water in an earthen pot (surahi) stays cool because evaporation from its walls cools it.'],
q:[Q('ద్రవం నీటి ఆవిరిగా మారడం?§Liquid changing into vapour?',['బాష్పీభవనం~Evaporation','సాంద్రీకరణం~Condensation','ఘనీభవనం~Freezing','ద్రవీభవనం~Melting'],'ఎండలో వేగంగా జరుగుతుంది§Faster in sunshine'),
Q('నీటి ఆవిరి ద్రవంగా మారడం?§Vapour changing into liquid?',['సాంద్రీకరణం~Condensation','బాష్పీభవనం~Evaporation','ద్రవీభవనం~Melting','ఉత్పతనం~Sublimation'],'చల్లని గ్లాసు బయట బిందువులు§Droplets on a cold glass'),
Q('మంచు కరిగి నీరు కావడం?§Ice turning into water?',['ద్రవీభవనం~Melting','ఘనీభవనం~Freezing','బాష్పీభవనం~Evaporation','సాంద్రీకరణం~Condensation'],'ఘనం → ద్రవం§Solid to liquid'),
Q('మేఘాలు ఎలా ఏర్పడతాయి?§How do clouds form?',['ఆవిరి చల్లబడి బిందువులుగా మారి~Vapour cools into droplets','నీరు గడ్డకట్టి~Water freezing on the ground','గాలి లేకపోవడం~Absence of air','మట్టి ఎండిపోవడం~Soil drying'],'సాంద్రీకరణం§Condensation'),
Q('భూమి, మేఘాలు, వర్షం మధ్య నీటి నిరంతర ప్రసరణ?§Continuous circulation of water on Earth?',['జలచక్రం~Water cycle','శిలాచక్రం~Rock cycle','ఆహార గొలుసు~Food chain','కార్బన్ చక్రం~Carbon cycle'],'జలచక్రం§Water cycle')]});
// Sources: NCERT Class 6 Ch.9 'Methods of Separation in Everyday Life' https://ncert.nic.in/textbook/pdf/fecu109.pdf ; Wikipedia 'Winnowing' https://en.wikipedia.org/wiki/Winnowing ; Britannica Kids 'Mixtures' (sedimentation, decantation) https://kids.britannica.com/kids/assembly/view/348621
A('science',[6],{id:'separation',i:'🧺',te:'మిశ్రమాల వేరు పద్ధతులు',en:'Methods of Separation',kw:'separation handpicking threshing winnowing sieving sedimentation decantation filtration evaporation magnetic separation churning mishramalu వేరు చేయడం చెరగడం తూర్పార పట్టడం జల్లెడ అవక్షేపణ వడపోత',
n:['# చేతితో ఏరడం§# Handpicking','బియ్యం నుంచి చిన్న రాళ్లు, పొట్టు వంటి పెద్ద ముక్కలను చేతితో ఏరడాన్ని హ్యాండ్‌పికింగ్ అంటారు.§Picking out stones or husk from rice by hand is handpicking.','# నూర్పిడి, తూర్పార పట్టడం§# Threshing and winnowing','కంకుల నుంచి ధాన్యాన్ని వేరు చేయడం నూర్పిడి (త్రెషింగ్). గాలి లేదా ఊదే గాలి ద్వారా తేలికైన పొట్టును ధాన్యం నుంచి వేరు చేయడం తూర్పార పట్టడం (విన్నోయింగ్).§Separating grain from stalks is threshing. Using wind or blown air to remove light husk from grain is winnowing.','# జల్లెడ§# Sieving','కణాల పరిమాణంలో తేడాను ఉపయోగించి జల్లెడతో వేరు చేయడం జల్లెడ పట్టడం. ఉదా: పిండిని జల్లెడ పట్టడం.§Separating by particle size using a sieve is sieving, e.g. sieving flour.','# అవక్షేపణ, డికాంటేషన్§# Sedimentation and decantation','ద్రవం అడుగున బరువైన భాగం స్థిరపడటం అవక్షేపణ. పాత్రను వంచి పైన ఉన్న ద్రవాన్ని వేరు చేయడం డికాంటేషన్ (ఉదా. టీ నుంచి ఆకులను వేరు చేయడం).§Heavier parts settling at the bottom is sedimentation. Tilting the vessel to pour off the liquid is decantation.','# బాష్పీభవనం, అయస్కాంత వేరు§# Evaporation and magnetic separation','ద్రవం ఆవిరిగా మారడం బాష్పీభవనం. అయస్కాంత పదార్థాలను (ఇనుము వంటివి) అయస్కాంతంతో వేరు చేయడం అయస్కాంత విభజన.§Evaporation changes a liquid into vapour. Using a magnet to separate magnetic substances such as iron is magnetic separation.','> పెరుగును చిలికి వెన్న తీయడం (చర్నింగ్) కూడా ఒక వేరు చేసే పద్ధతి.§> Churning curd to get butter is also a separation method.'],
q:[Q('కంకుల నుంచి ధాన్యం వేరు చేయడం?§Separating grain from stalks?',['నూర్పిడి~Threshing','జల్లెడ~Sieving','డికాంటేషన్~Decantation','బాష్పీభవనం~Evaporation'],'త్రెషింగ్§Threshing'),
Q('గాలితో పొట్టును వేరు చేసే పద్ధతి?§Method that uses wind to remove husk?',['విన్నోయింగ్~Winnowing','జల్లెడ~Sieving','అవక్షేపణ~Sedimentation','చేతితో ఏరడం~Handpicking'],'తేలికైన పొట్టు ఎగిరిపోతుంది§Light husk blows away'),
Q('పిండిని జల్లెడ పట్టడం దేనిపై ఆధారపడుతుంది?§Sieving depends on?',['కణ పరిమాణం~Particle size','రంగు~Colour','వాసన~Smell','రుచి~Taste'],'రంధ్రాల కంటే చిన్న కణాలు దాటుతాయి§Small particles pass through'),
Q('ఇనుప పొడిని ఇసుక నుంచి వేరు చేసే పద్ధతి?§Separating iron filings from sand?',['అయస్కాంత విభజన~Magnetic separation','విన్నోయింగ్~Winnowing','చర్నింగ్~Churning','నూర్పిడి~Threshing'],'ఇనుము అయస్కాంత పదార్థం§Iron is magnetic'),
Q('పాత్రను వంచి పైన ఉన్న ద్రవాన్ని వేరు చేయడం?§Tilting a vessel to pour off the liquid?',['డికాంటేషన్~Decantation','జల్లెడ~Sieving','నూర్పిడి~Threshing','ఉత్పతనం~Sublimation'],'అవక్షేపణ తర్వాత చేస్తారు§Done after sedimentation')]});
// Sources: NCERT Class 7 Ch.9 'Motion and Time' https://ncert.nic.in/textbook/pdf/gesc109.pdf ; NIST SI base units https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-4-two-classes-si-units-and-si-prefixes ; Wikipedia 'Speed' https://en.wikipedia.org/wiki/Speed
A('science',[7],{id:'speedtime',i:'⏱️',te:'వేగం, కాలం',en:'Speed and Time',kw:'speed distance time uniform non-uniform pendulum oscillation time period km/h m/s motion vegam kalam వేగం దూరం కాలం డోలనం లోలకం ఆవర్తన కాలం',
n:['# వేగం§# Speed','వస్తువు మొత్తం ప్రయాణించిన దూరాన్ని, అందుకు పట్టిన మొత్తం కాలంతో భాగిస్తే వచ్చేది వేగం. వేగం = దూరం ÷ కాలం.§Speed is the total distance covered divided by the total time taken. Speed = distance ÷ time.','# ప్రమాణాలు§# Units','వేగం ప్రాథమిక ప్రమాణం మీ/సె (m/s). కి.మీ/గం (km/h) కూడా వాడతారు. కాలం ప్రాథమిక ప్రమాణం సెకను.§The basic unit of speed is m/s; km/h is also used. The basic unit of time is the second.','# ఏకరీతి, అసమ చలనం§# Uniform and non-uniform motion','సమాన కాలాల్లో సమాన దూరాలు ప్రయాణిస్తే ఏకరీతి చలనం; లేకపోతే అసమ చలనం.§Equal distances in equal times is uniform motion; otherwise it is non-uniform.','# సరళ లోలకం§# Simple pendulum','లోలకం గుండ్రని బాబ్ దారానికి వేలాడుతూ ఉంటుంది. బాబ్ మధ్య స్థానం నుంచి బయలుదేరి ఒక చివరకు, తిరిగి అవతలి చివరకు వెళ్లి మధ్య స్థానానికి రావడం ఒక డోలనం. ఒక డోలనానికి పట్టే కాలాన్ని ఆవర్తన కాలం అంటారు.§A pendulum has a bob hanging by a thread. One complete to-and-fro motion is one oscillation, and the time for one oscillation is its time period.','# కొలత§# Measuring','ఆవర్తన కాలం కచ్చితంగా తెలుసుకోవడానికి 20 డోలనాలకు పట్టే కాలాన్ని కొలిచి 20తో భాగిస్తారు.§To find the time period accurately, measure the time for 20 oscillations and divide by 20.','> 100 కి.మీ దూరాన్ని 2 గంటల్లో వెళ్తే సగటు వేగం = 100 ÷ 2 = 50 కి.మీ/గం.§> 100 km in 2 hours gives average speed = 100 ÷ 2 = 50 km/h.'],
q:[Q('వేగం సూత్రం?§Formula of speed?',['దూరం ÷ కాలం~Distance ÷ time','కాలం ÷ దూరం~Time ÷ distance','దూరం × కాలం~Distance × time','దూరం + కాలం~Distance + time'],'v = d/t§v = d/t'),
Q('వేగం ప్రాథమిక ప్రమాణం?§Basic unit of speed?',['మీ/సె~m/s','కి.మీ~km','సెకను~second','కి.గ్రా~kg'],'మీటర్ ప్రతి సెకను§Metre per second'),
Q('150 కి.మీ ను 3 గంటల్లో వెళ్తే వేగం?§Speed if 150 km in 3 hours?',['50 కి.మీ/గం~50 km/h','450 కి.మీ/గం~450 km/h','153 కి.మీ/గం~153 km/h','0.02 కి.మీ/గం~0.02 km/h'],'150 ÷ 3 = 50§150 ÷ 3 = 50'),
Q('లోలకం ఒక డోలనానికి పట్టే కాలం?§Time for one oscillation of a pendulum?',['ఆవర్తన కాలం~Time period','వేగం~Speed','దూరం~Distance','పౌనఃపున్యం కాదు~Not frequency'],'దీనిని time period అంటారు§Called the time period'),
Q('సమాన కాలాల్లో సమాన దూరాలు ప్రయాణించే చలనం?§Motion covering equal distances in equal times?',['ఏకరీతి చలనం~Uniform motion','అసమ చలనం~Non-uniform motion','వృత్తాకార చలనం మాత్రమే~Only circular','నిశ్చలం~At rest'],'ఏకరీతి చలనం§Uniform motion')]});
// Sources: NCERT Class 8 Ch.9 'Friction' https://ncert.nic.in/textbook/pdf/hesc109.pdf ; Britannica 'Friction' https://www.britannica.com/science/friction ; Britannica 'Static friction' https://www.britannica.com/science/static-friction
A('science',[8],{id:'friction',i:'🛞',te:'ఘర్షణ',en:'Friction',kw:'friction static sliding rolling lubricant ball bearing rough surface gharshana ఘర్షణ స్థిర ఘర్షణ జారుడు ఘర్షణ దొర్లు ఘర్షణ కందెన',
n:['# ఘర్షణ అంటే§# What is friction','రెండు తలాలు తాకి ఉన్నప్పుడు వాటి సాపేక్ష చలనాన్ని వ్యతిరేకించే బలం ఘర్షణ. ఘర్షణ ఎల్లప్పుడూ ప్రయోగించిన బలానికి వ్యతిరేక దిశలో ఉంటుంది.§Friction is the force that opposes relative motion between surfaces in contact. It always acts opposite to the applied force.','# కారణం§# Cause','తలాల్లోని చిన్న చిన్న ఎగుడుదిగుళ్లు ఒకదానిలో ఒకటి ఇరుక్కోవడం వల్ల ఘర్షణ కలుగుతుంది. తలం గరుకుగా ఉంటే ఘర్షణ ఎక్కువ.§Friction arises because tiny irregularities on the surfaces interlock. Rough surfaces give more friction.','# రకాలు§# Types','స్థిర ఘర్షణ: నిశ్చల వస్తువు కదలడం మొదలుపెట్టకుండా ఆపేది. జారుడు ఘర్షణ: వస్తువు జారుతున్నప్పుడు ఉండేది; ఇది స్థిర ఘర్షణ కంటే కొంచెం తక్కువ. దొర్లు ఘర్షణ: చక్రాలు దొర్లేటప్పుడు ఉండేది; ఇది జారుడు ఘర్షణ కంటే తక్కువ.§Static friction stops a body at rest from starting to move. Sliding friction acts while sliding and is slightly smaller than static friction. Rolling friction acts when something rolls and is smaller than sliding friction.','# ఉపయోగం§# Uses','ఘర్షణ వల్లే మనం నడవగలం, మేకు గోడలో నిలుస్తుంది, బూట్ల అడుగున, టైర్లపై గాడులు పట్టు కోసం ఉంటాయి.§Friction lets us walk and holds a nail in a wall; grooves on shoes and tyres give grip.','# తగ్గించే మార్గాలు§# Reducing friction','కందెనలు (నూనె, గ్రీజు) వాడటం, బాల్ బేరింగ్‌లు వాడటం ద్వారా ఘర్షణ తగ్గించవచ్చు. యంత్రాల్లో ఘర్షణ అరుగుదలకు, వేడికి కారణమవుతుంది.§Lubricants and ball bearings reduce friction. In machines friction causes wear and heat.','> బరువైన పెట్టెను జరపడం మొదట కష్టం (స్థిర ఘర్షణ), జరగడం మొదలయ్యాక కొంచెం సులభం (జారుడు ఘర్షణ).§> A heavy box is hard to start moving (static friction) and a bit easier once sliding (sliding friction).'],
q:[Q('ఘర్షణ ఏ దిశలో ఉంటుంది?§Friction acts in which direction?',['ప్రయోగించిన బలానికి వ్యతిరేకం~Opposite to the applied force','అదే దిశ~Same direction','లంబ దిశ~Perpendicular','ఏదీ కాదు~None'],'సాపేక్ష చలనాన్ని వ్యతిరేకిస్తుంది§It opposes relative motion'),
Q('ఏ ఘర్షణ అతి తక్కువ?§Which friction is the smallest?',['దొర్లు ఘర్షణ~Rolling friction','జారుడు ఘర్షణ~Sliding friction','స్థిర ఘర్షణ~Static friction','అన్నీ సమానం~All equal'],'చక్రాలు ఘర్షణను తగ్గిస్తాయి§Wheels reduce friction'),
Q('ఘర్షణను తగ్గించేది?§What reduces friction?',['కందెన~Lubricant','గరుకు తలం~Rough surface','ఇసుక చల్లడం~Sprinkling sand','బరువు పెంచడం~Adding weight'],'నూనె, గ్రీజు§Oil and grease'),
Q('గరుకు తలంపై ఘర్షణ?§Friction on a rough surface?',['ఎక్కువ~More','తక్కువ~Less','సున్నా~Zero','మారదు~Same'],'ఎగుడుదిగుళ్లు ఎక్కువ§More irregularities'),
Q('నిశ్చల వస్తువు కదలడం ఆపే ఘర్షణ?§Friction that stops a body at rest from moving?',['స్థిర ఘర్షణ~Static friction','జారుడు ఘర్షణ~Sliding friction','దొర్లు ఘర్షణ~Rolling friction','గాలి~Air'],'స్థిర ఘర్షణ§Static friction')]});
// Sources: NCERT Class 8 Ch.4 'Combustion and Flame' https://ncert.nic.in/textbook/pdf/hesc104.pdf ; Britannica 'Combustion' https://www.britannica.com/science/combustion ; Science Learning Hub 'What is fire' https://www.sciencelearn.org.nz/resources/747-what-is-fire
A('science',[8],{id:'combustion',i:'🔥',te:'దహనం, మంట',en:'Combustion and Flame',kw:'combustion flame fuel ignition temperature fire extinguisher oxygen inflammable daham manta దహనం మంట జ్వలన ఉష్ణోగ్రత ఇంధనం అగ్నిమాపక',
n:['# దహనం అంటే§# What is combustion','పదార్థం ఆక్సిజన్‌తో చర్య జరిపి వేడిని ఇచ్చే రసాయన చర్య దహనం. కొన్నిసార్లు మంటతో, కొన్నిసార్లు మంట లేకుండా మండుతుంది.§Combustion is a chemical process in which a substance reacts with oxygen and gives heat, sometimes with a flame, sometimes without.','# మండడానికి కావలసినవి§# What burning needs','దహనానికి మండే పదార్థం (ఇంధనం), ఆక్సిజన్ (గాలి), జ్వలన ఉష్ణోగ్రత వరకు వేడి కావాలి.§Burning needs a fuel, oxygen (air) and heat up to the ignition temperature.','# జ్వలన ఉష్ణోగ్రత§# Ignition temperature','ఒక పదార్థం మండటం మొదలుపెట్టే అత్యల్ప ఉష్ణోగ్రతను జ్వలన ఉష్ణోగ్రత అంటారు. పెట్రోల్, ఆల్కహాల్, LPG వంటి వాటికి ఇది తక్కువ కాబట్టి అవి తేలికగా అంటుకుంటాయి; ఇలాంటివి సులభంగా మండే పదార్థాలు.§The lowest temperature at which a substance catches fire is its ignition temperature. Petrol, alcohol and LPG have low ones, so they catch fire easily; they are inflammable.','# మంటలను ఆర్పడం§# Putting out fires','నీరు మండే పదార్థాన్ని చల్లబరిచి, ఆవిరి కప్పి మంటను ఆర్పుతుంది. కానీ విద్యుత్ పరికరాల మంటలకు, నూనె, పెట్రోల్ మంటలకు నీరు సరిపోదు; వాటికి కార్బన్ డయాక్సైడ్ (CO₂) ఉత్తమం, అది మంటను దుప్పటిలా కప్పి ఇంధనానికి ఆక్సిజన్ చేరకుండా చేస్తుంది.§Water cools the burning material and its vapour covers the fire. Water is not suitable for electrical equipment or oil and petrol fires; CO₂ is best, covering the fire like a blanket and cutting off oxygen.','# జాగ్రత్త§# Safety','ఒంటికి మంట అంటుకుంటే దుప్పటి చుట్టి మంటను ఆర్పవచ్చు. మంటలతో ఆడకూడదు; ఇంట్లో గ్యాస్ లీకైతే స్విచ్‌లు వేయకూడదు, పెద్దలకు చెప్పాలి.§If clothes catch fire, wrapping a blanket around the person puts it out. Never play with fire; if gas leaks, do not touch switches and tell an adult.','> కాగితపు కప్పులో నీరు వేడి చేస్తే కాగితం కాలదు, ఎందుకంటే నీరు వేడిని గ్రహించి కాగితం జ్వలన ఉష్ణోగ్రత చేరకుండా చేస్తుంది.§> Water heated in a paper cup does not burn the paper, because the water takes up heat and keeps it below ignition temperature.'],
q:[Q('దహనంలో పదార్థం దేనితో చర్య జరుపుతుంది?§In combustion a substance reacts with?',['ఆక్సిజన్~Oxygen','నైట్రోజన్~Nitrogen','హీలియం~Helium','ఆర్గాన్~Argon'],'ఆక్సిజన్ అవసరం§Oxygen is needed'),
Q('జ్వలన ఉష్ణోగ్రత అంటే?§Ignition temperature is?',['మండటం మొదలయ్యే అత్యల్ప ఉష్ణోగ్రత~Lowest temperature at which a substance catches fire','అత్యధిక ఉష్ణోగ్రత~Highest temperature','నీటి మరుగు స్థానం~Boiling point of water','గది ఉష్ణోగ్రత~Room temperature'],'తక్కువ ఉంటే తేలికగా మండుతుంది§Lower means easier to ignite'),
Q('విద్యుత్ పరికరాల మంటకు ఉత్తమ ఆర్పే సాధనం?§Best for fires in electrical equipment?',['CO₂ ఆర్పే యంత్రం~CO₂ extinguisher','నీరు~Water','మట్టి నూనె~Kerosene','గాలి ఊదడం~Blowing air'],'నీరు విద్యుత్ ప్రమాదం§Water is unsafe'),
Q('దహనానికి అవసరం లేనిది?§Not needed for combustion?',['నీరు~Water','ఇంధనం~Fuel','ఆక్సిజన్~Oxygen','జ్వలన ఉష్ణోగ్రతకు వేడి~Heat to ignition temperature'],'ఇంధనం, ఆక్సిజన్, వేడి కావాలి§Fuel, oxygen and heat are needed'),
Q('సులభంగా మండే పదార్థం?§An inflammable substance?',['పెట్రోల్~Petrol','ఇసుక~Sand','నీరు~Water','గాజు~Glass'],'పెట్రోల్ జ్వలన ఉష్ణోగ్రత తక్కువ§Petrol has a low ignition temperature')]});
LD.reg('bsci4',1)})();
