// Science batch 6 (AksharaNova), Classes 6-7. NCERT: Class 6 Curiosity ch3 fecu103, ch5 fecu105; Class 7 gesc101 (ch1), gesc107 (ch7). Each fact has an independent second source (see per-topic comments).
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
// Sources: NCERT Class 6 ch3 'Mindful Eating' https://ncert.nic.in/textbook/pdf/fecu103.pdf (nutrients, scurvy/Vit C, goitre/iodine, vitamin chart, roughage, water) ; NHS vitamin C https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-c/ (lack of vitamin C -> scurvy) ; NHS vitamin D https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-d/ (rickets, sunlight) ; NHS iodine https://www.nhs.uk/conditions/vitamins-and-minerals/iodine/ ; NHS iron https://www.nhs.uk/conditions/vitamins-and-minerals/iron/ (iron-deficiency anaemia) ; NHS calcium https://www.nhs.uk/conditions/vitamins-and-minerals/calcium/ (bones and teeth) ; Wikipedia Night blindness https://en.wikipedia.org/wiki/Night_blindness (vitamin A)
A('science',[6],{id:'foodcomp',i:'🥗',te:'ఆహార అంశాలు (పోషకాలు)',en:'Food Components (Nutrients)',kw:'food nutrients carbohydrates proteins fats vitamins minerals roughage fibre water scurvy goitre rickets anaemia night blindness pushtikaharam ahaaram poshakalu పోషకాలు ఆహారం విటమిన్ ఖనిజాలు పిండిపదార్థాలు మాంసకృత్తులు కొవ్వులు',
n:['# పోషకాలు§# Nutrients','మన శరీరానికి శక్తి ఇచ్చి, పెరుగుదలకు తోడ్పడి, శరీరాన్ని బాగుచేసి, వ్యాధుల నుంచి కాపాడే ఆహార అంశాలను పోషకాలు అంటారు. ముఖ్య పోషకాలు: పిండిపదార్థాలు (కార్బోహైడ్రేట్లు), మాంసకృత్తులు (ప్రోటీన్లు), కొవ్వులు, విటమిన్లు, ఖనిజాలు.§Food components that give energy, support growth, repair the body and protect it from disease are called nutrients. The major nutrients are carbohydrates, proteins, fats, vitamins and minerals.','# శక్తినిచ్చేవి§# Energy-giving','కార్బోహైడ్రేట్లు, కొవ్వులు శక్తిని ఇస్తాయి. గ్లూకోజ్ ఒక కార్బోహైడ్రేట్. ధాన్యాలు (బియ్యం, గోధుమ) కార్బోహైడ్రేట్లకు మంచి వనరులు.§Carbohydrates and fats give us energy. Glucose is a carbohydrate. Cereals such as rice and wheat are good sources of carbohydrates.','# ప్రోటీన్లు§# Proteins','పప్పులు, బీన్స్, బఠానీలు, గింజలు మొక్కల నుంచి వచ్చే ప్రోటీన్ వనరులు. పాలు, పనీర్, గుడ్డు, చేప, మాంసం జంతు వనరులు. ప్రోటీన్లు శరీర పెరుగుదలకు, కండరాల నిర్మాణానికి ఉపయోగపడతాయి.§Pulses, beans, peas and nuts are plant sources of protein; milk, paneer, egg, fish and meat are animal sources. Proteins help the body grow and build muscles.','# విటమిన్లు, ఖనిజాలు§# Vitamins and minerals','విటమిన్లు, ఖనిజాలను రక్షక పోషకాలు అంటారు; ఇవి వ్యాధుల నుంచి కాపాడతాయి. లోపం వల్ల జబ్బులు వస్తాయి: విటమిన్ C లోపం వల్ల స్కర్వీ (చిగుళ్ళ నుంచి రక్తం కారడం, గాయాలు ఆలస్యంగా మానడం), విటమిన్ D లోపం వల్ల రికెట్స్ (ఎముకలు మెత్తబడి వంగడం).§Vitamins and minerals are protective nutrients. Their lack causes deficiency diseases: lack of vitamin C causes scurvy (bleeding gums, slow healing of wounds); lack of vitamin D causes rickets (soft, bent bones).','విటమిన్ A లోపం వల్ల చూపు తగ్గుతుంది (రేచీకటి). అయోడిన్ లోపం వల్ల మెడ ముందు భాగం వాపు (గాయిటర్) వస్తుంది. ఇనుము లోపం వల్ల రక్తహీనత (నీరసం, ఊపిరి ఆడకపోవడం) వస్తుంది.§Lack of vitamin A reduces vision (night blindness). Lack of iodine causes swelling at the front of the neck (goitre). Lack of iron causes anaemia (weakness, shortness of breath).','> అయోడిన్ ఉప్పు: మామూలు ఉప్పులో తగినంత అయోడిన్ లవణాలు కలిపిన ఉప్పు.§> Iodised salt is common salt mixed with the right amount of iodine salts.','# పీచు, నీరు§# Roughage and water','పీచు (రఫేజ్) పోషకాలను ఇవ్వదు, కానీ జీర్ణం కాని ఆహారాన్ని బయటకు పంపి మలవిసర్జన సాఫీగా అయ్యేలా చేస్తుంది. ఆకుకూరలు, తాజా పండ్లు, పొట్టు ధాన్యాలు, పప్పులు పీచుకు మంచి వనరులు. నీరు ఆహారం నుంచి పోషకాలు శరీరం గ్రహించడానికి, చెమట రూపంలో వ్యర్థాలు బయటకు పోవడానికి తోడ్పడుతుంది.§Roughage gives no nutrients but helps remove undigested food and keeps bowel movement smooth. Green leafy vegetables, fresh fruits, whole grains, pulses and nuts are good sources. Water helps the body absorb nutrients from food and remove waste through sweat.'],
q:[Q('నిమ్మ, నారింజ తింటే ఏ వ్యాధి తగ్గుతుంది?§Eating lemon and orange helps cure which disease?',['స్కర్వీ§Scurvy','రికెట్స్§Rickets','గాయిటర్§Goitre','రక్తహీనత§Anaemia'],'నిమ్మ, నారింజలో విటమిన్ C ఉంటుంది; దీని లోపం వల్ల స్కర్వీ వస్తుంది.§Citrus fruits contain vitamin C, and its lack causes scurvy.'),
Q('అయోడిన్ లోపం వల్ల వచ్చే వ్యాధి ఏది?§Which disease is caused by lack of iodine?',['గాయిటర్§Goitre','స్కర్వీ§Scurvy','రేచీకటి§Night blindness','రికెట్స్§Rickets'],'అయోడిన్ లోపం వల్ల మెడ ముందు భాగం వాపు (గాయిటర్) వస్తుంది.§Lack of iodine causes swelling at the front of the neck (goitre).'),
Q('ఎముకలు మెత్తబడి వంగే రికెట్స్ వ్యాధి ఏ విటమిన్ లోపం వల్ల వస్తుంది?§Rickets (soft, bent bones) is due to lack of which vitamin?',['విటమిన్ D§Vitamin D','విటమిన్ C§Vitamin C','విటమిన్ A§Vitamin A','విటమిన్ B1§Vitamin B1'],'విటమిన్ D ఎముకలు, పళ్ళు బలంగా ఉండటానికి కాల్షియం గ్రహించేందుకు సహాయపడుతుంది.§Vitamin D helps the body absorb calcium for strong bones and teeth.'),
Q('శక్తినిచ్చే పోషకాలు ఏవి?§Which nutrients give energy?',['కార్బోహైడ్రేట్లు, కొవ్వులు§Carbohydrates and fats','విటమిన్లు, ఖనిజాలు§Vitamins and minerals','పీచు, నీరు§Roughage and water','ఇనుము, అయోడిన్§Iron and iodine'],'కార్బోహైడ్రేట్లు, కొవ్వులను శక్తినిచ్చే పోషకాలు అంటారు.§Carbohydrates and fats are the energy-giving nutrients.'),
Q('పీచు (రఫేజ్) వల్ల ఉపయోగం ఏమిటి?§What is roughage useful for?',['జీర్ణం కాని ఆహారాన్ని బయటకు పంపడానికి§To remove undigested food','ఎముకలు వంగకుండా§To stop bones from bending','కంటి చూపుకు§For eyesight','రక్తం ఎర్రగా ఉండటానికి§To make blood red'],'పీచు జీర్ణం కాని ఆహారం బయటకు పోవడానికి తోడ్పడుతుంది.§Roughage helps remove undigested food.'),
Q('పప్పులు, పనీర్, గుడ్డు ప్రధానంగా ఏ పోషకానికి వనరులు?§Pulses, paneer and eggs are mainly sources of which nutrient?',['ప్రోటీన్లు§Proteins','పీచు§Roughage','నీరు§Water','అయోడిన్§Iodine'],'పప్పులు, పనీర్, గుడ్డు ప్రోటీన్లకు మంచి వనరులు.§Pulses, paneer and eggs are good protein sources.')]});
// Sources: NCERT Class 6 ch5 https://ncert.nic.in/textbook/pdf/fecu105.pdf (handspan, SI unit metre, cm, mm, km, curved line with thread, correct reading) ; NIST 'Meter' https://www.nist.gov/si-redefinition/meter (metre is the SI unit of length; earlier body-based units vary)
A('science',[6],{id:'measlen',i:'📏',te:'పొడవును కొలవడం',en:'Measuring Length',kw:'length measurement metre centimetre millimetre kilometre scale tape handspan unit SI podavu kolatha పొడవు కొలత మీటరు సెంటీమీటరు',
n:['# మన అవయవాలతో కొలత§# Measuring with body parts','జాన (హ్యాండ్‌స్పాన్) వంటి శరీర భాగాలతో కొలిస్తే ఫలితం మనిషి మనిషికీ మారుతుంది, ఎందుకంటే అందరి జానలు ఒకేలా ఉండవు.§Measuring with body parts such as the handspan gives different results for different people because everyone\'s handspan is different.','# ప్రామాణిక ప్రమాణాలు§# Standard units','అందరూ ఒకే విధంగా కొలవడానికి అంతర్జాతీయ ప్రమాణాల పద్ధతి (SI) వాడతారు. పొడవు SI ప్రమాణం మీటరు (m).§To measure the same way everywhere, the International System of Units (SI) is used. The SI unit of length is the metre (m).','1 మీటరు = 100 సెంటీమీటర్లు (cm). 1 సెం.మీ. = 10 మిల్లీమీటర్లు (mm). 1 కిలోమీటరు (km) = 1000 మీటర్లు.§1 m = 100 cm. 1 cm = 10 mm. 1 kilometre (km) = 1000 m.','> 15 సెం.మీ. స్కేలులో సెం.మీ.ను 10 సమాన భాగాలు చేస్తారు; ఒక భాగం 1 మి.మీ. = 0.1 సెం.మీ. ఈ స్కేలుతో కొలవగల అతి చిన్న విలువ 1 మి.మీ.§> A 15 cm scale divides each cm into 10 equal parts; each part is 1 mm = 0.1 cm, the smallest value this scale can measure.','# సరైన కొలత§# Correct measuring','కొలిచే వస్తువుకు తగిన స్కేలు వాడాలి: పెన్సిల్‌కు 15 సెం.మీ. స్కేలు, గది ఎత్తుకు మీటరు స్కేలు లేదా టేపు. చెట్టు చుట్టుకొలత, ఛాతీ కొలతకు దర్జీ వాడే సన్నని టేపు సరిపోతుంది.§Choose a scale that suits the object: a 15 cm scale for a pencil, a metre scale or tape for a room height. For a tree girth or chest size, a flexible tailor\'s tape is better.','# వంకర గీత పొడవు§# Length of a curved line','వంకర గీత పొడవును వంగే టేపుతో కొలవవచ్చు, లేదా దారం ఉంచి దాన్ని సరిచేసి మీటరు స్కేలుతో కొలవవచ్చు.§A curved line can be measured with a flexible tape, or by laying a thread along it, straightening the thread and measuring it with a metre scale.'],
q:[Q('పొడవు SI ప్రమాణం ఏది?§What is the SI unit of length?',['మీటరు§Metre','కిలోగ్రాము§Kilogram','సెకను§Second','లీటరు§Litre'],'పొడవు SI ప్రమాణం మీటరు (m).§The SI unit of length is the metre (m).'),
Q('1 మీటరు ఎన్ని సెంటీమీటర్లు?§How many centimetres are in 1 metre?',['100','10','1000','50'],'1 m = 100 cm.§1 m = 100 cm.'),
Q('1 కిలోమీటరు ఎన్ని మీటర్లు?§How many metres are in 1 kilometre?',['1000','100','10','10000'],'1 km = 1000 m.§1 km = 1000 m.'),
Q('వంకర గీత పొడవును ఎలా కొలవచ్చు?§How can we measure the length of a curved line?',['దారంతో వంకరగా ఉంచి, సరిచేసి స్కేలుతో కొలిచి§Lay a thread on it, straighten it and measure with a scale','నేరుగా మీటరు స్కేలుతో అంచనా వేసి§Guess with a straight metre scale','జానతో మాత్రమే§Only with a handspan','కొలవడం సాధ్యం కాదు§It cannot be measured'],'దారం లేదా వంగే టేపు వాడతారు.§A thread or a flexible tape is used.'),
Q('జానతో కొలిస్తే ఫలితం ఎందుకు మారుతుంది?§Why does a handspan measurement change from person to person?',['అందరి జానలు ఒకేలా ఉండవు§Everyone\'s handspan is different','టేబుల్ పొడవు మారుతుంది§The table length changes','మీటరు పొడవు మారుతుంది§The metre changes','జానకు ప్రమాణం ఉంది§The handspan is a standard unit'],'జాన పొడవు మనిషిని బట్టి మారుతుంది, అందుకే ప్రామాణిక ప్రమాణాలు వాడతారు.§Handspan length varies from person to person, so standard units are used.')]});
// Sources: NCERT Class 7 ch1 https://ncert.nic.in/textbook/pdf/gesc101.pdf (leaves food factories, stomata, chlorophyll, equation, starch, Cuscuta, pitcher plant, saprotrophs, symbiosis, lichens) ; Britannica Photosynthesis https://www.britannica.com/science/photosynthesis ; Britannica Pitcher plant https://www.britannica.com/plant/pitcher-plant ; Britannica Dodder (parasitic plant) https://www.britannica.com/plant/dodder ; Britannica Saprotroph https://www.britannica.com/science/saprotroph
A('science',[7],{id:'nutplant',i:'🌿',te:'మొక్కలలో పోషణ',en:'Nutrition in Plants',kw:'photosynthesis chlorophyll stomata autotroph heterotroph parasite cuscuta amarbel pitcher plant saprotroph fungi lichen symbiosis starch mokkala poshana కిరణజన్య సంయోగక్రియ పత్రహరితం మొక్కలు పోషణ',
n:['# స్వయంపోషకాలు§# Autotrophs','మొక్కలు తమ ఆహారాన్ని తామే తయారు చేసుకుంటాయి, అందుకే వాటిని స్వయంపోషకాలు అంటారు. జంతువులు ఇతర జీవుల నుంచి ఆహారం తీసుకుంటాయి; వాటిని పరపోషకాలు అంటారు.§Plants make their own food, so they are called autotrophs. Animals depend on others for food and are called heterotrophs.','# కిరణజన్య సంయోగక్రియ§# Photosynthesis','ఆకులు మొక్కల ఆహార కర్మాగారాలు. క్లోరోఫిల్ ఉన్న ఆకు కణాలు సూర్యకాంతిలో కార్బన్ డయాక్సైడ్, నీటిని ఉపయోగించి కార్బోహైడ్రేట్లను తయారు చేస్తాయి, ఆక్సిజన్ విడుదల అవుతుంది.§Leaves are the food factories of plants. Chlorophyll-containing leaf cells use sunlight, carbon dioxide and water to make carbohydrates, and oxygen is released.','> కార్బన్ డయాక్సైడ్ + నీరు → (సూర్యకాంతి, క్లోరోఫిల్) → కార్బోహైడ్రేట్ + ఆక్సిజన్§> Carbon dioxide + water → (sunlight, chlorophyll) → carbohydrate + oxygen','నీరు, ఖనిజాలను వేర్లు నేల నుంచి గ్రహిస్తాయి. గాలిలోని కార్బన్ డయాక్సైడ్‌ను ఆకుల ఉపరితలంపై ఉండే సూక్ష్మ రంధ్రాలు (పత్రరంధ్రాలు, స్టోమాటా) ద్వారా గ్రహిస్తాయి.§Roots absorb water and minerals from the soil. Carbon dioxide from the air enters through tiny pores on leaves called stomata.','ఆకులో పిండిపదార్థం (స్టార్చ్) ఉంటే కిరణజన్య సంయోగక్రియ జరిగిందని తెలుస్తుంది. స్టార్చ్ కూడా ఒక కార్బోహైడ్రేట్.§Starch in a leaf shows that photosynthesis has taken place. Starch is also a carbohydrate.','# ఇతర పోషణ విధానాలు§# Other modes of nutrition','అమర్‌బెల్ (కస్కుటా)కు క్లోరోఫిల్ ఉండదు; అది ఆశ్రయ మొక్క నుంచి తయారైన ఆహారం తీసుకుంటుంది, కాబట్టి పరాన్నజీవి. కీటకాలను పట్టి జీర్ణం చేసుకునే కూజా మొక్క వంటి వాటిని కీటకభక్షక మొక్కలు అంటారు.§Cuscuta (Amarbel) has no chlorophyll and takes ready-made food from its host plant, so it is a parasite. Plants such as the pitcher plant that trap and digest insects are called insectivorous plants.','పుట్టగొడుగులు వంటి శిలీంధ్రాలు చనిపోయిన, కుళ్ళిన పదార్థం నుంచి పోషకాలు గ్రహిస్తాయి; ఇది మృతజీవీ పోషణ. కొన్ని జీవులు కలిసి జీవిస్తాయి (సహజీవనం): లైకెన్‌లో శైవలం (ఆల్గా), శిలీంధ్రం కలిసి ఉంటాయి.§Fungi such as mushrooms absorb nutrients from dead and decaying matter (saprotrophic nutrition). Some organisms live together and share shelter and food (symbiosis); in lichens an alga and a fungus live together.'],
q:[Q('మొక్కల ఆహార కర్మాగారాలు ఏవి?§What are the food factories of plants?',['ఆకులు§Leaves','వేర్లు§Roots','పూలు§Flowers','కాయలు§Fruits'],'ఆకులలోని క్లోరోఫిల్ కణాలు ఆహారం తయారు చేస్తాయి.§Chlorophyll-containing cells in leaves make food.'),
Q('కిరణజన్య సంయోగక్రియలో విడుదలయ్యే వాయువు ఏది?§Which gas is released during photosynthesis?',['ఆక్సిజన్§Oxygen','కార్బన్ డయాక్సైడ్§Carbon dioxide','నైట్రోజన్§Nitrogen','హైడ్రోజన్§Hydrogen'],'కార్బన్ డయాక్సైడ్, నీరు కార్బోహైడ్రేట్, ఆక్సిజన్‌గా మారతాయి.§Carbon dioxide and water change into carbohydrate and oxygen.'),
Q('అమర్‌బెల్ (కస్కుటా) ఎలాంటి మొక్క?§What kind of plant is Cuscuta (Amarbel)?',['పరాన్నజీవి§Parasite','కీటకభక్షక మొక్క§Insectivorous plant','స్వయంపోషకం§Autotroph','మృతజీవి§Saprotroph'],'ఇది ఆశ్రయ మొక్క నుంచి ఆహారం తీసుకుంటుంది.§It takes food from its host plant.'),
Q('ఆకులలోని సూక్ష్మ రంధ్రాల పేరు ఏమిటి?§What are the tiny pores on leaves called?',['పత్రరంధ్రాలు (స్టోమాటా)§Stomata','వేరు రోమాలు§Root hairs','జైలం§Xylem','క్లోరోఫిల్§Chlorophyll'],'స్టోమాటా ద్వారా కార్బన్ డయాక్సైడ్ ఆకులోకి వెళుతుంది.§Carbon dioxide enters the leaf through stomata.'),
Q('చనిపోయిన, కుళ్ళిన పదార్థం నుంచి పోషకాలు గ్రహించే జీవులను ఏమంటారు?§Organisms that take nutrients from dead and decaying matter are called',['మృతజీవులు (సాప్రోట్రోఫ్‌లు)§Saprotrophs','స్వయంపోషకాలు§Autotrophs','పరాన్నజీవులు§Parasites','కీటకభక్షకాలు§Insectivores'],'పుట్టగొడుగులు వంటి శిలీంధ్రాలు ఉదాహరణ.§Fungi such as mushrooms are an example.'),
Q('లైకెన్‌లో కలిసి జీవించే రెండు జీవులు ఏవి?§Which two organisms live together in a lichen?',['శైవలం (ఆల్గా), శిలీంధ్రం§An alga and a fungus','శిలీంధ్రం, కీటకం§A fungus and an insect','మొక్క, జంతువు§A plant and an animal','రెండు శైవలాలు§Two algae'],'ఆల్గా ఆహారం తయారు చేస్తుంది; శిలీంధ్రం ఆశ్రయం, నీరు, ఖనిజాలు ఇస్తుంది.§The alga makes food; the fungus gives shelter, water and minerals.')]});
// Sources: NCERT Class 7 ch7 https://ncert.nic.in/textbook/pdf/gesc107.pdf (plasma, RBC haemoglobin, WBC, platelets, arteries, veins, valves, pulse 72-80) ; Britannica Artery https://www.britannica.com/science/artery (all but pulmonary artery carry oxygenated blood; veins thinner walls with valves) ; Britannica Blood https://www.britannica.com/science/blood-biochemistry (blood = RBC, WBC, platelets, plasma)
A('science',[7],{id:'bloodcirc',i:'🩸',te:'రక్తం, రక్తనాళాలు',en:'Blood and Blood Vessels',kw:'blood plasma rbc wbc platelets haemoglobin artery vein pulse capillary clot raktham rakta nalalu రక్తం ధమని సిర నాడి హిమోగ్లోబిన్',
n:['# రక్తం§# Blood','రక్తంలో ప్లాస్మా అనే ద్రవం ఉంటుంది; అందులో వివిధ రకాల కణాలు తేలుతూ ఉంటాయి.§Blood has a fluid called plasma in which different types of cells are suspended.','ఎర్ర రక్తకణాలలో హిమోగ్లోబిన్ అనే ఎర్రని వర్ణకం ఉంటుంది. ఇది ఆక్సిజన్‌తో కలిసి శరీరమంతా చేరుస్తుంది. హిమోగ్లోబిన్ వల్లే రక్తం ఎర్రగా కనిపిస్తుంది.§Red blood cells contain a red pigment called haemoglobin. It binds with oxygen and carries it around the body. Haemoglobin makes blood look red.','తెల్ల రక్తకణాలు శరీరంలోకి వచ్చే సూక్ష్మజీవులతో పోరాడతాయి. ప్లేట్‌లెట్లు రక్తం గడ్డకట్టడానికి తోడ్పడతాయి; అందుకే గాయం నుంచి రక్తస్రావం ఆగుతుంది.§White blood cells fight germs that enter the body. Platelets help blood clot, which stops bleeding from a cut.','# రక్తనాళాలు§# Blood vessels','ధమనులు గుండె నుంచి శరీర భాగాలకు ఆక్సిజన్ ఎక్కువగా ఉన్న రక్తాన్ని తీసుకెళతాయి. రక్తం వేగంగా, ఎక్కువ ఒత్తిడితో ప్రవహిస్తుంది కాబట్టి వాటి గోడలు మందంగా, సాగే గుణంతో ఉంటాయి.§Arteries carry oxygen-rich blood from the heart to body parts. Blood flows fast and at high pressure, so their walls are thick and elastic.','సిరలు శరీర భాగాల నుంచి కార్బన్ డయాక్సైడ్ ఎక్కువగా ఉన్న రక్తాన్ని గుండెకు తెస్తాయి. వాటి గోడలు పల్చగా ఉంటాయి; రక్తం గుండె వైపే వెళ్లేలా కవాటాలు ఉంటాయి.§Veins bring carbon dioxide-rich blood from body parts back to the heart. Their walls are thin and they have valves so that blood flows only towards the heart.','> మినహాయింపు: ఊపిరితిత్తుల ధమని గుండె నుంచి CO₂ ఎక్కువగా ఉన్న రక్తాన్ని ఊపిరితిత్తులకు తీసుకెళుతుంది; ఊపిరితిత్తుల సిర ఆక్సిజన్ ఎక్కువగా ఉన్న రక్తాన్ని గుండెకు తెస్తుంది.§> Exception: the pulmonary artery carries CO₂-rich blood from the heart to the lungs; the pulmonary vein brings oxygen-rich blood from the lungs to the heart.','# నాడి§# Pulse','మణికట్టు దగ్గర అనిపించే కొట్టుకోవడాన్ని నాడి (పల్స్) అంటారు; ఇది ధమనులలో రక్తం ప్రవహించడం వల్ల వస్తుంది. విశ్రాంతిలో ఉన్న వ్యక్తికి నిమిషానికి సుమారు 72 నుంచి 80 సార్లు ఉంటుందని NCERT చెబుతుంది.§The throbbing felt at the wrist is the pulse, caused by blood flowing in the arteries. NCERT says a resting person usually has 72 to 80 beats per minute.'],
q:[Q('రక్తం ఎర్రగా కనిపించడానికి కారణం ఏమిటి?§What makes blood look red?',['హిమోగ్లోబిన్§Haemoglobin','ప్లాస్మా§Plasma','ప్లేట్‌లెట్లు§Platelets','తెల్ల రక్తకణాలు§White blood cells'],'ఎర్ర రక్తకణాలలోని హిమోగ్లోబిన్ రక్తానికి ఎరుపు రంగు ఇస్తుంది.§Haemoglobin in red blood cells gives blood its red colour.'),
Q('గాయమైనప్పుడు రక్తం గడ్డకట్టడానికి ఏవి తోడ్పడతాయి?§Which help blood to clot at a cut?',['ప్లేట్‌లెట్లు§Platelets','ఎర్ర రక్తకణాలు§Red blood cells','తెల్ల రక్తకణాలు§White blood cells','ప్లాస్మా మాత్రమే§Plasma alone'],'ప్లేట్‌లెట్లు గడ్డ ఏర్పడేలా చేసి రక్తస్రావం ఆపుతాయి.§Platelets form a clot and stop bleeding.'),
Q('గుండె నుంచి శరీర భాగాలకు రక్తాన్ని తీసుకెళ్లే నాళాలు ఏవి?§Which vessels carry blood from the heart to body parts?',['ధమనులు§Arteries','సిరలు§Veins','కేశనాళికలు§Capillaries','రక్తకణాలు§Blood cells'],'ధమనుల గోడలు మందంగా ఉంటాయి.§Arteries have thick walls.'),
Q('సిరలలో కవాటాలు ఎందుకు ఉంటాయి?§Why do veins have valves?',['రక్తం గుండె వైపే ప్రవహించడానికి§So that blood flows only towards the heart','రక్తం వెనక్కి ప్రవహించడానికి§So that blood flows backwards','ఆక్సిజన్ తయారుచేయడానికి§To make oxygen','నాడి కొట్టడానికి§To make the pulse'],'కవాటాలు రక్తం గుండె వైపే వెళ్లేలా చేస్తాయి.§Valves let blood flow only towards the heart.'),
Q('ఊపిరితిత్తుల ధమని ఏ రక్తాన్ని తీసుకెళుతుంది?§Which blood does the pulmonary artery carry?',['కార్బన్ డయాక్సైడ్ ఎక్కువగా ఉన్న రక్తం§Carbon dioxide-rich blood','ఆక్సిజన్ ఎక్కువగా ఉన్న రక్తం§Oxygen-rich blood','కేవలం నీరు§Only water','రక్తం ఉండదు§No blood'],'ఊపిరితిత్తుల ధమని గుండె నుంచి ఊపిరితిత్తులకు CO₂ ఎక్కువగా ఉన్న రక్తాన్ని తీసుకెళుతుంది.§It carries CO₂-rich blood from the heart to the lungs.'),
Q('నాడి (పల్స్) దేని వల్ల వస్తుంది?§What causes the pulse?',['ధమనులలో రక్తం ప్రవహించడం§Blood flowing in the arteries','ఎముకలు కదలడం§Bones moving','సిరలలో కవాటాలు§Valves in veins','చర్మం కదలడం§Skin moving'],'ప్రతి గుండె కొట్టుకోవడం ధమనులలో ఒక నాడి కొట్టుకోవడాన్ని ఇస్తుంది.§Each heartbeat produces one pulse in the arteries.')]});
// Sources: NCERT Class 7 ch7 https://ncert.nic.in/textbook/pdf/gesc107.pdf (excretion, kidneys, urea, dialysis, xylem, phloem, transpiration) ; Britannica Xylem https://www.britannica.com/science/xylem (conducts water and minerals roots to rest of plant) ; Britannica Phloem https://www.britannica.com/science/phloem (conducts food made in leaves) ; Britannica Kidney https://www.britannica.com/science/kidney (expels metabolic wastes, maintains water balance)
A('science',[7],{id:'excretrans',i:'🚰',te:'విసర్జన, మొక్కలలో రవాణా',en:'Excretion and Transport in Plants',kw:'excretion kidney urine urea dialysis xylem phloem transpiration vasarjana mutra pindalu విసర్జన మూత్రపిండాలు మూత్రం జైలం ఫ్లోయం బాష్పోత్సేకం',
n:['# విసర్జన§# Excretion','కణాలు పనిచేసినప్పుడు విషపూరిత వ్యర్థాలు ఏర్పడతాయి. వాటిని శరీరం నుంచి తొలగించే ప్రక్రియను విసర్జన అంటారు.§Cells make toxic wastes when they work. The removal of such wastes from the body is called excretion.','రెండు మూత్రపిండాలలోని రక్తనాళాలు రక్తాన్ని వడపోస్తాయి. ఉపయోగకరమైనవి తిరిగి రక్తంలోకి పోతాయి; నీటిలో కరిగిన వ్యర్థాలు మూత్రంగా బయటకు వెళతాయి.§Blood capillaries in the two kidneys filter the blood. Useful substances go back into the blood; wastes dissolved in water leave as urine.','మూత్రం మూత్రపిండాల నుంచి మూత్రనాళాల ద్వారా మూత్రాశయానికి చేరి, మూత్రమార్గం (యూరిత్రా) ద్వారా బయటకు వెళుతుంది. మూత్రపిండాలు, మూత్రనాళాలు, మూత్రాశయం, మూత్రమార్గం కలిసి విసర్జన వ్యవస్థ.§Urine goes from the kidneys through the ureters to the urinary bladder and leaves through the urethra. The kidneys, ureters, bladder and urethra form the excretory system.','మనుషులలో ప్రధాన విసర్జక పదార్థం యూరియా. మూత్రపిండాలు పనిచేయకపోతే రక్తాన్ని కృత్రిమ మూత్రపిండం ద్వారా వడపోస్తారు; దీనిని డయాలసిస్ అంటారు. చెమట కూడా శరీరాన్ని చల్లబరుస్తుంది.§The main excretory product in humans is urea. If kidneys fail, blood is filtered by an artificial kidney; this is called dialysis. Sweat also cools the body.','# మొక్కలలో రవాణా§# Transport in plants','వేర్లు నేల నుంచి నీరు, ఖనిజాలు గ్రహిస్తాయి. వీటిని జైలం అనే నాళాలు వేర్ల నుంచి ఆకులకు, మొక్క అన్ని భాగాలకు చేరుస్తాయి.§Roots absorb water and minerals. Vessels called xylem carry them from the roots to the leaves and all other parts.','ఆకులలో తయారైన ఆహారాన్ని మొక్క అన్ని భాగాలకు ఫ్లోయం చేరుస్తుంది. జైలం, ఫ్లోయం కలిపి నాళికా కణజాలం.§Phloem carries food made in leaves to all parts of the plant. Xylem and phloem together are the vascular tissue.','నేల నుంచి గ్రహించిన నీటిలో కొంత ఆకుల పత్రరంధ్రాల ద్వారా ఆవిరి అవుతుంది; దీన్ని బాష్పోత్సేకం అంటారు. ఇది నీటిని పైకి లాగే చూషణ శక్తిని కలిగిస్తుంది.§Some of the water absorbed escapes as vapour through the stomata of leaves; this is transpiration. It creates a suction pull that draws water upwards.'],
q:[Q('మూత్రం నిల్వ అయ్యే అవయవం ఏది?§Which organ stores urine?',['మూత్రాశయం§Urinary bladder','మూత్రపిండం§Kidney','మూత్రనాళం§Ureter','ఊపిరితిత్తులు§Lungs'],'మూత్రం మూత్రాశయానికి చేరి, మూత్రమార్గం ద్వారా బయటకు పోతుంది.§Urine collects in the bladder and leaves through the urethra.'),
Q('మనుషులలో ప్రధాన విసర్జక పదార్థం ఏది?§What is the main excretory product in humans?',['యూరియా§Urea','గ్లూకోజ్§Glucose','స్టార్చ్§Starch','ఆక్సిజన్§Oxygen'],'మానవులలో ప్రధాన విసర్జక పదార్థం యూరియా.§Urea is the major excretory product in humans.'),
Q('మూత్రపిండాలు పనిచేయనప్పుడు రక్తాన్ని వడపోసే పద్ధతి పేరు?§What is the filtering of blood by an artificial kidney called?',['డయాలసిస్§Dialysis','ట్రాన్స్పిరేషన్§Transpiration','ఫోటోసింథసిస్§Photosynthesis','ఎక్స్‌రే§X-ray'],'కృత్రిమ మూత్రపిండం ద్వారా వడపోసే ప్రక్రియను డయాలసిస్ అంటారు.§Filtering by an artificial kidney is called dialysis.'),
Q('నీరు, ఖనిజాలను వేర్ల నుంచి ఆకులకు చేర్చే నాళాలు ఏవి?§Which vessels carry water and minerals from roots to leaves?',['జైలం§Xylem','ఫ్లోయం§Phloem','ధమనులు§Arteries','సిరలు§Veins'],'జైలం వేర్లను ఆకులతో కలిపే నిరంతర నాళాల వ్యవస్థ.§Xylem is a continuous network joining roots to leaves.'),
Q('ఆకులలో తయారైన ఆహారాన్ని మొక్క భాగాలకు చేర్చేది ఏది?§What carries food made in leaves to other parts of the plant?',['ఫ్లోయం§Phloem','జైలం§Xylem','వేరు రోమాలు§Root hairs','పత్రరంధ్రాలు§Stomata'],'ఆహారాన్ని రవాణా చేసే కణజాలం ఫ్లోయం.§Phloem transports food.'),
Q('ఆకుల నుంచి నీరు ఆవిరి కావడాన్ని ఏమంటారు?§Loss of water vapour from leaves is called',['బాష్పోత్సేకం§Transpiration','విసర్జన§Excretion','కిరణజన్య సంయోగక్రియ§Photosynthesis','శ్వాసక్రియ§Respiration'],'ఇది పత్రరంధ్రాల ద్వారా జరుగుతుంది.§It happens through the stomata.')]});
LD.reg('bsci7',1)})();
