// Telugu samethalu (proverbs) batch 9, Q(question te§en,[correct te~en,w1,w2,w3],explanation te§en)
// PUBLIC DOMAIN / COPYRIGHT: proverbs are anonymous folk sayings handed down by word of mouth, so no single author. Explanations, English translations and questions are my own wording. I did NOT copy any website explanation. (If the builder wants a legal opinion on folk sayings, treat as UNSURE.)
// TEXT SOURCES: each proverb text appears in 2+ of: telugubucket.com/1000-best-telugu-samethalu-telugu-proverbs, mysymedia.com/100-telugu-samethalu, peddabaalasiksha.com/baasha-vijnanam/proverbs, te.wikipedia.org/wiki/సామెతలు, todaytelugu.net/en/culture/samethalu. I checked by exact text match after removing spaces and punctuation. Pairs: అందని ద్రాక్ష, అనుమానం, ఆస్తి మూరెడు, అప్పుచేసి, కాకి పిల్ల, అడగందే, కంచే చేను (mysymedia + telugubucket); ఒక దెబ్బకు, ఓడలు బళ్ళు, చక్కనమ్మ, గంగిగోవు, ఢిల్లీకి రాజైనా, హనుమంతుడి ముందా (telugubucket + peddabaalasiksha); పెరుగుట విరుగుట (telugubucket + te.wikipedia).
// MEANINGS: the sense of each proverb is the standard everyday sense; the two sites that give meaning (todaytelugu, apedu) were not available for most of these, so the meanings are NOT source-verified. Flag for review by a Telugu teacher if needed.
// LEFT OUT: proverbs with violent, caste or gender-biased meanings, and ones where sources spell differently. Wording of a proverb may vary by region; the form used is the one in the sources.
(function(){const Q=(q,o,e)=>q+'|'+o.join('|')+'|'+e;const A=LD.add;
A('telugu',[3, 4, 5, 6, 7, 8, 9, 10],{id:'tel_sam1',i:'🗣️',te:'సామెతలు: జీవిత పాఠాలు',en:'Proverbs: Life lessons',kw:'samethalu proverbs telugu life lessons andani draksha appu ashta అందని ద్రాక్ష ఆస్తి మూరెడు అప్పుచేసి పప్పుకూడు అనుమానం సామెతలు',
n:['# సామెతలు§# Proverbs',
'సామెత అంటే తక్కువ మాటల్లో గొప్ప నీతి చెప్పే పాత మాట. పెద్దలు చెప్పిన ఇలాంటి మాటలు ఇక్కడ ఉన్నాయి.§A proverb is an old saying that gives a big lesson in few words. Here are some sayings handed down by elders.',
'> అందని ద్రాక్ష పుల్లన - దొరకని వస్తువు మంచిది కాదు అని చెప్పుకోవడం. ఒక పని చేయలేనప్పుడు దాన్ని తక్కువ చేసి మాట్లాడతారు.§> Grapes out of reach are sour - Saying something is no good because you could not get it. People run it down when they cannot do it.',
'> ఆస్తి మూరెడు ఆశ బారెడు - ఉన్నది కొంచెమే కానీ కోరికలు చాలా పెద్దవి.§> Wealth a cubit, desire a fathom - What one has is small, but the wishes are very big.',
'> అప్పుచేసి పప్పుకూడు - అప్పు చేసి మంచి భోజనం తినడం తెలివి కాదు. ఉన్నంతలో జీవించాలి.§> Dal and rice by borrowing - Eating well on borrowed money is not wise. Live within your means.',
'> అనుమానం పెనుభూతం - అనవసరమైన అనుమానం మనసును భయపెడుతుంది, సంబంధాలను పాడు చేస్తుంది.§> Doubt is a great ghost - Needless doubt frightens the mind and spoils relations.'],
q:[Q('అందని ద్రాక్ష పుల్లన అనే సామెత ఎప్పుడు వాడతారు?§When is the proverb Andani draksha pullana used?',['దొరకనిది తక్కువ అని చెప్పినప్పుడు~When we run down what we could not get','ద్రాక్ష తిన్నప్పుడు~When eating grapes','పండుగ రోజు~On a festival day','వర్షం వచ్చినప్పుడు~When it rains'],'దొరకనిదాన్ని తక్కువ చేయడం.§Running down what is out of reach.'),
Q('ఆస్తి మూరెడు ఆశ బారెడు అంటే?§What does Asti mooredu asha baredu mean?',['ఉన్నది కొంచెం, కోరికలు ఎక్కువ~Little wealth, big wishes','ఆస్తి ఎక్కువ~Wealth is large','ఆశ లేదు~There is no desire','మూర కొలత నేర్చుకో~Learn the cubit'],'మూర చిన్నది, బారెడు పెద్దది.§A cubit is small, a fathom is big.'),
Q('అప్పుచేసి పప్పుకూడు ఏ పాఠం చెబుతుంది?§What lesson does Appu chesi pappukoodu teach?',['ఉన్నంతలో జీవించాలి~Live within your means','అప్పు చేయాలి~Take loans','పప్పు తినాలి~Eat dal','ఎక్కువ తినాలి~Eat more'],'అప్పు చేసి తినడం మంచిది కాదు.§Eating on loans is not good.'),
Q('అనుమానం దేనితో పోల్చారు?§What is doubt compared to?',['పెద్ద భూతం~A great ghost','పెద్ద పర్వతం~A great mountain','పెద్ద నది~A great river','పెద్ద చెట్టు~A great tree'],'పెనుభూతం అంటే పెద్ద భూతం.§Penubhootam means a great ghost.'),
Q('సామెత అంటే ఏమిటి?§What is a samet (proverb)?',['తక్కువ మాటల్లో నీతి చెప్పే పాత మాట~An old saying that gives a lesson in few words','ఒక పాట~A song','ఒక కథ~A story','ఒక లెక్క~A sum'],'సామెతలు పెద్దల అనుభవాల మాటలు.§Proverbs carry the experience of elders.')]});
A('telugu',[3, 4, 5, 6, 7, 8, 9, 10],{id:'tel_sam2',i:'🗣️',te:'సామెతలు: ఇల్లు, బంధాలు',en:'Proverbs: Home and relations',kw:'samethalu proverbs telugu family kaki pilla adagande ammaina dilliki raja kanche chenu కాకి పిల్ల అడగందే అమ్మైనా ఢిల్లీకి రాజైనా కంచే చేను సామెతలు',
n:['# సామెతలు§# Proverbs',
'ఇవి ఇంటి గురించి, మనుషుల మధ్య సంబంధాల గురించి చెప్పే సామెతలు.§These proverbs speak about home and relations between people.',
'> కాకి పిల్ల కాకికి ముద్దు - ఎవరి బిడ్డ వారికి ముద్దు. ఎంత చిన్నదైనా తమదైనది అందరికీ ప్రేమగా ఉంటుంది.§> A crow chick is dear to the crow - Everyone loves their own child. Whatever it looks like, one loves what is one own.',
'> ఢిల్లీకి రాజైనా తల్లికి కొడుకే - ఎంత గొప్ప పదవిలో ఉన్నా తల్లికి బిడ్డ బిడ్డే.§> Even king of Delhi is still a mother son - Whatever high post one holds, to the mother a child is a child.',
'> అడగందే అమ్మైనా అన్నం పెట్టదు - మనకు ఏదైనా కావాలంటే అడగాలి. అడగకపోతే ఎవరికీ తెలియదు.§> Even a mother will not serve food unasked - If we want something, we must ask. Others cannot know if we do not say.',
'> కంచే చేను మేసినట్లు - కాపాడాల్సిన వారే నష్టం చేయడం.§> As if the fence ate the field - The very one who should protect does the harm.'],
q:[Q('కాకి పిల్ల కాకికి ముద్దు అంటే?§What does Kaki pilla kakiki muddu mean?',['ఎవరి బిడ్డ వారికి ముద్దు~Everyone loves their own child','కాకులు పాడతాయి~Crows sing','పిల్లలు ఆడతారు~Children play','కాకి నల్లన~Crow is black'],'తమ బిడ్డ ఎప్పుడూ ముద్దు.§One own child is always dear.'),
Q('ఢిల్లీకి రాజైనా తల్లికి కొడుకే అనేది దేని గురించి?§What is Dilliki rajaina tallik koduke about?',['తల్లి ప్రేమ~A mother love','రాజు సైన్యం~The army of a king','ఢిల్లీ నగరం~The city of Delhi','పన్నులు~Taxes'],'తల్లికి బిడ్డ ఎప్పుడూ బిడ్డే.§To a mother the child is always a child.'),
Q('అడగందే అమ్మైనా అన్నం పెట్టదు ఏ పాఠం ఇస్తుంది?§What lesson does Adagande ammaina annam pettadu give?',['కావలసింది అడగాలి~Ask for what you need','అడగకూడదు~Never ask','ఎక్కువ తినాలి~Eat more','వంట నేర్చుకోవాలి~Learn cooking'],'అడగకపోతే తెలియదు.§If we do not ask, others do not know.'),
Q('కంచే చేను మేసినట్లు అంటే?§What does Kanche chenu mesinatlu mean?',['కాపాడేవారే నష్టం చేయడం~The protector causing the harm','కంచె కట్టడం~Building a fence','చేను పండడం~The field ripening','పశువులు మేయడం~Cattle grazing'],'కంచె పొలాన్ని కాపాడాలి.§A fence should protect the field.'),
Q('కంచె అంటే ఏమిటి?§What is a kancha (kanche)?',['పొలం చుట్టూ రక్షణ కంచె~A fence around a field','ఒక పాత్ర~A vessel','ఒక పండు~A fruit','ఒక పాట~A song'],'కంచె అంటే పొలం చుట్టూ ఉన్న అడ్డు.§A fence is the barrier around a field.')]});
A('telugu',[3, 4, 5, 6, 7, 8, 9, 10],{id:'tel_sam3',i:'🗣️',te:'సామెతలు: లోక జ్ఞానం',en:'Proverbs: Worldly wisdom',kw:'samethalu proverbs telugu odalu bandlu chakkanamma gangigovu perugutha hanumanthudi okka debbaku ఓడలు బళ్ళు చక్కనమ్మ గంగిగోవు పెరుగుట విరుగుట హనుమంతుడి ఒక దెబ్బకు సామెతలు',
n:['# సామెతలు§# Proverbs',
'ఇవి జీవితం, మనుషులు, కాలం గురించి చెప్పే సామెతలు.§These proverbs speak about life, people and time.',
'> ఓడలు బళ్ళు అవుతాయి బళ్ళు ఓడలవుతాయి - కాలం మారుతుంది. ధనవంతులు పేదవారు కావచ్చు, పేదవారు ధనవంతులు కావచ్చు.§> Boats become carts and carts become boats - Time changes. The rich can become poor and the poor can become rich.',
'> చక్కనమ్మ చిక్కినా అందమే - మంచి గుణం ఉన్నవారికి కష్టకాలంలో కూడా విలువ తగ్గదు.§> A beautiful woman is beautiful even when thin - What is truly good keeps its value even in hard times.',
'> గంగిగోవు పాలు గరిటడైన చాలు - మంచి వస్తువు కొంచెం ఉన్నా చాలు. చెడ్డది ఎక్కువైనా లాభం లేదు.§> Even a ladle of cow milk is enough - A little of something good is enough. A lot of something bad does not help.',
'> పెరుగుట విరుగుట కొరకే - అతిగా పెరిగినది చివరికి పడిపోతుంది. గర్వం మంచిది కాదు.§> Growing is for breaking - What grows too much finally falls. Pride is not good.',
'> హనుమంతుడి ముందా కుప్పిగంతులు - తెలిసిన వారి ముందు గొప్పలు చెప్పకూడదు.§> Monkey tricks before Hanuman - Do not boast before someone who knows better.',
'> ఒక దెబ్బకు రెండు పిట్టలు - ఒక పనితో రెండు లాభాలు సాధించడం.§> Two birds with one blow - Getting two gains from one effort.'],
q:[Q('ఓడలు బళ్ళు అవుతాయి అంటే?§What does Odalu ballu avutayi mean?',['కాలం మారుతుంది~Times change','పడవ బండి అవుతుంది~A boat really becomes a cart','నది ఎండిపోతుంది~The river dries up','బండి పాతది~The cart is old'],'ఉన్నవారు లేనివారు కావచ్చు.§The well-off may lose and the poor may gain.'),
Q('గంగిగోవు పాలు గరిటడైన చాలు అనే సామెత ఏ గుణాన్ని చెబుతుంది?§What does Gangigovu palu garitadaina chalu teach?',['మంచి కొంచెమైనా విలువైనది~Even a little good is valuable','ఎక్కువ తాగాలి~Drink more','ఆవును కొనాలి~Buy a cow','పాలు ఖరీదు~Milk is costly'],'మంచిది కొంచెం చాలు.§A little good is enough.'),
Q('పెరుగుట విరుగుట కొరకే అంటే?§What does Perugut virugut korake mean?',['అతిగా పెరిగినది పడుతుంది~What grows too much will fall','చెట్లు పెరగాలి~Trees should grow','పెద్దవారు కావాలి~One should grow up','పెరుగు తినాలి~Eat curd'],'గర్వం పతనానికి దారి.§Pride leads to a fall.'),
Q('హనుమంతుడి ముందా కుప్పిగంతులు ఎప్పుడు అంటారు?§When do we say Hanumanthudi munda kuppigantulu?',['తెలిసినవారి ముందు గొప్పలు చెప్పినప్పుడు~When boasting before someone who knows better','హనుమంతుని పూజలో~During a puja of Hanuman','ఆటల్లో~During games','కోతిని చూసినప్పుడు~On seeing a monkey'],'తెలిసినవారి దగ్గర గొప్పలు పోవు.§Boasting does not work before the knowing.'),
Q('ఒక దెబ్బకు రెండు పిట్టలు అంటే?§What does Oka debbaku rendu pittalu mean?',['ఒక పనితో రెండు లాభాలు~Two gains from one effort','రెండు పక్షులను పట్టాలి~Catch two birds','రెండు పనులు మానాలి~Drop two tasks','రెండు దెబ్బలు~Two blows'],'ఒక ప్రయత్నంతో రెండు ఫలితాలు.§Two results with one attempt.')]});

LD.reg('btel9',1)})();
