LD.reg('maths',{
1:[
{id:'num',i:'🔢',te:'సంఖ్యలు 1–20',en:'Numbers 1–20',n:['# సంఖ్యలు§Numbers','ఒకటి నుండి ఇరవై వరకు లెక్కించండి. ప్రతి సంఖ్యకు ముందు, తరువాత ఒక సంఖ్య ఉంటుంది.§Count from one to twenty. Every number has one just before it and one just after it.','> 9 తరువాత 10, 14 కంటే ముందు 13§After 9 comes 10, before 14 comes 13'],g:['cnt:9','after:19','before:20','between:19']},
{id:'addsub',i:'➕',te:'కూడిక – తీసివేత',en:'Add and subtract',n:['# కూడిక§Adding','కలపడాన్ని కూడిక (+) అంటారు.§Putting together is called addition (+).','> 4 + 3 = 7','# తీసివేత§Subtracting','తీసివేయడాన్ని తీసివేత (−) అంటారు.§Taking away is called subtraction (−).','> 9 − 2 = 7'],g:['add:9','sub:10','missing:9']},
{id:'shape',i:'🔷',te:'ఆకారాలు, సమయం',en:'Shapes and time',n:['త్రిభుజానికి 3 భుజాలు, చతురస్రానికి 4 భుజాలు.§A triangle has 3 sides, a square has 4 sides.','చిన్న ముల్లు గంటను, పెద్ద ముల్లు నిమిషాలను చూపిస్తుంది.§The short hand shows the hour, the long hand shows the minutes.'],g:['shapes','clock'],q:['బంతి ఏ ఆకారంలో ఉంటుంది?§What shape is a ball?|గోళం~Sphere|చతురస్రం~Square|త్రిభుజం~Triangle|దీర్ఘచతురస్రం~Rectangle|బంతి గుండ్రంగా ఉంటుంది, దాన్ని గోళం అంటారు§A ball is round; the 3-D shape is a sphere','వారంలో ఎన్ని రోజులు?§How many days are in a week?|7|5|6|10|ఆదివారం నుండి శనివారం వరకు 7 రోజులు§Sunday to Saturday makes 7 days']}
],
2:[
{id:'num2',i:'🔢',te:'సంఖ్యలు 99 వరకు',en:'Numbers up to 99',n:['# స్థాన విలువ§Place value','రెండంకెల సంఖ్యలో పదులు, ఒకట్లు ఉంటాయి.§A two-digit number has tens and ones.','> 47 = 4 పదులు + 7 ఒకట్లు§47 = 4 tens + 7 ones','సరి సంఖ్యలు 2,4,6,8,0 తో ముగుస్తాయి. బేసి సంఖ్యలు 1,3,5,7,9 తో ముగుస్తాయి.§Even numbers end in 2,4,6,8,0. Odd numbers end in 1,3,5,7,9.'],g:['tens','between:90','big','small','even:40','odd:40']},
{id:'addsub2',i:'➕',te:'కూడిక – తీసివేత',en:'Add and subtract',n:['# కూడిక§Adding','ఒకట్లు కలిపి, తరువాత పదులు కలపండి. ఒకట్లు 10 దాటితే 1 పది తీసుకోండి.§Add the ones first, then the tens. If the ones go past 10, carry 1 ten.','> 38 + 25: 8+5=13 (3 రాయి, 1 పది పైకి), 3+2+1=6 → 63§38 + 25: 8+5=13 (write 3, carry 1), 3+2+1=6 → 63'],g:['add:40','sub:50','missing:30']},
{id:'tab2',i:'✖️',te:'ఎక్కాలు 2, 5, 10',en:'Tables of 2, 5 and 10',n:['ఎక్కం అంటే ఒకే సంఖ్యను మళ్ళీ మళ్ళీ కలపడం.§A table is adding the same number again and again.','> 5 × 3 = 5 + 5 + 5 = 15','2 ఎక్కంలో అన్నీ సరి సంఖ్యలే. 5 ఎక్కం 0 లేదా 5 తో ముగుస్తుంది.§All answers in the 2 table are even. The 5 table ends in 0 or 5.'],g:['table:2,2','table:5,5','table:10,10','skip']},
{id:'money2',i:'💰',te:'డబ్బు',en:'Money',n:['100 పైసలు = 1 రూపాయి.§100 paise = 1 rupee.','చిల్లర = ఇచ్చిన డబ్బు − వస్తువు ధర.§Change = money given − price of the item.','> ₹50 ఇచ్చి ₹35 వస్తువు కొంటే చిల్లర ₹15§Pay ₹50 for a ₹35 item and get ₹15 change'],g:['money']}
],
3:[
{id:'num3',i:'🔢',te:'3 అంకెల సంఖ్యలు',en:'3-digit numbers',n:['# స్థానాలు§Places','3 అంకెల సంఖ్యలో వందలు, పదులు, ఒకట్లు ఉంటాయి.§A 3-digit number has hundreds, tens and ones.','> 538 = 500 + 30 + 8','సంఖ్యను దగ్గరి 10 కి మార్చాలంటే ఒకట్ల అంకె 5 లేదా ఎక్కువైతే పైకి, తక్కువైతే కిందికి.§To round to the nearest 10: if the ones digit is 5 or more go up, otherwise go down.'],g:['hund','expand','round10','small']},
{id:'addsub3',i:'➕',te:'కూడిక – తీసివేత (3 అంకెలు)',en:'Add and subtract (3-digit)',n:['ఒకట్లు, పదులు, వందలు – కుడి నుండి ఎడమకు చేయండి.§Work right to left: ones, tens, hundreds.','> 456 + 278 = 734','తీసివేతలో చిన్న అంకె నుండి సాధ్యం కాకపోతే పక్క స్థానం నుండి 1 అప్పు తీసుకోండి.§In subtraction, if the top digit is smaller, borrow 1 from the next place.'],g:['add:300','sub:300','missing:90']},
{id:'muldiv3',i:'✖️',te:'గుణకారం – భాగహారం',en:'Multiply and divide',n:['గుణకారం = మళ్ళీ మళ్ళీ కూడిక. భాగహారం = సమానంగా పంచడం.§Multiplication is repeated addition. Division is sharing equally.','> 6 × 4 = 24, కాబట్టి 24 ÷ 4 = 6§6 × 4 = 24, so 24 ÷ 4 = 6'],g:['table:2,10','mul:10,10','div:10,10']},
{id:'meas3',i:'📏',te:'కొలతలు, సమయం',en:'Measurement and time',n:['1 మీటర్ = 100 సెం.మీ, 1 కి.మీ = 1000 మీటర్లు.§1 metre = 100 cm, 1 km = 1000 m.','1 కిలో = 1000 గ్రాములు, 1 లీటరు = 1000 మి.లీ.§1 kg = 1000 g, 1 litre = 1000 ml.','1 గంట = 60 నిమిషాలు.§1 hour = 60 minutes.'],g:['conv','time']}
],
4:[
{id:'big4',i:'🔢',te:'పెద్ద సంఖ్యలు',en:'Bigger numbers',n:['4 అంకెల సంఖ్యలో వేలు, వందలు, పదులు, ఒకట్లు ఉంటాయి.§A 4-digit number has thousands, hundreds, tens and ones.','> 5,386 = 5000 + 300 + 80 + 6','దగ్గరి 100 కి మార్చాలంటే పదుల అంకె చూడాలి: 5 లేదా ఎక్కువైతే పైకి.§To round to the nearest 100, look at the tens digit: 5 or more goes up.'],g:['thou','round100','add:900','sub:900']},
{id:'muldiv4',i:'✖️',te:'గుణకారం – భాగహారం',en:'Multiply and divide',n:['12 వరకు ఎక్కాలు వచ్చి ఉంటే గుణకార, భాగహారాలు సులభం.§Knowing tables up to 12 makes multiplication and division easy.','> 7 × 8 = 56, 56 ÷ 8 = 7','భాగహారంలో భాజ్యం = భాజకం × భాగఫలం + శేషం.§Dividend = divisor × quotient + remainder.'],g:['mul:12,12','div:12,12','table:6,12']},
{id:'frac4',i:'🍕',te:'భిన్నాలు',en:'Fractions',n:['భిన్నంలో పైన లవం, కింద హారం ఉంటాయి. హారం = మొత్తం సమాన భాగాలు.§In a fraction the top is the numerator and the bottom is the denominator. The denominator is the total number of equal parts.','హారం ఒకటే అయితే లవాలను కలపండి/తీసివేయండి.§With the same denominator, add or subtract the numerators.','> 2/7 + 3/7 = 5/7'],g:['fadd','fsub','frac']},
{id:'geo4',i:'📐',te:'చుట్టుకొలత – వైశాల్యం',en:'Perimeter and area',n:['చుట్టుకొలత = అన్ని భుజాల మొత్తం.§Perimeter = sum of all the sides.','దీర్ఘచతురస్రం: చుట్టుకొలత = 2 × (పొడవు + వెడల్పు), వైశాల్యం = పొడవు × వెడల్పు.§Rectangle: perimeter = 2 × (length + breadth), area = length × breadth.','చతురస్ర వైశాల్యం = భుజం × భుజం.§Area of a square = side × side.'],g:['rectP','rectA','sqA']}
],
5:[
{id:'hcf5',i:'🧩',te:'కారణాంకాలు, గుణజాలు',en:'Factors and multiples',n:['కారణాంకాలు = ఒక సంఖ్యను శేషం లేకుండా భాగించేవి.§Factors divide a number exactly.','గ.సా.భా (HCF) = ఉమ్మడి కారణాంకాలలో పెద్దది. క.సా.గు (LCM) = ఉమ్మడి గుణిజాలలో చిన్నది.§HCF is the greatest common factor. LCM is the least common multiple.','> 12, 18 ల HCF = 6, LCM = 36'],g:['hcf','lcm','sq:15']},
{id:'fracdec5',i:'🍰',te:'భిన్నాలు, దశాంశాలు',en:'Fractions and decimals',n:['హారాలు వేరైతే ముందు క.సా.గు తో సమానం చేయండి.§If denominators differ, make them equal using the LCM first.','> 1/2 + 1/3 = 3/6 + 2/6 = 5/6','దశాంశాలు కలిపేటప్పుడు దశాంశ బిందువులను ఒకే వరుసలో ఉంచండి.§When adding decimals, line up the decimal points.'],g:['fadd2','dec_add','dec_sub','frac']},
{id:'pct5',i:'💯',te:'శాతాలు',en:'Percentages',n:['శాతం అంటే ప్రతి 100 కు.§Percent means out of 100.','> 50% = 1/2, 25% = 1/4, 10% = 1/10','> 20% of 150 = 20/100 × 150 = 30'],g:['pct']},
{id:'bodmas5',i:'🧮',te:'BODMAS, వైశాల్యం',en:'BODMAS and area',n:['లెక్కించే క్రమం: బ్రాకెట్లు, ఘాతాలు, భాగహారం, గుణకారం, కూడిక, తీసివేత (BODMAS).§Order of operations: Brackets, Orders, Division, Multiplication, Addition, Subtraction.','> 3 + 4 × 2 = 3 + 8 = 11 (ముందు గుణకారం)§3 + 4 × 2 = 3 + 8 = 11 (multiply first)','త్రిభుజ వైశాల్యం = ½ × భూమి × ఎత్తు.§Area of a triangle = ½ × base × height.'],g:['bodmas','bodmas2','triA','rectA']}
],
6:[
{id:'int6',i:'➖',te:'పూర్ణాంకాలు',en:'Integers',n:['పూర్ణాంకాలు = …, −3, −2, −1, 0, 1, 2, 3, …§Integers are …, −3, −2, −1, 0, 1, 2, 3, …','సమాన గుర్తులు కలిపితే మొత్తం కలిపి అదే గుర్తు; వేరు గుర్తులైతే తీసివేసి పెద్ద సంఖ్య గుర్తు.§Same signs: add and keep the sign. Different signs: subtract and keep the sign of the bigger number.','> (−5) + 3 = −2'],g:['intadd']},
{id:'ratio6',i:'⚖️',te:'నిష్పత్తి – అనుపాతం',en:'Ratio and proportion',n:['రెండు రాశుల పోలికను నిష్పత్తి అంటారు: a : b.§Comparing two quantities is a ratio: a : b.','ఇరువైపులా ఒకే సంఖ్యతో భాగిస్తే సంక్షిప్త రూపం వస్తుంది.§Divide both sides by the same number to simplify.','> 12 : 18 = 2 : 3'],g:['ratio','pct']},
{id:'alg6',i:'🔤',te:'బీజగణిత పరిచయం',en:'Intro to algebra',n:['అక్షరం (x) తెలియని సంఖ్యను సూచిస్తుంది.§A letter (x) stands for an unknown number.','సమీకరణంలో రెండు వైపులా ఒకే పని చేస్తే సమీకరణం చెడదు.§Doing the same thing to both sides keeps an equation balanced.','> 2x + 3 = 11 → 2x = 8 → x = 4'],g:['eq1']},
{id:'geo6',i:'📐',te:'కోణాలు, వైశాల్యం',en:'Angles and area',n:['త్రిభుజంలో మూడు కోణాల మొత్తం 180°.§The three angles of a triangle add up to 180°.','పూరక కోణాల మొత్తం 90°, సంపూరక కోణాల మొత్తం 180°.§Complementary angles add to 90°, supplementary angles add to 180°.','శీర్షాభిముఖ కోణాలు సమానం.§Vertically opposite angles are equal.'],g:['angle3','comp','vert','triA']}
],
7:[
{id:'int7',i:'✖️',te:'పూర్ణాంకాల గుణకారం',en:'Integer multiplication',n:['సమాన గుర్తుల లబ్ధం ధనాత్మకం, వేరు గుర్తుల లబ్ధం ఋణాత్మకం.§Same signs give a positive product; different signs give a negative product.','> (−4) × (−3) = 12,  (−4) × 3 = −12'],g:['intadd','intmul']},
{id:'eq7',i:'⚖️',te:'సరళ సమీకరణాలు',en:'Simple equations',n:['తెలియని సంఖ్యను ఒక వైపు, తెలిసిన వాటిని మరో వైపు ఉంచండి. పక్కకు మారిస్తే గుర్తు మారుతుంది.§Keep the unknown on one side and numbers on the other. A term changes sign when it crosses over.','> 3x − 5 = 16 → 3x = 21 → x = 7'],g:['eq1','eq2']},
{id:'pl7',i:'🛒',te:'శాతాలు, లాభ–నష్టాలు',en:'Percentages, profit and loss',n:['లాభం = అమ్మిన ధర − కొన్న ధర (అమ్మిన ధర ఎక్కువైతే).§Profit = selling price − cost price (when SP is more).','అమ్మిన ధర = కొన్న ధర + లాభం.§Selling price = cost price + profit.','తగ్గింపు తరువాత ధర = ముద్రిత ధర − తగ్గింపు.§Price after discount = marked price − discount.'],g:['pl','disc','pct']},
{id:'exp7',i:'⚡',te:'ఘాతాలు',en:'Exponents',n:['aᵐ × aⁿ = aᵐ⁺ⁿ (ఆధారం ఒకటే అయితే ఘాతాలు కలపండి).§aᵐ × aⁿ = aᵐ⁺ⁿ (same base: add the powers).','a⁰ = 1 (a ≠ 0).','> 2³ = 8, 10⁴ = 10,000'],g:['exp','exp0','pow','sq:20']},
{id:'si7',i:'⭕',te:'సాధారణ వడ్డీ, వృత్తం',en:'Simple interest and circles',n:['సాధారణ వడ్డీ = (అసలు × రేటు × కాలం) / 100.§Simple interest = (Principal × Rate × Time) / 100.','వృత్త చుట్టుకొలత = 2πr, వైశాల్యం = πr² (π = 22/7).§Circumference = 2πr, area = πr² (π = 22/7).'],g:['si','circA','circC']}
],
8:[
{id:'sq8',i:'√',te:'వర్గాలు, ఘనాలు, మూలాలు',en:'Squares, cubes and roots',n:['వర్గం = సంఖ్య × అదే సంఖ్య. ఘనం = సంఖ్య × సంఖ్య × సంఖ్య.§Square = number × itself. Cube = number × number × number.','> √144 = 12, ∛125 = 5','పరిపూర్ణ వర్గాలు ఒకట్ల స్థానంలో 0,1,4,5,6,9 తో ముగుస్తాయి.§Perfect squares end in 0, 1, 4, 5, 6 or 9.'],g:['sq:25','cube:10','sqrt:30','cbrt']},
{id:'alg8',i:'🔤',te:'బీజీయ సర్వసమీకరణాలు',en:'Algebraic identities',n:['(a+b)² = a² + 2ab + b²','(a−b)² = a² − 2ab + b²','a² − b² = (a+b)(a−b)','> 101² = (100+1)² = 10000 + 200 + 1 = 10201'],g:['ident','sqdiff','eq2']},
{id:'ci8',i:'🏦',te:'చక్రవడ్డీ',en:'Compound interest',n:['చక్రవడ్డీలో వడ్డీపై కూడా వడ్డీ వస్తుంది.§In compound interest, interest is also earned on interest.','మొత్తం A = P(1 + R/100)ⁿ.§Amount A = P(1 + R/100)ⁿ.','చక్రవడ్డీ = A − P.§Compound interest = A − P.'],g:['ci','si']},
{id:'men8',i:'🧊',te:'ఘనాకృతుల కొలతలు',en:'Solid shapes',n:['దీర్ఘఘనం ఘనపరిమాణం = l × b × h.§Volume of a cuboid = l × b × h.','స్థూపం ఘనపరిమాణం = πr²h.§Volume of a cylinder = πr²h.','ఘనం (క్యూబ్) వైశాల్యం = 6a².§Surface area of a cube = 6a².'],g:['cuboid','cuboidS','cyl']}
],
9:[
{id:'poly9',i:'🧮',te:'బహుపదులు',en:'Polynomials',n:['బహుపది p(x) లో x = a వేస్తే వచ్చే విలువ p(a).§Putting x = a in a polynomial p(x) gives p(a).','p(a) = 0 అయితే a ఆ బహుపది శూన్యం (zero).§If p(a) = 0 then a is a zero of the polynomial.','> x − 3 శూన్యం x = 3§The zero of x − 3 is x = 3'],g:['polyv','zero','sqdiff','ident']},
{id:'coord9',i:'📍',te:'నిరూపక జ్యామితి',en:'Coordinate geometry',n:['బిందువు (x, y): x = అడ్డు (x-అక్షం), y = నిలువు (y-అక్షం).§Point (x, y): x is horizontal, y is vertical.','రెండు బిందువుల దూరం = √[(x₂−x₁)² + (y₂−y₁)²].§Distance = √[(x₂−x₁)² + (y₂−y₁)²].','మధ్య బిందువు = ((x₁+x₂)/2 , (y₁+y₂)/2).§Midpoint = ((x₁+x₂)/2 , (y₁+y₂)/2).'],g:['dist','midpt']},
{id:'geo9',i:'📐',te:'త్రిభుజాలు, పైథాగరస్',en:'Triangles and Pythagoras',n:['లంబకోణ త్రిభుజంలో కర్ణ² = భుజం² + భుజం².§In a right triangle, hypotenuse² = side² + side².','> 3, 4, 5 : 3² + 4² = 9 + 16 = 25 = 5²','n భుజాల బహుభుజి అంతర కోణాల మొత్తం (n−2) × 180°.§Interior angle sum of an n-sided polygon = (n−2) × 180°.'],g:['pyth','angle3','poly']},
{id:'stat9',i:'📊',te:'గణాంకాలు',en:'Statistics',n:['సగటు = విలువల మొత్తం ÷ విలువల సంఖ్య.§Mean = sum of values ÷ number of values.','మధ్యగతం = క్రమంలో పెట్టిన విలువల మధ్య విలువ.§Median = the middle value when values are arranged in order.','బాహుళకం = ఎక్కువసార్లు వచ్చే విలువ.§Mode = the value that appears most often.'],g:['mean','median','mode']},
{id:'real9',i:'🔁',te:'వాస్తవ సంఖ్యలు, ఘనాకృతులు',en:'Real numbers and solids',n:['యూక్లిడ్ భాగహార శేష సిద్ధాంతం: a = bq + r, 0 ≤ r < b.§Euclid division lemma: a = bq + r, 0 ≤ r < b.','దీర్ఘఘనం సంపూర్ణ తల వైశాల్యం = 2(lb + bh + hl).§Total surface area of a cuboid = 2(lb + bh + hl).','గోళ ఘనపరిమాణం = 4/3 πr³.§Volume of a sphere = 4/3 πr³.'],g:['euclid','cuboidS','sphere']}
],
10:[
{id:'real10',i:'🔢',te:'వాస్తవ సంఖ్యలు',en:'Real numbers',n:['యూక్లిడ్ భాగహార శేష సిద్ధాంతం: a = bq + r.§Euclid division lemma: a = bq + r.','HCF × LCM = రెండు సంఖ్యల లబ్ధం.§HCF × LCM = product of the two numbers.','√2, √3 వంటివి అకరణీయ సంఖ్యలు (అకరణీయం కానివి).§√2 and √3 are irrational numbers.'],g:['euclid','hcf','lcm']},
{id:'set10',i:'⭕',te:'సమితులు',en:'Sets',n:['సమితి = చక్కగా నిర్వచించిన వస్తువుల సముదాయం.§A set is a well-defined collection of objects.','A ∪ B = రెండింటిలో ఏదైనా ఒకదానిలో ఉన్నవి; A ∩ B = రెండింటిలో ఉన్నవి.§A ∪ B = in either set; A ∩ B = in both sets.','n(A∪B) = n(A) + n(B) − n(A∩B).'],g:['sets']},
{id:'poly10',i:'🧮',te:'బహుపదులు, సమీకరణాల జత',en:'Polynomials and linear pairs',n:['ax² + bx + c శూన్యాల మొత్తం = −b/a, లబ్ధం = c/a.§For ax² + bx + c: sum of zeros = −b/a, product = c/a.','రెండు సమీకరణాలను కూడి/తీసివేసి ఒక చరరాశిని తొలగించవచ్చు.§Add or subtract two equations to eliminate one variable.'],g:['poly2','zero','pair']},
{id:'quad10',i:'📈',te:'వర్గ సమీకరణాలు',en:'Quadratic equations',n:['ax² + bx + c = 0 లో విచక్షణి D = b² − 4ac.§For ax² + bx + c = 0, discriminant D = b² − 4ac.','D > 0: రెండు వేరు మూలాలు; D = 0: సమాన మూలాలు; D < 0: వాస్తవ మూలాలు లేవు.§D > 0: two distinct roots; D = 0: equal roots; D < 0: no real roots.','మూలాలు x = [−b ± √D] / 2a.§Roots x = [−b ± √D] / 2a.'],g:['quad','disc']},
{id:'ap10',i:'🪜',te:'అంక శ్రేఢులు',en:'Arithmetic progressions',n:['AP: ప్రతి పదానికి సమాన భేదం d కలుస్తుంది.§AP: each term adds the same common difference d.','nవ పదం aₙ = a + (n − 1)d.','మొదటి n పదాల మొత్తం Sₙ = n/2 [2a + (n−1)d].'],g:['ap','apsum']},
{id:'cg10',i:'📍',te:'నిరూపక జ్యామితి',en:'Coordinate geometry',n:['దూర సూత్రం: d = √[(x₂−x₁)² + (y₂−y₁)²].§Distance formula: d = √[(x₂−x₁)² + (y₂−y₁)²].','మధ్య బిందువు = ((x₁+x₂)/2 , (y₁+y₂)/2).§Midpoint = ((x₁+x₂)/2 , (y₁+y₂)/2).'],g:['dist','midpt']},
{id:'sim10',i:'🔺',te:'సరూప త్రిభుజాలు, స్పర్శరేఖలు',en:'Similar triangles and tangents',n:['సరూప త్రిభుజాల సంబంధ భుజాల నిష్పత్తి సమానం.§In similar triangles, matching sides are in the same ratio.','వృత్తానికి బాహ్య బిందువు నుండి గీసిన రెండు స్పర్శరేఖల పొడవులు సమానం.§Two tangents drawn from an outside point to a circle are equal in length.','స్పర్శ బిందువు వద్ద స్పర్శరేఖ వ్యాసార్థానికి లంబం.§A tangent is perpendicular to the radius at the point of contact.'],g:['similar','tang','pyth']},
{id:'trig10',i:'📐',te:'త్రికోణమితి',en:'Trigonometry',n:['లంబకోణ త్రిభుజంలో: sin θ = ఎదుటి/కర్ణం, cos θ = ప్రక్క/కర్ణం, tan θ = ఎదుటి/ప్రక్క.§In a right triangle: sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = opposite/adjacent.','# ముఖ్య విలువలు§Key values','> sin: 0°→0, 30°→1/2, 45°→1/√2, 60°→√3/2, 90°→1','> cos: 0°→1, 30°→√3/2, 45°→1/√2, 60°→1/2, 90°→0','> tan 30° = 1/√3, tan 45° = 1, tan 60° = √3','# సర్వసమీకరణాలు§Identities','sin²θ + cos²θ = 1;  1 + tan²θ = sec²θ;  1 + cot²θ = cosec²θ','sin θ = cos(90° − θ)'],g:['trig5','trig6','trig3','trig4','trigid'],q:['sin 30° + cos 60° = ?|1|1/2|0|2|1/2 + 1/2 = 1§1/2 + 1/2 = 1','sin²45° + cos²45° = ?|1|1/2|2|0|ఏ కోణానికైనా sin²θ + cos²θ = 1§For any angle, sin²θ + cos²θ = 1']},
{id:'tapp10',i:'🏗️',te:'త్రికోణమితి అనువర్తనాలు',en:'Applications of trigonometry',n:['ఉన్నతి కోణం = కంటి నుండి పైన ఉన్న వస్తువుకు గీసిన రేఖ, సమాంతర రేఖతో చేసే కోణం.§Angle of elevation: the angle between the horizontal and the line of sight to something above.','అవనతి కోణం = కంటి నుండి కింద ఉన్న వస్తువును చూసే కోణం.§Angle of depression: the angle to something below.','ఎత్తు = దూరం × tan θ.§Height = distance × tan θ.','> 45° లో ఎత్తు = దూరం, 60° లో ఎత్తు = దూరం × √3§At 45° height = distance; at 60° height = distance × √3'],g:['trig7','trig6','trig5']},
{id:'men10',i:'🧊',te:'క్షేత్రమితి',en:'Mensuration',n:['శంకువు ఘనపరిమాణం = ⅓ πr²h.§Volume of a cone = ⅓ πr²h.','గోళం ఘనపరిమాణం = 4/3 πr³, తల వైశాల్యం = 4πr².§Sphere: volume = 4/3 πr³, surface area = 4πr².','స్థూపం ఘనపరిమాణం = πr²h.§Volume of a cylinder = πr²h.'],g:['cone','sphere','cyl']},
{id:'sp10',i:'🎲',te:'గణాంకాలు, సంభావ్యత',en:'Statistics and probability',n:['సంభావ్యత = అనుకూల ఫలితాల సంఖ్య ÷ మొత్తం ఫలితాల సంఖ్య.§Probability = favourable outcomes ÷ total outcomes.','సంభావ్యత ఎప్పుడూ 0 నుండి 1 మధ్యలో ఉంటుంది.§Probability always lies between 0 and 1.','సగటు, మధ్యగతం, బాహుళకం – గణాంకాల కేంద్ర స్థానాలు.§Mean, median and mode are measures of central tendency.'],g:['prob','mean','median','mode']}
]
});
