(function(){'use strict';
// Martial Arts: Real Training Videos + technique cards + 21-day challenge. Videos are CC-licensed real footage from Wikimedia Commons, played via the official Commons embed player (not re-hosted).
const I=()=>window.MartialApp._i,L=(a,b)=>I().L(a,b),E=x=>I().E(x);
const CM='https://commons.wikimedia.org/wiki/File:',TH='https://upload.wikimedia.org/wikipedia/commons/thumb/';
const V={
kihon:{file:'Kihon_for_the_6th_kyu_test.ogv',th:'d/d6/Kihon_for_the_6th_kyu_test.ogv/500px--Kihon_for_the_6th_kyu_test.ogv.jpg',dur:'3:51',by:'ColoradoKarateClub',lic:'CC BY 2.0',licu:'https://creativecommons.org/licenses/by/2.0',lv:L('ప్రారంభం','Beginner')},
shodan:{file:'Karate,_Hean_Shodan.webm',th:'e/ec/Karate%2C_Hean_Shodan.webm/500px--Karate%2C_Hean_Shodan.webm.jpg',dur:'0:28',by:'Sdcsabac',lic:'CC BY-SA 4.0',licu:'https://creativecommons.org/licenses/by-sa/4.0',lv:L('ప్రారంభం','Beginner')},
godan:{file:'Heian_Godan.ogv',th:'9/98/Heian_Godan.ogv/500px--Heian_Godan.ogv.jpg',dur:'3:59',by:'ColoradoKarateClub',lic:'CC BY 2.0',licu:'https://creativecommons.org/licenses/by/2.0',lv:L('అడ్వాన్స్‌డ్ (చూడటానికి మాత్రమే)','Advanced (watch only)')}};
const T=(te,en)=>({te,en});
// k = pose key for the body-position figure; les = lesson index to practise; v = video id or null (honest gap)
const TECH=[
{id:'stance',ic:'🦵',n:T('ప్రాథమిక భంగిమ','Basic stance'),v:'kihon',k:'horse',les:3,e:T('కాళ్ళు వెడల్పుగా, మోకాళ్ళు కాలివేళ్ళ వైపు, వెన్ను నిటారుగా. వీడియోలో "Zenkutsu Dachi" మరియు "Kiba Dachi" భంగిమలు చూడండి.','Feet wide, knees toward the toes, back straight. In the video watch the "Zenkutsu Dachi" and "Kiba Dachi" stances.'),kp:[T('వెన్ను నిటారుగా','Back straight'),T('బరువు రెండు కాళ్ళపై','Weight on both legs')],ck:[T('కాళ్ళు భుజాల కంటే వెడల్పు','Feet wider than shoulders'),T('మోకాళ్ళు కాలివేళ్ళ మీదుగా','Knees over toes'),T('శ్వాస మెల్లగా','Breathe slowly')],q:[T('మోకాళ్ళు ఎటు చూడాలి?','Where should the knees point?'),[T('కాలివేళ్ళ వైపు','Toward the toes'),T('లోపలికి','Inward'),T('వెనక్కి','Backward')]]},
{id:'guard',ic:'🛡️',n:T('గార్డ్ (రక్షణ స్థితి)','Guard position'),v:null,k:'ready',les:2,e:T('చేతులను శరీరం ముందు ఉంచి సిద్ధంగా నిలబడటం. దీనికి తగిన ఉచిత నిజమైన వీడియో ఇంకా దొరకలేదు.','Standing ready with hands in front of the body. No suitable free real video found yet.'),kp:[T('చేతులు ముందు','Hands in front'),T('భుజాలు వదులు','Loose shoulders')],ck:[T('సిద్ధ స్థితిలో నిలబడండి','Stand in ready stance'),T('భుజాలు వదులుగా','Relax shoulders')]},
{id:'foot',ic:'👣',n:T('ఫుట్‌వర్క్','Footwork'),v:null,k:'bow',les:4,e:T('అడుగులు మెల్లగా, సమతుల్యంగా వేయడం. నిజమైన వీడియో ఇంకా లేదు.','Stepping slowly and in balance. No suitable real video yet.'),kp:[T('చిన్న అడుగులు','Small steps'),T('తల నిటారుగా','Head up')],ck:[T('ముందుకు ఒక అడుగు, వెనక్కి ఒక అడుగు','One step forward, one back'),T('సమతుల్యం కోల్పోకుండా','Stay balanced')]},
{id:'punch',ic:'👊',n:T('పంచ్ (గాలిలో, నియంత్రణతో)','Punching (in the air, controlled)'),v:null,k:'ready',les:2,e:T('"Oi Zuki" మరియు "Gyaku Zuki" వీడియోలో చూడండి. ఎవరికీ తగలకుండా గాలిలో మాత్రమే. సాధన బోధకుని పర్యవేక్షణలో.','Watch "Oi Zuki" and "Gyaku Zuki" in the video. Practised in the air only, never at a person, with an instructor.'),kp:[T('నడుము తిప్పడం','Turn the hip'),T('గాలిలో మాత్రమే','Air only')],ck:[T('బోధకుడు ఉన్నారు','An instructor is present'),T('ఎవరూ దగ్గరలో లేరు','Nobody within arm reach'),T('మెల్లగా మొదలుపెట్టాను','Started slowly')],q:[T('పంచ్ ఎక్కడ సాధన చేయాలి?','Where do we practise a punch?'),[T('గాలిలో, బోధకునితో','In the air, with an instructor'),T('స్నేహితునిపై','On a friend'),T('గోడపై','On a wall')]]},
{id:'kick',ic:'🦶',n:T('కిక్ (గాలిలో, నియంత్రణతో)','Kicking (in the air, controlled)'),v:null,k:'stork',les:6,e:T('"Mae Geri" (ముందు కిక్) వీడియోలో చూడండి. తక్కువ ఎత్తులో, గాలిలో, బోధకునితో మాత్రమే.','Watch "Mae Geri" (front kick) in the video. Low, in the air, only with an instructor.'),kp:[T('ఒక కాలిపై సమతుల్యం','Balance on one leg'),T('తక్కువ ఎత్తు','Keep it low')],ck:[T('గోడ లేదా కుర్చీ పట్టుకోండి','Hold a wall or chair'),T('బోధకుడు ఉన్నారు','An instructor is present'),T('ఎవరిపైనా కాదు','Never at a person')],q:[T('కిక్ ఎంత ఎత్తులో?','How high is a beginner kick?'),[T('తక్కువగా','Low'),T('తల ఎత్తు','Head height'),T('ఎంతైనా','As high as possible')]]},
{id:'block',ic:'✋',n:T('బ్లాకింగ్ (రక్షణ కదలికలు)','Blocking'),v:null,k:'ready',les:2,e:T('"Age Uke" (పైకి బ్లాక్) మరియు "Shuto Uke" వీడియోలో చూడండి. ఇవి రక్షణ కదలికలు.','Watch "Age Uke" (rising block) and "Shuto Uke" in the video. These are defensive moves.'),kp:[T('రక్షణ కోసం మాత్రమే','Defence only'),T('చేతులు కదిలించడం మెల్లగా','Move arms slowly')],ck:[T('గాలిలో సాధన','Practise in the air'),T('మెల్లగా','Slowly'),T('బోధకునితో','With an instructor')],q:[T('బ్లాకింగ్ దేనికి?','What is blocking for?'),[T('రక్షణకు','Defence'),T('కొట్టడానికి','Hitting'),T('భయపెట్టడానికి','Scaring')]]},
{id:'dist',ic:'↔️',n:T('దూరం నిర్వహణ','Distance management'),v:null,k:'ready',les:2,e:T('ఎప్పుడూ సురక్షిత దూరం ఉంచడం. ఇది భావన మాత్రమే; నిజమైన వీడియో లేదు.','Always keep a safe distance. A concept only; no real video.'),kp:[T('చేతి పొడవు దూరం','An arm\'s length apart')],ck:[T('చుట్టూ చేతి పొడవు స్థలం','An arm\'s length of space around')]},
{id:'bal',ic:'⚖️',n:T('సమతుల్యం మరియు కదలిక','Balance and movement'),v:'shodan',k:'stork',les:6,e:T('Heian Shodan అనే చిన్న ఫారమ్ (28 సెకన్లు). నెమ్మదిగా, క్రమంగా కదలికలు. పెద్దవాటిని చూడటానికి Heian Godan కూడా ఉంది (అడ్వాన్స్‌డ్, చూడటానికి మాత్రమే).','A short form, Heian Shodan (28 seconds): slow, ordered movements. Heian Godan (advanced, watch only) is also available.'),v2:'godan',kp:[T('నెమ్మదిగా, క్రమంగా','Slow and in order'),T('కళ్ళు ముందుకు','Eyes forward')],ck:[T('ఒక కాలిపై 5 లెక్కలు','Balance on one leg for 5 counts'),T('స్థలం ఖాళీగా','Clear space')],q:[T('ఫారమ్ ఎలా చేయాలి?','How do we do a form?'),[T('నెమ్మదిగా, క్రమంగా','Slowly, in order'),T('వేగంగా దూకుతూ','Fast and jumping'),T('కళ్ళు మూసుకుని','Eyes closed')]]},
{id:'fall',ic:'🤸',n:T('సురక్షిత పడటం','Safe falling'),v:null,k:'ready',les:0,e:T('పడే పద్ధతులు మ్యాట్ మరియు అర్హత గల బోధకునితో మాత్రమే నేర్వాలి. ఇంట్లో ప్రయత్నించకండి. వీడియో చేర్చలేదు.','Falling skills are learnt only on a mat with a qualified instructor. Do not try at home. No video included.'),kp:[T('బోధకునితో మాత్రమే','Instructor only')],ck:[T('ఇది ఇంట్లో చేయకూడదని అర్థమైంది','I understand: not at home')]},
{id:'aware',ic:'👀',n:T('స్వీయ రక్షణ అవగాహన','Self-defence awareness'),v:null,k:'ready',les:0,e:T('క్రమం: 1 అవగాహన 2 నివారణ 3 శాంతింపజేయడం 4 తప్పించుకోవడం 5 సహాయం కోరడం. పోరాటానికి ఎప్పుడూ ప్రోత్సహించము.','Order: 1 Awareness 2 Avoidance 3 De-escalation 4 Escape 5 Seek help. We never encourage fighting.'),kp:[T('ఇబ్బంది అనిపిస్తే వెళ్ళిపోండి','Walk away from trouble'),T('పెద్దవారికి చెప్పండి','Tell a trusted adult')],ck:[T('అవగాహన','Awareness'),T('నివారణ','Avoidance'),T('శాంతంగా మాట్లాడటం','De-escalation'),T('తప్పించుకోవడం','Escape'),T('సహాయం కోరడం','Seek help')],q:[T('ఇబ్బంది వస్తే మొదట ఏం చేయాలి?','If there is trouble, what first?'),[T('వెళ్ళిపోయి పెద్దవారికి చెప్పాలి','Walk away and tell an adult'),T('పోరాడాలి','Fight'),T('అరిచి కొట్టాలి','Shout and hit')]]},
{id:'grab',ic:'🤝',n:T('సాధారణ పట్టు నుండి తప్పించుకోవడం','Escaping simple grabs'),v:null,k:'ready',les:0,e:T('ఇది బోధకుని పర్యవేక్షణలో మాత్రమే. వీడియో ఇంకా లేదు. లక్ష్యం: తప్పించుకుని సహాయం కోరడం.','Instructor-supervised only. No video yet. The goal is to get free and get help.'),kp:[T('తప్పించుకో, సహాయం కోరు','Get free, get help')],ck:[T('బోధకునితో మాత్రమే','Instructor only')]},
{id:'react',ic:'⚡',n:T('రియాక్షన్ డ్రిల్స్','Reaction drills'),v:null,k:'ready',les:2,e:T('సురక్షిత ఆటలు: కాంతి లేదా శబ్దానికి చప్పట్లు కొట్టడం. నిజమైన వీడియో లేదు.','Safe games like clapping when you hear a sound. No real video.'),kp:[T('ఆటలా చేయండి','Keep it a game')],ck:[T('శబ్దం వినగానే చప్పట్లు','Clap when you hear the sound')]},
{id:'pair',ic:'👥',n:T('భాగస్వామి శిక్షణ','Partner training'),v:null,k:'ready',les:0,e:T('బోధకుని పర్యవేక్షణ, రక్షణ పరికరాలు తప్పనిసరి. ఇక్కడ చూపము.','Needs a qualified instructor and protective gear. Not shown here.'),kp:[T('బోధకుడు తప్పనిసరి','Instructor required')],ck:[T('ఇది అర్థమైంది','I understand')]},
{id:'pad',ic:'🥊',n:T('ఫోకస్ ప్యాడ్ శిక్షణ','Focus pad training'),v:null,k:'ready',les:0,e:T('బోధకుడు ప్యాడ్ పట్టుకుని, రక్షణ పరికరాలతో మాత్రమే. వీడియో లేదు.','Only with an instructor holding the pads and protective gear. No video.'),kp:[T('బోధకుడు తప్పనిసరి','Instructor required')],ck:[T('ఇది అర్థమైంది','I understand')]},
{id:'beg',ic:'🌱',n:T('ప్రారంభ డ్రిల్స్','Beginner drills'),v:null,k:'horse',les:3,e:T('ఈ వీడియో ప్రారంభ కిహోన్ (ప్రాథమిక) అభ్యాసాలు చూపుతుంది: భంగిమలు, బ్లాక్, పంచ్, కిక్. చూడండి, ఆ తర్వాత మెల్లగా సాధన చేయండి.','This video shows beginner kihon (basics): stances, blocks, punches, kicks. Watch first, then practise slowly.'),kp:[T('ముందు చూడండి','Watch first'),T('తర్వాత మెల్లగా','Then slowly')],ck:[T('వీడియో చూశాను','I watched the video'),T('బోధకునితో సాధన','Practise with an instructor')]}];
/* audit 2:30 AM: one distinct clip per card. Cards that used to repeat the Kihon clip now point to the Beginner drills card instead of showing the same video again. */
TECH.forEach(t=>{if(['punch','kick','block'].indexOf(t.id)>=0){t.v=null;t.e=T(t.e.te+' ఈ అంశానికి ప్రత్యేక వీడియో ఇంకా లేదు. "ప్రాథమిక భంగిమ" కార్డ్‌లోని కిహోన్ వీడియో చూడండి.',t.e.en+' There is no separate video for this topic yet. See the Kihon video on the "Basic stance" card.')}});
if(!TECH.some(t=>t.id==='adv'))TECH.push({id:'adv',ic:'🏆',n:T('అడ్వాన్స్‌డ్ ఫారమ్ (చూడటానికి మాత్రమే)','Advanced form (watch only)'),v:'godan',k:'stork',les:6,e:T('Heian Godan అనే ఉన్నత స్థాయి కటా. ఇది చూడటానికి మాత్రమే. సొంతంగా ప్రయత్నించకండి; అర్హత కలిగిన బోధకునితో మాత్రమే.','Heian Godan, a higher-level kata. Watch only. Do not try it alone; only with a qualified instructor.'),kp:[T('చూడండి, అనుకరించకండి','Watch, do not copy'),T('బోధకుడు తప్పనిసరి','Instructor required')],ck:[T('బోధకుని అనుమతి ఉంది','An instructor allows it'),T('చూడటం మాత్రమే, సాధన కాదు','Watching only, not practising')],q:[T('ఈ అడ్వాన్స్‌డ్ ఫారమ్‌తో ఏమి చేయాలి?','What should you do with this advanced form?'),[T('చూడండి; బోధకునితో మాత్రమే సాధన','Watch it; practise only with an instructor'),T('ఇంట్లో సొంతంగా ప్రయత్నించండి','Try it alone at home'),T('స్నేహితునిపై ప్రయత్నించండి','Try it on a friend')]]});
const KEY='aksharanova.mav.v1';let M={done:{},ch:[]};try{M=Object.assign(M,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
const sv=()=>{try{localStorage.setItem(KEY,JSON.stringify(M))}catch(e){}};
const NOTE=()=>`<div class="c warn"><b>🛡️</b> ${E(L('మార్షల్ ఆర్ట్స్ క్రమశిక్షణ, ఫిట్‌నెస్, ఆత్మవిశ్వాసం, వ్యక్తిగత భద్రత కోసం. అర్హత కలిగిన బోధకుని పర్యవేక్షణలో మాత్రమే సాధన చేయండి. రక్షణ పరికరాలు వాడండి. హింస, ప్రమాదకర విన్యాసాలు వద్దు.','Martial arts are for discipline, fitness, confidence and personal safety. Practise techniques under qualified supervision. Use protective gear. No violence or risky stunts.'))}</div>`;
const vcard=(vid)=>{const v=V[vid];return `<div class="c"><span class="tag" style="background:#12a37f;border-radius:8px;padding:2px 8px;font-size:12px;font-weight:700">🎥 ${L('నిజమైన శిక్షణ వీడియో','Real Training Video')}</span><div class="vwrap" data-f="${v.file}" style="position:relative;margin:8px 0;border-radius:12px;overflow:hidden;background:#000;aspect-ratio:16/9"><img src="${TH+v.th}" alt="" loading="lazy" style="width:100%;height:100%;object-fit:cover"><button class="b" data-a="vplay" data-v="${vid}" style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);border-radius:50%;width:64px;height:64px;font-size:26px">▶</button></div><div class="sm">⏱️ ${v.dur} · ${E(v.lv)} · ${L('మూలం','Source')}: <a href="${CM}${v.file}" target="_blank" rel="noopener" style="color:#7cf0c2">Wikimedia Commons</a> · ${E(v.by)} · <a href="${v.licu}" target="_blank" rel="noopener" style="color:#7cf0c2">${v.lic}</a></div><div class="row"><button class="b g" data-a="vfs" data-v="${vid}">⛶ ${L('ఫుల్ స్క్రీన్','Fullscreen')}</button></div></div>`};
let cur=0;
function list(){const done=Object.keys(M.done).length;let h=I().top('home')+`<h2>🎥 ${L('నిజమైన శిక్షణ వీడియోలు','Real Training Videos')}</h2>`+NOTE()+`<p class="sm">${L('వీడియోలు Wikimedia Commons లోని CC లైసెన్స్ నిజమైన ఫుటేజ్. మేము వాటిని కాపీ చేయము; అధికారిక ప్లేయర్ లో చూపుతాము. సరైన నిజమైన వీడియో లేని చోట పాఠం, సూచనలు మాత్రమే.','Real footage under CC licences from Wikimedia Commons, shown in its official player (not copied). Where no suitable real video exists, only the lesson and instructions are shown.')}</p><div class="c"><b>${done}/${TECH.length}</b> ${L('పూర్తి','done')} <div class="bar" style="margin-top:6px"><i style="width:${Math.round(done/TECH.length*100)}%"></i></div></div><button class="b" data-a="chal">📅 ${L('21 రోజుల ఛాలెంజ్','21-day challenge')} (${M.ch.length}/21)</button>`;
 TECH.forEach((t,i)=>{h+=`<button class="les" data-a="tech" data-v="${i}"><span class="ic">${t.ic}</span><span style="flex:1">${E(L(t.n.te,t.n.en))}<div class="sm">${t.v?'🎥 '+L('నిజమైన వీడియో','Real video'):L('నిజమైన వీడియో లేదు (యానిమేషన్)','No real video (animated)')}</div></span><span>${M.done[t.id]?'✅':'▶'}</span></button>`});I().render(h)}
function tech(i){cur=i;const t=TECH[i],D=I().D;let h=I().top('vlist')+`<h2>${t.ic} ${E(L(t.n.te,t.n.en))}</h2><div class="sm">${E(L(t.n.en,t.n.te))}</div>`;
 h+=`<h3>1 · ${L('చూడండి','Watch')}</h3>`+(t.v?vcard(t.v)+(t.v2?vcard(t.v2):''):`<div class="c cm">${L('ఈ అంశానికి తగిన ఉచిత నిజమైన వీడియో ఇంకా దొరకలేదు. సూచనలు క్రింద ఉన్నాయి.','No suitable free real video found for this yet. Instructions are below.')}</div>`);
 h+=`<h3>2 · ${L('అర్థం చేసుకోండి','Understand')}</h3><div class="c"><p>${E(L(t.e.te,t.e.en))}</p><p class="sm">${E(L(t.e.en,t.e.te))}</p><ul>${t.kp.map(k=>`<li>${E(L(k.te,k.en))} <span class="sm">/ ${E(L(k.en,k.te))}</span></li>`).join('')}</ul><button class="b g" data-a="vspeak">🔊 ${L('వినండి','Listen')}</button></div>`;
 h+=`<h3>3 · ${L('సాధన','Practice')}</h3><div class="c">${t.ck.map((c,j)=>`<label style="display:block;margin:6px 0"><input type="checkbox" class="vck" style="width:20px;height:20px;vertical-align:middle"> ${E(L(c.te,c.en))} <span class="sm">/ ${E(L(c.en,c.te))}</span></label>`).join('')}<button class="b" data-a="vprac" data-v="${t.les}">▶ ${L('ఇప్పుడు సాధన చేయండి','Practice Now')}</button></div>`;
 h+=`<h3>4 · ${L('పూర్తి','Complete')}</h3><div class="c">`;if(t.q){h+=`<b>${E(L(t.q[0].te,t.q[0].en))}</b><div class="sm">${E(L(t.q[0].en,t.q[0].te))}</div>`+[0,1,2].map(j=>(j+i)%3).map(j=>{const o=t.q[1][j];return `<button class="les" data-a="vans" data-v="${j}">${E(L(o.te,o.en))}</button>`}).join('')+`<div id="vres"></div>`}
 h+=`<button class="b ok" data-a="vdone">✅ ${L('పూర్తి అని గుర్తించు','Mark complete')}</button><div class="sm">${L('యాప్ కార్యకలాపం పూర్తి మాత్రమే, నైపుణ్యం కొలత కాదు.','App activity completion only, not a skill assessment.')}</div></div>`;
 h+=`<div class="row">${i<TECH.length-1?`<button class="b" data-a="tech" data-v="${i+1}">${L('తరువాత పాఠం','Next lesson')} →</button>`:''}</div>`;I().render(h)}
function chal(){const t=new Date().toISOString().slice(0,10),n=M.ch.length;let h=I().top('vlist')+`<h2>📅 ${L('21 రోజుల శిక్షణ ఛాలెంజ్','21-day training challenge')}</h2><div class="c"><p>${L('రోజుకు 5-10 నిమిషాలు: ఒక భంగిమ, ఒక శ్వాస అభ్యాసం, ఒక వీడియో. బోధకుని లేదా పెద్దవారి సమక్షంలో.','5-10 minutes a day: one stance, one breathing practice, one video. With an instructor or adult present.')}</p><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:6px">${Array.from({length:21},(_,i)=>`<div style="text-align:center;padding:8px 0;border-radius:8px;background:${i<n?'#12a37f':'#2a3566'}">${i+1}</div>`).join('')}</div><p>${n}/21</p>`+(M.ch.includes(t)?`<p>✅ ${L('ఈ రోజు పూర్తి','Done for today')}</p>`:`<button class="b ok" data-a="chday">✅ ${L('ఈ రోజు పూర్తి','Today done')}</button>`)+`<p class="sm">${L('బ్యాడ్జీలు: 7 రోజులు 🥉, 14 రోజులు 🥈, 21 రోజులు 🥇 (యాప్ కార్యకలాపం పూర్తి మాత్రమే).','Badges: 7 days 🥉, 14 days 🥈, 21 days 🥇 (app activity completion only).')} ${n>=21?'🥇':n>=14?'🥈':n>=7?'🥉':''}</p></div>`;I().render(h)}
function speak(){try{const t=TECH[cur];speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(L(t.n.te+'. '+t.e.te,t.n.en+'. '+t.e.en));u.lang=L('te-IN','en-IN');u.rate=.85;speechSynthesis.speak(u)}catch(e){}}
function vplay(id,fs){const v=V[id];const w=document.querySelector('.vwrap[data-f="'+v.file+'"]');if(!w)return;w.innerHTML='<iframe src="'+CM+v.file+'?embedplayer=yes" allowfullscreen allow="fullscreen" style="width:100%;height:100%;border:0" title="Real Training Video"></iframe>';if(fs){try{(w.requestFullscreen||w.webkitRequestFullscreen).call(w)}catch(e){}}}
document.addEventListener('click',e=>{const t=e.target.closest&&e.target.closest('#ma [data-a^=v],#ma [data-a=tech],#ma [data-a=chal],#ma [data-a=chday]');if(!t||!window.MartialApp||!window.MartialApp._i)return;const a=t.dataset.a,v=t.dataset.v;
 if(a==='vlist'||a==='videos'){list();e.stopImmediatePropagation()}else if(a==='tech'){tech(+v);e.stopImmediatePropagation()}else if(a==='chal'){chal();e.stopImmediatePropagation()}else if(a==='chday'){const d=new Date().toISOString().slice(0,10);if(!M.ch.includes(d)){M.ch.push(d);sv()}chal();e.stopImmediatePropagation()}
 else if(a==='vplay'){vplay(v,0);e.stopImmediatePropagation()}else if(a==='vfs'){vplay(v,1);e.stopImmediatePropagation()}else if(a==='vspeak'){speak();e.stopImmediatePropagation()}
 else if(a==='vprac'){I().lesson(+v);e.stopImmediatePropagation()}
 else if(a==='vans'){const q=TECH[cur].q;const ok=q[1][+v]&&+v===0;document.getElementById('vres').innerHTML=ok?'<p>✅ '+E(L('సరైనది!','Correct!'))+'</p>':'<p>❌ '+E(L('మళ్ళీ చూడండి: ','Review: '))+E(L(q[1][0].te,q[1][0].en))+'</p>';e.stopImmediatePropagation()}
 else if(a==='vdone'){const t0=TECH[cur];const all=[...document.querySelectorAll('.vck')].every(c=>c.checked);if(!all){alert(L('ముందు సాధన జాబితా పూర్తి చేయండి','Tick the practice checklist first'));}else{M.done[t0.id]=1;sv();list()}e.stopImmediatePropagation()}},true);
window.MartialVideos={open:list,tech,TECH,V};
})();
