(function(){'use strict';
// AksharaNova Meditation: short, safe, bilingual (Telugu + English) calm-mind lessons for children.
const KEY='aksharanova.med.v1';
const E=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TE=()=>{try{return S.lang==='te'}catch(e){return true}};
const REDUCE=()=>{try{return matchMedia('(prefers-reduced-motion: reduce)').matches}catch(e){return false}};
const today=()=>new Date().toISOString().slice(0,10);
let D={done:{},mins:0,streak:0,last:''},ov=null,tm=null,st=null;
function load(){try{const j=JSON.parse(localStorage.getItem(KEY)||'null');if(j)D=Object.assign(D,j)}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(D))}catch(e){}}
// bilingual pair: primary language big, the other one small underneath so kids learn both
const B=(t,e,big)=>{const a=TE()?[t,e]:[e,t];return `<div class="${big?'p1 big':'p1'}">${E(a[0])}</div><div class="p2" lang="${TE()?'en':'te'}">${E(a[1])}</div>`};
const LES=[
{id:'belly',ic:'🎈',n:['బొడ్డు శ్వాస','Belly breathing'],s:['మెల్లగా గాలి పీల్చండి, బొడ్డు బెలూన్ లా పెరుగుతుంది. తర్వాత మెల్లగా వదలండి.','Breathe in slowly and your tummy grows like a balloon. Then breathe out slowly.'],
 br:[4,4],sec:60,st:[['హాయిగా కూర్చోండి. వెన్ను నిటారుగా.','Sit comfortably with a straight back.'],['ఒక చెయ్యి బొడ్డు మీద పెట్టండి.','Put one hand on your tummy.'],['ముక్కుతో 4 లెక్కించి గాలి పీల్చండి.','Breathe in through your nose, count 4.'],['నోటితో 4 లెక్కించి మెల్లగా వదలండి.','Breathe out slowly, count 4.']],
 q:[['శ్వాస పీల్చినప్పుడు బొడ్డు ఏమవుతుంది?','What happens to your tummy when you breathe in?',['పెరుగుతుంది','Grows','కుంచించుకుపోతుంది','Shrinks','ఏమీ కాదు','Nothing'],0],['శ్వాస ఎలా తీసుకోవాలి?','How should we breathe?',['వేగంగా','Fast','మెల్లగా','Slowly','ఆపేసి','Hold for long'],1]]},
{id:'balloon',ic:'🌬️',n:['బెలూన్ శ్వాస','Balloon breath'],s:['మనసులో పెద్ద బెలూన్ ఊహించండి. ఊదినట్టు నెమ్మదిగా వదలండి.','Imagine a big balloon. Blow it up slowly with a long breath out.'],
 br:[4,6],sec:60,st:[['కళ్ళు మెల్లగా మూసుకోండి లేదా కింద చూడండి.','Close your eyes gently or look down.'],['4 లెక్కతో గాలి పీల్చండి.','Breathe in for 4.'],['6 లెక్కతో మెల్లగా వదలండి.','Breathe out for 6, slowly.'],['ఇబ్బందిగా అనిపిస్తే మామూలుగా శ్వాస తీసుకోండి.','If it feels hard, just breathe normally.']],
 q:[['వదిలే శ్వాస ఎలా ఉండాలి?','How should the out-breath be?',['పొడవుగా, మెల్లగా','Long and slow','చాలా వేగంగా','Very fast','ఆపేయడం','Stopped'],0],['ఇబ్బంది అనిపిస్తే?','If it feels hard?',['కొనసాగించాలి','Force it','మామూలుగా శ్వాస తీసుకోవాలి','Breathe normally','పరిగెత్తాలి','Run'],1]]},
{id:'listen',ic:'👂',n:['శ్రద్ధగా వినడం','Mindful listening'],s:['కళ్ళు మూసుకుని చుట్టూ ఉన్న శబ్దాలు వినండి. పక్షులు, గాలి, దూరపు మాటలు.','Close your eyes and listen to the sounds around you: birds, wind, far-away voices.'],
 br:null,sec:45,st:[['నిశ్శబ్దంగా కూర్చోండి.','Sit quietly.'],['మీకు వినిపించే శబ్దాలను లెక్కించండి.','Count the sounds you can hear.'],['దగ్గర శబ్దం, దూర శబ్దం గుర్తించండి.','Notice a near sound and a far sound.'],['మెల్లగా కళ్ళు తెరవండి.','Open your eyes slowly.']],
 q:[['మైండ్‌ఫుల్ లిజనింగ్ లో ఏం చేస్తాం?','What do we do in mindful listening?',['శబ్దాలను శ్రద్ధగా వింటాం','Listen carefully to sounds','పాటలు పాడతాం','Sing songs','పరిగెత్తుతాం','Run'],0],['కళ్ళు ఎలా ఉంచాలి?','What about our eyes?',['మెల్లగా మూసుకోవాలి','Gently closed','గట్టిగా మూయాలి','Squeezed shut','పెద్దగా తెరవాలి','Wide open'],0]]},
{id:'senses',ic:'🖐️',n:['5-4-3-2-1 ఇంద్రియాలు','5-4-3-2-1 senses'],s:['ఆందోళనగా ఉన్నప్పుడు మన చుట్టూ ఉన్నవి గమనిస్తే మనసు ప్రశాంతమవుతుంది.','When you feel worried, noticing things around you helps your mind feel calm.'],
 br:null,sec:60,st:[['5 వస్తువులు చూడండి.','See 5 things.'],['4 వస్తువులను తాకి చూడండి.','Touch 4 things.'],['3 శబ్దాలు వినండి.','Hear 3 sounds.'],['2 వాసనలు గమనించండి.','Notice 2 smells.'],['1 సారి మంచి శ్వాస తీసుకోండి.','Take 1 slow breath.']],
 q:[['5-4-3-2-1 లో 5 అంటే?','In 5-4-3-2-1, what is 5?',['5 వస్తువులు చూడటం','See 5 things','5 సార్లు దూకడం','Jump 5 times','5 మందిని పిలవడం','Call 5 people'],0],['ఇది ఎప్పుడు ఉపయోగపడుతుంది?','When does it help?',['ఆందోళనగా ఉన్నప్పుడు','When worried','ఆడుతున్నప్పుడు మాత్రమే','Only when playing','ఎప్పుడూ కాదు','Never'],0]]},
{id:'thanks',ic:'🙏',n:['కృతజ్ఞత','Gratitude'],s:['ఈ రోజు మీకు నచ్చిన 3 మంచి విషయాలు గుర్తు చేసుకోండి.','Remember 3 good things from today that you are thankful for.'],
 br:null,sec:45,st:[['కళ్ళు మూసుకోండి, ఒక మంచి శ్వాస తీసుకోండి.','Close your eyes, take one calm breath.'],['మీకు సహాయం చేసిన ఒకరిని తలచుకోండి.','Think of someone who helped you.'],['మీకు ఇష్టమైన ఒక వస్తువు లేదా ప్రదేశం తలచుకోండి.','Think of a thing or place you love.'],['మనసులో "ధన్యవాదాలు" చెప్పండి.','Say "thank you" in your mind.']],
 q:[['కృతజ్ఞత అంటే?','What is gratitude?',['మంచి విషయాలకు ధన్యవాదాలు చెప్పడం','Being thankful for good things','కోపంగా ఉండటం','Being angry','మర్చిపోవడం','Forgetting'],0],['ధన్యవాదాలు ఎవరికి చెప్పవచ్చు?','Who can we thank?',['అమ్మ, నాన్న, టీచర్, స్నేహితులు','Parents, teachers, friends','ఎవరికీ కాదు','No one','కేవలం అపరిచితులకు','Only strangers'],0]]},
{id:'focus',ic:'🔵',n:['ఏకాగ్రత చుక్క','Focus on a dot'],s:['ఒక చిన్న చుక్కను మెల్లగా చూడండి. మనసు వేరే వైపు వెళ్ళితే మళ్ళీ చుక్క దగ్గరకు తీసుకురండి.','Gently look at one small dot. When your mind wanders, bring it back to the dot.'],
 br:null,dot:1,sec:45,st:[['చుక్కను సౌకర్యంగా చూడండి, కళ్ళు బిగించకండి.','Look at the dot comfortably, do not strain your eyes.'],['ఆలోచనలు వస్తే సరే. మెల్లగా తిరిగి చుక్క దగ్గరకు.','Thoughts will come. Gently return to the dot.'],['కళ్ళు నొప్పిగా ఉంటే ఆపి కళ్ళు మూసుకోండి.','If your eyes feel tired, stop and rest them.']],
 q:[['మనసు వేరే వైపు వెళ్ళితే?','If your mind wanders?',['మెల్లగా చుక్క దగ్గరకు తీసుకురావాలి','Gently bring it back','తిట్టుకోవాలి','Scold yourself','ఆపేయాలి','Quit forever'],0],['కళ్ళు అలసిపోతే?','If your eyes get tired?',['విశ్రాంతి ఇవ్వాలి','Rest them','ఇంకా గట్టిగా చూడాలి','Stare harder','ఏమీ చేయకూడదు','Ignore'],0]]},
{id:'body',ic:'🧘',n:['శరీర విశ్రాంతి','Body relax'],s:['తల నుండి పాదాల వరకు ఒక్కో భాగాన్ని మెల్లగా వదులు చేయండి.','Relax each part slowly, from head to toes.'],
 br:null,sec:60,st:[['పడుకోండి లేదా కూర్చోండి.','Lie down or sit comfortably.'],['భుజాలను కిందకు వదలండి.','Let your shoulders drop.'],['చేతులు, కడుపు, కాళ్ళు వదులు చేయండి.','Relax hands, tummy and legs.'],['పాదాల వరకు ప్రశాంతంగా.','Calm all the way to your toes.']],
 q:[['ఏ భాగం నుండి మొదలుపెట్టాం?','Where do we start?',['తల','Head','పాదాలు','Feet','వేళ్ళు','Fingers'],0],['భుజాలు ఎలా ఉండాలి?','Shoulders should be?',['వదులుగా','Loose','పైకి బిగుతుగా','Tight and high','వెనక్కి','Pulled back hard'],0]]},
{id:'kind',ic:'💛',n:['దయతో కూడిన కోరికలు','Kind wishes'],s:['మీకూ, మీ కుటుంబానికీ, అందరికీ మంచి జరగాలని మనసులో కోరుకోండి.','Quietly wish good things for yourself, your family and everyone.'],
 br:null,sec:45,st:[['చెయ్యి గుండె మీద పెట్టండి.','Put a hand on your heart.'],['"నేను సంతోషంగా ఉండాలి" అనుకోండి.','Think "May I be happy."'],['"నా కుటుంబం సంతోషంగా ఉండాలి" అనుకోండి.','Think "May my family be happy."'],['"అందరూ సంతోషంగా ఉండాలి" అనుకోండి.','Think "May everyone be happy."']],
 q:[['ఈ ధ్యానంలో ఏం కోరుకుంటాం?','What do we wish here?',['అందరికీ మంచి జరగాలని','Good things for everyone','ఎవరినైనా ఓడించాలని','To beat someone','ఏమీ కాదు','Nothing'],0],['చెయ్యి ఎక్కడ పెట్టాలి?','Where does the hand go?',['గుండె మీద','On the heart','తల మీద','On the head','వీపు వెనక','Behind the back'],0]]}
];
const css=`#md{position:fixed;inset:0;z-index:9992;background:radial-gradient(circle at 50% 0,#1b2a5e,#0b1230 60%);color:#f6f8ff;overflow:auto;font-family:inherit}#md .w{max-width:560px;margin:0 auto;padding:12px 12px 80px}#md h2{margin:8px 0}#md .c{background:#18204a;border:1px solid #7ab9ff44;border-radius:16px;padding:12px;margin:10px 0}#md .b{background:#1d6fd1;color:#fff;border:0;border-radius:12px;padding:11px 14px;font-size:15px;font-weight:700;margin:4px 4px 4px 0;min-height:44px}#md .b.g{background:#2a3566}#md .b.ok{background:#12a37f}#md .top{display:flex;justify-content:space-between}#md .row{display:flex;gap:8px;flex-wrap:wrap}#md .les{display:flex;align-items:center;gap:10px;width:100%;text-align:left;background:#202b50;border:1px solid #7ab9ff55;border-radius:14px;padding:11px;margin:7px 0;color:#f6f8ff;font-size:15px;min-height:48px}#md .les .ic{font-size:26px}#md .p1{font-size:15px}#md .p1.big{font-size:18px;font-weight:700}#md .p2{font-size:13px;opacity:.75;margin-bottom:6px}#md .sm{font-size:12px;opacity:.8}#md .warn{border-color:#ffb84d99;background:#2b2314}#md .orb{width:150px;height:150px;border-radius:50%;margin:16px auto;background:radial-gradient(circle at 35% 30%,#a8fff0,#4da3ff);box-shadow:0 0 40px #4da3ff88;transform:scale(.6);display:flex;align-items:center;justify-content:center;color:#06122e;font-weight:800;font-size:18px;text-align:center}#md .dot{width:22px;height:22px;border-radius:50%;background:#ffb84d;margin:50px auto;box-shadow:0 0 18px #ffb84d}#md .bar{height:8px;background:#2a3566;border-radius:6px;overflow:hidden}#md .bar>i{display:block;height:100%;background:linear-gradient(90deg,#7cf0c2,#4da3ff);width:0}`;
const top=b=>`<div class="top"><button class="b g" data-a="${b||'home'}">← ${TE()?'వెనుకకు':'Back'}</button><button class="b g" data-a="close">✕</button></div>`;
function render(h){ov.innerHTML='<div class="w">'+h+'</div>';ov.scrollTop=0}
function home(){stop();let h=top('close')+`<h2>🧘 ${TE()?'ధ్యానం · Meditation':'Meditation · ధ్యానం'}</h2>`+B('ప్రశాంతంగా ఉండటానికి చిన్న, సులభమైన అభ్యాసాలు. తెలుగు మరియు ఇంగ్లీష్ రెండూ నేర్చుకోండి.','Short, simple practices for a calm mind. Learn Telugu and English together.')
 +`<div class="c warn">${B('ఇది ఆరోగ్య చికిత్స కాదు. ఆందోళన లేదా బాధ ఎక్కువగా ఉంటే పెద్దవారికి లేదా టీచర్ కు చెప్పండి. అసౌకర్యంగా అనిపిస్తే ఆపేయండి.','This is not medical treatment. If you feel very worried or sad, tell a trusted adult or teacher. Stop if anything feels uncomfortable.')}</div>`
 +`<div class="c"><div class="row" style="justify-content:space-between"><span>🔥 ${TE()?'వరుస':'Streak'} <b>${D.streak}</b></span><span>⏱️ ${D.mins} ${TE()?'నిమి':'min'}</span><span>${Object.keys(D.done).length}/${LES.length}</span></div></div>`;
 LES.forEach((l,i)=>{h+=`<button class="les" data-a="lesson" data-v="${i}"><span class="ic">${l.ic}</span><span style="flex:1"><div class="p1">${E(TE()?l.n[0]:l.n[1])}</div><div class="p2" style="margin:0">${E(TE()?l.n[1]:l.n[0])}</div></span><span>${D.done[l.id]?'✅':'▶'}</span></button>`});
 h+=`<p class="sm">${TE()?'పురోగతి ఈ ఫోన్ లోనే ఉంటుంది. "పూర్తి" అంటే యాప్ లో అభ్యాసం చేశారని మాత్రమే.':'Progress stays on this phone. "Done" only means you finished the activity in the app.'}</p>`;render(h)}
function lesson(i){stop();const l=LES[i];st={i};let h=top()+`<h2>${l.ic} ${E(TE()?l.n[0]:l.n[1])}</h2><div class="p2" style="margin-top:-6px">${E(TE()?l.n[1]:l.n[0])}</div>`+`<div class="c">${B(l.s[0],l.s[1])}</div>`;
 h+=l.dot?'<div class="dot" id="mdv"></div>':`<div class="orb" id="mdv" aria-hidden="true">${l.br?'':'🌿'}</div>`;
 h+=`<div class="c"><b>⏱️ ${l.sec} ${TE()?'సెకన్లు':'sec'}</b><div class="bar" style="margin:8px 0"><i id="mdb"></i></div><div id="mdt" class="p1 big" style="text-align:center;min-height:26px"></div><div class="row"><button class="b" data-a="start">▶ ${TE()?'మొదలుపెట్టు':'Start'}</button><button class="b g" data-a="stop">⏹ ${TE()?'ఆపు':'Stop'}</button><button class="b g" data-a="listen">🔊 ${TE()?'వినండి':'Listen'}</button></div></div>`;
 h+=`<div class="c"><b>${TE()?'దశలు':'Steps'}</b><ol style="padding-left:20px">`+l.st.map(s=>`<li>${B(s[0],s[1])}</li>`).join('')+`</ol></div><button class="b" data-a="quiz" data-v="${i}">❓ ${TE()?'చిన్న క్విజ్':'Quick quiz'}</button>`;render(h)}
function stop(){clearInterval(tm);tm=null;try{speechSynthesis.cancel()}catch(e){}}
function start(){const l=LES[st.i];stop();const v=document.getElementById('mdv'),b=document.getElementById('mdb'),t=document.getElementById('mdt');let el=0;const R=REDUCE();
 const tick=()=>{el++;b.style.width=Math.min(100,el*100/l.sec)+'%';if(l.br){const c=l.br[0]+l.br[1],p=(el-1)%c,inh=p<l.br[0];const n=inh?p+1:p-l.br[0]+1;t.textContent=(inh?(TE()?'పీల్చండి · Breathe in ':'Breathe in · పీల్చండి '):(TE()?'వదలండి · Breathe out ':'Breathe out · వదలండి '))+n;if(!R){v.style.transition='transform 1s linear';v.style.transform='scale('+(inh?.6+.5*n/l.br[0]:1.1-.5*n/l.br[1])+')'}}else{const k=l.st[Math.min(l.st.length-1,Math.floor((el-1)/l.sec*l.st.length))];t.textContent=TE()?k[0]:k[1]}
  if(el>=l.sec){stop();t.textContent=TE()?'బాగుంది! 🎉 · Well done!':'Well done! 🎉 · బాగుంది!';D.mins=Math.round((D.mins+l.sec/60)*10)/10;const d=today();if(D.last!==d){const y=new Date(Date.now()-864e5).toISOString().slice(0,10);D.streak=D.last===y?D.streak+1:1;D.last=d}D.done[l.id]=d;save()}};
 if(l.br&&!R&&v)v.style.transform='scale(.6)';tick();tm=setInterval(tick,1000)}
function listen(){try{const l=LES[st.i];const txt=(TE()?l.n[0]+'. '+l.s[0]+' '+l.st.map(s=>s[0]).join(' '):l.n[1]+'. '+l.s[1]+' '+l.st.map(s=>s[1]).join(' '));speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(txt);u.lang=TE()?'te-IN':'en-IN';u.rate=.85;speechSynthesis.speak(u)}catch(e){}}
function quiz(i){stop();st={i,qi:0,right:0};qshow()}
function qshow(){const l=LES[st.i],q=l.q[st.qi];let h=top('lesson:'+st.i)+`<div class="sm">${l.ic} ${st.qi+1}/${l.q.length}</div><div class="c">${B(q[0],q[1],1)}</div>`;for(let j=0;j<3;j++){const o=[q[2][j*2],q[2][j*2+1]];h+=`<button class="les" data-a="ans" data-v="${j}"><span style="flex:1">${B(o[0],o[1])}</span></button>`}render(h)}
function ans(j){const l=LES[st.i],q=l.q[st.qi],ok=j===q[3];if(ok)st.right++;st.qi++;const more=st.qi<l.q.length;render(top('lesson:'+st.i)+`<div class="c ${ok?'':'warn'}"><b>${ok?'✅ '+(TE()?'సరైనది!':'Correct!'):'❌ '+(TE()?'మళ్ళీ ప్రయత్నించండి':'Try again next time')}</b>${ok?'':'<div class="p2">'+E(TE()?q[2][q[3]*2]:q[2][q[3]*2+1])+'</div>'}</div><button class="b" data-a="${more?'qnext':'finish'}">${more?(TE()?'తరువాత':'Next'):(TE()?'ముగించు':'Finish')} →</button>`)}
function finish(){const l=LES[st.i];render(top()+`<h2>🎉 ${TE()?'బాగుంది':'Well done'}</h2><div class="c"><p>${st.right}/${l.q.length} ${TE()?'సరైనవి':'correct'}</p><p class="sm">${TE()?'ఇది యాప్ లో అభ్యాసం పూర్తి చేసినందుకు మాత్రమే.':'This is only for finishing the app activity.'}</p></div><div class="row"><button class="b" data-a="lesson" data-v="${Math.min(LES.length-1,st.i+1)}">${TE()?'తరువాత పాఠం':'Next lesson'} →</button><button class="b g" data-a="home">${TE()?'జాబితా':'List'}</button></div>`)}
function click(e){const t=e.target.closest('[data-a]');if(!t)return;const a=t.dataset.a,v=t.dataset.v;try{SFX.tap()}catch(x){}
 if(a==='close')close();else if(a==='home')home();else if(a==='lesson')lesson(+v);else if(a&&a.indexOf('lesson:')===0)lesson(+a.split(':')[1]);else if(a==='start')start();else if(a==='stop'){stop()}else if(a==='listen')listen();else if(a==='quiz')quiz(+v);else if(a==='ans')ans(+v);else if(a==='qnext')qshow();else if(a==='finish')finish()}
function onPop(){if(ov)close(true)}
function close(fp){stop();if(ov){ov.remove();ov=null}window.removeEventListener('popstate',onPop);if(!fp){try{if(location.hash==='#meditation')history.back()}catch(e){}}}
function open(){if(ov)return;load();if(!document.getElementById('mdcss')){const s=document.createElement('style');s.id='mdcss';s.textContent=css;document.head.appendChild(s)}ov=document.createElement('div');ov.id='md';document.body.appendChild(ov);ov.addEventListener('click',click);window.addEventListener('popstate',onPop);try{history.pushState({md:1},'','#meditation')}catch(e){}home()}
function selfTest(){return LES.map(l=>(l.q.length>=2&&l.q.every(q=>q[2].length===6&&q[3]>=0&&q[3]<3)&&l.st.length>=3?'ok ':'FAIL ')+l.id)}
window.MeditationApp={open,selfTest,LES};
})();
