// Content pack import. Original wording; sources recorded in pack files.
(function(){const Q=(q,o,e)=>q+"|"+o.join("|")+"|"+e;const A=function(s,c,t){LD.ov(s,c,t)};
A("gk",[7, 8, 9, 10],{id:"gkm_india_rbi_basics",i:"🏦",te:"భారతీయ రిజర్వు బ్యాంకు - ప్రాథమిక విషయాలు",en:"Reserve Bank of India: Basics",kw:"RBI Reserve Bank monetary currency banknotes coins రిజర్వు బ్యాంకు ద్రవ్య విధానం rijarvu byanku",n:["# సారాంశం§# Summary", "RBI అంటే Reserve Bank of India; తెలుగులో భారతీయ రిజర్వు బ్యాంకు.§RBI stands for Reserve Bank of India.", "RBI Act, 1934 దాని చట్టబద్ధమైన ఆధారం. కార్యకలాపాలు 1 ఏప్రిల్ 1935న ప్రారంభమయ్యాయి.§The RBI Act, 1934 provides its statutory basis. Operations began on 1 April 1935.", "1949లో RBI జాతీయీకరణ జరిగింది. అప్పటి నుంచి పూర్తిగా భారత ప్రభుత్వ యాజమాన్యంలో ఉంది.§RBI was nationalised in 1949 and has since been wholly owned by the Government of India.", "ద్రవ్య విధానం, బ్యాంకు పర్యవేక్షణ, నియంత్రణ RBI ముఖ్య విధులు.§Monetary policy, bank supervision and regulation are core RBI functions.", "RBI banknotesను జారీ చేస్తుంది. ఒక రూపాయి నోటును భారత ప్రభుత్వం జారీ చేస్తుంది.§RBI issues banknotes. The Government of India issues the one-rupee note.", "నాణేల రూపకల్పన, తయారీ భారత ప్రభుత్వ బాధ్యత. ప్రభుత్వం తయారు చేసిన నాణేలను RBI చలామణికి పంపిణీ చేస్తుంది.§The Government of India designs and mints coins. RBI distributes Government-minted coins into circulation.", "ఈ పాఠం స్థిర చరిత్ర, ప్రాథమిక విధులపై ఉంది. 6 అక్టోబర్ 2026 తనిఖీ తేదీ; ప్రస్తుత వడ్డీ రేటు లేదా గవర్నర్ వివరాలు ఇవ్వలేదు.§This lesson covers historical facts and basic functions. 6 October 2026 is the verification date; current interest rates and Governor details are not included.", "# పద్ధతి§# Method", "1. చట్టం, కార్యకలాపాల ప్రారంభం, జాతీయీకరణ తేదీలను వేరు చేయండి.§1. Separate the Act, commencement and nationalisation dates.", "2. నోట్ల జారీ, నాణేల తయారీ, పంపిణీ పనులను కలపవద్దు.§2. Do not confuse note issue, coin minting and distribution.", "> ఉదా: 1934, 1935, 1949ను RBI సంఘటనలతో జతచేయండి. → 1934 చట్టం; 1935 కార్యకలాపాల ప్రారంభం. → 1949 జాతీయీకరణ సంవత్సరం. → జవాబు: చట్టం 1934; కార్యకలాపాలు 1935; జాతీయీకరణ 1949.§> Example: Match 1934, 1935 and 1949 to RBI events. → 1934 is the Act year; 1935 is the commencement year. → 1949 is the nationalisation year. → Answer: Act: 1934; operations: 1935; nationalisation: 1949.", "> ఉదా: నాణేలను RBI తయారు చేస్తుందని విద్యార్థి అన్నాడు. సరిచేయండి. → తయారీ, పంపిణీ వేరు చేయండి. → ప్రభుత్వం తయారు చేస్తుంది; RBI పంపిణీ చేస్తుంది. → జవాబు: నాణేల తయారీ భారత ప్రభుత్వ బాధ్యత; RBI చలామణికి పంపిణీ చేస్తుంది.§> Example: A student says RBI mints coins. Correct the statement. → Separate minting from distribution. → Government mints; RBI distributes. → Answer: Coin minting is the Government of India’s responsibility; RBI distributes coins into circulation.", "# మూలం§# Source", "https://www.rbi.org.in/scripts/AboutusDisplay.aspx (2026-10-06)§https://www.rbi.org.in/scripts/AboutusDisplay.aspx (2026-10-06)"],
q:[Q("RBI పూర్తి పేరు ఏమిటి?§What does RBI stand for?",["భారతీయ రిజర్వు బ్యాంకు§Reserve Bank of India","భారతీయ రైల్వే బోర్డు§Railway Board of India","భారతీయ నదుల బ్యూరో§River Bureau of India","భారతీయ క్రీడా మండలి§Sports Council of India"],"RBI అంటే Reserve Bank of India.§RBI stands for Reserve Bank of India."),
Q("RBI కార్యకలాపాలు ప్రారంభించిన సంవత్సరం?§In which year did RBI begin operations?",["1935","1934","1947","1949"],"చట్టం 1934నాటిది; కార్యకలాపాలు 1935లో ప్రారంభమయ్యాయి.§The Act dates to 1934; operations began in 1935."),
Q("RBI కార్యకలాపాలు ప్రారంభించిన తేదీ?§On which date did RBI begin operations?",["1 ఏప్రిల్ 1935§1 April 1935","15 ఆగస్టు 1947§15 August 1947","26 జనవరి 1950§26 January 1950","2 జూన్ 2014§2 June 2014"],"రెండు RBI చరిత్ర మూలాలు 1 ఏప్రిల్ 1935ను పేర్కొంటాయి.§Both RBI history sources identify 1 April 1935."),
Q("RBI జాతీయీకరణ జరిగిన సంవత్సరం?§In which year was RBI nationalised?",["1949","1935","1934","2014"],"RBI జాతీయీకరణ 1949లో జరిగింది.§RBI was nationalised in 1949."),
Q("RBIకి చట్టబద్ధమైన ఆధారం ఇచ్చిన చట్టం?§Which Act provides RBI’s statutory basis?",["భారతీయ రిజర్వు బ్యాంకు చట్టం, 1934§Reserve Bank of India Act, 1934","నాణేల చట్టం, 2011§Coinage Act, 2011","విద్యా హక్కు చట్టం, 2009§Right to Education Act, 2009","వన్యప్రాణి సంరక్షణ చట్టం, 1972§Wild Life (Protection) Act, 1972"],"RBI Act, 1934 బ్యాంకు కార్యకలాపాలకు చట్టబద్ధమైన ఆధారం.§The RBI Act, 1934 provides the Bank’s statutory basis."),
Q("RBI ప్రధాన విధుల్లో ఒకటి?§Which is a main function of RBI?",["ద్రవ్య విధానం§Monetary policy","వాతావరణ అంచనా§Weather forecasting","అడవి జంతువుల లెక్కింపు§Wildlife census","రైలు సమయపట్టిక§Rail timetable"],"RBI ద్రవ్య విధానాన్ని రూపొందించి అమలు చేస్తుంది.§RBI formulates and implements monetary policy."),
Q("బ్యాంకు పర్యవేక్షణ, నియంత్రణతో సంబంధం ఉన్న సంస్థ?§Which institution is associated with bank supervision and regulation?",["భారతీయ రిజర్వు బ్యాంకు§Reserve Bank of India","భారత అంతరిక్ష పరిశోధన సంస్థ§Indian Space Research Organisation","భారత వాతావరణ శాఖ§India Meteorological Department","భారత పురావస్తు శాఖ§Archaeological Survey of India"],"బ్యాంకు పర్యవేక్షణ, నియంత్రణ RBI ముఖ్య విధుల్లో ఉన్నాయి.§Bank supervision and regulation are core RBI functions."),
Q("నాణేల తయారీ, రూపకల్పన బాధ్యత ఎవరిది?§Who is responsible for designing and minting coins?",["భారత ప్రభుత్వం§Government of India","ఒక ప్రైవేటు దుకాణం§A private shop","పాఠశాల ప్రధానోపాధ్యాయుడు§A school headteacher","స్థానిక క్రీడా జట్టు§A local sports team"],"నాణేల రూపకల్పన, తయారీ ప్రభుత్వ బాధ్యత; RBI పంపిణీలో పాత్ర వహిస్తుంది.§Coin design and minting are Government responsibilities; RBI has a distribution role."),
Q("చట్టం, ప్రారంభ సంవత్సరం సరైన క్రమం?§Correct order of Act year and operations year?",["1934 → 1935","1935 → 1934","1949 → 1935","2011 → 1934"],"మొదట RBI Act, 1934; తరువాత 1935లో కార్యకలాపాలు.§First the RBI Act, 1934; then operations in 1935."),
Q("RBI స్థాపన, జాతీయీకరణ సంవత్సరాల మధ్య తేడా?§Difference between RBI’s establishment and nationalisation years?",["14","1","35","49"],"1949 − 1935 = 14 సంవత్సరాలు.§1949 minus 1935 equals 14 years."),
Q("RBI ప్రతి భారతీయ కరెన్సీ నోటును జారీ చేస్తుంది అనడం ఎందుకు తప్పు?§Why is it wrong to say RBI issues every Indian currency note?",["ఒక రూపాయి నోటు భారత ప్రభుత్వం జారీ చేస్తుంది§The Government of India issues the one-rupee note","అన్ని నోట్లు పాఠశాలలు జారీ చేస్తాయి§Schools issue all notes","RBI నాణేలను మాత్రమే తయారు చేస్తుంది§RBI only mints coins","నోట్లు కరెన్సీ కావు§Notes are not currency"],"RBI banknotesను జారీ చేస్తుంది; ఒక రూపాయి నోటు ప్రభుత్వ జారీ. ఈ మినహాయింపును ఉంచాలి.§RBI issues banknotes; the one-rupee note is issued by the Government. Preserve this exception."),
Q("నాణేలు, RBI మధ్య సరైన సంబంధం?§Correct relationship between coins and RBI?",["ప్రభుత్వం తయారు చేసిన నాణేలను RBI చలామణికి పంపిణీ చేస్తుంది§RBI distributes Government-minted coins into circulation","RBI మాత్రమే అన్ని నాణేలను తయారు చేస్తుంది§RBI alone mints all coins","RBIకి నాణేల పంపిణీతో సంబంధం లేదు§RBI has no coin-distribution role","విద్యార్థులు మాత్రమే నాణేలను జారీ చేస్తారు§Only students issue coins"],"తయారీ, పంపిణీ వేరు పనులు: ప్రభుత్వం తయారు చేస్తుంది; RBI పంపిణీ చేస్తుంది.§Minting and distribution differ: Government mints; RBI distributes."),
Q("చరిత్రలో సరైన క్రమం?§Correct historical sequence?",["1934 చట్టం → 1935 కార్యకలాపాలు → 1949 జాతీయీకరణ§1934 Act → 1935 operations → 1949 nationalisation","1949 జాతీయీకరణ → 1935 కార్యకలాపాలు → 1934 చట్టం§1949 nationalisation → 1935 operations → 1934 Act","1935 కార్యకలాపాలు → 1949 జాతీయీకరణ → 1934 చట్టం§1935 operations → 1949 nationalisation → 1934 Act","1949 చట్టం → 2014 కార్యకలాపాలు → 2023 జాతీయీకరణ§1949 Act → 2014 operations → 2023 nationalisation"],"చట్టం, ప్రారంభం, జాతీయీకరణను వేరు సంఘటనలుగా వరుసలో ఉంచండి.§Order the Act, commencement and nationalisation as separate events."),
Q("నోటు జారీ, నాణేల పంపిణీని ఏ అంశంలో చదవాలి?§Under which function should note issue and coin distribution be studied?",["కరెన్సీ నిర్వహణ§Currency management","ఖగోళ పరిశీలన§Astronomical observation","క్రీడా ఎంపిక§Sports selection","అడవి సర్వే§Forest survey"],"కరెన్సీ నిర్వహణలో నోట్ల జారీ, ప్రభుత్వ నాణేల పంపిణీ ఉంటాయి.§Currency management includes issuing notes and distributing Government coins."),
Q("జాతీయీకరణ తరువాత RBI యాజమాన్యం?§Who owns RBI following nationalisation?",["భారత ప్రభుత్వం§Government of India","ఒక పాఠశాల§A school","ఒక విదేశీ క్రీడా జట్టు§A foreign sports team","ఒక ప్రైవేటు పర్యాటకుడు§A private tourist"],"జాతీయీకరణ తరువాత RBI పూర్తిగా భారత ప్రభుత్వ యాజమాన్యంలో ఉంది.§Following nationalisation, RBI is wholly owned by the Government of India.")]});
LD.reg("pk12",1)})();
