(function(){'use strict';
const KEY='aksharanova.puzzles.v1',SKEY='aksharanova.speed.v1';
const L=(te,en)=>{try{return S.lang==='te'?te:en}catch(e){return en}};
const E=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tapSound=true;try{tapSound=localStorage.getItem('aksharanova.puzzles.tapSound')!=='off'}catch(e){}let tapAC=null;function letterTap(){if(!tapSound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;tapAC=tapAC||new C();tapAC.resume();const o=tapAC.createOscillator(),g=tapAC.createGain(),t=tapAC.currentTime;o.type='sine';o.frequency.setValueAtTime(660,t);o.frequency.exponentialRampToValueAtTime(440,t+.065);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.055,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+.075);o.connect(g);g.connect(tapAC.destination);o.start(t);o.stop(t+.08)}catch(e){}}const R=n=>Math.floor(Math.random()*n);
const shuf=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=R(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const XW=new Set(["ABET", "ABLE", "ACRE", "ACT", "ANT", "ANY", "APE", "ARE", "ARM", "ART", "ARTS", "ASP", "ASTER", "ATE", "AUNT", "BAG", "BAKE", "BALE", "BAN", "BARE", "BAT", "BEAK", "BEAR", "BEAT", "BEE", "BETA", "BIG", "BIN", "BLOW", "BORE", "BOW", "BOWL", "BOY", "BUR", "BUS", "BUT", "CAN", "CAPE", "CARE", "CAT", "CATER", "COAL", "COLA", "COW", "CRATE", "DALE", "DARE", "DAY", "DEAL", "DEAR", "DEER", "DEN", "DEW", "DOG", "DUNE", "DUST", "DYE", "EAR", "EARN", "EARTH", "EAST", "EAT", "EATS", "END", "ERA", "EVIL", "EYE", "FAN", "FARE", "FEAR", "FEEL", "FIN", "FLEA", "FLEE", "FLOW", "FLUE", "FOAL", "FOWL", "FREE", "FUEL", "GAB", "GINS", "GNAT", "GOD", "GUM", "GUNS", "HATER", "HEARS", "HEART", "HEN", "HOSE", "HOW", "ICE", "ITS", "JOY", "LAME", "LAMP", "LAP", "LAPSE", "LATE", "LAW", "LEAD", "LEAF", "LEAPS", "LEAST", "LID", "LIME", "LIP", "LIVE", "LOAF", "LOOP", "LOSE", "LOST", "LOT", "LOTS", "LOW", "LURE", "MALE", "MAR", "MAY", "MEAL", "MILE", "MOB", "MOW", "MUG", "NAB", "NAG", "NAP", "NEAR", "NEST", "NET", "NETS", "NIPS", "NOSE", "NOTE", "NOW", "NUDE", "NUTS", "OIL", "ONES", "OPT", "OPTS", "ORB", "OWL", "OWN", "PACE", "PAD", "PAL", "PALES", "PALM", "PAN", "PARE", "PART", "PAT", "PATE", "PAW", "PEA", "PEAR", "PEAT", "PEN", "PIG", "PINS", "PIT", "POLO", "POOL", "PORE", "POST", "POT", "POTS", "PREY", "PYRE", "RACE", "RAM", "RAPE", "RAT", "RATES", "RATS", "RAW", "REACT", "READ", "REAP", "REED", "REEF", "RITE", "ROB", "ROBE", "ROPE", "ROW", "RUB", "RULE", "RUNT", "SAT", "SATE", "SAW", "SEA", "SEAT", "SEE", "SENT", "SHARE", "SHOE", "SIGN", "SING", "SINK", "SIP", "SIT", "SKIN", "SLATE", "SLOT", "SNIP", "SNUG", "SOLE", "SOW", "SPA", "SPIN", "SPOT", "STALE", "STAR", "STARE", "STAY", "STEAL", "STOP", "STUN", "SUB", "SUNG", "SWAY", "TAB", "TALE", "TALES", "TAN", "TANG", "TAP", "TAPE", "TAR", "TARS", "TEA", "TEAL", "TEARS", "TEAS", "TEN", "TIER", "TIP", "TIRE", "TONE", "TOP", "TOPS", "TOY", "TRACE", "TRAP", "TUB", "TUNA", "TUNE", "TURN", "VEIL", "VILE", "WAR", "WAS", "WAY", "WAYS", "WEB", "WED", "WHO", "WOLF", "WON"]);
const GAMES=[['scr','🔤','పదాల అల్లిక','Word Scramble'],['mem','🃏','జ్ఞాపక జంటలు','Memory Match'],['num','🔢','సంఖ్యల పజిల్','Number Puzzle'],['odd','🧐','వేరైనది కనుగొనండి','Odd One Out'],['sld','🧩','జారే పజిల్','Sliding Puzzle']];
const DIFF=[['e','🟢','సులభం','Easy'],['m','🟡','మధ్యస్థం','Medium'],['h','🔴','కఠినం','Hard']];
const gname=g=>{const x=GAMES.find(y=>y[0]===g);return x[1]+' '+L(x[2],x[3])};
const dname=d=>{const x=DIFF.find(y=>y[0]===d);return x[1]+' '+L(x[2],x[3])};
// ---------- content
const WEN=[['CAT','Says meow','మ్యావ్ అంటుంది','e'],['DOG','Barks at night','రాత్రి మొరుగుతుంది','e'],['SUN','Shines in the day','పగలు వెలుగు ఇస్తుంది','e'],['HEN','Lays eggs','గుడ్లు పెడుతుంది','e'],['BUS','Takes children to school','బడికి తీసుకెళ్తుంది','e'],['FISH','Lives in water','నీటిలో ఉంటుంది','e'],['BIRD','Has wings','రెక్కలు ఉంటాయి','e'],['TREE','Gives shade','నీడ ఇస్తుంది','e'],['MOON','Seen at night','రాత్రి కనిపిస్తుంది','e'],['STAR','Twinkles','మెరుస్తుంది','e'],['BOOK','You read it','చదువుతాం','e'],['RAIN','Falls from clouds','మేఘాల నుండి పడుతుంది','e'],
['APPLE','A red fruit','ఎర్రని పండు','m'],['MANGO','King of fruits','పండ్ల రాజు','m'],['ZEBRA','Striped animal','చారల జంతువు','m'],['HORSE','Runs fast','వేగంగా పరుగెత్తుతుంది','m'],['TABLE','You write on it','దీనిపై రాస్తాం','m'],['SCHOOL','Where we learn','మనం నేర్చుకునే చోటు','m'],['PENCIL','Used to write','రాయడానికి వాడతాం','m'],['FLOWER','Smells sweet','మంచి వాసన వస్తుంది','m'],['PLANET','Earth is one','భూమి ఒకటి','m'],
['ELEPHANT','Has a long trunk','పొడవాటి తొండం ఉంటుంది','h'],['BUTTERFLY','Colourful insect','రంగురంగుల కీటకం','h'],['MOUNTAIN','Very tall land','చాలా ఎత్తైన భూమి','h'],['UMBRELLA','Keeps rain away','వానను ఆపుతుంది','h'],['COMPUTER','Used for work and games','పనికి, ఆటలకు వాడతాం','h'],['TEACHER','Helps you learn','నేర్పిస్తారు','h'],['PEACOCK','National bird','జాతీయ పక్షి','h'],['DOLPHIN','Swims in the sea','సముద్రంలో ఈదుతుంది','h']];
const WTE=[[['ఆ','వు'],'A farm animal that gives milk','పాలు ఇచ్చే జంతువు','e'],[['బ','డి'],'Where we study','మనం చదువుకునే చోటు','e'],[['చే','ప'],'Lives in water','నీటిలో ఉంటుంది','e'],[['కో','తి'],'Jumps on trees','చెట్లపై దూకుతుంది','e'],[['అ','మ్మ'],'Mother','తల్లి','e'],[['పు','వ్వు'],'Smells sweet','మంచి వాసన వస్తుంది','e'],[['తో','ట'],'Plants grow here','మొక్కలు పెరిగే చోటు','e'],[['ఏ','ను','గు'],'Has a long trunk','పొడవాటి తొండం','e'],[['పి','ల్లి'],'Says meow','మ్యావ్ అంటుంది','e'],[['చె','ట్టు'],'Gives shade','నీడ ఇస్తుంది','e'],
[['నె','మ','లి'],'National bird','జాతీయ పక్షి','m'],[['గొ','డు','గు'],'Keeps rain away','వానను ఆపుతుంది','m'],[['పు','స్త','కం'],'You read it','చదువుతాం','m'],[['ఆ','కా','శం'],'Sky','పైన ఉండేది','m'],[['స','ము','ద్రం'],'Very big salty water','చాలా పెద్ద ఉప్పు నీరు','m'],[['వి','మా','నం'],'Flies in the sky','ఆకాశంలో ఎగురుతుంది','m'],
[['తె','లం','గా','ణ'],'Our state','మన రాష్ట్రం','h'],[['పా','ఠ','శా','ల'],'Where we learn','నేర్చుకునే చోటు','h'],[['గ్రం','థా','ల','యం'],'Many books are kept here','చాలా పుస్తకాలు ఉండే చోటు','h'],[['కం','ప్యూ','ట','ర్'],'Used for work and games','పనికి, ఆటలకు వాడతాం','h'],[['ఉ','పా','ధ్యా','యు','డు'],'Teaches students','విద్యార్థులకు నేర్పిస్తారు','h'],[['సీ','తా','కో','క','చి','లు','క'],'Colourful flying insect','రంగురంగుల కీటకం','h']];
const MEM=[['🐘','Elephant','ఏనుగు'],['🐯','Tiger','పులి'],['🐒','Monkey','కోతి'],['🐄','Cow','ఆవు'],['🐟','Fish','చేప'],['🦚','Peacock','నెమలి'],['🍎','Apple','ఆపిల్'],['🥭','Mango','మామిడి'],['🍌','Banana','అరటి'],['🌸','Flower','పువ్వు'],['☀️','Sun','సూర్యుడు'],['🌙','Moon','చంద్రుడు'],['📖','Book','పుస్తకం'],['🚌','Bus','బస్సు']];
const CAT={an:['🐘🐅🐒🐄🐕🐈','Animals','జంతువులు'],bi:['🦚🦜🐔🦆🦅🦉','Birds','పక్షులు'],fr:['🍎🍌🥭🍇🍊🍉','Fruits','పండ్లు'],ve:['🥕🍆🌽🥔🧅🥦','Vegetables','కూరగాయలు'],vh:['🚌🚗🚲🚂🛵🚜','Vehicles','వాహనాలు'],sp:['⚽🏏🏸🎾🏀🏐','Sports','ఆటలు'],sc:['📖✏️🎒📏📐🖊️','School things','బడి వస్తువులు'],we:['☀️🌧️⛅❄️🌈⚡','Weather','వాతావరణం']};
const em=s=>s.match(/\p{Extended_Pictographic}\uFE0F?/gu)||[];
const SIM=[['fr','ve'],['an','bi'],['sc','sp'],['vh','sp']];
// ---------- state
let D={xp:0,coins:0,best:{},done:{},days:{},log:[],v:1},ov=null,stack=[],closing=false,G=null;
function load(){try{const r=localStorage.getItem(KEY);D=Object.assign({xp:0,coins:0,best:{},done:{},days:{},log:[],v:1},r?JSON.parse(r):{})}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(D))}catch(e){}}
function shareToSpeed(xp,coins){try{const r=localStorage.getItem(SKEY);if(!r)return;const s=JSON.parse(r);s.xp=(s.xp||0)+xp;s.coins=(s.coins||0)+coins;localStorage.setItem(SKEY,JSON.stringify(s))}catch(e){}}
const totalStars=()=>Object.values(D.best).reduce((a,b)=>a+b,0);
const totalDone=()=>Object.values(D.done).reduce((a,b)=>a+b,0);
const css=`#pz{position:fixed;inset:0;z-index:9991;background:#0b1230;color:#f6f8ff;overflow:auto;-webkit-user-select:none;user-select:none}
#pz .w{max-width:560px;margin:0 auto;padding:12px 14px 40px}#pz h2{margin:6px 0;font-size:22px}#pz h3{margin:14px 0 6px;font-size:17px}
#pz .c{background:#202b50;border:1px solid #7ab9ff44;border-radius:16px;padding:12px;margin:10px 0}
#pz .b{background:linear-gradient(#35cbe0,#2a8fd0);color:#041024;border-radius:14px;padding:11px 14px;font-weight:800;font-size:16px;margin:5px 4px 5px 0;border:0;min-height:44px;touch-action:manipulation}
#pz .g{background:#202b50;color:#f6f8ff;border:1px solid #7ab9ff66}#pz .b[disabled]{opacity:.45}
#pz .top{display:flex;gap:8px;justify-content:space-between}#pz .sm{font-size:13px;opacity:.85}
#pz .grid{display:grid;gap:8px}#pz .g2{grid-template-columns:1fr 1fr}
#pz .k{background:#0f1633;border-radius:12px;padding:10px;text-align:center}#pz .k b{display:block;font-size:20px;color:#35cbe0}
#pz .tile{background:#0f1633;border:2px solid #7ab9ff66;color:#fff;border-radius:12px;min-width:46px;min-height:50px;font-size:22px;font-weight:800;margin:4px;padding:6px 10px;touch-action:manipulation}
#pz .pzfb{display:inline-block;padding:8px 16px;border-radius:14px;font-weight:800;font-size:16px;animation:pzpop .35s ease}#pz .pzfb.ok{color:#eafff3;background:linear-gradient(135deg,#00c853,#00e5ff);box-shadow:0 0 14px #00e676cc,0 0 30px #00e5ff88}#pz .pzfb.no{color:#fff0f3;background:linear-gradient(135deg,#ff1744,#d500f9);box-shadow:0 0 14px #ff1744cc,0 0 28px #d500f988}#pz .slot.good{border-color:#00e676!important;color:#eafff3;box-shadow:0 0 12px #00e676cc;background:#06301f}#pz .slot.bad{border-color:#ff1744!important;box-shadow:0 0 12px #ff1744cc;background:#3a0a14}@keyframes pzpop{0%{transform:scale(.6);opacity:0}100%{transform:scale(1);opacity:1}}#pz .tile.on{background:#35cbe0;color:#041024}#pz .tile.ok{background:#14532d}#pz .tile.no{background:#7f1d1d}
#pz .slot{display:inline-block;min-width:44px;min-height:50px;border-bottom:3px solid #35cbe0;margin:4px;font-size:24px;font-weight:800;text-align:center;line-height:50px;color:#f6f8ff}
#pz .card{aspect-ratio:1;border-radius:12px;background:linear-gradient(135deg,#7c3aed,#db2777);display:flex;align-items:center;justify-content:center;font-size:28px;color:#fff;border:2px solid #ffffff55;touch-action:manipulation;text-align:center;font-weight:800;padding:2px}
#pz .card.up{background:#fffde7;color:#0b1230;font-size:15px}#pz .card.up.em{font-size:34px}#pz .card.done{background:#14532d;color:#fff;opacity:.85}
#pz .sl{aspect-ratio:1;border-radius:10px;background:linear-gradient(135deg,#35cbe0,#7c3aed);color:#fff;font-size:26px;font-weight:900;display:flex;align-items:center;justify-content:center;border:0;touch-action:manipulation}#pz .sl.hole{background:#0f1633;border:2px dashed #7ab9ff44}
#pz .opt{display:block;width:100%;background:#0f1633;color:#fff;border:1px solid #7ab9ff55;border-radius:12px;padding:12px;margin:6px 0;font-size:20px;font-weight:800;min-height:48px;touch-action:manipulation}#pz .opt.ok{background:#14532d}#pz .opt.no{background:#7f1d1d}
#pz .big{font-size:48px;text-align:center;padding:6px}#pz .stars{font-size:34px;text-align:center;letter-spacing:6px}`;
const PAL=['#35cbe0','#ffd166','#7cff8a','#ff7ad9','#ff9f5a','#c4a5ff'];
function render(h){h=h.replace(/\p{Extended_Pictographic}\uFE0F?/gu,()=>'<svg aria-hidden="true" width="18" height="18" viewBox="0 0 18 18" style="vertical-align:middle"><circle cx="9" cy="9" r="6" fill="none" stroke="currentColor"/><circle cx="9" cy="9" r="2" fill="currentColor"/></svg>');ov.innerHTML='<div class="w">'+h+'</div>';ov.scrollTop=0;let i=0;ov.querySelectorAll('h2,h3,.c>b:first-child').forEach(e=>{e.style.color=PAL[i++%PAL.length]})}
function go(fn,a){stack.push([fn,a]);fn(a)}
function onPop(){if(!ov)return;G=null;if(stack.length>1){stack.pop();try{history.pushState({pz:1},'','#puzzles')}catch(e){}const t=stack[stack.length-1];t[0](t[1])}else kill()}
function kill(){if(ov){ov.remove();ov=null}window.removeEventListener('popstate',onPop);stack=[];closing=false;G=null}
function closeAll(){if(!ov)return;kill();try{history.back()}catch(e){}}
const HOW={scr:['అక్షరాలను సరైన క్రమంలో నొక్కి పదం తయారు చేయండి. తప్పయితే ↩ నొక్కండి.','Tap the letters in the right order to make the word. Use Undo to fix a mistake.'],mem:['రెండు కార్డులను తిప్పండి. జతగా ఉంటే ఉంటాయి. అన్ని జతలను కనుక్కోండి.','Flip two cards. If they match they stay. Find all the pairs.'],num:['ప్రశ్న చదివి సరైన జవాబును నొక్కండి.','Read the question and tap the correct answer.'],odd:['మిగతా వాటికంటే భిన్నమైనదాన్ని నొక్కండి.','Tap the one that does not belong with the others.'],sld:['ఖాళీ పక్కన ఉన్న టైల్‌ను నొక్కితే అది ఖాళీలోకి జరుగుతుంది. 1,2,3… క్రమంలో అమర్చండి, ఖాళీ చివర ఉండాలి.','Tap a tile next to the blank to slide it in. Arrange 1, 2, 3… in order with the blank last.']};
const top=()=>`<div class="top"><button class="b g" data-a="back">← ${L('వెనుకకు','Back')}</button><button class="b g" data-a="close">✕</button></div>${G&&HOW[G.g]?`<div class="sm" style="padding:2px 4px 6px">❓ <b>${L('ఎలా ఆడాలి','How to play')}:</b> ${L(HOW[G.g][0],HOW[G.g][1])}</div>`:''}`;
function click(e){const b=e.target.closest('[data-a]');if(!b||b.disabled)return;const a=b.dataset.a,v=b.dataset.v;if(A[a])A[a](v,b)}
// ---------- home
function nextPick(){let best=null;for(const g of GAMES)for(const d of DIFF){const k=g[0]+d[0];const bs=D.best[k]||0;if(bs<3){const sc=(D.done[k]||0)*10+DIFF.findIndex(x=>x[0]===d[0]);if(!best||sc<best.sc)best={g:g[0],d:d[0],sc}}}return best||{g:'scr',d:'e'}}
function home(){const np=nextPick();let h=top()+`<h2>🧩 ${L('పజిల్స్','Puzzles')}</h2><div class="grid g2"><div class="k"><b>⭐ ${totalStars()}</b>${L('నక్షత్రాలు','Stars')}</div><div class="k"><b>${D.xp} XP · ${D.coins}🪙</b>${L('పాయింట్లు','Points')}</div></div>`;
h+=`<div class="c" style="border-color:#7cff8a"><b>👉 ${L('తరువాత ఆడండి','Play next')}</b><p style="margin:6px 0">${gname(np.g)} · ${dname(np.d)}</p><button class="b" data-a="start" data-v="${np.g}:${np.d}">▶ ${L('ఆడండి','Play')}</button></div>`;
GAMES.forEach(g=>{h+=`<div class="c"><b>${g[1]} ${L(g[2],g[3])}</b><div style="margin-top:6px">${DIFF.map(d=>{const bs=D.best[g[0]+d[0]]||0;return`<button class="b g" data-a="start" data-v="${g[0]}:${d[0]}">${d[1]} ${L(d[2],d[3])}<br><span class="sm">${'⭐'.repeat(bs)||'☆'}</span></button>`}).join('')}</div></div>`});
h+=`<button class="b g" data-a="par">👪 ${L('తల్లిదండ్రుల వీక్షణ','Parent view')}</button>`;render(h)}
function parScr(){const g=GAMES.map(x=>{const n=DIFF.reduce((a,d)=>a+(D.done[x[0]+d[0]]||0),0);const st=DIFF.reduce((a,d)=>a+(D.best[x[0]+d[0]]||0),0);return`<tr><td>${x[1]} ${L(x[2],x[3])}</td><td>${n}</td><td>${st}/9⭐</td></tr>`}).join('');const last=D.log.slice(-5).reverse().map(l=>`<p class="sm">${l.d}: ${E(gname(l.g))} · ${dname(l.f)} · ${'⭐'.repeat(l.s)}</p>`).join('')||`<p class="sm">${L('ఇంకా ఆడలేదు','No puzzles played yet')}</p>`;
render(top()+`<h2>👪 ${L('తల్లిదండ్రుల వీక్షణ','Parent view')}</h2><div class="grid g2"><div class="k"><b>${totalDone()}</b>${L('పూర్తయిన పజిల్స్','Puzzles completed')}</div><div class="k"><b>${Object.keys(D.days).length}</b>${L('ఆడిన రోజులు','Days played')}</div><div class="k"><b>⭐ ${totalStars()}</b>${L('నక్షత్రాలు','Stars')}</div><div class="k"><b>${D.xp}</b>XP</div></div><div class="c"><table style="width:100%;font-size:14px"><tr class="sm"><td>${L('ఆట','Game')}</td><td>${L('పూర్తి','Done')}</td><td>${L('ఉత్తమ','Best')}</td></tr>${g}</table></div><div class="c"><b>🧪 ${L('ఇటీవలివి','Recent')}</b>${last}</div><p class="sm">${L('పజిల్స్ ఆలోచనా శక్తిని, పదజాలాన్ని, లెక్కలను పెంచుతాయి.','Puzzles build thinking, vocabulary and number skills.')}</p>`)}
// ---------- finish
function finish(stars,info){const g=G.g,d=G.d,k=g+d;D.done[k]=(D.done[k]||0)+1;D.best[k]=Math.max(D.best[k]||0,stars);D.days[today()]=1;const xp=stars*5+5,coins=stars;D.xp+=xp;D.coins+=coins;D.log.push({d:today(),g,f:d,s:stars});D.log=D.log.slice(-60);save();shareToSpeed(xp,coins);
const next=g+':'+d;const ng=GAMES[(GAMES.findIndex(x=>x[0]===g)+1)%GAMES.length][0];
const nd=stars===3&&d!=='h'?DIFF[DIFF.findIndex(x=>x[0]===d)+1][0]:d;
render(top()+`<h2>🎉 ${L('పూర్తి!','Well done!')}</h2><div class="stars">${'⭐'.repeat(stars)}${'☆'.repeat(3-stars)}</div><div class="c"><p>${info||''}</p><p>+${xp} XP · +${coins} 🪙</p></div>${stars===3&&d!=='h'?`<button class="b" data-a="start" data-v="${g}:${nd}">⬆ ${L('తరువాత స్థాయి','Next level')}: ${dname(nd)}</button>`:''}<button class="b ${stars===3&&d!=='h'?'g':''}" data-a="start" data-v="${next}">▶ ${L('తరువాత పజిల్','Next puzzle')}</button><button class="b g" data-a="start" data-v="${ng}:${d}">➡ ${L('తరువాత ఆట','Next game')}: ${E(gname(ng))}</button><button class="b g" data-a="home">🏠 ${L('పజిల్స్ హోమ్','Puzzles home')}</button>`)}
// ---------- 1 scramble
function scr(){const te=G.lang==='te';const pool=te?WTE:WEN;let list=pool.filter(w=>w[te?3:3]===G.d);const set=shuf(list).slice(0,6);G.set=set;G.i=0;G.wrong=0;G.hints=0;G.ok=0;scrRound()}
function scrRound(){const te=G.lang==='te';const w=G.set[G.i];const units=te?w[0]:w[0].split('');G.units=units;G.ans=[];let tiles=shuf(units.map((u,i)=>({u,i})));let tries=0;while(tiles.map(t=>t.u).join('')===units.join('')&&tries++<5)tiles=shuf(tiles);G.tiles=tiles;scrDraw()}
function scrDraw(){const te=G.lang==='te';const w=G.set[G.i];const hint=te?L(w[2],w[1]):L(w[2],w[1]);const used=G.ans.map(a=>a.i);
render(top()+`<div class="sm">${gname('scr')} · ${dname(G.d)} · ${G.i+1}/${G.set.length}</div><div class="c"><button class="b g" data-a="lang">🌐 ${G.lang==='te'?'తెలుగు → English':'English → తెలుగు'}</button><p>💡 ${E(G.hintOn?hint:L('సూచన కావాలంటే నొక్కండి','Tap the lightbulb for a hint'))}</p><button class="b g" data-a="sound" aria-pressed="${tapSound}">${tapSound?L('శబ్దం ON','Sound ON'):L('శబ్దం OFF','Sound OFF')}</button><button class="b g" data-a="hint">💡 ${L('సూచన','Hint')}</button></div><p class="sm" style="text-align:center">${L('మీ సమాధానం','Your answer')}</p><div style="text-align:center;min-height:62px">${G.units.map((_,k)=>`<span class="slot">${G.ans[k]?E(G.ans[k].u):''}</span>`).join('')}</div><p class="sm" style="text-align:center">${L('కలిపిన అక్షరాలు - నొక్కి పదం చేయండి','Mixed tiles - tap to make the word')}</p><div style="text-align:center">${G.tiles.map(t=>`<button class="tile ${used.includes(t.i)?'on':''}" data-a="stile" data-v="${t.i}" ${used.includes(t.i)?'disabled':''}>${E(t.u)}</button>`).join('')}</div><div style="text-align:center"><button class="b g" data-a="sundo">⌫ ${L('వెనక్కి','Undo')}</button><button class="b" data-a="scheck" ${G.ans.length===G.units.length?'':'disabled'}>✔ ${L('సరిచూడు','Check')}</button></div><div class="sm" id="pzm" style="text-align:center;min-height:20px"></div>`)}
// ---------- 2 memory
function mem(){const n={e:3,m:6,h:8}[G.d];const cols=n===3?3:4;const pick=shuf(MEM).slice(0,n);let cards=[];pick.forEach((p,i)=>{cards.push({id:i,t:'e',x:p[0]});cards.push({id:i,t:'n',x:G.lang==='te'?p[2]:p[1]})});G.cards=shuf(cards);G.cols=cols;G.open=[];G.found=0;G.moves=0;G.n=n;G.lock=false;memDraw()}
function memDraw(){render(top()+`<div class="sm">${gname('mem')} · ${dname(G.d)}</div><div class="c" style="text-align:center"><button class="b g" data-a="lang">🌐 ${G.lang==='te'?'తెలుగు → English':'English → తెలుగు'}</button> ${L('ఎత్తులు','Moves')}: <b id="pzmv">${G.moves}</b> · ${L('జంటలు','Pairs')}: <b id="pzpr">${G.found}/${G.n}</b></div><div class="grid" style="grid-template-columns:repeat(${G.cols},1fr)">${G.cards.map((c,i)=>`<button class="card" data-a="mcard" data-v="${i}" id="pzc${i}">❓</button>`).join('')}</div><p class="sm" style="text-align:center">${L('ఒక బొమ్మను, దాని పేరును జతచేయండి','Match each picture with its name')}</p>`)}
// ---------- 3 number
function numQ(d){const r=n=>1+R(n);let q,a,w;
if(d==='e'){const x=r(15),y=r(10);if(R(2)){q=x+' + '+y+' = ?';a=x+y;w=q.replace('?',a)}else{const X=x+y;q=X+' − '+y+' = ?';a=x;w=X+' − '+y+' = '+a}}
else if(d==='m'){const t=R(3);if(t===0){const s=r(20),st=2+R(8);q=[s,s+st,s+2*st,s+3*st].join(', ')+', ?';a=s+4*st;w=L('ప్రతిసారీ +'+st,'Add '+st+' each time')+': '+(s+3*st)+' + '+st+' = '+a}else if(t===1){const x=2+R(9),y=2+R(9);q=x+' × '+y+' = ?';a=x*y;w=q.replace('?',a)}else{const x=r(30),y=r(30);q=x+' + ? = '+(x+y);a=y;w=(x+y)+' − '+x+' = '+y}}
else{const t=R(3);if(t===0){const x=2+R(9),y=2+R(9),z=r(20);q='('+x+' × '+y+') + '+z+' = ?';a=x*y+z;w=x+' × '+y+' = '+(x*y)+', + '+z+' = '+a}else if(t===1){const y=2+R(8),a0=2+R(9);q=(y*a0)+' ÷ '+y+' = ?';a=a0;w=y+' × '+a0+' = '+(y*a0)}else{const s=r(10),st=2+R(5);q=[s,s+st,s+3*st,s+6*st,s+10*st].join(', ')+', ?';a=s+15*st;w=L('తేడా 1,2,3.. రెట్టింపు: ','Gaps grow: ')+'+'+(5*st)+' → '+a}}
let opts=new Set([a]);while(opts.size<4){const v=a+(R(2)?1:-1)*(1+R(Math.max(3,Math.round(a/5))));if(v>=0&&v!==a)opts.add(v)}
return{q,a,w,o:shuf([...opts])}}
function num(){G.qs=Array.from({length:8},()=>numQ(G.d));G.i=0;G.ok=0;numDraw()}
function numDraw(){const q=G.qs[G.i];render(top()+`<div class="sm">${gname('num')} · ${dname(G.d)} · ${G.i+1}/${G.qs.length}</div><div class="c"><div class="big">${E(q.q)}</div></div>${q.o.map(o=>`<button class="opt" data-a="nans" data-v="${o}">${o}</button>`).join('')}<div class="sm" id="pzm" style="min-height:40px"></div>`)}
// ---------- 4 odd
function oddQ(d){let a,b;if(d==='h'){[a,b]=shuf(SIM)[0];if(R(2))[a,b]=[b,a]}else{const k=Object.keys(CAT);a=k[R(k.length)];do{b=k[R(k.length)]}while(b===a||SIM.some(s=>s.includes(a)&&s.includes(b)))}
const n=d==='e'?3:4;const A1=shuf(em(CAT[a][0])).slice(0,n),B1=shuf(em(CAT[b][0]))[0];const items=shuf([...A1.map(x=>({x,odd:0})),{x:B1,odd:1}]);return{items,a,b}}
function odd(){G.qs=Array.from({length:8},()=>oddQ(G.d));G.i=0;G.ok=0;oddDraw()}
function oddDraw(){const q=G.qs[G.i];render(top()+`<div class="sm">${gname('odd')} · ${dname(G.d)} · ${G.i+1}/${G.qs.length}</div><div class="c"><b>${L('వేరైనది ఏది?','Which one is different?')}</b></div><div class="grid g2">${q.items.map((it,k)=>`<button class="opt big" style="font-size:44px" data-a="oans" data-v="${k}">${it.x}</button>`).join('')}</div><div class="sm" id="pzm" style="min-height:40px"></div>`)}
// ---------- 5 sliding
function sld(){const n=G.d==='h'?4:3;const moves=G.d==='e'?14:G.d==='m'?40:70;let b=[...Array(n*n).keys()].map(x=>x+1);b[n*n-1]=0;let blank=n*n-1,prev=-1;for(let k=0;k<moves;k++){const r=Math.floor(blank/n),c=blank%n;const nb=[];if(r>0)nb.push(blank-n);if(r<n-1)nb.push(blank+n);if(c>0)nb.push(blank-1);if(c<n-1)nb.push(blank+1);const ch=nb.filter(x=>x!==prev);const t=ch[R(ch.length)];b[blank]=b[t];b[t]=0;prev=blank;blank=t}
if(b.every((v,i)=>v===(i+1)%(n*n)))return sld();G.n=n;G.b=b;G.moves=0;G.k=moves;sldDraw()}
function sldDraw(){const n=G.n;render(top()+`<div class="sm">${gname('sld')} · ${dname(G.d)}</div><div class="c" style="text-align:center">${L('ఎత్తులు','Moves')}: <b>${G.moves}</b> · ${L('1 నుండి వరుసగా అమర్చండి','Arrange 1, 2, 3... in order')}</div><div class="grid" style="grid-template-columns:repeat(${n},1fr)">${G.b.map((v,i)=>`<button class="sl ${v?'':'hole'}" data-a="slide" data-v="${i}">${v||''}</button>`).join('')}</div><button class="b g" data-a="start" data-v="sld:${G.d}">🔀 ${L('కొత్తది','New puzzle')}</button>`)}
// ---------- actions
const A={back(){history.back()},close(){closeAll()},home(){stack.length=1;G=null;home()},par(){go(parScr)},
start(v){const[g,d]=v.split(':');const lang=(()=>{try{return S.lang==='te'?'te':'en'}catch(e){return'en'}})();G={g,d,lang};if(stack.length&&stack[stack.length-1][0]===play)stack.pop();go(play,{g,d,lang})},
lang(){G.lang=G.lang==='te'?'en':'te';play({g:G.g,d:G.d,lang:G.lang})},
sound(){tapSound=!tapSound;try{localStorage.setItem('aksharanova.puzzles.tapSound',tapSound?'on':'off')}catch(e){}scrDraw()},
hint(){G.hintOn=1;G.hints++;scrDraw()},
stile(v){const t=G.tiles.find(x=>x.i===+v);if(!t||G.ans.find(a=>a.i===t.i))return;letterTap();G.ans.push(t);scrDraw()},
sundo(){G.ans.pop();scrDraw()},
scheck(){const w=G.ans.map(a=>a.u).join(''),t=G.units.join('');const m=document.getElementById('pzm');const srt=x=>x.split('').sort().join('');const alt=G.lang!=='te'&&w!==t&&srt(w)===srt(t)&&(XW.has(w)||WEN.some(z=>z[0]===w));if(w===t||alt){G.ok++;G.hintOn=0;if(m)m.innerHTML='<span class="pzfb ok">✅ '+(alt?L('సరైనదే! ఇది కూడా సరైన పదం: ','Also a valid word: ')+E(w):L('సరైనది!','Correct!'))+'</span>';{const sl=ov.querySelectorAll('.slot');sl.forEach(x=>x.classList.add('good'))}setTimeout(()=>{if(!G)return;G.i++;if(G.i>=G.set.length){const st=G.wrong<=1&&G.hints<=2?3:G.wrong<=4?2:1;finish(st,L('సరైన పదాలు','Words solved')+': '+G.ok+'/'+G.set.length)}else scrRound()},alt?2200:1600)}else{G.wrong++;if(m)m.innerHTML='<span class="pzfb no">❌ '+L('మళ్ళీ ప్రయత్నించండి','Try again')+'</span>';ov.querySelectorAll('.slot').forEach(x=>x.classList.add('bad'));G.ans=[];setTimeout(scrDraw,900)}},
mcard(v){if(G.lock)return;const i=+v;const c=G.cards[i];if(c.f||G.open.includes(i))return;const el=document.getElementById('pzc'+i);el.className='card up'+(c.t==='e'?' em':'');el.textContent=c.x;G.open.push(i);if(G.open.length===2){G.moves++;document.getElementById('pzmv').textContent=G.moves;const[a,b]=G.open.map(x=>G.cards[x]);if(a.id===b.id&&a.t!==b.t){a.f=b.f=1;G.open.forEach(x=>document.getElementById('pzc'+x).className='card done');G.open=[];G.found++;document.getElementById('pzpr').textContent=G.found+'/'+G.n;if(G.found===G.n)setTimeout(()=>{if(!G)return;const st=G.moves<=G.n*1.6?3:G.moves<=G.n*2.6?2:1;finish(st,L('ఎత్తులు','Moves')+': '+G.moves)},600)}else{G.lock=true;const o=G.open.slice();G.open=[];setTimeout(()=>{if(!G)return;o.forEach(x=>{const e=document.getElementById('pzc'+x);if(e){e.className='card';e.textContent='❓'}});G.lock=false},800)}}},
nans(v,b){if(G.done)return;G.done=1;const q=G.qs[G.i];const ok=+v===q.a;b.classList.add(ok?'ok':'no');if(ok)G.ok++;else[...ov.querySelectorAll('.opt')].forEach(x=>{if(+x.dataset.v===q.a)x.classList.add('ok')});const m=document.getElementById('pzm');if(m)m.innerHTML=(ok?'✅ ':'❌ ')+E(q.w);const gg=G;setTimeout(()=>{if(G!==gg)return;G.done=0;G.i++;if(G.i>=G.qs.length){const st=G.ok>=7?3:G.ok>=5?2:1;finish(st,L('సరైన జవాబులు','Correct')+': '+G.ok+'/'+G.qs.length)}else numDraw()},ok?900:2200)},
oans(v,b){if(G.done)return;G.done=1;const q=G.qs[G.i];const ok=q.items[+v].odd===1;b.classList.add(ok?'ok':'no');if(ok)G.ok++;else[...ov.querySelectorAll('.opt')].forEach((x,k)=>{if(q.items[k].odd)x.classList.add('ok')});const m=document.getElementById('pzm');if(m)m.innerHTML=(ok?'✅ ':'❌ ')+L('వేరైనది: ','Odd one: ')+L(CAT[q.b][2],CAT[q.b][1])+' / '+L(CAT[q.a][2],CAT[q.a][1]);const gg=G;setTimeout(()=>{if(G!==gg)return;G.done=0;G.i++;if(G.i>=G.qs.length){const st=G.ok>=7?3:G.ok>=5?2:1;finish(st,L('సరైన జవాబులు','Correct')+': '+G.ok+'/'+G.qs.length)}else oddDraw()},ok?800:2000)},
slide(v){const i=+v,n=G.n,z=G.b.indexOf(0);const r1=Math.floor(i/n),c1=i%n,r2=Math.floor(z/n),c2=z%n;if(Math.abs(r1-r2)+Math.abs(c1-c2)!==1)return;G.b[z]=G.b[i];G.b[i]=0;G.moves++;sldDraw();if(G.b.every((x,k)=>x===(k+1)%(n*n))){const st=G.moves<=G.k*1.6?3:G.moves<=G.k*3.5?2:1;setTimeout(()=>{if(G)finish(st,L('ఎత్తులు','Moves')+': '+G.moves)},500)}}};
function play(o){G=Object.assign({},o);const f={scr,mem,num,odd,sld}[o.g];f()}
function open(){if(ov)return;load();if(!document.getElementById('pzcss')){const s=document.createElement('style');s.id='pzcss';s.textContent=css;document.head.appendChild(s)}ov=document.createElement('div');ov.id='pz';document.body.appendChild(ov);ov.addEventListener('click',click);window.addEventListener('popstate',onPop);try{history.pushState({pz:1},'','#puzzles')}catch(e){}stack=[];closing=false;go(home)}
function selfTest(){const r=[];const ck=(n,c)=>r.push((c?'ok ':'FAIL ')+n);WTE.forEach(w=>{if(w[0].join('').length<2)ck('te '+w[0],0)});for(let i=0;i<300;i++){['e','m','h'].forEach(d=>{const q=numQ(d);if(!q.o.includes(q.a)||new Set(q.o).size!==4)ck('numq '+q.q,0)})}
// verify numeric answers by re-evaluating arithmetic forms
ck('words',WEN.length>=28&&WTE.length>=20);return r}
window.PuzzleApp={open,selfTest,numQ,_state:()=>G};
})();
