(function(){'use strict';
const KEY='aksharanova.sr.v1';let P=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x==null?'':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ST;try{ST=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){ST=null}
if(!ST)ST={lang:(localStorage.getItem('akn.lang')==='en'?'en':'te'),cur:'S1',pf:{}};
const mk=n=>({name:n,runs:[],days:{},streak:{cur:0,best:0,last:''},cert:null,delayed:null,lb:{on:false,hide:true,rankOnly:false,under13:false,parent:false}});
if(!ST.pf[ST.cur])ST.pf[ST.cur]=mk('Student 1');
const me=()=>ST.pf[ST.cur];const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(ST))}catch(e){}};
const L=()=>ST.lang;
const bi=(te,en)=>`<span class="bi"><span class="te">${esc(te)}</span><span class="en">${esc(en)}</span></span>`;
const il=(te,en)=>`<span class="bi inl"><span class="te">${esc(te)}</span><span class="en">${esc(en)}</span></span>`;
const pick=(o,k)=>o[k+'_'+L()]||o[k+'_en'];
const bk=(o,k)=>bi(o[k+'_te'],o[k+'_en']);
function toast(m){const t=$('#toast');t.textContent=m;t.className='show';clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='',2600)}
// ---------- audio (Sadaltager clips only) ----------
let aIdx=null;function aud(id){const ogg=(()=>{try{return !!document.createElement('audio').canPlayType('audio/ogg; codecs=opus')}catch(e){return true}})();
 (aIdx||(aIdx=fetch('../learn/audio/'+(ogg?'index.json':'index_m.json')+'?v='+Date.now()).then(r=>r.ok?r.json():{}).catch(()=>({})))).then(m=>{let k=L()==='te'?id:id+'__en';if(!m[k]&&m[id]&&k!==id){k=id;toast(L()==='te'?'':'English voice coming soon - playing Telugu voice')}
 if(!m[k])return toast(L()==='te'?'వాయిస్ పాఠం త్వరలో వస్తుంది':'Voice lesson coming soon');
 const go=()=>{const s=window.__AUD&&window.__AUD[k];if(!s)return toast('Voice lesson coming soon');try{window.__a&&window.__a.pause()}catch(e){}const a=new Audio(s);window.__a=a;try{a.playbackRate=+localStorage.getItem('akn.spd')||1}catch(e){}a.onerror=()=>toast(L()==='te'?'ఈ ఫోన్‌లో ఆడియో ప్లే కాలేదు':'Audio could not play on this device');const p=a.play();if(p&&p.catch)p.catch(()=>toast('Tap Listen again'))};
 if(window.__AUD&&window.__AUD[k])return go();const e=document.createElement('script');e.src='../learn/audio/'+m[k]+'.js?v=1';e.onload=()=>{go();e.remove()};e.onerror=()=>toast('Voice lesson coming soon');document.head.appendChild(e)})}
const lis=id=>`<button class="btn o" data-aud="${id}">🔊 ${il('వినండి','Listen')}</button>`;
// ---------- scoring ----------
const TH={INTERMEDIATE:[180,70,55,0,0],ADVANCED:[250,75,70,0,70],MASTER:[350,80,82,70,80]};
function score(pass,qs,ans,secs,lang,extra){extra=extra||{};const words=extra.words||pass.word_count;const mins=Math.max(secs,1)/60;const wpm=Math.round(words/mins);
 let tot=0,got=0,dt=0,dg=0;qs.forEach((q,i)=>{tot+=q.points;const ok=ans[i]===q.answer;if(ok)got+=q.points;if(q.type==='detail'){dt++;if(ok)dg++}});
 const comp=tot?Math.round(100*got/tot):0;const acc=extra.acc!=null?extra.acc:(dt?Math.round(100*dg/dt):comp);
 let ret=extra.ret,retEst=false;if(ret==null){ret=Math.round(comp*.85);retEst=true}
 const tgt=lang==='te'?300:500;let flag='';let valid=true;let spd=Math.min(100,100*wpm/tgt);
 if(wpm>900&&!extra.paced){flag='toofast';valid=false;spd=0}
 if(extra.ansSecs!=null&&extra.ansSecs<5){flag='rushed';valid=false}
 let eff=.3*spd+.35*comp+.15*acc+.2*ret;if(comp<50)eff=Math.min(eff,35);else if(comp<60)eff=Math.min(eff,50);else if(comp<70)eff=Math.min(eff,65);eff=Math.round(eff);
 const mem=extra.mem!=null?extra.mem:Math.round(.5*comp+.5*ret);const sc=lang==='te'?.6:1;
 let rating='BEGINNER';for(const k of['INTERMEDIATE','ADVANCED','MASTER']){const t=TH[k];if(wpm>=t[0]*sc&&comp>=t[1]&&eff>=t[2]&&ret>=t[3]&&acc>=t[4])rating=k}
 return{wpm,comp,acc,ret,retEst,mem,eff,effwpm:Math.round(wpm*comp/100),time:Math.round(secs),valid,flag,rating,words}}
const tip=r=>{const T=P.ui.result_tips;let t;if(r.flag==='toofast'||(r.wpm>=250&&r.comp<70))t=T[2];else if(r.comp<60)t=T[0];else if(r.comp>=80&&r.wpm>=(r.lang==='te'?180:300))t=T[3];else if(r.comp>=80)t=T[1];else return['సమతుల్యంగా చదువుతున్నారు. కొనసాగించండి.','Balanced reading. Keep practising.'];return[t.te,t.en]};
// ---------- helpers ----------
const pas=id=>P.passages.find(p=>p.id===id);const dayDef=n=>P.daily_challenges[n-1];
const doneN=()=>Object.values(me().days).filter(d=>d.done).length;
const today=()=>new Date().toISOString().slice(0,10);
function markDay(n){const p=me();p.days[n]={done:true,ts:Date.now()};const t=today(),s=p.streak;if(s.last!==t){const y=new Date(Date.now()-864e5).toISOString().slice(0,10);s.cur=(s.last===y)?s.cur+1:1;s.last=t;s.best=Math.max(s.best,s.cur)}save()}
const validRuns=()=>me().runs.filter(r=>r.valid&&!r.paced);
const lastRun=()=>me().runs[me().runs.length-1];
// ---------- router ----------
const app=$('#app');let tmr=null;
function go(h){if(location.hash==='#'+h)route();else location.hash='#'+h}
function back(){if(history.length>1)history.back();else location.href='../'}
window.addEventListener('hashchange',route);
function shell(title,body,home){clearInterval(tmr);document.body.className='l-'+L();app.innerHTML=`<div class="top"><button class="ib" id="bk" aria-label="Back">‹</button><div class="tt">${title}</div><button class="ib" id="lg">${L()==='te'?'EN':'తె'}</button></div><main>${body}</main>`;$('#bk').onclick=()=>{if(!location.hash||location.hash==='#home')location.href='../';else back()};$('#lg').onclick=()=>{ST.lang=L()==='te'?'en':'te';save();route()};$$('[data-aud]').forEach(b=>b.onclick=()=>aud(b.dataset.aud));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));window.scrollTo(0,0)}
function route(){if(!P)return;const h=(location.hash||'#home').slice(1).split('/');const v=h[0];({home,level:()=>level(h[1]),lesson:()=>lesson(h[1]),day:()=>dayView(+h[1]),dash,lb,refs,cert,practice,pos:positioning,run:()=>startRun(h[1])}[v]||home)()}
// ---------- home ----------
function home(){const p=me(),n=doneN();const nxt=[...Array(14).keys()].map(i=>i+1).find(i=>!p.days[i]&&true)||14;
 shell(bi('స్పీడ్ రీడింగ్ ఛాలెంజ్','Speed Reading Challenge'),`<div class="card o" style="text-align:center"><div style="font-size:12px;letter-spacing:3px;color:#38bdf8">${esc(P.ui.tagline_en)}</div><h1>${bk(P.ui,'course_title')}</h1><div class="bi"><span class="te">${esc(P.ui.tagline_te)}</span><span class="en">${esc(P.ui.tagline_en)}</span></div></div>
 <div class="card"><div class="bar"><i style="width:${Math.round(n/14*100)}%"></i></div><div class="stat"><div class="st"><b>${n}/14</b><span>${il('పూర్తయిన ఛాలెంజ్‌లు','Challenges done')}</span></div><div class="st"><b>${p.streak.cur}</b><span>${il('రోజుల స్ట్రీక్','Day streak')}</span></div><div class="st"><b>${(validRuns().slice(-1)[0]||{}).wpm||'-'}</b><span>${il('ప్రస్తుత WPM','Current WPM')}</span></div></div></div>
 <div class="lang"><button class="${L()==='te'?'on':''}" id="lt">తెలుగు</button><button class="${L()==='en'?'on':''}" id="le">English</button></div>
 <button class="btn o" data-go="day/${nxt}">▶ ${il('ఈ రోజు ఛాలెంజ్','Today\'s challenge')}: ${il('రోజు','Day')} ${nxt}</button>${lis('SR_INTRO')}
 <div class="card"><b>${il('విద్యార్థి ప్రవాహం','Student flow')}</b><div style="font-size:12px;opacity:.9">Learn › Watch › Practice › Challenge › Quiz › Score › Progress › Next Level</div></div>
 <h3>${il('4 స్థాయిలు','4 levels')}</h3>${['BEGINNER','INTERMEDIATE','ADVANCED','MASTER'].map((k,i)=>{const v=P.ui.levels[k];return`<button class="lv" style="--c:${['#38bdf8','#a78bfa','#fb923c','#f472b6'][i]}" data-go="level/${k}"><span class="n">${i+1}</span><span><b>${bi(v.te,k)}</b><span style="font-size:12px;opacity:.85">${bi(v.desc_te,v.desc_en)}</span><span style="font-size:11px;opacity:.7">${il('రోజులు','Days')} ${v.days[0]}-${v.days[v.days.length-1]}</span></span></button>`}).join('')}
 <h3>${il('14 రోజుల ఛాలెంజ్','14-day challenge')}</h3><div class="days">${[...Array(14).keys()].map(i=>`<div class="dot ${p.days[i+1]?'on':''} ${i+1===nxt?'cur':''}" data-go="day/${i+1}">${i+1}</div>`).join('')}</div>
 <div class="row2"><button class="btn g" data-go="dash">📊 ${il('ప్రగతి','Progress')}</button><button class="btn g" data-go="lb">🏆 ${il('లీడర్‌బోర్డ్','Leaderboard')}</button><button class="btn g" data-go="practice">🎯 ${il('ప్రాక్టీస్','Practice')}</button><button class="btn g" data-go="refs">📚 ${il('సూచనలు & పరిశోధన','References')}</button><button class="btn g" data-go="cert">🎓 ${il('సర్టిఫికెట్','Certificate')}</button><button class="btn g" data-go="pos">ℹ️ ${il('వేగం గురించి','About speed')}</button></div>`);
 $('#lt').onclick=()=>{ST.lang='te';save();route()};$('#le').onclick=()=>{ST.lang='en';save();route()}}
function positioning(){const p=P.positioning;shell(bi('వేగం గురించి నిజం','The honest truth about speed'),`<div class="card o"><h2>${bi(p.headline_te,p.headline_en)}</h2><p>${bi(p.body_te,p.body_en)}</p></div>${lis('SR_POSITIONING')}`)}
function level(k){const v=P.ui.levels[k];shell(bi(v.te,k),`<div class="card"><p>${bi(v.desc_te,v.desc_en)}</p></div>${lis('SR_LEVEL_'+k)}<h3>${il('పాఠాలు','Lessons')}</h3>${v.lessons.map(id=>{const l=P.lessons.find(x=>x.id===id);return`<button class="lv" style="--c:#38bdf8" data-go="lesson/${id}"><span class="n">${id}</span><span><b>${bk(l,'title')}</b></span></button>`}).join('')}<h3>${il('ఛాలెంజ్‌లు','Challenges')}</h3>${v.days.map(d=>{const c=dayDef(d);return`<button class="lv" style="--c:#fb923c" data-go="day/${d}"><span class="n">${d}</span><span><b>${bk(c,'title')}</b>${me().days[d]?' ✅':''}</span></button>`}).join('')}`)}
const eyes=()=>`<div class="eyes" aria-label="eye movement demo"><i style="top:24px"></i><i style="top:64px"></i><b></b></div>`;
function lesson(id){const l=P.lessons.find(x=>x.id===id);const dn=P.daily_challenges.find(d=>d.lesson===id);
 shell(bk(l,'title'),`${lis('SR_L_'+id)}<div class="card"><h3>📖 ${il('నేర్చుకోండి','Learn')}</h3><p>${bk(l,'exp')}</p></div><div class="card p"><h3>👁️ ${il('చూడండి','Watch')}</h3>${eyes()}<p>${bk(l,'watch')}</p></div><div class="card"><h3>🧭 ${il('చేయండి','Steps')}</h3><ol style="padding-left:18px">${l.steps_en.map((s,i)=>`<li>${bi(l.steps_te[i],s)}</li>`).join('')}</ol>${lis('SR_L_'+id+'_STEPS')}</div><div class="card o"><h3>✍️ ${il('ప్రాక్టీస్','Practice')}</h3><p>${bk(l,'practice')}</p></div>${dn?`<button class="btn o" data-go="day/${dn.day}">▶ ${il('ఛాలెంజ్','Challenge')} ${il('రోజు','Day')} ${dn.day}</button>`:''}<button class="btn g" data-go="practice">🎯 ${il('ఫ్రీ ప్రాక్టీస్','Free practice')}</button>`)}
function dayView(n){if(!(n>=1&&n<=14))return home();const c=dayDef(n);const done=me().days[n];const lid=c.lesson&&c.lesson!=='-'?c.lesson:null;const due=n===11&&me().delayed&&Date.now()-me().delayed.ts>=12*36e5&&!me().delayed.done;
 shell(il('రోజు','Day')+' '+n+': '+bk(c,'title'),`<div class="card o">${done?'<div class="flag">✅ '+il('ఈ ఛాలెంజ్ పూర్తయింది','Challenge completed')+'</div>':''}<p>${bk(c,'intro')}</p>${lis('SR_DAY'+String(n).padStart(2,'0')+'_INTRO')}</div><div class="card"><h3>🧭 ${il('సూచనలు','Instructions')}</h3><ol style="padding-left:18px">${c.steps_en.map((s,i)=>`<li>${bi(c.steps_te[i],s)}</li>`).join('')}</ol>${lis('SR_DAY'+String(n).padStart(2,'0')+'_STEPS')}</div><div class="card"><div style="font-size:12px"><b>${il('కొలత','Measures')}:</b> ${esc(c.metrics)}</div><div style="font-size:12px"><b>${il('పాస్ నియమం','Pass rule')}:</b> ${esc(c.pass_rule)}</div><div style="font-size:12px;opacity:.85">${bk(c,'guidance')}</div></div>${lid?`<button class="btn g" data-go="lesson/${lid}">📖 ${il('పాఠం చదవండి','Read the lesson')} ${lid}</button>`:''}<button class="btn o" data-go="run/d${n}">▶ ${il('ఛాలెంజ్ మొదలుపెట్టండి','Start challenge')}</button><div class="row2">${n>1?`<button class="btn g" data-go="day/${n-1}">‹ ${il('ముందు రోజు','Previous')}</button>`:'<span></span>'}${n<14?`<button class="btn g" data-go="day/${n+1}">${il('తర్వాత రోజు','Next')} ›</button>`:''}</div>`)}
function practice(){const ps=P.passages;shell(bi('ఫ్రీ ప్రాక్టీస్','Free practice'),`<div class="card"><p>${il('ఏ పాసేజ్ అయినా చదివి స్కోర్ చూడండి. ఇవి 14 రోజుల ఛాలెంజ్‌లో లెక్కకు రావు.','Read any passage and see your score. These do not count as daily challenges.')}</p></div>${ps.map(p=>`<button class="lv" style="--c:${p.lang==='te'?'#fb923c':'#38bdf8'}" data-go="run/p${p.id}"><span class="n">${p.lang==='te'?'తె':'EN'}</span><span><b>${bk(p,'title')}</b><span style="font-size:11px;opacity:.8">${p.word_count} ${il('పదాలు','words')} · ${esc(p.level)}</span></span></button>`).join('')}`)}
// ---------- engine ----------
let E=null;
function startRun(code){const isDay=code[0]==='d';const cfg={};if(isDay){const n=+code.slice(1);const c=dayDef(n);cfg.day=n;cfg.pid=c.passage.split(',')[0];cfg.mode={2:'pace',4:'pace',5:'pace',6:'pace',3:'free',7:'skim',8:'scan'}[n]||'free';cfg.chunk={2:3,4:3,5:4,6:4}[n]||0;cfg.wpm={2:120,4:160,5:180,6:220}[n]||0;cfg.title=bk(c,'title');if(n===13)cfg.pid='A2';if(n===12)cfg.screen=true;}else{cfg.pid=code.slice(1);cfg.mode='free';cfg.title=il('ఫ్రీ ప్రాక్టీస్','Free practice');cfg.practice=true}
 const ps=pas(cfg.pid);cfg.ps=ps;
 if(cfg.day===11&&me().delayed&&!me().delayed.done&&Date.now()-me().delayed.ts>=12*36e5){return recallRun(cfg)}
 E={cfg,phase:'ready',words:ps.text.split(/\s+/).filter(Boolean),active:0,t0:0,paused:false,ps0:0,pauses:0,reached:0,regress:0,pos:0,rounds:0,taps:[]};drawEngine()}
function recallRun(cfg){const d=me().delayed;const qs=d.qs;E={cfg,phase:'recall',qs,ans:[],qi:0};drawQ()}
function wordsHTML(){return E.words.map((w,i)=>`<span class="w" data-i="${i}">${esc(w)} </span>`).join('')}
function drawEngine(){const c=E.cfg,ps=c.ps;const sk=c.mode==='skim',sc=c.mode==='scan';const kw=sc?P.skim_scan_support.scan_A2:null;
 shell(c.title,`<div class="card"><b>${bk(ps,'title')}</b> <span style="font-size:11px;opacity:.7">${ps.word_count} ${il('పదాలు','words')}</span>${c.mode==='pace'?`<div style="font-size:12px;margin-top:4px">${il('హైలైట్ వేగం','Highlighter pace')}: <button class="ib" id="sm">−</button> <b id="sv">${c.wpm}</b> WPM <button class="ib" id="sp">+</button></div>`:''}${c.mode==='free'&&c.day===3?`<div style="font-size:12px;margin-top:4px">${il('వెనక్కి వెళ్లిన సార్లు','Times you went back')}: <b id="rg">0</b> <button class="ib" id="rgb">↩</button></div>`:''}${sc?`<div class="flag">${il('ఈ పదాలను పాసేజ్‌లో వెతికి నొక్కండి','Find and tap these in the passage')}: ${kw.map(k=>`<b>${esc(k.keyword)}</b> (${esc(pick(k,'find'))})`).join(', ')}</div>`:''}${sk?`<div class="flag">${il('45 సెకన్లలో ముఖ్య ఆలోచన పట్టుకోండి','Get the main idea in 45 seconds')}</div>`:''}</div>
 <div class="live"><div><b id="lt1">0:00</b><span>${il('సమయం','Time')}</span></div><div><b id="lw">0</b><span>WPM</span></div><div><b id="lc">0/${E.words.length}</b><span>${il('పదాలు','Words')}</span></div><div><b id="lp">0%</b><span>${il('ప్రగతి','Progress')}</span></div></div><div class="bar"><i id="pb" style="width:0%"></i></div>
 <div class="rd ${ps.lang==='te'?'te':''} ${c.screen?'screen':''} blur" id="rd">${wordsHTML()}</div>
 <div class="row3"><button class="btn o" id="st">▶ START<small>${il('ప్రారంభించు','Start')}</small></button><button class="btn g" id="pa" disabled>⏸ PAUSE<small>${il('ఆపు','Pause')}</small></button><button class="btn" id="fi" disabled>✔ FINISH<small>${il('పూర్తి','Finish')}</small></button></div>${lis('SR_ENG_READY')}`);
 $('#st').onclick=startRead;$('#pa').onclick=pauseRead;$('#fi').onclick=finishRead;
 if($('#sm')){$('#sm').onclick=()=>{c.wpm=Math.max(60,c.wpm-20);$('#sv').textContent=c.wpm};$('#sp').onclick=()=>{c.wpm=Math.min(500,c.wpm+20);$('#sv').textContent=c.wpm}}
 if($('#rgb'))$('#rgb').onclick=()=>{if(E.phase==='read'&&!E.paused){E.regress++;$('#rg').textContent=E.regress}};
 $('#rd').addEventListener('scroll',reachScroll);$$('#rd .w').forEach(s=>s.onclick=()=>{if(E.phase!=='read'||E.paused)return;const i=+s.dataset.i;if(c.mode==='scan'){scanTap(i,s);return}E.reached=Math.max(E.reached,i+1);upd()})}
function actSecs(){if(!E.t0)return 0;const now=Date.now();return(E.paused?E.ps0-E.t0-E.active:now-E.t0-E.active)/1000}
function reachScroll(){if(E.phase!=='read'||E.cfg.mode==='pace')return;const rd=$('#rd');const sp=$$('#rd .w');const bot=rd.scrollTop+rd.clientHeight+2;let lo=0,hi=sp.length-1,r=0;while(lo<=hi){const m=(lo+hi)>>1;if(sp[m].offsetTop+sp[m].offsetHeight<=bot){r=m+1;lo=m+1}else hi=m-1}E.reached=Math.max(E.reached,r);upd()}
function upd(){if(!E||E.phase!=='read')return;const s=Math.max(actSecs(),0);const m=Math.floor(s/60),ss=Math.floor(s%60);$('#lt1').textContent=m+':'+String(ss).padStart(2,'0');const w=E.reached;$('#lc').textContent=w+'/'+E.words.length;const wpm=s>2?Math.round(w/(s/60)):0;$('#lw').textContent=wpm;const pc=Math.min(100,Math.round(100*w/E.words.length));$('#lp').textContent=pc+'%';$('#pb').style.width=pc+'%'}
function startRead(){const c=E.cfg;E.phase='read';E.t0=Date.now();E.active=0;$('#rd').classList.remove('blur');$('#st').disabled=true;$('#pa').disabled=false;$('#fi').disabled=false;
 if(c.mode==='skim'){E.skimEnd=Date.now()+45000}
 if(c.mode==='free'||c.mode==='skim'||c.mode==='scan'){E.reached=0;reachScroll();if($('#rd').scrollHeight<=$('#rd').clientHeight+4)E.reached=E.words.length}
 tmr=setInterval(()=>{if(E.paused)return;if(c.mode==='pace')pacerStep();upd();if(c.mode==='skim'&&Date.now()>E.skimEnd){finishRead()}},c.mode==='pace'?Math.max(120,60000/c.wpm*c.chunk/1):250);
 if(c.mode==='pace'){E.pos=0;hl()}}
function hl(){const c=E.cfg;$$('#rd .hl').forEach(e=>e.classList.remove('hl'));let a=E.pos,b=Math.min(E.words.length,a+c.chunk);if(c.day===5){while(b<E.words.length&&!/[,.;:!?]$/.test(E.words[b-1])&&b-a<7)b++}E.pend=b;for(let i=a;i<b;i++){const s=$('#rd .w[data-i="'+i+'"]');if(s)s.classList.add('hl')}const f=$('#rd .w[data-i="'+a+'"]');if(f)f.scrollIntoView({block:'center'});E.reached=Math.max(E.reached,b)}
function pacerStep(){const c=E.cfg;E.pos=E.pend;if(E.pos>=E.words.length){if(c.day===2&&actSecs()<180){E.pos=0;E.rounds++;E.reached=0}else{finishRead();return}}hl()}
function pauseRead(){if(E.phase!=='read')return;const b=$('#pa');if(!E.paused){E.paused=true;E.ps0=Date.now();E.pauses++;b.innerHTML='▶ RESUME<small>'+il('కొనసాగించు','Resume')+'</small>';$('#rd').classList.add('blur')}else{E.active+=Date.now()-E.ps0;E.paused=false;b.innerHTML='⏸ PAUSE<small>'+il('ఆపు','Pause')+'</small>';$('#rd').classList.remove('blur')}}
let scanFound={};function scanTap(i,s){const kws=P.skim_scan_support.scan_A2;const w=E.words[i].toLowerCase().replace(/[^a-z0-9]/g,'');kws.forEach(k=>{if(w.indexOf(k.keyword.toLowerCase())>=0&&!scanFound[k.keyword]){scanFound[k.keyword]=1;s.classList.add('tapw');s.style.background='#bbf7d0';toast('✔ '+k.keyword)}})}
function finishRead(){if(!E||E.phase!=='read')return;clearInterval(tmr);if(E.paused){E.active+=Date.now()-E.ps0;E.paused=false}const secs=(Date.now()-E.t0-E.active)/1000;E.secs=secs;E.scan=Object.keys(scanFound).length;scanFound={};
 if(E.cfg.mode==='pace'){E.reached=E.words.length}
 const ratio=E.reached/E.words.length;E.partial=ratio<.9&&E.cfg.mode!=='pace'&&E.cfg.mode!=='skim'&&E.cfg.mode!=='scan';E.wordsUsed=E.partial?Math.max(E.reached,1):E.words.length;if(E.cfg.mode==='skim'||E.cfg.mode==='scan')E.wordsUsed=E.words.length;
 E.phase='q';E.qs=E.cfg.ps.qs.slice();
 if(E.cfg.mode==='skim'){const mi=E.qs.findIndex(q=>q.type==='main idea'||q.type==='main_idea'||/main/i.test(q.type));if(mi>0){const q=E.qs.splice(mi,1)[0];E.qs.unshift(q)}E.skimSecs=secs}
 E.ans=[];E.qi=0;E.qT=Date.now();E.ansMs=0;
 if(E.cfg.day===10){return kwStep()}
 drawQ()}
function kwStep(){shell(E.cfg.title,`<div class="card"><h3>✍️ ${il('గుర్తున్న 5 ముఖ్య పదాలు రాయండి','Write 5 key words you remember')}</h3><p style="font-size:13px">${il('పాసేజ్ చూడకుండా రాయండి.','Do not look at the passage.')}</p>${[0,1,2,3,4].map(i=>`<input class="inp kw" placeholder="${i+1}">`).join('')}</div><button class="btn o" id="kn">${il('కొనసాగించు','Continue')}</button>`);$('#kn').onclick=()=>{const set=new Set(E.words.map(w=>w.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'')).filter(w=>w.length>3));const k=$$('.kw').map(i=>i.value.trim().toLowerCase().replace(/[^\p{L}\p{N}]/gu,'')).filter(x=>x);E.kwHit=Math.min(5,k.filter(x=>set.has(x)).length);E.kwN=5;E.qT=Date.now();drawQ()}}
function drawQ(){const r=E.phase==='recall';const q=E.qs[E.qi];const n=E.qs.length;shell(E.cfg.title,`<div class="card"><div class="bar"><i style="width:${Math.round(E.qi/n*100)}%"></i></div><div style="font-size:12px;opacity:.8">${il('ప్రశ్న','Question')} ${E.qi+1}/${n}${r?' · '+il('నిన్నటి పాసేజ్','From yesterday'):''}</div><h3>${bi(q.q_te,q.q_en)}</h3>${q.options.map((o,i)=>`<button class="opt" data-i="${i}">${bi(o.te,o.en)}</button>`).join('')}</div>`);
 $$('.opt').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;E.ans[E.qi]=i;E.ansMs+=Date.now()-E.qT;$$('.opt').forEach(x=>x.disabled=true);b.classList.add(i===q.answer?'ok':'no');if(i!==q.answer)$$('.opt')[q.answer].classList.add('ok');setTimeout(()=>{E.qi++;E.qT=Date.now();if(E.qi>=n)(r?recallDone():results());else drawQ()},900)})}
function recallDone(){const d=me().delayed;let ok=0;E.qs.forEach((q,i)=>{if(E.ans[i]===q.answer)ok++});d.done=true;d.ret=Math.round(100*ok/E.qs.length);save();E.words=E.cfg.ps.text.split(/\s+/);E.phase='ready';toast(L()==='te'?'జ్ఞాపకం: '+d.ret+'%':'Recall: '+d.ret+'%');drawEngine()}
function passDay(n,r,x){const c=r.comp;switch(n){case 1:case 14:return true;case 2:return c>=60;case 3:return x.regress<3&&c>=60;case 4:return c>=65;case 5:return c>=70;case 6:{const h=Math.floor(x.qs.length/2);const f=(a,b)=>{let t=0,g=0;for(let i=a;i<b;i++){t+=x.qs[i].points;if(x.ans[i]===x.qs[i].answer)g+=x.qs[i].points}return t?100*g/t:0};return f(h,x.qs.length)>=f(0,h)-10}case 7:{const q=x.qs[0];return x.ans[0]===q.answer&&x.skimSecs<=46}case 8:return x.scan>=2;case 9:return c>=75;case 10:return(x.kwHit!=null?100*(x.kwHit/5*.5+ (c/100)*.5):c)>=60;case 11:return x.pauses<=2&&c>=70;case 12:{const prev=validRuns().filter(z=>z.day===9||z.day===1).map(z=>z.comp);const paper=prev.length?prev[prev.length-1]:70;return c>=paper-10}case 13:return r.eff>=55}return true}
function results(){const c=E.cfg,ps=c.ps;const ansSecs=E.ansMs/1000;const x={words:E.wordsUsed,ansSecs,paced:c.mode==='pace'};
 if(c.day===10&&E.kwHit!=null){const comp0=Math.round(100*E.qs.reduce((a,q,i)=>a+(E.ans[i]===q.answer?q.points:0),0)/E.qs.reduce((a,q)=>a+q.points,0));x.mem=Math.round(.5*(100*(E.kwHit/5*.5+comp0/100*.5))+.5*Math.round(comp0*.85))}
 const secs=c.mode==='skim'?E.skimSecs:E.secs;
 let dl=null;if(c.day===13){const d=me().delayed;}
 if(c.day===14){const d=me().delayed;if(d&&d.done&&d.ret!=null)x.ret=d.ret}
 const r=score(ps,E.qs,E.ans,secs,ps.lang,x);const ok=c.day?(r.valid&&passDay(c.day,r,{qs:E.qs,ans:E.ans,regress:E.regress,pauses:E.pauses,skimSecs:E.skimSecs,scan:E.scan,kwHit:E.kwHit})):null;
 const run=Object.assign({ts:Date.now(),day:c.day||0,pid:ps.id,lang:ps.lang,paced:c.mode==='pace',partial:E.partial,pass:ok,mode:c.mode},r);me().runs.push(run);
 if(c.day&&ok)markDay(c.day);if(c.day===10)me().delayed={ts:Date.now(),qs:ps.qs.slice(0,3),done:false};save();showResult(run,c,ok)}
const ring=(v,l,col)=>{const a=Math.max(0,Math.min(100,v))/100*226;return`<div style="text-align:center"><svg width="84" height="84" viewBox="0 0 84 84"><circle cx="42" cy="42" r="36" fill="none" stroke="#142257" stroke-width="8"/><circle cx="42" cy="42" r="36" fill="none" stroke="${col}" stroke-width="8" stroke-linecap="round" stroke-dasharray="${a} 226" transform="rotate(-90 42 42)"/><text x="42" y="47" text-anchor="middle" fill="#fff" font-size="16" font-weight="800">${Math.round(v)}</text></svg><div style="font-size:10px;line-height:1.1">${l}</div></div>`};
function showResult(r,c,ok){const t=tip(r);const lr=P.certificate.rating_labels[r.rating];shell(c.title,`<div class="card res o"><div class="big">${r.eff}</div><div>${il('సామర్థ్య స్కోర్','Efficiency score')} / 100</div><div style="margin:6px 0;font-weight:800">${bi(lr[1],lr[0])}</div>${ok===null?'':`<div class="flag">${ok?'✅ '+il('ఛాలెంజ్ పూర్తయింది','Challenge completed'):'↻ '+il('ఈసారి కాదు. మళ్లీ ప్రయత్నించండి.','Not this time. Try again.')}</div>`}</div>
 <div class="card" style="display:flex;justify-content:space-around;flex-wrap:wrap;gap:6px">${ring(r.comp,il('అవగాహన %','Comprehension %'),'#38bdf8')}${ring(r.acc,il('ఖచ్చితత్వం %','Accuracy %'),'#a78bfa')}${ring(r.retEst?r.ret:r.ret,il('జ్ఞాపకం %','Retention %')+(r.retEst?'*':''),'#fb923c')}</div>
 <div class="stat"><div class="st"><b>${r.wpm}</b><span>WPM</span></div><div class="st"><b>${r.effwpm}</b><span>${il('అర్థమైన పదాలు/నిమి','Understood WPM')}</span></div><div class="st"><b>${Math.floor(r.time/60)}:${String(r.time%60).padStart(2,'0')}</b><span>${il('చదివిన సమయం','Reading time')}</span></div></div>
 ${r.flag==='toofast'?`<div class="flag">⚠️ ${il('ఇది నిజమైన చదువు కంటే చాలా వేగం. ఈ ప్రయత్నం బెస్ట్‌లో లెక్కించబడదు.','Too fast to be real reading. This attempt is not counted as a best.')}</div>`:''}${r.flag==='rushed'?`<div class="flag">⚠️ ${il('జవాబులు తొందరగా ఇచ్చారు. ఈ ప్రయత్నం లెక్కలోకి రాదు.','Answers were rushed. This attempt is not counted.')}</div>`:''}${E.partial?`<div class="flag">${il('మీరు పాసేజ్‌లో 90% వరకు రాలేదు. చదివిన భాగం ఆధారంగా లెక్కించాం.','You did not reach 90% of the passage. Speed uses the words reached.')}</div>`:''}${r.retEst?`<div class="disc">* ${il('అంచనా (రేపు జ్ఞాపకశక్తి టెస్ట్ ఉంటుంది)','Estimated until a delayed recall is done')}</div>`:''}
 <div class="tip">${L()==='te'?esc(t[0]):esc(t[1])}</div>${c.day===14?'':''}
 <button class="btn o" id="nx">${c.day===14?'🎓 '+il('రిపోర్ట్ & సర్టిఫికెట్','Report & certificate'):(ok||c.practice?il('తర్వాత','Next')+' ›':'↻ '+il('మళ్లీ ప్రయత్నించండి','Try again'))}</button><button class="btn g" data-go="dash">📊 ${il('ప్రగతి','Progress')}</button>`);
 $('#nx').onclick=()=>{if(c.day===14)go('cert');else if(c.practice)go('practice');else if(ok)go('day/'+Math.min(14,c.day+1));else go('day/'+c.day)}}
// ---------- dashboard ----------
function line(rs,key,col){if(rs.length<2)return'';const W=300,H=110,mx=Math.max(100,...rs.map(r=>r[key]));const pts=rs.map((r,i)=>[10+i*(W-20)/Math.max(1,rs.length-1),H-10-(r[key]/mx)*(H-20)]);return`<polyline fill="none" stroke="${col}" stroke-width="2.5" points="${pts.map(p=>p.join(',')).join(' ')}"/>`+pts.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="${col}"/>`).join('')}
function dash(){const p=me(),vr=validRuns(),all=p.runs;const last=vr[vr.length-1]||all[all.length-1]||{};const best=Math.max(0,...vr.filter(r=>r.comp>=70).map(r=>r.wpm));const l7=vr.slice(-7);const avg=l7.length?Math.round(l7.reduce((a,r)=>a+r.wpm,0)/l7.length):0;const tot=Math.round(all.reduce((a,r)=>a+r.time,0)/60);
 const d1=all.find(r=>r.day===1),d14=[...all].reverse().find(r=>r.day===14);const A=d1||all[0],B=d14||(all.length>1?all[all.length-1]:null);
 const bars=(k,lab)=>{const a=A?A[k]:0,b=B?B[k]:0,m=Math.max(a,b,1);return`<div style="margin:8px 0"><div style="font-size:12px">${lab}</div><div style="display:flex;gap:6px;align-items:center"><div style="width:42px;font-size:10px">${il('ముందు','Before')}</div><div class="bar" style="flex:1"><i style="width:${100*a/m}%;background:#a78bfa"></i></div><b style="width:44px;text-align:right">${a}</b></div><div style="display:flex;gap:6px;align-items:center"><div style="width:42px;font-size:10px">${il('తర్వాత','After')}</div><div class="bar" style="flex:1"><i style="width:${100*b/m}%"></i></div><b style="width:44px;text-align:right">${b}</b></div></div>`};
 shell(bi('నా ప్రగతి','My progress'),`<div class="card"><b>${esc(p.name)}</b> <button class="ib" id="pn" style="height:32px;font-size:12px">✎</button>${lis('SR_DASH_INTRO')}<div class="stat" style="margin-top:8px"><div class="st"><b>${last.wpm||'-'}</b><span>${il('ప్రస్తుత WPM','Current WPM')}</span></div><div class="st"><b>${best||'-'}</b><span>${il('బెస్ట్ WPM','Best WPM')}</span></div><div class="st"><b>${avg||'-'}</b><span>${il('సగటు WPM','Average WPM')}</span></div><div class="st"><b>${last.comp!=null?last.comp+'%':'-'}</b><span>${il('అవగాహన','Comprehension')}</span></div><div class="st"><b>${last.mem!=null?last.mem+'%':'-'}</b><span>${il('జ్ఞాపకం','Memory')}</span></div><div class="st"><b>${last.acc!=null?last.acc+'%':'-'}</b><span>${il('ఖచ్చితత్వం','Accuracy')}</span></div><div class="st"><b>${last.eff!=null?last.eff:'-'}</b><span>${il('సామర్థ్య స్కోర్','Efficiency')}</span></div><div class="st"><b>${p.streak.cur}</b><span>${il('రోజుల స్ట్రీక్','Streak')} (${il('బెస్ట్','best')} ${p.streak.best})</span></div><div class="st"><b>${doneN()}/14</b><span>${il('ఛాలెంజ్‌లు','Challenges')}</span></div></div><div style="text-align:center;margin-top:8px;font-size:13px">${il('మొత్తం చదివిన సమయం','Total reading time')}: <b>${tot}</b> ${il('నిమిషాలు','min')}</div></div>
 <div class="card"><h3>${il('ముందు vs తర్వాత','Before vs After')}</h3>${A?bars('wpm','WPM')+bars('effwpm',il('అర్థమైన WPM','Understood WPM'))+bars('comp',il('అవగాహన %','Comprehension %'))+bars('mem',il('జ్ఞాపకం %','Memory %')):'<p>'+il('మొదటి టెస్ట్ తర్వాత ఇక్కడ కనిపిస్తుంది.','Appears after your first test.')+'</p>'}${A&&B&&B.wpm>A.wpm&&B.comp<=A.comp-10?`<div class="flag">${il('వేగం పెరిగింది కానీ అవగాహన తగ్గింది. కొంచెం నెమ్మదించి, ప్రివ్యూ ప్రాక్టీస్ చేయండి.','Your speed went up but understanding dropped. Slow slightly and practise previewing.')}</div>`:''}</div>
 <div class="card"><h3>${il('ప్రయత్నాల గ్రాఫ్','Progress chart')}</h3><svg viewBox="0 0 300 110" width="100%"><rect width="300" height="110" fill="#0d1a46" rx="10"/>${line(vr,'wpm','#38bdf8')}${line(vr,'eff','#fb923c')}</svg><div style="font-size:11px"><span style="color:#38bdf8">● WPM</span> &nbsp; <span style="color:#fb923c">● ${il('సామర్థ్యం','Efficiency')}</span></div></div>
 <button class="btn o" data-go="home">⚡ ${il('ఛాలెంజ్ కొనసాగించు','Continue challenge')}</button>`);
 $('#pn').onclick=()=>{const n=prompt(L()==='te'?'పేరు (ఐచ్ఛికం)':'Name (optional)',p.name);if(n!==null){p.name=n.trim().slice(0,24)||p.name;save();route()}}}
// ---------- leaderboard ----------
function lb(){const p=me(),l=p.lb;const rows=Object.keys(ST.pf).map(k=>({k,p:ST.pf[k]})).filter(o=>o.p.lb.on&&(!o.p.lb.under13||o.p.lb.parent)).map(o=>{const vr=o.p.runs.filter(r=>r.valid&&!r.paced&&r.comp>=60);const best=vr.sort((a,b)=>b.eff-a.eff)[0];return best?{k:o.k,name:o.p.name,hide:o.p.lb.hide,rankOnly:o.p.lb.rankOnly,wpm:best.wpm,comp:best.comp,eff:best.eff,n:Object.values(o.p.days).filter(d=>d.done).length}:null}).filter(Boolean).sort((a,b)=>b.eff-a.eff||b.comp-a.comp||b.n-a.n);
 const sw=(id,txt,v)=>`<label style="display:flex;gap:8px;align-items:center;margin:8px 0;font-size:14px"><input type="checkbox" id="${id}" ${v?'checked':''} style="width:20px;height:20px"> <span>${txt}</span></label>`;
 shell(bi('క్లాస్‌రూమ్ లీడర్‌బోర్డ్','Classroom leaderboard'),`<div class="card"><p>${bk(P.leaderboard,'text')}</p>${lis('SR_LEADERBOARD_INTRO')}</div><div class="card"><b>${esc(p.name)}</b>${sw('l0',il('ఈ ఫోన్ లీడర్‌బోర్డ్‌లో నన్ను చూపించు','Show me on this device\'s leaderboard'),l.on)}${sw('l1',bi(P.leaderboard.privacy_controls[1].te,P.leaderboard.privacy_controls[1].en),l.hide)}${sw('l2',bi(P.leaderboard.privacy_controls[2].te,P.leaderboard.privacy_controls[2].en),l.rankOnly)}${sw('l3',il('నా వయసు 13 లోపు','I am under 13'),l.under13)}${l.under13?sw('l4',il('తల్లిదండ్రులు అనుమతించారు','A parent allows it'),l.parent):''}<button class="btn g" id="lx">${bi(P.leaderboard.privacy_controls[3].te,P.leaderboard.privacy_controls[3].en)}</button></div>
 <div class="card"><table class="lb"><tr><th>#</th><th>${il('పేరు','Name')}</th><th>WPM</th><th>${il('అవగాహన','Comp %')}</th><th>${il('సామర్థ్యం','Eff')}</th><th>${il('ఛాలెంజ్','Done')}</th></tr>${rows.length?rows.map((o,i)=>`<tr${o.k===ST.cur?' style="color:#fb923c"':''}><td>${i+1}</td><td>${o.hide&&o.k!==ST.cur?'Reader '+String(i+1).padStart(2,'0'):esc(o.name)}</td><td>${o.rankOnly&&o.k!==ST.cur?'-':o.wpm}</td><td>${o.rankOnly&&o.k!==ST.cur?'-':o.comp}</td><td>${o.rankOnly&&o.k!==ST.cur?'-':o.eff}</td><td>${o.n}</td></tr>`).join(''):`<tr><td colspan="6">${il('ఇంకా ఎవరూ లేరు','No one yet')}</td></tr>`}</table></div>
 <div class="card"><b>${il('ఈ ఫోన్‌లో విద్యార్థులు','Students on this phone')}</b>${Object.keys(ST.pf).map(k=>`<button class="btn ${k===ST.cur?'o':'g'}" data-sw="${k}">${esc(ST.pf[k].name)}</button>`).join('')}<button class="btn g" id="np">＋ ${il('కొత్త విద్యార్థి','Add student')}</button></div><div class="card disc">${P.leaderboard.privacy_notes.map(esc).join('<br>')}<br>${il('లీడర్‌బోర్డ్ ఈ పరికరంలోనే ఉంటుంది.','The leaderboard stays on this device.')}</div>`);
 [['l0','on'],['l1','hide'],['l2','rankOnly'],['l3','under13'],['l4','parent']].forEach(([i,k])=>{const e=$('#'+i);if(e)e.onchange=()=>{l[k]=e.checked;if(k==='under13'&&!e.checked)l.parent=false;if(k==='on'&&e.checked)l.hide=true;save();route()}});
 $('#lx').onclick=()=>{if(confirm(L()==='te'?'ఈ విద్యార్థి ఎంట్రీలు తొలగించాలా?':'Delete this student\'s entries?')){p.runs=[];p.days={};p.lb.on=false;save();route()}};$$('[data-sw]').forEach(b=>b.onclick=()=>{ST.cur=b.dataset.sw;save();route()});$('#np').onclick=()=>{const n=prompt(L()==='te'?'విద్యార్థి పేరు':'Student name');if(n){const k='S'+Date.now();ST.pf[k]=mk(n.trim().slice(0,24));ST.cur=k;save();route()}}}
// ---------- references ----------
function refs(){const u=P.references.ui;shell(bk(u,'section_title'),`${lis('SR_REF_DISCLAIMER')}${P.references.cards.map(c=>`<div class="card"><div style="font-size:11px;color:#38bdf8">#${c.n}</div><h3 style="margin:2px 0">${esc(c.source)}</h3><div style="font-size:13px;font-weight:700">${bi(c.topic_te,c.topic_en)}</div><p style="font-size:13px">${bi(c.desc_te,c.desc_en)}</p><a class="btn" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${il(u.button_te,u.button_en)} ↗</a><div class="u" style="font-size:11px;opacity:.7;word-break:break-all">${esc(c.url)}</div></div>`).join('')}<div class="disc">${bk(u,'disclaimer')}</div>`)}
// ---------- certificate ----------
function certData(){const p=me(),all=p.runs;const d1=all.find(r=>r.day===1),d14=[...all].reverse().find(r=>r.day===14);return{p,d1,d14}}
function cert(){const {p,d1,d14}=certData();const n=doneN();const ok=d14&&n>=10;
 if(!ok){return shell(bi('సర్టిఫికెట్','Certificate'),`<div class="card"><p>${il('14వ రోజు ఛాలెంజ్ పూర్తి చేసి, కనీసం 10 రోజులు పూర్తయితే సర్టిఫికెట్ వస్తుంది.','Finish Day 14 and at least 10 of 14 days to earn your certificate.')}</p><div class="stat"><div class="st"><b>${n}/14</b><span>${il('రోజులు','Days done')}</span></div><div class="st"><b>${d14?'✔':'✖'}</b><span>${il('14వ రోజు','Day 14')}</span></div></div></div><button class="btn o" data-go="home">${il('కొనసాగించు','Continue')}</button>`)}
 if(!p.cert)p.cert={id:'SRC-'+today().replace(/-/g,'')+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),date:today()};save();
 shell(bi('సర్టిఫికెట్','Certificate'),`${lis('SR_CERT_ISSUED')}<div class="card"><h3>${il('మీ పేరు','Your name')}</h3><input class="inp" id="cn" value="${esc(p.name)}" maxlength="30"></div><canvas id="cv" width="1200" height="850" style="width:100%;border-radius:12px;border:1px solid #38bdf8"></canvas><a class="btn o" id="dl" download="SV-AksharaNova-SpeedReading-Certificate.png">⬇ ${il('సర్టిఫికెట్ డౌన్‌లోడ్','Download certificate')}</a><button class="btn g" id="pr">🖨 ${il('ప్రింట్','Print')}</button><button class="btn g" data-go="dash">📊 ${il('ప్రగతి','Progress')}</button>`);
 const draw=()=>{p.name=$('#cn').value.trim()||p.name;save();drawCert($('#cv'),p,d1,d14);$('#dl').href=$('#cv').toDataURL('image/png')};draw();$('#cn').oninput=draw;$('#pr').onclick=()=>{const w=window.open('');w.document.write('<img src="'+$('#cv').toDataURL()+'" style="width:100%">');w.document.close();w.print()}}
function drawCert(cv,p,d1,d14){const x=cv.getContext('2d');const C=P.certificate;const g=x.createLinearGradient(0,0,1200,850);g.addColorStop(0,'#0a1030');g.addColorStop(1,'#1e1b5e');x.fillStyle=g;x.fillRect(0,0,1200,850);x.strokeStyle='#38bdf8';x.lineWidth=6;x.strokeRect(24,24,1152,802);x.strokeStyle='#fb923c';x.lineWidth=2;x.strokeRect(40,40,1120,770);x.textAlign='center';x.fillStyle='#fb923c';x.font='800 20px Poppins,sans-serif';x.fillText('SV AKSHARANOVA',600,92);x.fillStyle='#fff';x.font='800 50px Poppins,sans-serif';x.fillText(C.title_en,600,160);x.font='700 28px "Noto Sans Telugu",sans-serif';x.fillStyle='#38bdf8';x.fillText(C.title_te,600,204);x.fillStyle='#cfe';x.font='400 22px Poppins,sans-serif';x.fillText(C.programme_en,600,246);
 x.fillStyle='#fff';x.font='800 54px Poppins,"Noto Sans Telugu",sans-serif';x.fillText(p.name,600,330);x.fillStyle='#fb923c';x.fillRect(300,346,600,3);
 const wrap=(t,y,f,col,w)=>{x.font=f;x.fillStyle=col;const ws=t.split(' ');let l='';ws.forEach(a=>{if(x.measureText(l+a).width>w){x.fillText(l,600,y);y+=32;l=''}l+=a+' '});x.fillText(l,600,y);return y+32};
 const R=d14||{};const sw=d1?d1.wpm:'-',sc=d1?d1.comp:'-';const rep=s=>s.replace('{NAME}',p.name).replace('{START_WPM}',sw).replace('{FINAL_WPM}',R.wpm).replace('{WPM_GAIN}',d1?(R.wpm-d1.wpm>=0?'+':'')+(R.wpm-d1.wpm):'-').replace('{START_COMP}',sc).replace('{FINAL_COMP}',R.comp).replace('{MEMORY}',R.mem).replace('{ACC}',R.acc).replace('{EFF}',R.eff).replace('{RATING}',R.rating);
 let y=wrap(rep(C.body_en),392,'400 24px Poppins,sans-serif','#fff',900);y=wrap(rep(C.body_te),y+4,'400 22px "Noto Sans Telugu",sans-serif','#cfe',900);
 x.fillStyle='#10194a';x.fillRect(120,y+8,960,150);x.fillStyle='#38bdf8';x.font='700 26px Poppins,sans-serif';x.fillText(rep('{RATING}')+'  ·  '+P.certificate.rating_labels[R.rating][1],600,y+48);x.fillStyle='#fff';x.font='400 22px Poppins,sans-serif';x.fillText(rep('WPM {START_WPM} → {FINAL_WPM} ({WPM_GAIN})   Comprehension {START_COMP}% → {FINAL_COMP}%'),600,y+86);x.fillText(rep('Memory {MEMORY}%   Accuracy {ACC}%   Efficiency {EFF}/100'),600,y+120);
 x.fillStyle='#9fb0e8';x.font='400 16px Poppins,sans-serif';const ft=C.footer_en;wrap(ft,748,'400 15px Poppins,sans-serif','#9fb0e8',980);x.textAlign='left';x.fillStyle='#fb923c';x.font='700 18px Poppins,sans-serif';x.fillText(p.cert.id,70,800);x.textAlign='right';x.fillText(p.cert.date,1130,800)}
// ---------- boot ----------
fetch('pack.json?v=1').then(r=>r.json()).then(j=>{P=j;route()}).catch(()=>{app.innerHTML='<p style="padding:20px">Could not load. Check internet and reload.</p>'});
})();
